// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "Manifest": {
    "name": "L Sevin"
  },
  "LocaleLayout": {
    "title": "L Sevin",
    "description": "Plataforma de salud automatizada que optimiza la programación de pacientes, desde estancias en hoteles hasta citas médicas"
  },
  "Error": {
    "title": "Algo salió mal",
    "description": "Por favor, contacta al administrador del sistema."
  },
  "NotFoundPage": {
    "title": "Página no encontrada",
    "description": "Por favor, usa la página principal del sitio web."
  },
  "Admin": {
    "dashboard": "Panel",
    "consultings": "Consultas",
    "serviceProvidersRequest": "Solicitudes de proveedores de servicios",
    "categories": "Categorías",
    "serviceDefinitions": "Definiciones de servicio",
    "providerTypes": "Tipos de proveedores",
    "staff": "Personal",
    "serviceProviders": "Proveedores de servicios"
  },
  "HomePage": {
    "title": "L Sevin - Salud Automatizada",
    "description": "Optimizando la programación de pacientes desde estancias en hoteles hasta citas médicas",
    "keywords": "automatización sanitaria,automatización de salud,turismo médico,reserva médica",
    "heroTitle": "Vive los mejores servicios médicos con nosotros",
    "heroDescription": "En el camino hacia el bienestar, te ofrecemos los mejores servicios médicos con un equipo de especialistas de primer nivel, equipos avanzados y un entorno seguro y relajante comprometido con un tratamiento de alta calidad y una atención excepcional.",
    "heroSubtext": "Llevemos tu salud a nuevas alturas juntos...",
    "registerRequest": "Enviar solicitud",
    "consultationRequest": "Solicitar consulta",
    "category": "Categoría",
    "providerTypes": "Tipos de proveedores",
    "serviceProviders": {
      "title": "Proveedores de servicios",
      "noProviders": "No hay proveedores de servicios disponibles por el momento",
      "priceStartsFrom": "Desde",
      "view": "Ver",
      "viewAll": "Ver Todo",
      "grade": {
        "label": "Grado"
      }
    },
    "ByType": {
      "title": "Explorar proveedores de servicios",
      "description": "Encuentra los mejores proveedores de servicios para tus necesidades",
      "noResults": "No se encontraron proveedores de servicios",
      "loading": "Cargando...",
      "error": "Error al cargar los proveedores de servicios. Por favor, inténtalo de nuevo.",
      "filters": {
        "title": "Filtros",
        "search": "Buscar",
        "searchPlaceholder": "Buscar proveedores...",
        "location": "Ubicación",
        "attributes": "Atributos",
        "country": "País",
        "city": "Ciudad",
        "clearAll": "Limpiar Todo",
        "selectCountry": "Selecciona un país",
        "selectCity": "Selecciona una ciudad",
        "allCountries": "Todos los Países",
        "allCities": "Todas las Ciudades",
        "selectCountryFirst": "Selecciona primero un país",
        "loadingCities": "Cargando ciudades...",
        "noFilters": "No hay filtros disponibles",
        "activeFilters": "Filtros Activos",
        "any": "Cualquiera",
        "yes": "Sí",
        "no": "No",
        "booleanTrue": "Sí",
        "booleanFalse": "No"
      }
    },
    "locationSwitcher": {
      "countries": "Países",
      "cities": "Ciudades",
      "allCountries": "Todos los países",
      "allCities": "Todas las ciudades",
      "loading": "Cargando..."
    }
  },
  "ServiceProviderPage": {
    "title": "Proveedor de servicios",
    "description": "Detalles del proveedor de servicios",
    "keywords": "proveedor de servicios,detalles del proveedor de servicios,página del proveedor de servicios",
    "contactProvider": "Contactar al proveedor",
    "aboutProvider": "Acerca de este proveedor",
    "availableServices": "Servicios disponibles",
    "policies": "Políticas",
    "viewGallery": "Ver galería",
    "images": "Imágenes",
    "imagesCount": "{count} imágenes",
    "noDescription": "No hay descripción disponible",
    "address": "Dirección",
    "location": "Ubicación",
    "ourStaff": "Nuestro personal",
    "noServices": "No hay servicios disponibles",
    "noPolicies": "No hay políticas disponibles",
    "noImages": "No hay imágenes disponibles",
    "close": "Cerrar",
    "attributes": "Atributos",
    "requests": {
      "title": "Solicitudes al proveedor de servicios",
      "description": "Gestiona todas las solicitudes de los clientes para el proveedor de servicios.",
      "provider": "Proveedor",
      "customer": "Cliente",
      "email": "Correo electrónico",
      "message": "Mensaje",
      "form": {
        "message": {
          "label": "Mensaje",
          "placeholder": "Escribe tu mensaje..."
        }
      },
      "status": {
        "title": "Estado",
        "Pending": "Pendiente",
        "Approved": "Aprobado",
        "Rejected": "Rechazado"
      },
      "date": "Fecha",
      "actions": "Acciones",
      "approve": "Aprobar",
      "reject": "Rechazar",
      "viewAddRequest": "Ver / Añadir solicitud",
      "myRequests": "Mis solicitudes",
      "formTitle": "Contactar al proveedor",
      "formMessage": "Mensaje",
      "submit": "Enviar",
      "openRequests": "Solicitudes abiertas"
    },
    "Comments": {
      "title": "Comentarios y Reseñas",
      "allComments": "Todos los Comentarios",
      "yourComment": "Tu comentario",
      "noComments": "Aún no hay comentarios. ¡Sé el primero en comentar!",
      "loading": "Cargando comentarios...",
      "loadError": "Error al cargar comentarios",
      "rating": "Calificación",
      "comment": "Tu Comentario",
      "commentPlaceholder": "Comparte tu experiencia...",
      "submit": "Enviar Comentario",
      "submitting": "Enviando...",
      "addSuccess": "Comentario Añadido",
      "addSuccessMessage": "Tu comentario ha sido publicado exitosamente.",
      "addFailed": "Error al Añadir Comentario",
      "deleteConfirmTitle": "Eliminar Comentario",
      "deleteConfirm": "¿Estás seguro de que quieres eliminar este comentario?",
      "deleteSuccess": "Comentario Eliminado",
      "deleteSuccessMessage": "Tu comentario ha sido eliminado exitosamente.",
      "deleteFailed": "Error al Eliminar Comentario",
      "form": {
        "commentText": {
          "label": "Texto del comentario"
        }
      }
    }
  },
  "LocaleSwitcher": {
    "label": "Cambiar idioma",
    "fa": "Persa",
    "en": "Inglés",
    "tr": "Türkçe",
    "ar": "Arapça",
    "es": "Español",
    "ku": "Kurdish",
    "de": "Deutsch",
    "fr": "Français"
  },
  "Logo": {
    "medical": "Salud",
    "tourism": "Turismo",
    "beauty": "Belleza"
  },
  "UserInfo": {
    "profile": "Perfil",
    "settings": "Configuración",
    "signOut": "Cerrar sesión",
    "adminPanel": "Panel de administración"
  },
  "FormErrors": {
    "required": "{field} es obligatorio",
    "tooShort": "{field} debe tener al menos {length} caracteres",
    "invalid": "{field} no es válido",
    "invalidEmail": "Correo electrónico no válido",
    "invalidPhoneNumber": "Por favor, introduce un número de teléfono válido",
    "passwordTooShort": "La contraseña debe tener al menos {length} caracteres",
    "passwordsDoNotMatch": "Las contraseñas no coinciden",
    "invalidCode": "El código de verificación debe tener 6 dígitos",
    "invalidFile": "Por favor, sube un archivo válido",
    "invalidFileType": "El tipo de archivo no es compatible",
    "fileTooLarge": "El tamaño del archivo supera el límite (máx. 5 MB)",
    "notMatch": "Las contraseñas no coinciden",
    "invalidPhone": "Por favor, introduce un número de teléfono válido"
  },
  "User": {
    "Information": {
      "incompleteProfileTitle": "Perfil incompleto",
      "completeProfileWarning": "Por favor, completa tu información",
      "goToProfile": "Ir al perfil"
    },
    "Profile": {
      "page": {
        "title": "Información del perfil",
        "description": "Para actualizar tu información de perfil, introduce cuidadosamente los datos a continuación."
      },
      "personalInfo": {
        "title": "Información personal",
        "base": "Información base",
        "documents": "Documentos"
      },
      "tabs": {
        "basic": "Información básica",
        "additional": "Información adicional",
        "documents": "Documentos"
      },
      "form": {
        "firstName": {
          "label": "Nombre"
        },
        "lastName": {
          "label": "Apellido"
        },
        "email": {
          "label": "Correo electrónico"
        },
        "phoneNumber": {
          "label": "Número de teléfono"
        },
        "birthDate": {
          "label": "Fecha de nacimiento"
        },
        "gender": {
          "label": "Género"
        },
        "country": "País",
        "city": "Ciudad",
        "street": "Calle",
        "detail": "Detalles adicionales",
        "zipCode": "Código postal",
        "documentType": {
          "label": "Tipo de documento"
        },
        "documentFile": {
          "label": "Archivo del documento"
        },
        "existingDocuments": "Tus documentos subidos",
        "viewDocument": "Ver documento",
        "address": {
          "countryCode": "Código de país",
          "cityCode": "Código de ciudad",
          "street": "Calle",
          "detail": "Detalles adicionales",
          "zipCode": "Código postal"
        }
      },
      "placeholders": {
        "birthDate": "Selecciona la fecha de nacimiento",
        "documentType": "Selecciona el tipo de documento",
        "documentFile": "Haz clic para subir o arrastra y suelta"
      },
      "messages": {
        "updateSuccess": "Perfil actualizado correctamente",
        "documentUploadSuccess": "Documento subido correctamente",
        "deleteDocumentConfirmationTitle": "Eliminar documento",
        "deleteDocumentConfirmationMessage": "¿Seguro que quieres eliminar este documento?",
        "deleteDocumentSuccess": "Documento eliminado correctamente",
        "deleteDocumentError": "No se pudo eliminar el documento"
      },
      "validation": {
        "countryRequired": "Por favor, selecciona un país",
        "cityRequired": "Por favor, selecciona una ciudad"
      },
      "errors": {
        "updateFailed": "No se pudo actualizar el perfil",
        "documentUploadFailed": "No se pudo subir el documento",
        "documentDeleteFailed": "No se pudo eliminar el documento",
        "invalidFileType": "Tipo de archivo no válido",
        "fileTooLarge": "El archivo es demasiado grande",
        "supportedFormats": "Formatos admitidos: .zip, .pdf, formato de imagen (máx. 5 MB)"
      },
      "buttons": {
        "save": "Guardar cambios",
        "upload": "Subir documento",
        "delete": "Eliminar documento"
      }
    }
  },
  "Common": {
    "Gender": {
      "title": "Género",
      "male": "Hombre",
      "female": "Mujer",
      "other": "Otro"
    },
    "DocumentType": {
      "title": "Tipo de documento",
      "Passport": "Pasaporte",
      "Visa": "Visa",
      "DriverLicense": "Licencia de conducir",
      "BankStatement": "Estado de cuenta bancario",
      "IdCard": "Documento de identidad",
      "Medical": "Historial médico",
      "Beauty": "Procedimiento estético",
      "Tourism": "Documento de turismo",
      "Other": "Otro"
    },
    "FileUpload": {
      "errors": {
        "fileError": "Error de archivo, verifica los requisitos",
        "fileTooLarge": "El archivo es demasiado grande. El tamaño máximo es {size}MB"
      }
    },
    "Address": {
      "title": "Dirección",
      "country": "País",
      "city": "Ciudad",
      "street": "Calle",
      "detail": "Detalles adicionales",
      "zipCode": "Código postal"
    },
    "Location": {
      "title": "Ubicación",
      "country": "País",
      "city": "Ciudad",
      "selectCountry": "Selecciona un país",
      "selectCity": "Selecciona una ciudad",
      "noCountrySelected": "Ningún país seleccionado",
      "noCitiesAvailable": "No hay ciudades disponibles",
      "loading": "Cargando..."
    },
    "DatePicker": {
      "placeholder": "Selecciona la fecha",
      "range": "Rango de fechas",
      "multiple": "Fechas múltiples",
      "single": "Fecha única"
    },
    "DataTable": {
      "search": "Buscar...",
      "reset": "Restablecer",
      "noResults": "Sin resultados.",
      "rowsSelected": "{count} de {total} fila(s) seleccionada(s).",
      "page": "Página {current} de {total}",
      "clearFilters": "Limpiar filtros",
      "sortAscending": "Orden ascendente",
      "sortDescending": "Orden descendente",
      "hideColumn": "Ocultar columna"
    },
    "Input": {
      "search": "Buscar..."
    },
    "Fetcher": {
      "noData": "No se encontraron datos",
      "error": "Ocurrió un error: {detail}"
    },
    "Confirm": {
      "title": "Atención",
      "cancel": "Cancelar",
      "confirm": "Confirmar"
    }
  },
  "Auth": {
    "SignUp": {
      "page": {
        "title": "Registrarse",
        "description": "Para registrarte, introduce cuidadosamente la información a continuación.",
        "alreadyHaveAccount": "¿Ya tienes una cuenta?",
        "login": "Iniciar sesión"
      },
      "form": {
        "firstName": {
          "label": "Nombre"
        },
        "lastName": {
          "label": "Apellido"
        },
        "email": {
          "label": "Correo electrónico"
        },
        "phoneNumber": {
          "label": "Número de teléfono"
        },
        "password": {
          "label": "Contraseña"
        },
        "signUp": "Enviar código"
      },
      "placeholders": {
        "firstName": "Juan",
        "lastName": "Pérez",
        "email": "ejemplo@gmail.com",
        "password": "*******"
      },
      "errors": {
        "invalidPhone": "Número de teléfono no válido"
      },
      "messages": {
        "signUpSuccess": "Registro exitoso",
        "signUpError": "Error al enviar el código. Inténtalo de nuevo."
      }
    },
    "SignIn": {
      "page": {
        "title": "Iniciar sesión",
        "description": "Para iniciar sesión, introduce tu información de registro.",
        "noAccount": "¿No tienes una cuenta?",
        "signUp": "Regístrate",
        "forgotPassword": "¿Olvidaste tu contraseña?"
      },
      "form": {
        "userNameOrEmail": {
          "label": "Correo electrónico o número de teléfono"
        },
        "password": {
          "label": "Contraseña"
        },
        "remember": "Recuérdame",
        "login": "Iniciar sesión"
      },
      "errors": {
        "invalidCredentials": "Credenciales no válidas",
        "authError": "Error de autenticación"
      },
      "messages": {
        "loginSuccess": "Inicio de sesión exitoso",
        "loginError": "Error al iniciar sesión. Inténtalo de nuevo."
      }
    },
    "ForgotPassword": {
      "page": {
        "title": "Olvidé mi contraseña",
        "description": "Para recuperar tu contraseña, introduce tu número de teléfono.",
        "rememberPassword": "¿Recordaste tu contraseña?",
        "login": "Iniciar sesión"
      },
      "form": {
        "phoneNumber": "Número de teléfono",
        "submit": "Enviar enlace de recuperación",
        "userNameOrEmail": {
          "label": "Correo electrónico o número de teléfono"
        }
      },
      "messages": {
        "success": "Enlace de recuperación enviado.",
        "error": "Error al enviar el enlace de recuperación. Inténtalo de nuevo."
      }
    },
    "Otp": {
      "page": {
        "title": "Código de verificación",
        "description": "Introduce el código de verificación enviado a {mobile}.",
        "wrongNumber": "¿Número incorrecto?",
        "changeNumber": "Cambiar número"
      },
      "form": {
        "verify": "Verificar",
        "resendCode": "Reenviar código",
        "resendCodeTimer": "Reenviar código ({time})",
        "code": {
          "label": "Código de verificación"
        },
        "phoneNumber": {
          "label": "Número de teléfono"
        }
      },
      "messages": {
        "success": "Código verificado correctamente.",
        "error": "Error al verificar el código. Inténtalo de nuevo.",
        "resendSuccess": "Código de verificación enviado correctamente.",
        "resendError": "Error al enviar el código de verificación. Inténtalo de nuevo."
      }
    },
    "VerifyEmail": {
      "form": {
        "email": "Correo electrónico",
        "code": "Código de verificación"
      },
      "messages": {
        "success": "Correo electrónico verificado correctamente.",
        "error": "Error al verificar el correo electrónico. Inténtalo de nuevo."
      }
    },
    "OnBoarding": {
      "step1": {
        "title": "Tu salud es nuestra prioridad",
        "description": "Una experiencia única de servicios médicos avanzados con comodidades completas y un viaje fácil y agradable, diseñado para tus necesidades específicas y con atención a detalles importantes del viaje.",
        "primaryButton": "Siguiente",
        "secondaryButton": "Omitir"
      },
      "step2": {
        "title": "Estancia, tratamiento, relajación",
        "description": "Desde servicios médicos especializados y avanzados hasta alojamiento en los mejores hoteles, te brindamos una experiencia única y un viaje cómodo y sin preocupaciones para satisfacer tus necesidades.",
        "primaryButton": "Iniciar sesión/Registrarse",
        "secondaryButton": "Omitir"
      },
      "step3": {
        "title": "Tu viaje de salud comienza aquí",
        "description": "Empieza hoy tu viaje de salud personalizado con nosotros. Nuestro equipo de expertos está listo para brindarte la mejor atención y experiencia.",
        "primaryButton": "Comenzar",
        "secondaryButton": "Iniciar sesión"
      }
    }
  },
  "Dashboard": {
    "page": {
      "title": "Resumen del panel",
      "description": "Panel de administración con estadísticas del sistema y resumen de actividad reciente"
    },
    "stats": {
      "totalConsultings": {
        "title": "Consultas totales",
        "description": "Solicitudes de consulta activas"
      },
      "pendingServiceProviderRequests": {
        "title": "Solicitudes pendientes",
        "description": "En espera de aprobación"
      },
      "totalServiceProviders": {
        "title": "Proveedores de servicios",
        "description": "Proveedores registrados"
      },
      "totalStaff": {
        "title": "Miembros del personal",
        "description": "Personal activo"
      }
    },
    "recentConsultings": {
      "title": "Consultas recientes",
      "viewAll": "Ver todo",
      "empty": "No hay solicitudes de consulta recientes",
      "table": {
        "customer": "Cliente",
        "category": "Categoría",
        "description": "Descripción",
        "date": "Fecha"
      }
    },
    "recentRequests": {
      "title": "Solicitudes recientes a proveedores",
      "viewAll": "Ver todo",
      "empty": "No hay solicitudes recientes a proveedores de servicios",
      "table": {
        "customer": "Cliente",
        "serviceProvider": "Proveedor de servicios",
        "message": "Mensaje",
        "status": {
          "title": "Estado",
          "Pending": "Pendiente",
          "Approved": "Aprobado",
          "Rejected": "Rechazado"
        },
        "date": "Fecha"
      }
    },
    "quickActions": {
      "title": "Acciones rápidas",
      "totalConsultings": {
        "title": "Consultas",
        "description": "Gestionar solicitudes de consulta"
      },
      "totalServiceProviders": {
        "title": "Proveedores de servicios",
        "description": "Gestionar proveedores de servicios"
      },
      "totalCategories": {
        "title": "Categorías",
        "description": "Gestionar categorías de servicio"
      },
      "totalStaff": {
        "title": "Personal",
        "description": "Gestionar miembros del personal"
      },
      "totalProviderTypes": {
        "title": "Tipos de proveedores",
        "description": "Gestionar tipos de proveedores"
      },
      "totalServiceDefinitions": {
        "title": "Definiciones de servicio",
        "description": "Gestionar definiciones de servicio"
      }
    }
  },
  "Consulting": {
    "page": {
      "title": "Solicitar consulta",
      "description": "Solicita una consulta para tus necesidades médicas o estéticas.",
      "adminTitle": "Solicitudes de consulta",
      "adminDescription": "Gestiona todas las solicitudes de consulta de los clientes."
    },
    "table": {
      "customer": "Cliente",
      "email": "Correo electrónico",
      "description": "Descripción",
      "category": "Categoría"
    },
    "form": {
      "formTitle": "Solicitud de consulta",
      "formDescription": "Por favor, proporciona los detalles de tu solicitud de consulta.",
      "categoryId": {
        "label": "Categoría"
      },
      "categoryName": {
        "label": "Nombre de la categoría"
      },
      "description": {
        "label": "Descripción"
      },
      "documentIds": {
        "label": "Documentos relacionados"
      }
    },
    "placeholders": {
      "category": "Selecciona una categoría",
      "searchCategory": "Buscar categorías...",
      "description": "Describe tus necesidades y requisitos en detalle..."
    },
    "descriptions": {
      "description": "Proporciona la mayor cantidad de detalles posible sobre tus necesidades y cualquier historial médico o inquietud relevante.",
      "documents": "Selecciona los documentos relevantes para tu solicitud de consulta."
    },
    "messages": {
      "createSuccess": "Solicitud de consulta enviada correctamente",
      "noDocuments": "Aún no has subido documentos. Por favor, sube documentos relevantes primero.",
      "noCategories": "No se encontraron categorías."
    },
    "errors": {
      "createFailed": "No se pudo enviar la solicitud de consulta"
    },
    "buttons": {
      "submit": "Enviar solicitud",
      "uploadDocuments": "Subir documentos"
    }
  },
  "Category": {
    "name": "Categoría",
    "page": {
      "title": "Categorías",
      "description": "Gestionar categorías y su jerarquía"
    },
    "add": {
      "page": {
        "title": "Añadir categoría",
        "description": "Crear una nueva categoría"
      },
      "title": "Añadir nueva categoría",
      "childTitle": "Añadir subcategoría"
    },
    "update": {
      "page": {
        "title": "Actualizar categoría",
        "description": "Editar información de la categoría"
      },
      "title": "Actualizar categoría"
    },
    "form": {
      "name": {
        "label": "Nombre",
        "translations": "El nombre de la categoría es obligatorio en al menos un idioma"
      },
      "namePlaceholder": "Introduce el nombre de la categoría",
      "description": {
        "label": "Descripción",
        "translations": "La descripción de la categoría es obligatoria en al menos un idioma"
      },
      "descriptionPlaceholder": "Introduce la descripción de la categoría",
      "parentId": "Categoría principal",
      "parentIdPlaceholder": "Selecciona la categoría principal",
      "displayOrder": "Orden de visualización",
      "displayOrderPlaceholder": "Introduce el orden de visualización",
      "isActive": "Activo",
      "create": "Crear categoría",
      "update": "Actualizar categoría",
      "creating": "Creando...",
      "updating": "Actualizando...",
      "cancel": "Cancelar"
    },
    "table": {
      "name": "Nombre",
      "description": "Descripción",
      "parent": "Principal",
      "displayOrder": "Orden",
      "status": "Estado",
      "actions": "Acciones"
    },
    "actions": {
      "addCategory": "Añadir categoría",
      "addChildCategory": "Añadir subcategoría",
      "editCategory": "Editar categoría",
      "deleteCategory": "Eliminar categoría",
      "deleteCategoryDescription": "¿Seguro que quieres eliminar esta categoría?",
      "toggleActivation": "Activar/Desactivar"
    },
    "status": {
      "active": "Activo",
      "inactive": "Inactivo"
    },
    "messages": {
      "success": "Operación de categoría completada correctamente",
      "error": "No se pudo realizar la operación de categoría",
      "deleteConfirmation": "¿Seguro que quieres eliminar \"{name}\"?",
      "deleteSuccess": "Categoría eliminada correctamente",
      "deleteError": "No se pudo eliminar la categoría",
      "deleteErrorLog": "Error al eliminar la categoría:"
    }
  },
  "ServiceDefinition": {
    "name": "Definición de servicio",
    "page": {
      "title": "Definiciones de servicio",
      "description": "Gestionar definiciones de servicio y sus configuraciones"
    },
    "add": {
      "page": {
        "title": "Añadir definición de servicio",
        "description": "Crear una nueva definición de servicio"
      },
      "title": "Añadir nueva definición de servicio"
    },
    "update": {
      "page": {
        "title": "Actualizar definición de servicio",
        "description": "Editar información de la definición de servicio"
      },
      "title": "Actualizar definición de servicio"
    },
    "form": {
      "name": {
        "label": "Nombre"
      },
      "description": {
        "label": "Descripción"
      },
      "categoryId": {
        "label": "Categoría",
        "placeholder": "Selecciona la categoría"
      },
      "durationMinutes": {
        "label": "Duración (minutos)",
        "placeholder": "Introduce la duración en minutos"
      },
      "currency": {
        "label": "Moneda",
        "placeholder": "Introduce la moneda"
      },
      "value": {
        "label": "Precio",
        "placeholder": "Introduce el valor del precio"
      },
      "pricingModel": {
        "label": "Modelo de precio",
        "placeholder": "Selecciona el modelo de precio"
      },
      "isActive": {
        "label": "Activo"
      },
      "attributeDefinitions": "Definiciones de atributos",
      "requirements": "Requisitos",
      "create": "Crear definición de servicio",
      "update": "Actualizar definición de servicio",
      "creating": "Creando...",
      "updating": "Actualizando...",
      "cancel": "Cancelar"
    },
    "table": {
      "name": "Nombre",
      "category": "Categoría",
      "description": "Descripción",
      "duration": "Duración",
      "price": "Precio",
      "status": "Estado",
      "actions": "Acciones"
    },
    "actions": {
      "addServiceDefinition": "Añadir definición de servicio",
      "editServiceDefinition": "Editar definición de servicio",
      "deleteServiceDefinition": "Eliminar definición de servicio",
      "deleteServiceDefinitionDescription": "¿Seguro que quieres eliminar esta definición de servicio?",
      "toggleActivation": "Activar/Desactivar",
      "viewDetails": "Ver detalles",
      "removeAttribute": "Eliminar atributo",
      "removeAttributeDescription": "¿Seguro que quieres eliminar esta definición de atributo?",
      "removeRequirement": "Eliminar requisito",
      "removeRequirementDescription": "¿Seguro que quieres eliminar este requisito?",
      "retry": "Reintentar",
      "cancel": "Cancelar",
      "save": "Guardar",
      "saving": "Guardando..."
    },
    "status": {
      "active": "Activo",
      "inactive": "Inactivo"
    },
    "messages": {
      "success": "Operación de definición de servicio completada correctamente",
      "error": "No se pudo realizar la operación de definición de servicio",
      "updated": "Definición de servicio actualizada correctamente",
      "attributeAddSuccess": "Atributo añadido correctamente",
      "attributeRemoveSuccess": "Atributo eliminado correctamente",
      "requirementAddSuccess": "Requisito añadido correctamente",
      "requirementRemoveSuccess": "Requisito eliminado correctamente",
      "attributeUpdateSuccess": "Atributo actualizado correctamente",
      "requirementUpdateSuccess": "Requisito actualizado correctamente",
      "fetchError": "No se pudo obtener los detalles de la definición de servicio"
    },
    "pricingModels": {
      "Fixed": "Precio fijo",
      "Variable": "Precio variable",
      "Hourly": "Tarifa por hora",
      "Package": "Precio por paquete"
    },
    "attributes": {
      "title": "Definiciones de atributos",
      "description": "Gestionar definiciones de atributos del servicio y sus opciones",
      "addAttribute": "Añadir atributo",
      "addNew": "Añadir nuevo atributo",
      "noAttributes": "Aún no hay atributos definidos",
      "form": {
        "name": {
          "label": "Nombre del atributo",
          "placeholder": "Introduce el nombre del atributo"
        },
        "description": {
          "label": "Descripción",
          "placeholder": "Introduce la descripción del atributo"
        },
        "attributeType": "Tipo de atributo",
        "attributeTypePlaceholder": "Selecciona el tipo de atributo",
        "isRequired": "Obligatorio",
        "affectsPricing": "Afecta al precio",
        "displayOrder": "Orden de visualización",
        "options": "Opciones",
        "addOption": "Añadir opción",
        "noOptions": "Haz clic en 'Añadir opción' para crear opciones de selección",
        "add": "Añadir atributo",
        "adding": "Añadiendo...",
        "displayName": {
          "label": "Nombre para mostrar",
          "placeholder": "Introduce el nombre para mostrar"
        },
        "value": "Valor",
        "extraPrice": "Precio adicional",
        "type": "Tipo",
        "required": "Obligatorio",
        "affectsPricingLabel": "Afecta al precio",
        "yes": "Sí",
        "no": "No"
      }
    },
    "requirements": {
      "title": "Requisitos",
      "description": "Gestionar requisitos y condiciones del servicio",
      "addRequirement": "Añadir requisito",
      "addNew": "Añadir nuevo requisito",
      "noRequirements": "Aún no hay requisitos definidos",
      "mandatory": "Obligatorio",
      "optional": "Opcional",
      "form": {
        "description": {
          "label": "Descripción del requisito",
          "placeholder": "Introduce la descripción del requisito"
        },
        "isMandatory": "Requisito obligatorio",
        "isMandatoryDescription": "Indica si este requisito es obligatorio para el servicio",
        "add": "Añadir requisito",
        "adding": "Añadiendo...",
        "update": "Actualizar requisito",
        "updating": "Actualizando...",
        "cancel": "Cancelar"
      }
    },
    "details": {
      "title": "Detalles de la definición de servicio",
      "description": "Vista detallada de {name} con gestión de atributos y requisitos",
      "basicInfo": "Información básica",
      "pricingInfo": "Información de precios"
    },
    "tabs": {
      "overview": "Resumen",
      "attributes": "Atributos",
      "requirements": "Requisitos"
    },
    "search": {
      "placeholder": "Buscar definiciones de servicio...",
      "noResults": "No se encontró ninguna definición de servicio."
    },
    "units": {
      "minutes": "min",
      "minutesShort": "min"
    }
  },
  "Staff": {
    "name": "Personal",
    "page": {
      "title": "Personal",
      "description": "Gestionar miembros del personal y sus horarios"
    },
    "add": {
      "page": {
        "title": "Añadir personal",
        "description": "Crear un nuevo miembro del personal"
      },
      "title": "Añadir nuevo miembro del personal"
    },
    "update": {
      "page": {
        "title": "Actualizar personal",
        "description": "Editar información del miembro del personal"
      },
      "title": "Actualizar miembro del personal"
    },
    "form": {
      "name": {
        "label": "Nombre completo",
        "placeholder": "Introduce el nombre completo del miembro del personal"
      },
      "biography": {
        "label": "Biografía",
        "placeholder": "Introduce la biografía del miembro del personal"
      },
      "title": {
        "label": "Cargo",
        "placeholder": "Introduce el cargo del miembro del personal"
      },
      "profileImageUrl": "URL de la imagen de perfil",
      "profileImageUrlPlaceholder": "Introduce la URL de la imagen de perfil",
      "isActive": "Activo",
      "availabilities": "Horario de disponibilidad",
      "serviceAssignments": "Asignaciones de servicios",
      "create": "Crear miembro del personal",
      "update": "Actualizar miembro del personal",
      "creating": "Creando...",
      "updating": "Actualizando...",
      "cancel": "Cancelar"
    },
    "table": {
      "name": "Nombre",
      "title": "Cargo",
      "status": "Estado",
      "services": "Servicios",
      "biography": "Biografía",
      "actions": "Acciones"
    },
    "actions": {
      "addStaff": "Añadir miembro del personal",
      "editStaff": "Editar miembro del personal",
      "deleteStaff": "Eliminar miembro del personal",
      "deleteStaffDescription": "¿Seguro que quieres eliminar a este miembro del personal?",
      "viewDetails": "Ver detalles",
      "toggleActivation": "Activar/Desactivar",
      "retry": "Reintentar",
      "cancel": "Cancelar",
      "save": "Guardar",
      "saving": "Guardando..."
    },
    "status": {
      "active": "Activo",
      "inactive": "Inactivo"
    },
    "messages": {
      "success": "Operación de personal completada correctamente",
      "error": "No se pudo realizar la operación de personal",
      "fetchError": "No se pudieron cargar los detalles del personal",
      "availabilityAddSuccess": "Disponibilidad añadida correctamente",
      "availabilityAddError": "No se pudo añadir la disponibilidad",
      "availabilityUpdateSuccess": "Disponibilidad actualizada correctamente",
      "availabilityUpdateError": "No se pudo actualizar la disponibilidad",
      "availabilityRemoveSuccess": "Disponibilidad eliminada correctamente",
      "availabilityRemoveError": "No se pudo eliminar la disponibilidad",
      "serviceAddSuccess": "Servicio asignado correctamente",
      "serviceAddError": "No se pudo asignar el servicio",
      "serviceUpdateSuccess": "Servicio actualizado correctamente",
      "serviceUpdateError": "No se pudo actualizar el servicio",
      "serviceRemoveSuccess": "Servicio eliminado correctamente",
      "serviceRemoveError": "No se pudo eliminar el servicio",
      "serviceSelectionRequired": "Por favor, selecciona un servicio para asignar"
    },
    "details": {
      "title": "Detalles del personal",
      "description": "Viendo detalles de {name}",
      "basicInfo": "Información básica",
      "statsInfo": "Estadísticas",
      "totalAvailabilities": "Total de disponibilidades",
      "totalServices": "Total de servicios",
      "activeServices": "Servicios activos"
    },
    "tabs": {
      "overview": "Resumen",
      "availabilities": "Disponibilidades",
      "services": "Servicios"
    },
    "availability": {
      "title": "Disponibilidad del personal",
      "description": "Gestionar el horario de disponibilidad del miembro del personal",
      "noAvailabilities": "No hay horarios de disponibilidad configurados",
      "recurring": "Recurrente",
      "specific": "Fecha específica",
      "specificDate": "Fecha específica",
      "add": {
        "title": "Añadir nueva disponibilidad",
        "description": "Configura un nuevo horario de disponibilidad para este miembro del personal"
      },
      "form": {
        "dayOfWeek": "Día de la semana",
        "startTime": "Hora de inicio",
        "endTime": "Hora de fin",
        "isRecurring": "Recurrente semanal",
        "specificDate": "Fecha específica",
        "status": "Estado",
        "selectStartTime": "Selecciona la hora de inicio",
        "selectEndTime": "Selecciona la hora de fin"
      },
      "timePicker": {
        "selectTime": "Seleccionar hora",
        "hour": "Hora",
        "minute": "Min",
        "selected": "Seleccionado"
      },
      "validation": {
        "startTimeAfterEnd": "La hora de inicio debe ser anterior a la hora de fin",
        "endTimeBeforeStart": "La hora de fin debe ser posterior a la hora de inicio",
        "endTimeMustBeAfterStartTime": "La hora de fin debe ser posterior a la hora de inicio",
        "timeAutoAdjusted": "La hora de fin se ajustó automáticamente"
      },
      "days": {
        "Sunday": "Domingo",
        "Monday": "Lunes",
        "Tuesday": "Martes",
        "Wednesday": "Miércoles",
        "Thursday": "Jueves",
        "Friday": "Viernes",
        "Saturday": "Sábado"
      },
      "status": {
        "available": "Disponible",
        "busy": "Ocupado",
        "onLeave": "De licencia",
        "inactive": "Inactivo"
      },
      "actions": {
        "add": "Añadir disponibilidad"
      },
      "removeDialog": {
        "title": "Eliminar disponibilidad",
        "description": "¿Seguro que quieres eliminar esta disponibilidad? Esta acción no se puede deshacer."
      },
      "badges": {
        "available": "Disponible",
        "busy": "Ocupado",
        "onLeave": "De licencia",
        "inactive": "Inactivo"
      }
    },
    "services": {
      "title": "Servicios asignados",
      "description": "Gestionar los servicios que este miembro del personal puede proporcionar",
      "noServices": "No hay servicios asignados a este miembro del personal",
      "allServicesAssigned": "Todos los servicios disponibles han sido asignados a este miembro del personal",
      "add": {
        "title": "Asignar nuevo servicio",
        "description": "Asignar una definición de servicio a este miembro del personal"
      },
      "form": {
        "serviceDefinition": "Servicio",
        "selectService": "Selecciona un servicio para asignar",
        "notes": "Notas",
        "notesPlaceholder": "Introduce cualquier nota o instrucción especial para esta asignación de servicio"
      },
      "actions": {
        "add": "Asignar servicio"
      },
      "removeDialog": {
        "title": "Eliminar asignación de servicio",
        "description": "¿Seguro que quieres eliminar esta asignación de servicio? Esta acción no se puede deshacer."
      }
    },
    "units": {
      "minutes": "min",
      "minutesShort": "min"
    }
  },
  "ServiceProvider": {
    "name": "Proveedor de servicios",
    "contactProvider": "Contactar al proveedor",
    "aboutProvider": "Acerca de este proveedor",
    "availableServices": "Servicios disponibles",
    "viewGallery": "Ver galería",
    "images": "Imágenes",
    "imagesCount": "{count} imágenes",
    "noDescription": "No hay descripción disponible",
    "noServices": "No hay servicios disponibles",
    "noPolicies": "No hay políticas disponibles",
    "noImages": "No hay imágenes disponibles",
    "page": {
      "title": "Proveedores de servicios",
      "description": "Gestionar proveedores de servicios y sus perfiles completos"
    },
    "add": {
      "page": {
        "title": "Añadir proveedor de servicios",
        "description": "Crear un nuevo proveedor de servicios"
      },
      "title": "Añadir nuevo proveedor de servicios"
    },
    "update": {
      "page": {
        "title": "Actualizar proveedor de servicios",
        "description": "Editar información del proveedor de servicios"
      },
      "title": "Actualizar proveedor de servicios"
    },
    "details": {
      "page": {
        "title": "Detalles del proveedor de servicios",
        "description": "Vista integral de la gestión del proveedor de servicios"
      },
      "title": "Detalles del proveedor de servicios",
      "basicInfo": "Información básica",
      "statsInfo": "Estadísticas",
      "totalStaff": "Total de personal",
      "totalServices": "Total de servicios",
      "totalPolicies": "Total de políticas",
      "totalGalleryItems": "Total de elementos en galería",
      "totalAttributes": "Total de atributos",
      "tabs": {
        "info": "Información",
        "staff": "Personal",
        "services": "Servicios",
        "policies": "Políticas",
        "gallery": "Galería",
        "attributes": "Atributos"
      }
    },
    "form": {
      "name": {
        "label": "Nombre del proveedor",
        "placeholder": "Introduce el nombre del proveedor"
      },
      "description": {
        "label": "Descripción",
        "placeholder": "Introduce la descripción del proveedor"
      },
      "providerTypeId": {
        "label": "Tipo de proveedor",
        "placeholder": "Selecciona el tipo de proveedor"
      },
      "grade": {
        "label": "Grado (Opcional)",
        "placeholder": "Selecciona el grado",
        "none": "Sin grado"
      },
      "country": {
        "label": "País",
        "placeholder": "Selecciona el país"
      },
      "city": {
        "label": "Ciudad",
        "placeholder": "Selecciona la ciudad"
      },
      "coordinates": {
        "label": "Coordenadas",
        "description": "Introduce las coordenadas"
      },
      "location": {
        "label": "Ubicación",
        "placeholder": "Introduce la ubicación"
      },
      "email": {
        "label": "Correo electrónico",
        "placeholder": "Introduce el correo del proveedor"
      },
      "phoneNumber": {
        "label": "Número de teléfono",
        "placeholder": "Introduce el número de teléfono"
      },
      "sections": {
        "basicInfo": "Información básica",
        "addressInfo": "Información de la dirección",
        "contactInfo": "Información de contacto"
      },
      "street": {
        "label": "Calle",
        "placeholder": "Introduce la dirección"
      },
      "detail": {
        "label": "Detalles de la dirección",
        "placeholder": "Introduce detalles adicionales de la dirección"
      },
      "zipCode": {
        "label": "Código postal",
        "placeholder": "Introduce el código postal"
      },
      "selectCountryFirst": "Primero selecciona un país",
      "noCitiesAvailable": "No hay ciudades disponibles para el país seleccionado",
      "actions": {
        "save": "Guardar cambios",
        "saving": "Guardando...",
        "cancel": "Cancelar"
      },
      "website": "Sitio web",
      "websitePlaceholder": "Introduce la URL del sitio web",
      "address": "Información de la dirección",
      "isActive": "Activo",
      "staffAssignments": "Asignaciones de personal",
      "serviceOfferings": "Ofertas de servicios",
      "create": "Crear proveedor de servicios",
      "update": "Actualizar proveedor de servicios",
      "creating": "Creando...",
      "updating": "Actualizando...",
      "cancel": "Cancelar"
    },
    "table": {
      "headers": {
        "name": "Nombre",
        "description": "Descripción",
        "providerType": "Tipo de proveedor",
        "contactEmail": "Correo",
        "contactPhone": "Teléfono",
        "address": "Dirección",
        "serviceCount": "Servicios",
        "staffCount": "Personal",
        "status": "Estado",
        "createDate": "Creado",
        "actions": "Acciones"
      },
      "filters": {
        "searchPlaceholder": "Buscar proveedores de servicios...",
        "providerType": "Tipo de proveedor",
        "status": "Estado",
        "active": "Activo",
        "inactive": "Inactivo",
        "reset": "Restablecer filtros"
      },
      "actions": {
        "title": "Acciones",
        "edit": "Editar",
        "delete": "Eliminar",
        "add": "Añadir proveedor de servicios"
      }
    },
    "actions": {
      "addServiceProvider": "Añadir proveedor de servicios",
      "editServiceProvider": "Editar proveedor de servicios",
      "deleteServiceProvider": "Eliminar proveedor de servicios",
      "deleteServiceProviderDescription": "¿Seguro que quieres eliminar este proveedor de servicios?",
      "viewDetails": "Ver detalles",
      "toggleActivation": "Activar/Desactivar",
      "add": "Añadir",
      "cancel": "Cancelar"
    },
    "status": {
      "label": "Estado",
      "active": "Activo",
      "inactive": "Inactivo"
    },
    "staff": {
      "title": "Gestión de personal",
      "description": "Gestionar asignaciones de personal para este proveedor de servicios",
      "noStaff": "No hay personal asignado a este proveedor de servicios",
      "add": {
        "title": "Asignar miembro del personal",
        "description": "Asignar un miembro del personal a este proveedor de servicios"
      },
      "form": {
        "staffMember": "Miembro del personal",
        "selectStaff": "Selecciona un miembro del personal para asignar",
        "notes": "Notas de la asignación",
        "notesPlaceholder": "Introduce cualquier nota especial para esta asignación de personal (opcional)"
      },
      "actions": {
        "add": "Asignar personal",
        "save": "Guardar cambios",
        "cancel": "Cancelar"
      },
      "messages": {
        "addSuccess": "Miembro del personal asignado correctamente",
        "addError": "No se pudo asignar al miembro del personal",
        "updateSuccess": "Asignación de personal actualizada correctamente",
        "updateError": "No se pudo actualizar la asignación de personal",
        "removeSuccess": "Asignación de personal eliminada correctamente",
        "removeError": "No se pudo eliminar la asignación de personal",
        "staffSelectionRequired": "Por favor, selecciona un miembro del personal para asignar"
      },
      "removeDialog": {
        "title": "Eliminar asignación de personal",
        "description": "¿Seguro que quieres eliminar esta asignación de personal? Esta acción no se puede deshacer."
      }
    },
    "gallery": {
      "title": "Gestión de galería",
      "description": "Gestionar imágenes y medios para este proveedor de servicios",
      "noItems": "Aún no se han añadido elementos a la galería",
      "add": {
        "title": "Subir elemento a la galería",
        "description": "Sube una nueva imagen o elemento multimedia"
      },
      "form": {
        "title": "Título",
        "titlePlaceholder": "Introduce el título de la imagen",
        "description": "Descripción",
        "descriptionPlaceholder": "Introduce la descripción de la imagen (opcional)",
        "file": "Seleccionar archivo",
        "filePlaceholder": "Haz clic para subir o arrastra y suelta",
        "fileHint": "PNG, JPG, WEBP o GIF (máx. 10 MB)",
        "displayOrder": "Orden de visualización"
      },
      "actions": {
        "add": "Subir elemento",
        "save": "Guardar cambios",
        "cancel": "Cancelar",
        "remove": "Eliminar elemento",
        "edit": "Editar elemento"
      },
      "messages": {
        "addSuccess": "Elemento de la galería subido correctamente",
        "addError": "No se pudo subir el elemento de la galería",
        "updateSuccess": "Elemento de la galería actualizado correctamente",
        "updateError": "No se pudo actualizar el elemento de la galería",
        "removeSuccess": "Elemento de la galería eliminado correctamente",
        "removeError": "No se pudo eliminar el elemento de la galería",
        "titleRequired": "Por favor, introduce un título para la imagen",
        "descriptionRequired": "Por favor, introduce una descripción para la imagen"
      },
      "errors": {
        "fileRequired": "Por favor, selecciona un archivo para subir",
        "invalidFileType": "Tipo de archivo no válido. Solo se admiten imágenes",
        "fileTooLarge": "El archivo es demasiado grande. El tamaño máximo es 10 MB",
        "addFailed": "No se pudo subir el elemento de la galería",
        "removeFailed": "No se pudo eliminar el elemento de la galería"
      },
      "removeDialog": {
        "title": "Eliminar elemento de la galería",
        "description": "¿Seguro que quieres eliminar este elemento de la galería? Esta acción no se puede deshacer."
      }
    },
    "services": {
      "title": "Gestión de servicios",
      "description": "Gestionar los servicios ofrecidos por este proveedor",
      "noServices": "No hay servicios asignados a este proveedor",
      "add": {
        "title": "Asignar servicio",
        "description": "Asignar una definición de servicio a este proveedor"
      },
      "form": {
        "serviceDefinition": "Servicio",
        "selectService": "Selecciona un servicio para asignar",
        "notes": "Notas de la asignación",
        "notesPlaceholder": "Introduce cualquier nota especial para esta asignación de servicio (opcional)",
        "selectedService": "Detalles del servicio seleccionado",
        "serviceName": "Nombre del servicio",
        "serviceDescription": "Descripción del servicio",
        "description": "Descripción",
        "price": "Precio",
        "duration": "Duración"
      },
      "actions": {
        "add": "Asignar servicio",
        "save": "Guardar cambios",
        "cancel": "Cancelar"
      },
      "messages": {
        "addSuccess": "Servicio asignado correctamente",
        "addError": "No se pudo asignar el servicio",
        "updateSuccess": "Servicio actualizado correctamente",
        "updateError": "No se pudo actualizar el servicio",
        "removeSuccess": "Asignación de servicio eliminada correctamente",
        "removeError": "No se pudo eliminar la asignación de servicio",
        "serviceSelectionRequired": "Por favor, selecciona un servicio para asignar",
        "priceRequired": "Por favor, introduce un precio",
        "currencyRequired": "Por favor, selecciona una moneda",
        "durationRequired": "Por favor, introduce una duración"
      },
      "removeDialog": {
        "title": "Eliminar asignación de servicio",
        "description": "¿Seguro que quieres eliminar esta asignación de servicio? Esta acción no se puede deshacer."
      },
      "units": {
        "minutesShort": "min"
      }
    },
    "policies": {
      "title": "Gestión de políticas",
      "description": "Gestionar políticas para este proveedor de servicios",
      "noPolicies": "No hay políticas configuradas para este proveedor",
      "add": {
        "title": "Añadir política",
        "description": "Definir una nueva política para este proveedor de servicios"
      },
      "form": {
        "type": "Tipo de política",
        "typePlaceholder": "Introduce el tipo de política (p. ej., Política de cancelación, Política de reembolso)",
        "description": "Descripción de la política",
        "descriptionPlaceholder": "Introduce una descripción detallada de la política..."
      },
      "actions": {
        "add": "Añadir política",
        "save": "Guardar cambios",
        "cancel": "Cancelar"
      },
      "messages": {
        "addSuccess": "Política añadida correctamente",
        "addError": "No se pudo añadir la política",
        "updateSuccess": "Política actualizada correctamente",
        "updateError": "No se pudo actualizar la política",
        "removeSuccess": "Política eliminada correctamente",
        "removeError": "No se pudo eliminar la política",
        "typeRequired": "Por favor, introduce un tipo de política",
        "descriptionRequired": "Por favor, introduce una descripción de la política",
        "duplicateType": "Ya existe una política de este tipo"
      },
      "removeDialog": {
        "title": "Eliminar política",
        "description": "¿Seguro que quieres eliminar esta política? Esta acción no se puede deshacer."
      }
    },
    "attributes": {
      "title": "Gestión de atributos",
      "description": "Gestionar atributos personalizados basados en las definiciones del tipo de proveedor",
      "noAttributes": "No hay atributos configurados para este proveedor",
      "availableDefinitions": "Definiciones disponibles",
      "noAvailableDefinitions": "Todos los atributos disponibles para este tipo de proveedor han sido configurados",
      "add": {
        "title": "Añadir atributo",
        "description": "Configurar un nuevo valor de atributo para este proveedor de servicios"
      },
      "form": {
        "attributeDefinition": "Definición de atributo",
        "selectAttribute": "Selecciona un atributo para configurar",
        "selectedAttribute": "Detalles del atributo seleccionado",
        "name": "Nombre",
        "type": "Tipo",
        "required": "Obligatorio",
        "value": "Valor del atributo",
        "valuePlaceholder": "Introduce el valor para este atributo...",
        "selectValue": "Selecciona un valor",
        "yes": "Sí",
        "no": "No"
      },
      "actions": {
        "add": "Añadir atributo",
        "save": "Guardar cambios",
        "cancel": "Cancelar",
        "retry": "Reintentar"
      },
      "messages": {
        "addSuccess": "Atributo añadido correctamente",
        "addError": "No se pudo añadir el atributo",
        "updateSuccess": "Atributo actualizado correctamente",
        "updateError": "No se pudo actualizar el atributo",
        "removeSuccess": "Atributo eliminado correctamente",
        "removeError": "No se pudo eliminar el atributo",
        "attributeRequired": "Por favor, selecciona una definición de atributo",
        "valueRequired": "Por favor, introduce un valor para el atributo",
        "fetchError": "No se pudieron cargar las definiciones de atributos"
      },
      "removeDialog": {
        "title": "Eliminar atributo",
        "description": "¿Seguro que quieres eliminar este atributo? Esta acción no se puede deshacer."
      }
    },
    "search": {
      "placeholder": "Buscar miembros del personal...",
      "noResults": "No se encontró ningún miembro del personal."
    },
    "messages": {
      "success": "Operación del proveedor de servicios completada correctamente",
      "error": "No se pudo realizar la operación del proveedor de servicios",
      "deleteSuccess": "Proveedor de servicios eliminado correctamente",
      "deleteError": "No se pudo eliminar el proveedor de servicios",
      "statusChanged": "Estado del proveedor de servicios cambiado correctamente",
      "statusChangeError": "No se pudo cambiar el estado del proveedor de servicios"
    },
    "errors": {
      "invalidPhone": "Por favor, introduce un número de teléfono válido",
      "createFailed": "No se pudo crear el proveedor de servicios",
      "updateFailed": "No se pudo actualizar el proveedor de servicios",
      "gradeRequired": "El grado es obligatorio",
      "gradeInvalid": "El grado debe estar entre A y E",
      "gradeNotUnique": "Ya existe un proveedor de servicios con este grado para este tipo en esta ubicación"
    },
    "delete": {
      "dialog": {
        "title": "Eliminar proveedor de servicios",
        "description": "¿Seguro que quieres eliminar este proveedor de servicios? Esta acción no se puede deshacer.",
        "cancel": "Cancelar",
        "confirm": "Eliminar"
      }
    }
  },
  "ProviderType": {
    "name": "Tipo de proveedor",
    "page": {
      "title": "Tipos de proveedores",
      "description": "Gestionar tipos de proveedores y sus definiciones de atributos"
    },
    "add": {
      "page": {
        "title": "Añadir tipo de proveedor",
        "description": "Crear un nuevo tipo de proveedor"
      },
      "title": "Añadir nuevo tipo de proveedor"
    },
    "update": {
      "page": {
        "title": "Actualizar tipo de proveedor",
        "description": "Editar información del tipo de proveedor"
      },
      "title": "Actualizar tipo de proveedor"
    },
    "form": {
      "name": {
        "label": "Nombre"
      },
      "description": {
        "label": "Descripción"
      },
      "isActive": "Activo",
      "attributes": "Definiciones de atributos",
      "attributesPlaceholder": "Atributos ({count} definidos)",
      "create": "Crear tipo de proveedor",
      "update": "Actualizar tipo de proveedor",
      "creating": "Creando...",
      "updating": "Actualizando...",
      "cancel": "Cancelar",
      "selectProviderType": "Selecciona el tipo de proveedor",
      "iconUrl": {
        "label": "Icono",
        "placeholder": "Seleccionar icono"
      }
    },
    "table": {
      "name": "Nombre",
      "description": "Descripción",
      "icon": "Icono",
      "attributes": "Atributos",
      "status": "Estado",
      "actions": "Acciones"
    },
    "actions": {
      "addProviderType": "Añadir tipo de proveedor",
      "editProviderType": "Editar tipo de proveedor",
      "deleteProviderType": "Eliminar tipo de proveedor",
      "deleteProviderTypeDescription": "¿Seguro que quieres eliminar este tipo de proveedor?",
      "activate": "Activar",
      "deactivate": "Desactivar",
      "toggleActivation": "Activar/Desactivar",
      "viewDetails": "Ver detalles",
      "removeAttribute": "Eliminar atributo",
      "removeAttributeDescription": "¿Seguro que quieres eliminar esta definición de atributo?",
      "retry": "Reintentar",
      "cancel": "Cancelar",
      "save": "Guardar",
      "saving": "Guardando..."
    },
    "status": {
      "active": "Activo",
      "inactive": "Inactivo"
    },
    "messages": {
      "success": "Operación del tipo de proveedor completada correctamente",
      "error": "No se pudo realizar la operación del tipo de proveedor",
      "updated": "Tipo de proveedor actualizado correctamente",
      "attributeAddSuccess": "Definición de atributo añadida correctamente",
      "attributeRemoveSuccess": "Definición de atributo eliminada correctamente",
      "attributeUpdateSuccess": "Definición de atributo actualizada correctamente"
    },
    "attributes": {
      "title": "Definiciones de atributos",
      "description": "Gestionar definiciones de atributos del tipo de proveedor y sus opciones",
      "addAttribute": "Añadir atributo",
      "addNew": "Añadir nuevo atributo",
      "noAttributes": "Aún no hay atributos definidos",
      "form": {
        "name": {
          "label": "Nombre del atributo"
        },
        "description": {
          "label": "Descripción"
        },
        "attributeType": "Tipo de atributo",
        "attributeTypePlaceholder": "Selecciona el tipo de atributo",
        "isRequired": "Obligatorio",
        "validationRules": "Reglas de validación",
        "validationRulesPlaceholder": "Introduce reglas de validación (opcional)",
        "options": "Opciones",
        "addOption": "Añadir opción",
        "noOptions": "Haz clic en 'Añadir opción' para crear opciones de selección",
        "add": "Añadir atributo",
        "adding": "Añadiendo...",
        "displayName": {
          "label": "Nombre para mostrar"
        },
        "value": {
          "label": "Valor"
        },
        "type": "Tipo",
        "required": "Obligatorio",
        "rules": "Reglas",
        "optionsCount": "Opciones",
        "yes": "Sí",
        "no": "No"
      }
    },
    "details": {
      "title": "Detalles del tipo de proveedor",
      "description": "Vista detallada de {name} con gestión de atributos",
      "basicInfo": "Información básica",
      "statistics": "Estadísticas",
      "created": "Creado",
      "modified": "Modificado",
      "attributeDefinitionsCount": "Definiciones de atributos"
    },
    "tabs": {
      "overview": "Resumen",
      "attributes": "Atributos"
    },
    "search": {
      "placeholder": "Buscar tipos de proveedores...",
      "noResults": "No se encontró ningún tipo de proveedor."
    }
  },
  "shared": {
    "selectOption": "Selecciona una opción",
    "searchPlaceholder": "Buscar...",
    "noResults": "No se encontraron resultados"
  },
  "LocalizedInput": {
    "placeholder": "Introduce {field} en {language}"
  },
  "List": {
    "loading": "Cargando...",
    "loadMore": "Cargar más"
  }
};
export default messages;