// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "Manifest": {
    "name": "L Sevin"
  },
  "LocaleLayout": {
    "title": "L Sevin",
    "description": "Plateforme de santé automatisée qui simplifie la planification des patients, de l'hébergement aux rendez-vous médicaux"
  },
  "Error": {
    "title": "Une erreur s'est produite",
    "description": "Veuillez contacter l'administrateur du système."
  },
  "NotFoundPage": {
    "title": "Page introuvable",
    "description": "Veuillez utiliser la page d'accueil du site."
  },
  "Admin": {
    "dashboard": "Tableau de bord",
    "consultings": "Consultations",
    "serviceProvidersRequest": "Demandes des prestataires de services",
    "categories": "Catégories",
    "serviceDefinitions": "Définitions de services",
    "providerTypes": "Types de prestataires",
    "staff": "Personnel",
    "serviceProviders": "Prestataires de services"
  },
  "HomePage": {
    "title": "L Sevin - Santé automatisée",
    "description": "Simplifier la planification des patients, de l'hébergement aux rendez-vous médicaux",
    "keywords": "automatisation santé,automatisation du secteur de la santé,tourisme médical,réservation médicale",
    "heroTitle": "Vivez les meilleurs services médicaux avec nous",
    "heroDescription": "Sur le chemin du bien-être, nous vous offrons des services médicaux de premier ordre, avec une équipe de spécialistes, des équipements de pointe et un environnement sûr et relaxant, engagés pour des soins et des traitements de haute qualité.",
    "heroSubtext": "Élevons votre santé à un nouveau niveau, ensemble...",
    "registerRequest": "Soumettre une demande",
    "consultationRequest": "Demander une consultation",
    "category": "Catégorie",
    "providerTypes": "Types de fournisseurs",
    "serviceProviders": {
      "title": "Prestataires de services",
      "noProviders": "Aucun prestataire disponible pour le moment",
      "priceStartsFrom": "À partir de",
      "view": "Voir",
      "viewAll": "Voir tout",
      "grade": {
        "label": "Note"
      }
    },
    "ByType": {
      "title": "Parcourir les prestataires de services",
      "description": "Trouvez les meilleurs prestataires de services pour vos besoins",
      "noResults": "Aucun prestataire de services trouvé",
      "loading": "Chargement...",
      "error": "Échec du chargement des prestataires de services. Veuillez réessayer.",
      "filters": {
        "title": "Filtres",
        "search": "Rechercher",
        "searchPlaceholder": "Rechercher des prestataires...",
        "location": "Localisation",
        "attributes": "Attributs",
        "country": "Pays",
        "city": "Ville",
        "clearAll": "Tout effacer",
        "selectCountry": "Sélectionnez un pays",
        "selectCity": "Sélectionnez une ville",
        "allCountries": "Tous les pays",
        "allCities": "Toutes les villes",
        "selectCountryFirst": "Sélectionnez d'abord un pays",
        "loadingCities": "Chargement des villes...",
        "noFilters": "Aucun filtre disponible",
        "activeFilters": "Filtres actifs",
        "any": "Tout",
        "yes": "Oui",
        "no": "Non",
        "booleanTrue": "Oui",
        "booleanFalse": "Non"
      }
    },
    "locationSwitcher": {
      "countries": "Pays",
      "cities": "Villes",
      "allCountries": "Tous les pays",
      "allCities": "Toutes les villes",
      "loading": "Chargement..."
    }
  },
  "ServiceProviderPage": {
    "title": "Prestataire de services",
    "description": "Détails du prestataire de services",
    "keywords": "prestataire de services,détails du prestataire,page prestataire",
    "contactProvider": "Contacter le prestataire",
    "aboutProvider": "À propos de ce prestataire",
    "availableServices": "Services disponibles",
    "policies": "Politiques",
    "viewGallery": "Voir la galerie",
    "images": "Images",
    "imagesCount": "{count} images",
    "noDescription": "Aucune description disponible",
    "address": "Adresse",
    "location": "Emplacement",
    "ourStaff": "Notre personnel",
    "noServices": "Aucun service disponible",
    "noPolicies": "Aucune politique disponible",
    "noImages": "Aucune image disponible",
    "close": "Fermer",
    "attributes": "Attributs",
    "requests": {
      "title": "Demandes au prestataire de services",
      "description": "Gérer toutes les demandes des clients adressées aux prestataires.",
      "provider": "Prestataire",
      "customer": "Client",
      "email": "E-mail",
      "message": "Message",
      "form": {
        "message": {
          "label": "Message",
          "placeholder": "Écrivez votre message..."
        }
      },
      "status": {
        "title": "Statut",
        "Pending": "En attente",
        "Approved": "Approuvé",
        "Rejected": "Refusé"
      },
      "date": "Date",
      "actions": "Actions",
      "approve": "Approuver",
      "reject": "Refuser",
      "viewAddRequest": "Voir / Ajouter une demande",
      "myRequests": "Mes demandes",
      "formTitle": "Contacter le prestataire",
      "formMessage": "Message",
      "submit": "Envoyer",
      "openRequests": "Demandes ouvertes"
    },
    "Comments": {
      "title": "Commentaires et Avis",
      "allComments": "Tous les Commentaires",
      "yourComment": "Votre commentaire",
      "noComments": "Aucun commentaire pour le moment. Soyez le premier à commenter!",
      "loading": "Chargement des commentaires...",
      "loadError": "Échec du chargement des commentaires",
      "rating": "Évaluation",
      "comment": "Votre Commentaire",
      "commentPlaceholder": "Partagez votre expérience...",
      "submit": "Envoyer le Commentaire",
      "submitting": "Envoi en cours...",
      "addSuccess": "Commentaire Ajouté",
      "addSuccessMessage": "Votre commentaire a été publié avec succès.",
      "addFailed": "Échec de l'ajout du commentaire",
      "deleteConfirmTitle": "Supprimer le Commentaire",
      "deleteConfirm": "Êtes-vous sûr de vouloir supprimer ce commentaire?",
      "deleteSuccess": "Commentaire Supprimé",
      "deleteSuccessMessage": "Votre commentaire a été supprimé avec succès.",
      "deleteFailed": "Échec de la suppression du commentaire",
      "form": {
        "commentText": {
          "label": "Texte du commentaire"
        }
      }
    }
  },
  "LocaleSwitcher": {
    "label": "Changer de langue",
    "fa": "Persan",
    "en": "Anglais",
    "tr": "Turc",
    "ar": "Arabe",
    "es": "Espagnol",
    "ku": "Kurde",
    "de": "Allemand",
    "fr": "Français"
  },
  "Logo": {
    "medical": "Médical",
    "tourism": "Tourisme",
    "beauty": "Beauté"
  },
  "UserInfo": {
    "profile": "Profil",
    "settings": "Paramètres",
    "signOut": "Se déconnecter",
    "adminPanel": "Panneau d'administration"
  },
  "FormErrors": {
    "required": "{field} est requis",
    "tooShort": "{field} doit contenir au moins {length} caractères",
    "invalid": "{field} est invalide",
    "invalidEmail": "Adresse e-mail invalide",
    "invalidPhoneNumber": "Veuillez saisir un numéro de téléphone valide",
    "passwordTooShort": "Le mot de passe doit contenir au moins {length} caractères",
    "passwordsDoNotMatch": "Les mots de passe ne correspondent pas",
    "invalidCode": "Le code de vérification doit comporter 6 chiffres",
    "invalidFile": "Veuillez téléverser un fichier valide",
    "invalidFileType": "Type de fichier non pris en charge",
    "fileTooLarge": "La taille du fichier dépasse la limite (max 5 Mo)",
    "notMatch": "Les mots de passe ne correspondent pas",
    "invalidPhone": "Veuillez saisir un numéro de téléphone valide"
  },
  "User": {
    "Information": {
      "incompleteProfileTitle": "Profil incomplet",
      "completeProfileWarning": "Veuillez compléter vos informations",
      "goToProfile": "Aller au profil"
    },
    "Profile": {
      "page": {
        "title": "Informations du profil",
        "description": "Pour mettre à jour votre profil, veuillez saisir soigneusement les informations ci-dessous."
      },
      "personalInfo": {
        "title": "Informations personnelles",
        "base": "Informations de base",
        "documents": "Documents"
      },
      "tabs": {
        "basic": "Informations de base",
        "additional": "Informations supplémentaires",
        "documents": "Documents"
      },
      "form": {
        "firstName": {
          "label": "Prénom"
        },
        "lastName": {
          "label": "Nom"
        },
        "email": {
          "label": "E-mail"
        },
        "phoneNumber": {
          "label": "Numéro de téléphone"
        },
        "birthDate": {
          "label": "Date de naissance"
        },
        "gender": {
          "label": "Sexe"
        },
        "country": "Pays",
        "city": "Ville",
        "street": "Rue",
        "detail": "Détails supplémentaires",
        "zipCode": "Code postal",
        "documentType": {
          "label": "Type de document"
        },
        "documentFile": {
          "label": "Fichier du document"
        },
        "existingDocuments": "Vos documents téléversés",
        "viewDocument": "Voir le document",
        "address": {
          "countryCode": "Code pays",
          "cityCode": "Code ville",
          "street": "Rue",
          "detail": "Détails supplémentaires",
          "zipCode": "Code postal"
        }
      },
      "placeholders": {
        "birthDate": "Sélectionner la date de naissance",
        "documentType": "Sélectionner le type de document",
        "documentFile": "Cliquer pour téléverser ou glisser-déposer"
      },
      "messages": {
        "updateSuccess": "Profil mis à jour avec succès",
        "documentUploadSuccess": "Document téléversé avec succès",
        "deleteDocumentConfirmationTitle": "Supprimer le document",
        "deleteDocumentConfirmationMessage": "Voulez-vous vraiment supprimer ce document ?",
        "deleteDocumentSuccess": "Document supprimé avec succès",
        "deleteDocumentError": "Échec de la suppression du document"
      },
      "validation": {
        "countryRequired": "Veuillez sélectionner un pays",
        "cityRequired": "Veuillez sélectionner une ville"
      },
      "errors": {
        "updateFailed": "Échec de la mise à jour du profil",
        "documentUploadFailed": "Échec du téléversement du document",
        "documentDeleteFailed": "Échec de la suppression du document",
        "invalidFileType": "Type de fichier invalide",
        "fileTooLarge": "Fichier trop volumineux",
        "supportedFormats": "Formats pris en charge : .zip, .pdf, formats image (max 5 Mo)"
      },
      "buttons": {
        "save": "Enregistrer les modifications",
        "upload": "Téléverser un document",
        "delete": "Supprimer le document"
      }
    }
  },
  "Common": {
    "Gender": {
      "title": "Sexe",
      "male": "Homme",
      "female": "Femme",
      "other": "Autre"
    },
    "DocumentType": {
      "title": "Type de document",
      "Passport": "Passeport",
      "Visa": "Visa",
      "DriverLicense": "Permis de conduire",
      "BankStatement": "Relevé bancaire",
      "IdCard": "Carte d'identité",
      "Medical": "Dossier médical",
      "Beauty": "Procédure esthétique",
      "Tourism": "Document de tourisme",
      "Other": "Autre"
    },
    "FileUpload": {
      "errors": {
        "fileError": "Erreur de fichier, veuillez vérifier les exigences",
        "fileTooLarge": "Fichier trop volumineux. Taille maximale {size} Mo"
      }
    },
    "Address": {
      "title": "Adresse",
      "country": "Pays",
      "city": "Ville",
      "street": "Rue",
      "detail": "Détails supplémentaires",
      "zipCode": "Code postal"
    },
    "Location": {
      "title": "Emplacement",
      "country": "Pays",
      "city": "Ville",
      "selectCountry": "Sélectionner un pays",
      "selectCity": "Sélectionner une ville",
      "noCountrySelected": "Aucun pays sélectionné",
      "noCitiesAvailable": "Aucune ville disponible",
      "loading": "Chargement..."
    },
    "DatePicker": {
      "placeholder": "Sélectionner une date",
      "range": "Plage de dates",
      "multiple": "Dates multiples",
      "single": "Date unique"
    },
    "DataTable": {
      "search": "Rechercher...",
      "reset": "Réinitialiser",
      "noResults": "Aucun résultat.",
      "rowsSelected": "{count} sur {total} ligne(s) sélectionnée(s).",
      "page": "Page {current} sur {total}",
      "clearFilters": "Effacer les filtres",
      "sortAscending": "Tri croissant",
      "sortDescending": "Tri décroissant",
      "hideColumn": "Masquer la colonne"
    },
    "Input": {
      "search": "Rechercher..."
    },
    "Fetcher": {
      "noData": "Aucune donnée trouvée",
      "error": "Une erreur s'est produite : {detail}"
    },
    "Confirm": {
      "title": "Attention",
      "cancel": "Annuler",
      "confirm": "Confirmer"
    }
  },
  "Auth": {
    "SignUp": {
      "page": {
        "title": "S'inscrire",
        "description": "Pour vous inscrire, veuillez saisir soigneusement les informations ci-dessous.",
        "alreadyHaveAccount": "Vous avez déjà un compte ?",
        "login": "Se connecter"
      },
      "form": {
        "firstName": {
          "label": "Prénom"
        },
        "lastName": {
          "label": "Nom"
        },
        "email": {
          "label": "E-mail"
        },
        "phoneNumber": {
          "label": "Numéro de téléphone"
        },
        "password": {
          "label": "Mot de passe"
        },
        "signUp": "Envoyer le code"
      },
      "placeholders": {
        "firstName": "Jean",
        "lastName": "Dupont",
        "email": "exemple@gmail.com",
        "password": "*******"
      },
      "errors": {
        "invalidPhone": "Numéro de téléphone invalide"
      },
      "messages": {
        "signUpSuccess": "Inscription réussie",
        "signUpError": "Erreur lors de l'envoi du code. Veuillez réessayer."
      }
    },
    "SignIn": {
      "page": {
        "title": "Connexion",
        "description": "Pour vous connecter, veuillez saisir vos informations d'inscription.",
        "noAccount": "Pas de compte ?",
        "signUp": "S'inscrire",
        "forgotPassword": "Mot de passe oublié ?"
      },
      "form": {
        "userNameOrEmail": {
          "label": "E-mail ou numéro de téléphone"
        },
        "password": {
          "label": "Mot de passe"
        },
        "remember": "Se souvenir de moi",
        "login": "Se connecter"
      },
      "errors": {
        "invalidCredentials": "Identifiants invalides",
        "authError": "Erreur d'authentification"
      },
      "messages": {
        "loginSuccess": "Connexion réussie",
        "loginError": "Erreur lors de la connexion. Veuillez réessayer."
      }
    },
    "ForgotPassword": {
      "page": {
        "title": "Mot de passe oublié",
        "description": "Pour récupérer votre mot de passe, veuillez saisir votre numéro de téléphone.",
        "rememberPassword": "Vous vous souvenez de votre mot de passe ?",
        "login": "Se connecter"
      },
      "form": {
        "phoneNumber": "Numéro de téléphone",
        "submit": "Envoyer le lien de récupération",
        "userNameOrEmail": {
          "label": "E-mail ou numéro de téléphone"
        }
      },
      "messages": {
        "success": "Lien de récupération envoyé.",
        "error": "Erreur lors de l'envoi du lien. Veuillez réessayer."
      }
    },
    "Otp": {
      "page": {
        "title": "Code de vérification",
        "description": "Saisissez le code de vérification envoyé à {mobile}.",
        "wrongNumber": "Mauvais numéro ?",
        "changeNumber": "Changer de numéro"
      },
      "form": {
        "verify": "Vérifier",
        "resendCode": "Renvoyer le code",
        "resendCodeTimer": "Renvoyer le code ({time})",
        "code": {
          "label": "Code de vérification"
        },
        "phoneNumber": {
          "label": "Numéro de téléphone"
        }
      },
      "messages": {
        "success": "Code vérifié avec succès.",
        "error": "Erreur lors de la vérification. Veuillez réessayer.",
        "resendSuccess": "Code de vérification envoyé avec succès.",
        "resendError": "Erreur lors de l'envoi du code. Veuillez réessayer."
      }
    },
    "VerifyEmail": {
      "form": {
        "email": "E-mail",
        "code": "Code de vérification"
      },
      "messages": {
        "success": "E-mail vérifié avec succès.",
        "error": "Erreur lors de la vérification de l'e-mail. Veuillez réessayer."
      }
    },
    "OnBoarding": {
      "step1": {
        "title": "Votre santé est notre priorité",
        "description": "Une expérience unique de services médicaux avancés avec des commodités complètes et un voyage simple et agréable, conçu pour vos besoins spécifiques et en tenant compte des détails importants du voyage.",
        "primaryButton": "Suivant",
        "secondaryButton": "Ignorer"
      },
      "step2": {
        "title": "Séjour, traitement, détente",
        "description": "Des services médicaux spécialisés et avancés à l'hébergement dans les meilleurs hôtels, nous vous offrons une expérience unique et un voyage confortable et sans souci pour répondre à vos besoins.",
        "primaryButton": "Se connecter / S'inscrire",
        "secondaryButton": "Ignorer"
      },
      "step3": {
        "title": "Votre parcours de santé commence ici",
        "description": "Commencez dès aujourd'hui votre parcours de santé personnalisé avec nous. Notre équipe d'experts est prête à vous fournir les meilleurs soins et la meilleure expérience.",
        "primaryButton": "Commencer",
        "secondaryButton": "Se connecter"
      }
    }
  },
  "Dashboard": {
    "page": {
      "title": "Vue d'ensemble du tableau de bord",
      "description": "Tableau de bord d'administration avec statistiques système et aperçu de l'activité récente"
    },
    "stats": {
      "totalConsultings": {
        "title": "Consultations totales",
        "description": "Demandes de consultation actives"
      },
      "pendingServiceProviderRequests": {
        "title": "Demandes en attente",
        "description": "En attente d'approbation"
      },
      "totalServiceProviders": {
        "title": "Prestataires de services",
        "description": "Prestataires enregistrés"
      },
      "totalStaff": {
        "title": "Membres du personnel",
        "description": "Personnel actif"
      }
    },
    "recentConsultings": {
      "title": "Consultations récentes",
      "viewAll": "Tout afficher",
      "empty": "Aucune demande de consultation récente",
      "table": {
        "customer": "Client",
        "category": "Catégorie",
        "description": "Description",
        "date": "Date"
      }
    },
    "recentRequests": {
      "title": "Demandes récentes des prestataires",
      "viewAll": "Tout afficher",
      "empty": "Aucune demande récente",
      "table": {
        "customer": "Client",
        "serviceProvider": "Prestataire de services",
        "message": "Message",
        "status": {
          "title": "Statut",
          "Pending": "En attente",
          "Approved": "Approuvé",
          "Rejected": "Refusé"
        },
        "date": "Date"
      }
    },
    "quickActions": {
      "title": "Actions rapides",
      "totalConsultings": {
        "title": "Consultations",
        "description": "Gérer les demandes de consultation"
      },
      "totalServiceProviders": {
        "title": "Prestataires",
        "description": "Gérer les prestataires"
      },
      "totalCategories": {
        "title": "Catégories",
        "description": "Gérer les catégories de services"
      },
      "totalStaff": {
        "title": "Personnel",
        "description": "Gérer les membres du personnel"
      },
      "totalProviderTypes": {
        "title": "Types de prestataires",
        "description": "Gérer les types de prestataires"
      },
      "totalServiceDefinitions": {
        "title": "Définitions de services",
        "description": "Gérer les définitions de services"
      }
    }
  },
  "Consulting": {
    "page": {
      "title": "Demander une consultation",
      "description": "Demandez une consultation pour vos besoins médicaux ou esthétiques.",
      "adminTitle": "Demandes de consultation",
      "adminDescription": "Gérer toutes les demandes de consultation des clients."
    },
    "table": {
      "customer": "Client",
      "email": "E-mail",
      "description": "Description",
      "category": "Catégorie"
    },
    "form": {
      "formTitle": "Demande de consultation",
      "formDescription": "Veuillez fournir les détails de votre demande de consultation.",
      "categoryId": {
        "label": "Catégorie"
      },
      "categoryName": {
        "label": "Nom de la catégorie"
      },
      "description": {
        "label": "Description"
      },
      "documentIds": {
        "label": "Documents associés"
      }
    },
    "placeholders": {
      "category": "Sélectionner une catégorie",
      "searchCategory": "Rechercher des catégories...",
      "description": "Veuillez décrire en détail vos besoins et exigences..."
    },
    "descriptions": {
      "description": "Fournissez un maximum de détails sur vos besoins et toute histoire médicale ou préoccupation pertinente.",
      "documents": "Sélectionnez les documents pertinents pour votre demande."
    },
    "messages": {
      "createSuccess": "Demande de consultation envoyée avec succès",
      "noDocuments": "Vous n'avez pas encore téléversé de documents. Veuillez téléverser des documents pertinents d'abord.",
      "noCategories": "Aucune catégorie trouvée."
    },
    "errors": {
      "createFailed": "Échec de l'envoi de la demande de consultation"
    },
    "buttons": {
      "submit": "Envoyer la demande",
      "uploadDocuments": "Téléverser des documents"
    }
  },
  "Category": {
    "name": "Catégorie",
    "page": {
      "title": "Catégories",
      "description": "Gérer les catégories et leur hiérarchie"
    },
    "add": {
      "page": {
        "title": "Ajouter une catégorie",
        "description": "Créer une nouvelle catégorie"
      },
      "title": "Ajouter une nouvelle catégorie",
      "childTitle": "Ajouter une sous-catégorie"
    },
    "update": {
      "page": {
        "title": "Mettre à jour la catégorie",
        "description": "Modifier les informations de la catégorie"
      },
      "title": "Mettre à jour la catégorie"
    },
    "form": {
      "name": {
        "label": "Nom",
        "translations": "Le nom de la catégorie est requis dans au moins une langue"
      },
      "namePlaceholder": "Saisir le nom de la catégorie",
      "description": {
        "label": "Description",
        "translations": "La description de la catégorie est requise dans au moins une langue"
      },
      "descriptionPlaceholder": "Saisir la description de la catégorie",
      "parentId": "Catégorie parente",
      "parentIdPlaceholder": "Sélectionner la catégorie parente",
      "displayOrder": "Ordre d'affichage",
      "displayOrderPlaceholder": "Saisir l'ordre d'affichage",
      "isActive": "Actif",
      "create": "Créer la catégorie",
      "update": "Mettre à jour la catégorie",
      "creating": "Création...",
      "updating": "Mise à jour...",
      "cancel": "Annuler"
    },
    "table": {
      "name": "Nom",
      "description": "Description",
      "parent": "Parent",
      "displayOrder": "Ordre",
      "status": "Statut",
      "actions": "Actions"
    },
    "actions": {
      "addCategory": "Ajouter une catégorie",
      "addChildCategory": "Ajouter une sous-catégorie",
      "editCategory": "Modifier la catégorie",
      "deleteCategory": "Supprimer la catégorie",
      "deleteCategoryDescription": "Voulez-vous vraiment supprimer cette catégorie ?",
      "toggleActivation": "Basculer l'activation"
    },
    "status": {
      "active": "Actif",
      "inactive": "Inactif"
    },
    "messages": {
      "success": "Opération sur la catégorie effectuée avec succès",
      "error": "Échec de l'opération sur la catégorie",
      "deleteConfirmation": "Voulez-vous vraiment supprimer « {name} » ?",
      "deleteSuccess": "Catégorie supprimée avec succès",
      "deleteError": "Échec de la suppression de la catégorie",
      "deleteErrorLog": "Erreur lors de la suppression de la catégorie :"
    }
  },
  "ServiceDefinition": {
    "name": "Définition de service",
    "page": {
      "title": "Définitions de services",
      "description": "Gérer les définitions de services et leurs configurations"
    },
    "add": {
      "page": {
        "title": "Ajouter une définition de service",
        "description": "Créer une nouvelle définition de service"
      },
      "title": "Ajouter une nouvelle définition de service"
    },
    "update": {
      "page": {
        "title": "Mettre à jour la définition de service",
        "description": "Modifier les informations de la définition de service"
      },
      "title": "Mettre à jour la définition de service"
    },
    "form": {
      "name": {
        "label": "Nom"
      },
      "description": {
        "label": "Description"
      },
      "categoryId": {
        "label": "Catégorie",
        "placeholder": "Sélectionner une catégorie"
      },
      "durationMinutes": {
        "label": "Durée (minutes)",
        "placeholder": "Saisir la durée en minutes"
      },
      "currency": {
        "label": "Devise",
        "placeholder": "Saisir la devise"
      },
      "value": {
        "label": "Prix",
        "placeholder": "Saisir le prix"
      },
      "pricingModel": {
        "label": "Modèle de tarification",
        "placeholder": "Sélectionner un modèle"
      },
      "isActive": {
        "label": "Actif"
      },
      "attributeDefinitions": "Définitions d'attributs",
      "requirements": "Exigences",
      "create": "Créer la définition de service",
      "update": "Mettre à jour la définition de service",
      "creating": "Création...",
      "updating": "Mise à jour...",
      "cancel": "Annuler"
    },
    "table": {
      "name": "Nom",
      "category": "Catégorie",
      "description": "Description",
      "duration": "Durée",
      "price": "Prix",
      "status": "Statut",
      "actions": "Actions"
    },
    "actions": {
      "addServiceDefinition": "Ajouter une définition de service",
      "editServiceDefinition": "Modifier la définition de service",
      "deleteServiceDefinition": "Supprimer la définition de service",
      "deleteServiceDefinitionDescription": "Voulez-vous vraiment supprimer cette définition de service ?",
      "toggleActivation": "Basculer l'activation",
      "viewDetails": "Voir les détails",
      "removeAttribute": "Supprimer l'attribut",
      "removeAttributeDescription": "Voulez-vous vraiment supprimer cette définition d'attribut ?",
      "removeRequirement": "Supprimer l'exigence",
      "removeRequirementDescription": "Voulez-vous vraiment supprimer cette exigence ?",
      "retry": "Réessayer",
      "cancel": "Annuler",
      "save": "Enregistrer",
      "saving": "Enregistrement en cours..."
    },
    "status": {
      "active": "Actif",
      "inactive": "Inactif"
    },
    "messages": {
      "success": "Opération de définition de service réussie",
      "error": "Échec de l'opération de définition de service",
      "updated": "Définition de service mise à jour avec succès",
      "attributeAddSuccess": "Attribut ajouté avec succès",
      "attributeRemoveSuccess": "Attribut supprimé avec succès",
      "requirementAddSuccess": "Exigence ajoutée avec succès",
      "requirementRemoveSuccess": "Exigence supprimée avec succès",
      "attributeUpdateSuccess": "Définition d'attribut mise à jour avec succès",
      "requirementUpdateSuccess": "Exigence mise à jour avec succès",
      "fetchError": "Échec du chargement des détails de la définition de service"
    },
    "pricingModels": {
      "Fixed": "Prix fixe",
      "Variable": "Prix variable",
      "Hourly": "Taux horaire",
      "Package": "Prix forfaitaire"
    },
    "attributes": {
      "title": "Définitions d'attributs",
      "description": "Gérer les attributs du service et leurs options",
      "addAttribute": "Ajouter un attribut",
      "addNew": "Ajouter un nouvel attribut",
      "noAttributes": "Aucun attribut défini",
      "form": {
        "name": {
          "label": "Nom de l'attribut",
          "placeholder": "Saisir le nom de l'attribut"
        },
        "description": {
          "label": "Description",
          "placeholder": "Saisir la description de l'attribut"
        },
        "attributeType": "Type d'attribut",
        "attributeTypePlaceholder": "Sélectionner un type d'attribut",
        "isRequired": "Obligatoire",
        "affectsPricing": "Influence le prix",
        "displayOrder": "Ordre d'affichage",
        "options": "Options",
        "addOption": "Ajouter une option",
        "noOptions": "Cliquez sur « Ajouter une option » pour créer des choix",
        "add": "Ajouter l'attribut",
        "adding": "Ajout en cours...",
        "displayName": {
          "label": "Nom d'affichage",
          "placeholder": "Saisir le nom d'affichage"
        },
        "value": "Valeur",
        "extraPrice": "Supplément",
        "type": "Type",
        "required": "Obligatoire",
        "affectsPricingLabel": "Influence le prix",
        "yes": "Oui",
        "no": "Non"
      }
    },
    "requirements": {
      "title": "Exigences",
      "description": "Gérer les exigences et conditions du service",
      "addRequirement": "Ajouter une exigence",
      "addNew": "Ajouter une nouvelle exigence",
      "noRequirements": "Aucune exigence définie",
      "mandatory": "Obligatoire",
      "optional": "Optionnel",
      "form": {
        "description": {
          "label": "Description de l'exigence",
          "placeholder": "Saisir la description de l'exigence"
        },
        "isMandatory": "Exigence obligatoire",
        "isMandatoryDescription": "Cette exigence est-elle obligatoire pour le service",
        "add": "Ajouter l'exigence",
        "adding": "Ajout en cours...",
        "update": "Mettre à jour l'exigence",
        "updating": "Mise à jour en cours...",
        "cancel": "Annuler"
      }
    },
    "details": {
      "title": "Détails de la définition de service",
      "description": "Vue détaillée de {name} avec gestion des attributs et exigences",
      "basicInfo": "Informations de base",
      "pricingInfo": "Informations tarifaires"
    },
    "tabs": {
      "overview": "Aperçu",
      "attributes": "Attributs",
      "requirements": "Exigences"
    },
    "search": {
      "placeholder": "Rechercher des définitions de services...",
      "noResults": "Aucune définition de service trouvée."
    },
    "units": {
      "minutes": "min",
      "minutesShort": "min"
    }
  },
  "Staff": {
    "name": "Personnel",
    "page": {
      "title": "Personnel",
      "description": "Gérer les membres du personnel et leurs plannings"
    },
    "add": {
      "page": {
        "title": "Ajouter un membre du personnel",
        "description": "Créer un nouveau membre"
      },
      "title": "Ajouter un nouveau membre du personnel"
    },
    "update": {
      "page": {
        "title": "Mettre à jour le personnel",
        "description": "Modifier les informations du membre"
      },
      "title": "Mettre à jour le membre du personnel"
    },
    "form": {
      "name": {
        "label": "Nom complet",
        "placeholder": "Saisir le nom complet"
      },
      "biography": {
        "label": "Biographie",
        "placeholder": "Saisir la biographie du membre"
      },
      "title": {
        "label": "Titre",
        "placeholder": "Saisir le poste/titre du membre"
      },
      "profileImageUrl": "URL de la photo de profil",
      "profileImageUrlPlaceholder": "Saisir l'URL de la photo de profil",
      "isActive": "Actif",
      "availabilities": "Planning de disponibilité",
      "serviceAssignments": "Affectations de services",
      "create": "Créer le membre",
      "update": "Mettre à jour le membre",
      "creating": "Création...",
      "updating": "Mise à jour...",
      "cancel": "Annuler",
      "save": "Enregistrer",
      "saving": "Enregistrement en cours..."
    },
    "table": {
      "name": "Nom",
      "title": "Titre",
      "status": "Statut",
      "services": "Services",
      "biography": "Biographie",
      "actions": "Actions"
    },
    "actions": {
      "addStaff": "Ajouter un membre",
      "editStaff": "Modifier le membre",
      "deleteStaff": "Supprimer le membre",
      "deleteStaffDescription": "Voulez-vous vraiment supprimer ce membre du personnel ?",
      "viewDetails": "Voir les détails",
      "toggleActivation": "Basculer l'activation",
      "retry": "Réessayer",
      "cancel": "Annuler"
    },
    "status": {
      "active": "Actif",
      "inactive": "Inactif"
    },
    "messages": {
      "success": "Opération sur le personnel réussie",
      "error": "Échec de l'opération sur le personnel",
      "fetchError": "Échec du chargement des détails du membre",
      "availabilityAddSuccess": "Disponibilité ajoutée avec succès",
      "availabilityAddError": "Échec de l'ajout de la disponibilité",
      "availabilityUpdateSuccess": "Disponibilité mise à jour avec succès",
      "availabilityUpdateError": "Échec de la mise à jour de la disponibilité",
      "availabilityRemoveSuccess": "Disponibilité supprimée avec succès",
      "availabilityRemoveError": "Échec de la suppression de la disponibilité",
      "serviceAddSuccess": "Service affecté avec succès",
      "serviceAddError": "Échec de l'affectation du service",
      "serviceUpdateSuccess": "Service mis à jour avec succès",
      "serviceUpdateError": "Échec de la mise à jour du service",
      "serviceRemoveSuccess": "Service retiré avec succès",
      "serviceRemoveError": "Échec du retrait du service",
      "serviceSelectionRequired": "Veuillez sélectionner un service à affecter"
    },
    "details": {
      "title": "Détails du membre",
      "description": "Affichage des détails pour {name}",
      "basicInfo": "Informations de base",
      "statsInfo": "Statistiques",
      "totalAvailabilities": "Total des disponibilités",
      "totalServices": "Total des services",
      "activeServices": "Services actifs"
    },
    "tabs": {
      "overview": "Aperçu",
      "availabilities": "Disponibilités",
      "services": "Services"
    },
    "availability": {
      "title": "Disponibilités du membre",
      "description": "Gérer le planning de disponibilité du membre",
      "noAvailabilities": "Aucune disponibilité configurée",
      "recurring": "Récurrent",
      "specific": "Date spécifique",
      "specificDate": "Date spécifique",
      "add": {
        "title": "Ajouter une disponibilité",
        "description": "Configurer une nouvelle disponibilité pour ce membre"
      },
      "form": {
        "dayOfWeek": "Jour de la semaine",
        "startTime": "Heure de début",
        "endTime": "Heure de fin",
        "isRecurring": "Récurrent chaque semaine",
        "specificDate": "Date spécifique",
        "status": "Statut",
        "selectStartTime": "Sélectionner l'heure de début",
        "selectEndTime": "Sélectionner l'heure de fin"
      },
      "timePicker": {
        "selectTime": "Sélectionner l'heure",
        "hour": "Heure",
        "minute": "Minute",
        "selected": "Sélectionné"
      },
      "validation": {
        "startTimeAfterEnd": "L'heure de début doit être antérieure à l'heure de fin",
        "endTimeBeforeStart": "L'heure de fin doit être postérieure à l'heure de début",
        "endTimeMustBeAfterStartTime": "L'heure de fin doit être postérieure à l'heure de début",
        "timeAutoAdjusted": "L'heure de fin a été ajustée automatiquement"
      },
      "days": {
        "Sunday": "Dimanche",
        "Monday": "Lundi",
        "Tuesday": "Mardi",
        "Wednesday": "Mercredi",
        "Thursday": "Jeudi",
        "Friday": "Vendredi",
        "Saturday": "Samedi"
      },
      "status": {
        "available": "Disponible",
        "busy": "Occupé",
        "onLeave": "En congé",
        "inactive": "Inactif"
      },
      "actions": {
        "add": "Ajouter la disponibilité"
      },
      "removeDialog": {
        "title": "Supprimer la disponibilité",
        "description": "Voulez-vous vraiment supprimer cette disponibilité ? Cette action est irréversible."
      },
      "badges": {
        "available": "Disponible",
        "busy": "Occupé",
        "onLeave": "En congé",
        "inactive": "Inactif"
      }
    },
    "services": {
      "title": "Services affectés",
      "description": "Gérer les services que ce membre peut fournir",
      "noServices": "Aucun service affecté à ce membre",
      "allServicesAssigned": "Tous les services disponibles ont déjà été affectés à ce membre",
      "add": {
        "title": "Affecter un nouveau service",
        "description": "Affecter une définition de service à ce membre"
      },
      "form": {
        "serviceDefinition": "Service",
        "selectService": "Sélectionner un service",
        "notes": "Notes",
        "notesPlaceholder": "Saisir des notes particulières pour cette affectation"
      },
      "actions": {
        "add": "Affecter le service"
      },
      "removeDialog": {
        "title": "Retirer l'affectation du service",
        "description": "Voulez-vous vraiment retirer cette affectation ? Cette action est irréversible."
      }
    },
    "units": {
      "minutes": "min",
      "minutesShort": "min"
    }
  },
  "ServiceProvider": {
    "name": "Prestataire de services",
    "contactProvider": "Contacter le prestataire",
    "aboutProvider": "À propos de ce prestataire",
    "availableServices": "Services disponibles",
    "viewGallery": "Voir la galerie",
    "images": "Images",
    "imagesCount": "{count} images",
    "noDescription": "Aucune description disponible",
    "noServices": "Aucun service disponible",
    "noPolicies": "Aucune politique disponible",
    "noImages": "Aucune image disponible",
    "page": {
      "title": "Prestataires de services",
      "description": "Gérer les prestataires et leurs profils complets"
    },
    "add": {
      "page": {
        "title": "Ajouter un prestataire",
        "description": "Créer un nouveau prestataire"
      },
      "title": "Ajouter un nouveau prestataire"
    },
    "update": {
      "page": {
        "title": "Mettre à jour le prestataire",
        "description": "Modifier les informations du prestataire"
      },
      "title": "Mettre à jour le prestataire"
    },
    "details": {
      "page": {
        "title": "Détails du prestataire",
        "description": "Vue complète de la gestion du prestataire"
      },
      "title": "Détails du prestataire",
      "basicInfo": "Informations de base",
      "statsInfo": "Statistiques",
      "totalStaff": "Personnel total",
      "totalServices": "Total des services",
      "totalPolicies": "Total des politiques",
      "totalGalleryItems": "Total des éléments de galerie",
      "totalAttributes": "Total des attributs",
      "tabs": {
        "info": "Informations",
        "staff": "Personnel",
        "services": "Services",
        "policies": "Politiques",
        "gallery": "Galerie",
        "attributes": "Attributs"
      }
    },
    "form": {
      "name": {
        "label": "Nom du prestataire",
        "placeholder": "Saisir le nom du prestataire"
      },
      "description": {
        "label": "Description",
        "placeholder": "Saisir la description du prestataire"
      },
      "providerTypeId": {
        "label": "Type de prestataire",
        "placeholder": "Sélectionner un type de prestataire"
      },
      "grade": {
        "label": "Note (optionnel)",
        "placeholder": "Sélectionner une note",
        "none": "Aucune note"
      },
      "country": {
        "label": "Pays",
        "placeholder": "Sélectionner un pays"
      },
      "city": {
        "label": "Ville",
        "placeholder": "Sélectionner une ville"
      },
      "coordinates": {
        "label": "Coordonnées",
        "description": "Saisir les coordonnées"
      },
      "location": {
        "label": "Emplacement",
        "description": "Saisir l'emplacement"
      },
      "email": {
        "label": "E-mail",
        "placeholder": "Saisir l'e-mail du prestataire"
      },
      "phoneNumber": {
        "label": "Numéro de téléphone",
        "placeholder": "Saisir le numéro de téléphone"
      },
      "sections": {
        "basicInfo": "Informations de base",
        "addressInfo": "Adresse",
        "contactInfo": "Coordonnées"
      },
      "street": {
        "label": "Rue",
        "placeholder": "Saisir la rue et le numéro"
      },
      "detail": {
        "label": "Détails de l'adresse",
        "placeholder": "Saisir des détails supplémentaires"
      },
      "zipCode": {
        "label": "Code postal",
        "placeholder": "Saisir le code postal"
      },
      "selectCountryFirst": "Veuillez d'abord sélectionner un pays",
      "noCitiesAvailable": "Aucune ville disponible pour le pays sélectionné",
      "actions": {
        "save": "Enregistrer les modifications",
        "saving": "Enregistrement...",
        "cancel": "Annuler"
      },
      "website": "Site web",
      "websitePlaceholder": "Saisir l'URL du site web",
      "address": "Informations d'adresse",
      "isActive": "Actif",
      "staffAssignments": "Affectations du personnel",
      "serviceOfferings": "Offres de services",
      "create": "Créer le prestataire",
      "update": "Mettre à jour le prestataire",
      "creating": "Création...",
      "updating": "Mise à jour...",
      "cancel": "Annuler"
    },
    "table": {
      "headers": {
        "name": "Nom",
        "description": "Description",
        "providerType": "Type de prestataire",
        "contactEmail": "E-mail",
        "contactPhone": "Téléphone",
        "address": "Adresse",
        "serviceCount": "Services",
        "staffCount": "Personnel",
        "status": "Statut",
        "createDate": "Créé le",
        "actions": "Actions"
      },
      "filters": {
        "searchPlaceholder": "Rechercher des prestataires...",
        "providerType": "Type de prestataire",
        "status": "Statut",
        "active": "Actif",
        "inactive": "Inactif",
        "reset": "Réinitialiser les filtres"
      },
      "actions": {
        "title": "Actions",
        "edit": "Modifier",
        "delete": "Supprimer",
        "add": "Ajouter un prestataire"
      }
    },
    "actions": {
      "addServiceProvider": "Ajouter un prestataire",
      "editServiceProvider": "Modifier le prestataire",
      "deleteServiceProvider": "Supprimer le prestataire",
      "deleteServiceProviderDescription": "Voulez-vous vraiment supprimer ce prestataire ?",
      "viewDetails": "Voir les détails",
      "toggleActivation": "Basculer l'activation",
      "add": "Ajouter",
      "cancel": "Annuler"
    },
    "status": {
      "label": "Statut",
      "active": "Actif",
      "inactive": "Inactif"
    },
    "staff": {
      "title": "Gestion du personnel",
      "description": "Gérer les affectations du personnel pour ce prestataire",
      "noStaff": "Aucun membre du personnel affecté à ce prestataire",
      "add": {
        "title": "Affecter un membre du personnel",
        "description": "Affecter un membre du personnel à ce prestataire"
      },
      "form": {
        "staffMember": "Membre du personnel",
        "selectStaff": "Sélectionner un membre du personnel",
        "notes": "Notes",
        "notesPlaceholder": "Saisir des notes particulières pour cette affectation (optionnel)"
      },
      "actions": {
        "add": "Affecter",
        "save": "Enregistrer les modifications",
        "cancel": "Annuler"
      },
      "messages": {
        "addSuccess": "Membre du personnel affecté avec succès",
        "addError": "Échec de l'affectation du membre du personnel",
        "updateSuccess": "Affectation mise à jour avec succès",
        "updateError": "Échec de la mise à jour de l'affectation",
        "removeSuccess": "Affectation retirée avec succès",
        "removeError": "Échec du retrait de l'affectation",
        "staffSelectionRequired": "Veuillez sélectionner un membre du personnel"
      },
      "removeDialog": {
        "title": "Retirer l'affectation du personnel",
        "description": "Voulez-vous vraiment retirer cette affectation ? Cette action est irréversible."
      }
    },
    "gallery": {
      "title": "Gestion de la galerie",
      "description": "Gérer les images et médias pour ce prestataire",
      "noItems": "Aucun élément de galerie ajouté pour le moment",
      "add": {
        "title": "Téléverser un élément de galerie",
        "description": "Téléverser une nouvelle image ou un nouveau média"
      },
      "form": {
        "title": "Titre",
        "titlePlaceholder": "Saisir le titre de l'image",
        "description": "Description",
        "descriptionPlaceholder": "Saisir la description (optionnel)",
        "file": "Sélectionner un fichier",
        "filePlaceholder": "Cliquer pour téléverser ou glisser-déposer",
        "fileHint": "PNG, JPG, WEBP ou GIF (max 10 Mo)",
        "displayOrder": "Ordre d'affichage"
      },
      "actions": {
        "add": "Téléverser",
        "save": "Enregistrer les modifications",
        "cancel": "Annuler",
        "remove": "Supprimer",
        "edit": "Modifier"
      },
      "messages": {
        "addSuccess": "Élément de galerie téléversé avec succès",
        "addError": "Échec du téléversement de l'élément",
        "updateSuccess": "Élément de galerie mis à jour avec succès",
        "updateError": "Échec de la mise à jour de l'élément",
        "removeSuccess": "Élément de galerie supprimé avec succès",
        "removeError": "Échec de la suppression de l'élément",
        "titleRequired": "Veuillez saisir un titre",
        "descriptionRequired": "Veuillez saisir une description"
      },
      "errors": {
        "fileRequired": "Veuillez sélectionner un fichier",
        "invalidFileType": "Type de fichier invalide. Seules les images sont prises en charge",
        "fileTooLarge": "Fichier trop volumineux. Taille maximale 10 Mo",
        "addFailed": "Échec du téléversement de l'élément de galerie",
        "removeFailed": "Échec de la suppression de l'élément de galerie"
      },
      "removeDialog": {
        "title": "Supprimer l'élément de galerie",
        "description": "Voulez-vous vraiment supprimer cet élément ? Cette action est irréversible."
      }
    },
    "services": {
      "title": "Services",
      "description": "Gérer les services proposés par ce prestataire",
      "noServices": "Aucun service disponible",
      "add": {
        "title": "Ajouter un service",
        "description": "Ajouter un nouveau service à ce prestataire"
      },
      "form": {
        "serviceDefinition": "Définition de service",
        "selectService": "Sélectionner un service",
        "serviceName": "Nom du service",
        "serviceDescription": "Description du service",
        "price": "Prix",
        "currency": "Devise",
        "selectCurrency": "Sélectionner une devise",
        "duration": "Durée",
        "notes": "Notes",
        "notesPlaceholder": "Notes supplémentaires pour ce service"
      },
      "actions": {
        "add": "Ajouter le service",
        "save": "Enregistrer les modifications",
        "cancel": "Annuler"
      },
      "messages": {
        "addSuccess": "Service ajouté avec succès",
        "addError": "Échec de l'ajout du service",
        "updateSuccess": "Service mis à jour avec succès",
        "updateError": "Échec de la mise à jour du service",
        "removeSuccess": "Service supprimé avec succès",
        "removeError": "Échec de la suppression du service",
        "serviceSelectionRequired": "Veuillez sélectionner une définition de service",
        "priceRequired": "Veuillez saisir un prix",
        "currencyRequired": "Veuillez sélectionner une devise",
        "durationRequired": "Veuillez saisir une durée"
      },
      "removeDialog": {
        "title": "Supprimer le service",
        "description": "Voulez-vous vraiment supprimer ce service ? Cette action est irréversible."
      },
      "units": {
        "minutesShort": "min"
      }
    },
    "policies": {
      "title": "Gestion des politiques",
      "description": "Gérer les politiques pour ce prestataire",
      "noPolicies": "Aucune politique configurée pour ce prestataire",
      "add": {
        "title": "Ajouter une politique",
        "description": "Définir une nouvelle politique pour ce prestataire"
      },
      "form": {
        "type": "Type de politique",
        "typePlaceholder": "Saisir le type (ex. : politique d'annulation, de remboursement)",
        "description": "Description de la politique",
        "descriptionPlaceholder": "Saisir une description détaillée..."
      },
      "actions": {
        "add": "Ajouter la politique",
        "save": "Enregistrer les modifications",
        "cancel": "Annuler"
      },
      "messages": {
        "addSuccess": "Politique ajoutée avec succès",
        "addError": "Échec de l'ajout de la politique",
        "updateSuccess": "Politique mise à jour avec succès",
        "updateError": "Échec de la mise à jour de la politique",
        "removeSuccess": "Politique supprimée avec succès",
        "removeError": "Échec de la suppression de la politique",
        "typeRequired": "Veuillez saisir un type de politique",
        "descriptionRequired": "Veuillez saisir une description",
        "duplicateType": "Une politique de ce type existe déjà"
      },
      "removeDialog": {
        "title": "Supprimer la politique",
        "description": "Voulez-vous vraiment supprimer cette politique ? Cette action est irréversible."
      }
    },
    "attributes": {
      "title": "Gestion des attributs",
      "description": "Gérer les attributs personnalisés selon les définitions du type de prestataire",
      "noAttributes": "Aucun attribut configuré pour ce prestataire",
      "availableDefinitions": "Définitions disponibles",
      "noAvailableDefinitions": "Tous les attributs disponibles pour ce type de prestataire ont été configurés",
      "add": {
        "title": "Ajouter un attribut",
        "description": "Configurer une nouvelle valeur d'attribut pour ce prestataire"
      },
      "form": {
        "attributeDefinition": "Définition d'attribut",
        "selectAttribute": "Sélectionner un attribut à configurer",
        "selectedAttribute": "Détails de l'attribut sélectionné",
        "name": "Nom",
        "type": "Type",
        "required": "Obligatoire",
        "value": "Valeur de l'attribut",
        "valuePlaceholder": "Saisir la valeur de l'attribut...",
        "selectValue": "Sélectionner une valeur",
        "yes": "Oui",
        "no": "Non"
      },
      "actions": {
        "add": "Ajouter l'attribut",
        "save": "Enregistrer les modifications",
        "cancel": "Annuler",
        "retry": "Réessayer"
      },
      "messages": {
        "addSuccess": "Attribut ajouté avec succès",
        "addError": "Échec de l'ajout de l'attribut",
        "updateSuccess": "Attribut mis à jour avec succès",
        "updateError": "Échec de la mise à jour de l'attribut",
        "removeSuccess": "Attribut supprimé avec succès",
        "removeError": "Échec de la suppression de l'attribut",
        "attributeRequired": "Veuillez sélectionner une définition d'attribut",
        "valueRequired": "Veuillez saisir une valeur pour l'attribut",
        "fetchError": "Échec du chargement des définitions d'attributs"
      },
      "removeDialog": {
        "title": "Supprimer l'attribut",
        "description": "Voulez-vous vraiment supprimer cet attribut ? Cette action est irréversible."
      }
    },
    "search": {
      "placeholder": "Rechercher des membres du personnel...",
      "noResults": "Aucun membre trouvé."
    },
    "messages": {
      "success": "Opération sur le prestataire réussie",
      "error": "Échec de l'opération sur le prestataire",
      "deleteSuccess": "Prestataire supprimé avec succès",
      "deleteError": "Échec de la suppression du prestataire",
      "statusChanged": "Statut du prestataire modifié avec succès",
      "statusChangeError": "Échec de la modification du statut"
    },
    "errors": {
      "invalidPhone": "Veuillez saisir un numéro de téléphone valide",
      "createFailed": "Échec de la création du prestataire",
      "updateFailed": "Échec de la mise à jour du prestataire",
      "gradeRequired": "La note est requise",
      "gradeInvalid": "La note doit être comprise entre A et E",
      "gradeNotUnique": "Un prestataire avec cette note existe déjà pour ce type et cet emplacement"
    },
    "delete": {
      "dialog": {
        "title": "Supprimer le prestataire",
        "description": "Voulez-vous vraiment supprimer ce prestataire ? Cette action est irréversible.",
        "cancel": "Annuler",
        "confirm": "Supprimer"
      }
    }
  },
  "ProviderType": {
    "name": "Type de prestataire",
    "page": {
      "title": "Types de prestataires",
      "description": "Gérer les types de prestataires et leurs définitions d'attributs"
    },
    "add": {
      "page": {
        "title": "Ajouter un type de prestataire",
        "description": "Créer un nouveau type de prestataire"
      },
      "title": "Ajouter un nouveau type de prestataire"
    },
    "update": {
      "page": {
        "title": "Mettre à jour le type de prestataire",
        "description": "Modifier les informations du type de prestataire"
      },
      "title": "Mettre à jour le type de prestataire"
    },
    "form": {
      "name": {
        "label": "Nom"
      },
      "description": {
        "label": "Description"
      },
      "isActive": "Actif",
      "attributes": "Définitions d'attributs",
      "attributesPlaceholder": "Attributs ({count} définis)",
      "create": "Créer le type de prestataire",
      "update": "Mettre à jour le type de prestataire",
      "creating": "Création...",
      "updating": "Mise à jour...",
      "cancel": "Annuler",
      "selectProviderType": "Sélectionner un type de prestataire",
      "iconUrl": {
        "label": "Icône",
        "placeholder": "Sélectionner l'icône"
      }
    },
    "table": {
      "name": "Nom",
      "description": "Description",
      "icon": "Icône",
      "attributes": "Attributs",
      "status": "Statut",
      "actions": "Actions"
    },
    "actions": {
      "addProviderType": "Ajouter un type de prestataire",
      "editProviderType": "Modifier le type de prestataire",
      "deleteProviderType": "Supprimer le type de prestataire",
      "deleteProviderTypeDescription": "Voulez-vous vraiment supprimer ce type de prestataire ?",
      "activate": "Activer",
      "deactivate": "Désactiver",
      "toggleActivation": "Basculer l'activation",
      "viewDetails": "Voir les détails",
      "removeAttribute": "Supprimer l'attribut",
      "removeAttributeDescription": "Voulez-vous vraiment supprimer cette définition d'attribut ?",
      "retry": "Réessayer",
      "cancel": "Annuler",
      "save": "Enregistrer",
      "saving": "Enregistrement en cours..."
    },
    "status": {
      "active": "Actif",
      "inactive": "Inactif"
    },
    "messages": {
      "success": "Opération sur le type de prestataire réussie",
      "error": "Échec de l'opération sur le type de prestataire",
      "updated": "Type de prestataire mis à jour avec succès",
      "attributeAddSuccess": "Définition d'attribut ajoutée avec succès",
      "attributeRemoveSuccess": "Définition d'attribut supprimée avec succès",
      "attributeUpdateSuccess": "Définition d'attribut mise à jour avec succès"
    },
    "attributes": {
      "title": "Définitions d'attributs",
      "description": "Gérer les définitions d'attributs du type de prestataire et leurs options",
      "addAttribute": "Ajouter un attribut",
      "addNew": "Ajouter un nouvel attribut",
      "noAttributes": "Aucun attribut défini",
      "form": {
        "name": {
          "label": "Nom de l'attribut"
        },
        "description": {
          "label": "Description"
        },
        "attributeType": "Type d'attribut",
        "attributeTypePlaceholder": "Sélectionner un type d'attribut",
        "isRequired": "Obligatoire",
        "validationRules": "Règles de validation",
        "validationRulesPlaceholder": "Saisir les règles de validation (optionnel)",
        "options": "Options",
        "addOption": "Ajouter une option",
        "noOptions": "Cliquez sur « Ajouter une option » pour créer des choix",
        "add": "Ajouter l'attribut",
        "adding": "Ajout en cours...",
        "displayName": {
          "label": "Nom d'affichage"
        },
        "value": {
          "label": "Valeur"
        },
        "type": "Type",
        "required": "Obligatoire",
        "rules": "Règles",
        "optionsCount": "Options",
        "yes": "Oui",
        "no": "Non"
      }
    },
    "details": {
      "title": "Détails du type de prestataire",
      "description": "Vue détaillée de {name} avec gestion des attributs",
      "basicInfo": "Informations de base",
      "statistics": "Statistiques",
      "created": "Créé le",
      "modified": "Modifié le",
      "attributeDefinitionsCount": "Définitions d'attributs"
    },
    "tabs": {
      "overview": "Aperçu",
      "attributes": "Attributs"
    },
    "search": {
      "placeholder": "Rechercher des types de prestataires...",
      "noResults": "Aucun type de prestataire trouvé."
    }
  },
  "shared": {
    "selectOption": "Sélectionner une option",
    "searchPlaceholder": "Rechercher...",
    "noResults": "Aucun résultat trouvé"
  },
  "LocalizedInput": {
    "placeholder": "Saisir {field} en {language}"
  },
  "List": {
    "loading": "Chargement...",
    "loadMore": "Charger plus"
  }
};
export default messages;