// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
   "UploadFiles": {
    "title": "Upload documents",
    "subtitle": "Please upload the requested files for your booking",
    "description": "Supported formats: PNG, JPG, JPEG, PDF",
    "requiredBadge": "Required",
    "optionalBadge": "Optional",
    "chooseFile": "Choose file",
    "continueBtn": "Continue",
    "changeFile": "Change file",
    "uploadRequiredHint": "Required files must be uploaded before continuing.",
    "acceptedFilesDesc": "PNG, JPG, JPEG, PDF — maximum file size: 10 MB.",
    "acceptedFilesTitle": "Accepted files",
    "replaceFile": "Replace file",
        "uploadBtn": "Choose file",
    "uploadCardTitle": "Upload Documents",
    "uploadCardDesc": "Attach the required documents for this booking.",
    "filesUploaded": "uploaded",
    "requiredFilesPending": "Some required files still need to be uploaded before you continue.",
    "removeFile": "Remove file",
    "uploadFile": "Upload file",
    "uploaded": "Uploaded",
    "notUploaded": "Not uploaded",
    "fileSelected": "File selected",
    "noFileSelected": "No file selected",
    "continue": "Continue",
    "back": "Back",
    "skip": "Skip",
    "uploadHint": "PNG, JPG or PDF",
    "uploadHelp": "Please upload a clear and readable file",
    "requiredFilesMessage": "Please upload all required documents before continuing",
    "successMessage": "Files uploaded successfully",
    "errorMessage": "Failed to upload file",
    "invalidFileType": "Invalid file type",
    "fileTooLarge": "File size is too large",
    "selectDocument": "Select a document",
    "document": "Document",
    "documents": "Documents"
  },
  "Manifest": {
    "name": "L Sevin"
  },
  "LocaleLayout": {
    "title": "L Sevin",
    "description": "پلاتفۆرمی خۆکارەکان بۆ چاودێری تەندرووستی کە خولەکخستنەکانی نەخۆشەکان لە مانەوەگایەکانەوە تا چاوپێکەوتنە پزیشکییەکان ڕێکدەخات"
  },
  "Error": {
    "title": "هەڵەیەک ڕوویدا",
    "description": "تکایە پەیوەندی بکە بە بەڕێوەبەری سیستەم."
  },
  "NotFoundPage": {
    "title": "لاپەڕە نەدۆزرایەوە",
    "description": "تکایە لاپەڕەی سەرەکی ماڵپەڕەکە بەکاربهێنە."
  },
  "Admin": {
    "dashboard": "داشبۆرد",
    "consultings": "ڕاوێژکارییەکان",
    "serviceProvidersRequest": "داواکارییەکانی دابینکەرانی خزمەت",
    "categories": "هاوپۆلەکان",
    "serviceDefinitions": "پەسناسی خزمەت",
    "providerTypes": "جۆری دابینکەر",
    "staff": "کارمەندان",
    "serviceProviders": "دابینکەرانی خزمەت"
  },
  "HomePage": {
    "title": "L Sevin - تەندرووستی خۆکار",
    "description": "ڕێکخستنی خولەکخستنەکانی نەخۆش لە مانەوەگایەکانەوە تا چاوپێکەوتنە پزیشکییەکان",
    "keywords": "خۆکارکردنی تەندرووستی, تەندرووستی خۆکار, گەشتیاری پزیشکی, حجزکردنی پزیشکی",
    "heroTitle": "باشترین خزمەتگوزاریی پزیشکی لەگەڵ مەوە تاقی بکەوە",
    "heroDescription": "لە گەشتێکی تەندرووستی‌دا، باشترین خزمەتگوزاریی پزیشکی بە تیمێکی شارەزای باڵا، کەرەستە پێشکەوتوو و ژینگەیەکی ئارام و دڵنیادەست دەخەینە دەستتدا بەپێی چارەسەری بەرز و چاودێری تایبەتی.",
    "heroSubtext": "با لەگەڵ یەکتر تەندرووستییەکت بەرزیتر بکەین...",
    "registerRequest": "ناردنی داواکاری",
    "consultationRequest": "داوای ڕاوێژکردن",
    "category": "هاوپۆل",
    "providerTypes": "جۆرەکانی دابینکەران",
    "serviceProviders": {
      "title": "دابینکەرانی خزمەت",
      "noProviders": "لە ئێستادا هیچ دابینکەری خزمەت بەردەست نییە",
      "priceStartsFrom": "دەستدەکات لە",
      "view": "دیاریکردن",
      "viewAll": "دیاری هەموو",
      "grade": {
        "label": "پلە"
      }
    },
    "ByType": {
      "title": "گەڕان بۆ دابینکەرانی خزمەت",
      "description": "باشترین دابینکەرانی خزمەت بۆ پێداویستییەکانت بدۆزەوە",
      "noResults": "هیچ دابینکەری خزمەت نەدۆزرایەوە",
      "loading": "بارکردن...",
      "error": "شکستی بارکردنی دابینکەرانی خزمەت. تکایە دووبارە هەوڵ بدەرەوە.",
      "filters": {
        "title": "فلتەرەکان",
        "search": "گەڕان",
        "searchPlaceholder": "گەڕان لە دابینکەر...",
        "location": "شوێن",
        "attributes": "تایبەتمەندییەکان",
        "country": "وڵات",
        "city": "شار",
        "clearAll": "پاکردنەوەی هەموو",
        "selectCountry": "وڵاتێک هەڵبژێرە",
        "selectCity": "شارێک هەڵبژێرە",
        "allCountries": "هەموو وڵاتەکان",
        "allCities": "هەموو شارەکان",
        "selectCountryFirst": "سەرەتا وڵاتێک هەڵبژێرە",
        "loadingCities": "بارکردنی شارەکان...",
        "noFilters": "هیچ فلتەرێک بەردەست نییە",
        "activeFilters": "فلتەرە چالاکەکان",
        "any": "هەر کام",
        "yes": "بەڵێ",
        "no": "نەخێر",
        "booleanTrue": "بەڵێ",
        "booleanFalse": "نەخێر"
      }
    },
    "locationSwitcher": {
      "countries": "وڵاتەکان",
      "cities": "شارەکان",
      "allCountries": "هەموو وڵاتەکان",
      "allCities": "هەموو شارەکان",
      "loading": "لە بارکردنەدایە..."
    }
  },
  "ServiceProviderPage": {
    "title": "دابینکەری خزمەت",
    "description": "وردەکاریی دابینکەری خزمەت",
    "keywords": "دابینکەری خزمەت, وردەکاریکانی دابینکەری خزمەت, لاپەڕەی دابینکەر",
    "contactProvider": "پەیوەندی بە دابینکەر بکە",
    "aboutProvider": "دەربارەی ئەم دابینکەرە",
    "availableServices": "خزمەتە بەردەستەکان",
    "policies": "سیاسەتەکان",
    "viewGallery": "بینینی گەلەری",
    "images": "وێنەکان",
    "imagesCount": "{count} وێنە",
    "noDescription": "هیچ پەسناسیەک بەردەست نییە",
    "address": "ناونیشان",
    "location": "شوێن",
    "ourStaff": "کارمەندەکانمان",
    "noServices": "هیچ خزمەتێک بەردەست نییە",
    "noPolicies": "هیچ سیاسەتیەک بەردەست نییە",
    "noImages": "هیچ وێنەیەک بەردەست نییە",
    "close": "داخستن",
    "attributes": "تایبەتمەندییەکان",
    "requests": {
      "title": "داواکارییەکانی دابینکەری خزمەت",
      "description": "بەڕێوەبردنی هەموو داواکارییەکانی خەریداران بۆ دابینکەری خزمەت.",
      "provider": "دابینکەر",
      "customer": "خەریدار",
      "email": "ئیمەیل",
      "message": "پەیام",
      "form": {
        "message": {
          "label": "پەیام",
          "placeholder": "پەیامت لێرە بنووسە..."
        }
      },
      "status": {
        "title": "دۆخ",
        "Pending": "چاوەڕوان",
        "Approved": "پەسەندکراو",
        "Rejected": "ڕەتکراو"
      },
      "date": "بەروار",
      "actions": "کردارەکان",
      "approve": "پەسەندکردن",
      "reject": "ڕەتکردن",
      "viewAddRequest": "بینین / زیادکردنی داواکاری",
      "myRequests": "داواکارییەکانم",
      "formTitle": "پەیوەندی بە دابینکەر بکە",
      "formMessage": "پەیام",
      "submit": "ناردن",
      "openRequests": "داواکارییە کراوەکان"
    },
    "Comments": {
      "title": "بۆچوون و هەڵسەنگاندن",
      "allComments": "هەموو بۆچوونەکان",
      "yourComment": "بۆچوونی تۆ",
      "noComments": "هێشتا هیچ بۆچوونێک نییە. یەکەم کەس بە!",
      "loading": "بارکردنی بۆچوونەکان...",
      "loadError": "شکستی بارکردنی بۆچوونەکان",
      "rating": "هەڵسەنگاندن",
      "comment": "بۆچوونی تۆ",
      "commentPlaceholder": "ئەزموونی خۆت هاوبەش بکە...",
      "submit": "ناردنی بۆچوون",
      "submitting": "لە ناردن...",
      "addSuccess": "بۆچوون زیادکرا",
      "addSuccessMessage": "بۆچوونەکەت بە سەرکەوتوویی بڵاوکرایەوە.",
      "addFailed": "شکستی زیادکردنی بۆچوون",
      "deleteConfirmTitle": "سڕینەوەی بۆچوون",
      "deleteConfirm": "دڵنیای کە دەتەوێت ئەم بۆچوونە بسڕیتەوە؟",
      "deleteSuccess": "بۆچوون سڕایەوە",
      "deleteSuccessMessage": "بۆچوونەکەت بە سەرکەوتوویی سڕایەوە.",
      "deleteFailed": "شکستی سڕینەوەی بۆچوون",
      "form": {
        "commentText": {
          "label": "بۆچوونی تۆ"
        }
      }
    }
  },
  "LocaleSwitcher": {
    "label": "گۆڕینی زمان",
    "fa": "فارسی",
    "en": "English",
    "tr": "Türkçe",
    "ar": "عەرەبی",
    "es": "Español",
    "ku": "Kurdish",
    "de": "Deutsch",
    "fr": "Français"
  },
  "Logo": {
    "medical": "پزیشکی",
    "tourism": "گەشتیاری",
    "beauty": "دڵرایەتی"
  },
  "UserInfo": {
    "profile": "پرۆفایل",
    "settings": "ڕێكخستنەکان",
    "signOut": "چوونەدەرەوە",
    "adminPanel": "پەڕەی بەڕێوەبردن"
  },
  "FormErrors": {
    "required": "{field} پێویستە",
    "tooShort": "{field} پێویستە کەمترین {length} پیت بێت",
    "invalid": "{field} نادروستە",
    "invalidEmail": "ناونیشانی ئیمێڵ نادروستە",
    "invalidPhoneNumber": "تکایە ژمارەی تەلەفۆنی دروست بنوسە",
    "passwordTooShort": "تێپەڕەوشە پێویستە کەمترین {length} پیت بێت",
    "passwordsDoNotMatch": "تێپەڕەوشەکان یەك ناگرن",
    "invalidCode": "کۆدی دڵنیاکردنەوە پێویستە ٦ ژمارە بێت",
    "invalidFile": "تکایە پەڕگەیەکی دروست بار بکە",
    "invalidFileType": "جۆری پەڕگە پاڵپشتی ناکرێت",
    "fileTooLarge": "قەبارەی پەڕگە بەربەستەکە تێدەپەڕێت (زۆرترین 5MB)",
    "notMatch": "تێپەڕەوشەکان یەك ناگرن",
    "invalidPhone": "تکایە ژمارەی تەلەفۆنی دروست بنوسە"
  },
  "User": {
    "Information": {
      "incompleteProfileTitle": "پرۆفایل نەتەواوە",
      "completeProfileWarning": "تکایە زانیاریەکانت تەواو بکە",
      "goToProfile": "چوونە پرۆفایل"
    },
    "Profile": {
      "page": {
        "title": "زانیاریی پرۆفایل",
        "description": "بۆ نوێکردنەوەی زانیاریی پرۆفایل، تکایە وریا نەوسینەکان پڕ بکە."
      },
      "personalInfo": {
        "title": "زانیاریی کەسی",
        "base": "زانیاریی بنەڕەتی",
        "documents": "بەڵگەنامەکان"
      },
      "tabs": {
        "basic": "زانیاریی سادە",
        "additional": "زانیاریی زیادە",
        "documents": "بەڵگەنامەکان"
      },
      "form": {
        "firstName": {
          "label": "ناوی یەکەم"
        },
        "lastName": {
          "label": "ناوی دووەم"
        },
        "email": {
          "label": "ئیمەیل"
        },
        "phoneNumber": {
          "label": "ژمارەی تەلەفۆن"
        },
        "birthDate": {
          "label": "بەرواری لەدایکبوون"
        },
        "gender": {
          "label": "رەگەز"
        },
        "country": "وڵات",
        "city": "شار",
        "street": "سەردەمی",
        "detail": "وردەکاریی زیاتر",
        "zipCode": "کۆدی پۆستی",
        "documentType": {
          "label": "جۆری بەڵگە"
        },
        "documentFile": {
          "label": "پەڕگەی بەڵگە"
        },
        "existingDocuments": "بەڵگەنامە بارکراوەکانت",
        "viewDocument": "بینینی بەڵگە",
        "address": {
          "countryCode": "کۆدی وڵات",
          "cityCode": "کۆدی شار",
          "street": "سەردەمی",
          "detail": "وردەکاریی زیاتر",
          "zipCode": "کۆدی پۆستی"
        }
      },
      "placeholders": {
        "birthDate": "بەرواری لەدایکبوون دیاری بکە",
        "documentType": "جۆری بەڵگە دیاری بکە",
        "documentFile": "کرتە بکە بۆ بارکردن یان ڕاکێشە و دابنێ"
      },
      "messages": {
        "updateSuccess": "پرۆفایل بە سەرکەوتوویی نوێ کرایەوە",
        "documentUploadSuccess": "بەڵگە بە سەرکەوتوویی بارکرا",
        "deleteDocumentConfirmationTitle": "سڕینەوەی بەڵگە",
        "deleteDocumentConfirmationMessage": "دڵنیایت دەوێت ئەم بەڵگەیە بسڕیتەوە؟",
        "deleteDocumentSuccess": "بەڵگە بە سەرکەوتوویی سڕایەوە",
        "deleteDocumentError": "نەتوانرا بەڵگە بسڕدرێتەوە"
      },
      "validation": {
        "countryRequired": "تکایە وڵات هەڵبژێرە",
        "cityRequired": "تکایە شار هەڵبژێرە"
      },
      "errors": {
        "updateFailed": "نوێکردنەوەی پرۆفایل شکستی هێنا",
        "documentUploadFailed": "بارکردنی بەڵگە شکستی هێنا",
        "documentDeleteFailed": "سڕینەوەی بەڵگە شکستی هێنا",
        "invalidFileType": "جۆری پەڕگە نادروستە",
        "fileTooLarge": "پەڕگە گەورەیە زۆر",
        "supportedFormats": "فورماتە پاڵپشتکراوەکان: .zip, .pdf, شێوازی وێنە (زۆرترین 5MB)"
      },
      "buttons": {
        "save": "پاشەکەوتکردنی گۆڕانکارییەکان",
        "upload": "بارکردنی بەڵگە",
        "delete": "سڕینەوەی بەڵگە"
      }
    }
  },
  "Common": {
    "Gender": {
      "title": "رەگەز",
      "male": "نێر",
      "female": "مێ",
      "other": "هی تر"
    },
    "DocumentType": {
      "title": "جۆری بەڵگە",
      "Passport": "پاسپۆرت",
      "Visa": "ڤیزا",
      "DriverLicense": "مۆڵەتی شۆفێری",
      "BankStatement": "هەژمارنامەی بانکی",
      "IdCard": "کارتی ناسنامە",
      "Medical": "تۆمارە پزیشکییەکان",
      "Beauty": "پرۆسێدۆری جوانکاری",
      "Tourism": "بەڵگەی گەشتیاری",
      "Other": "هی تر"
    },
    "FileUpload": {
      "errors": {
        "fileError": "هەڵەی پەڕگە، تکایە پێداویستییەکان بپشکنە",
        "fileTooLarge": "پەڕگە گەورەیە زۆر. زۆرترین قەبارە {size}MB ـە"
      }
    },
    "Address": {
      "title": "ناونیشان",
      "country": "وڵات",
      "city": "شار",
      "street": "سەردەمی",
      "detail": "وردەکاریی زیاتر",
      "zipCode": "کۆدی پۆستی"
    },
    "Location": {
      "title": "شوێن",
      "country": "وڵات",
      "city": "شار",
      "selectCountry": "وڵاتێك هەڵبژێرە",
      "selectCity": "شارێك هەڵبژێرە",
      "noCountrySelected": "هیچ وڵاتێك هەڵنەبژێردراوە",
      "noCitiesAvailable": "هیچ شارێك بەردەست نییە",
      "loading": "لە بارکردنەدایە..."
    },
    "DatePicker": {
      "placeholder": "بەروار هەڵبژێرە",
      "range": "مەودای بەروار",
      "multiple": "چەندین بەروار",
      "single": "یەک بەروار"
    },
    "DataTable": {
      "search": "گەڕان...",
      "reset": "ڕێست",
      "noResults": "هیچ ئەنجامێك نییە.",
      "rowsSelected": "{count} لە {total} ڕیز دیاریکرا.",
      "page": "لاپەڕە {current} لە {total}",
      "clearFilters": "پاڵەوانەکان پاکبکەرەوە",
      "sortAscending": "ڕیزکردن بەرزی",
      "sortDescending": "ڕیزکردن خوارەوە",
      "hideColumn": "شاردنەوەی ستوون"
    },
    "Input": {
      "search": "گەڕان..."
    },
    "Fetcher": {
      "noData": "هیچ داتایەک نەدۆزرایەوە",
      "error": "هەڵەیەک ڕووی دا: {detail}"
    },
    "Confirm": {
      "title": "ئاگاداری",
      "cancel": "هەڵوەشاندنەوە",
      "confirm": "دڵنیاکردنەوە"
    }
  },
  "Auth": {
    "SignUp": {
      "page": {
        "title": "خۆتۆمارکردن",
        "description": "بۆ خۆتۆمارکردن، تکایە زانیارییەکانی خوارەوە بە وردی پڕ بکە.",
        "alreadyHaveAccount": "پێشتر هەژمارت هەیە؟",
        "login": "چوونەژوورەوە"
      },
      "form": {
        "firstName": {
          "label": "ناوی یەکەم"
        },
        "lastName": {
          "label": "ناوی دووەم"
        },
        "email": {
          "label": "ئیمەیل"
        },
        "phoneNumber": {
          "label": "ژمارەی تەلەفۆن"
        },
        "password": {
          "label": "تێپەڕەوشە"
        },
        "signUp": "ناردنی کۆد"
      },
      "placeholders": {
        "firstName": "John",
        "lastName": "Doe",
        "email": "[example@gmail.com](mailto:example@gmail.com)",
        "password": "*******"
      },
      "errors": {
        "invalidPhone": "ژمارەی تەلەفۆن نادروستە"
      },
      "messages": {
        "signUpSuccess": "خۆتۆمارکردن سەرکەوتوو بوو",
        "signUpError": "هەڵە لە ناردنی کۆد. تکایە دووبارە هەوڵ بدە."
      }
    },
    "SignIn": {
      "page": {
        "title": "چوونەژوورەوە",
        "description": "بۆ چوونەژوورەوە، تکایە زانیاریی خۆتۆمارکردنت بنووسە.",
        "noAccount": "هەژمارت نییە؟",
        "signUp": "خۆتۆمارکردن",
        "forgotPassword": "تێپەڕەوشە لەبیرچووە؟"
      },
      "form": {
        "userNameOrEmail": {
          "label": "ئیمەیل یان ژمارەی تەلەفۆن"
        },
        "password": {
          "label": "تێپەڕەوشە"
        },
        "remember": "بیرم بهێنە",
        "login": "چوونەژوورەوە"
      },
      "errors": {
        "invalidCredentials": "زانیارییەکان نادروستن",
        "authError": "هەڵەی دڵنیاکردنەوە"
      },
      "messages": {
        "loginSuccess": "چوونەژوورەوە سەرکەوتوو بوو",
        "loginError": "هەڵە لە چوونەژوورەوە. تکایە دووبارە هەوڵ بدە."
      }
    },
    "ForgotPassword": {
      "page": {
        "title": "تێپەڕەوشە لەبیرچوو",
        "description": "بۆ گەراندنەوەی تێپەڕەوشە، تکایە ژمارەی تەلەفۆنت بنووسە.",
        "rememberPassword": "تێپەڕەوشەت لەبیرت ھەیە؟",
        "login": "چوونەژوورەوە"
      },
      "form": {
        "phoneNumber": "ژمارەی تەلەفۆن",
        "submit": "ناردنی لینکى گەراندنەوە",
        "userNameOrEmail": {
          "label": "ئیمەیل یان ژمارەی تەلەفۆن"
        }
      },
      "messages": {
        "success": "لینکی گەراندنەوە نەردرا.",
        "error": "هەڵە لە ناردنی لینک. تکایە دووبارە هەوڵ بدە."
      }
    },
    "Otp": {
      "page": {
        "title": "کۆدی دڵنیاکردنەوە",
        "description": "کۆدی دڵنیاکردنەوەی نێردراو بۆ {mobile} بنووسە.",
        "wrongNumber": "ژمارە هەڵەیە؟",
        "changeNumber": "گۆڕینی ژمارە"
      },
      "form": {
        "verify": "دڵنیاکردنەوە",
        "resendCode": "دووبارە ناردنی کۆد",
        "resendCodeTimer": "دووبارە ناردنی کۆد ({time})",
        "code": {
          "label": "کۆدی دڵنیاکردنەوە"
        },
        "phoneNumber": {
          "label": "ژمارەی تەلەفۆن"
        }
      },
      "messages": {
        "success": "کۆد بە سەرکەوتوویی دڵنیای کرایەوە.",
        "error": "هەڵە لە دڵنیاکردنەوەی کۆد. تکایە دووبارە هەوڵ بدە.",
        "resendSuccess": "کۆدی دڵنیاکردنەوە بە سەرکەوتوویی نێردرا.",
        "resendError": "هەڵە لە ناردنی کۆد. تکایە دووبارە هەوڵ بدە."
      }
    },
    "VerifyEmail": {
      "form": {
        "email": "ئیمەیل",
        "code": "کۆدی دڵنیاکردنەوە"
      },
      "messages": {
        "success": "ئیمەیل بە سەرکەوتوویی دڵنیای کرایەوە.",
        "error": "هەڵە لە دڵنیاکردنەوەی ئیمەیل. تکایە دووبارە هەوڵ بدە."
      }
    },
    "OnBoarding": {
      "step1": {
        "title": "تەندرووستیی تۆ پێشەنگی ئێمەیە",
        "description": "ئەزموونێکی تایبەت لە خزمەتگوزاریی پزیشکی پێشکەوتوو، بە هەموو ئاراستەکارییەکان و گەشتێکی ئارام، کەرەستەیەک کە بۆ پێویستەکانت دیزاین کرابێت و وریایی وردەکاریی گەشت تێدا هێندراوە.",
        "primaryButton": "دواتر",
        "secondaryButton": "بازدان"
      },
      "step2": {
        "title": "مانەوە، چارەسەری، ئارامبوون",
        "description": "لە خزمەتگوزاریی پزیشکی تایبەتی و پێشکەوتووەوە تا مانەوە لە باشترین هۆتێلەکان، ئەزموونێکی تایبەت و گەشتێکی ئاسایش‌دار بۆ تۆمان دایاریکردووە.",
        "primaryButton": "چوونەژوورەوە/خۆتۆمارکردن",
        "secondaryButton": "بازدان"
      },
      "step3": {
        "title": "گەشتی تەندرووستیت لێرە دەست پێدەکات",
        "description": "لە ئەمڕۆوە دەست بکە بە گەشتی تایبەتی تەندرووستیت. تیمێکی شارەزای ئێمە ئامادەیە باشترین چاودێری و ئەزموونت پێشکەش بکات.",
        "primaryButton": "دەستپێک",
        "secondaryButton": "چوونەژوورەوە"
      }
    }
  },
  "Dashboard": {
    "page": {
      "title": "کورتەی داشبۆرد",
      "description": "داشبۆردی بەڕێوەبردن بە ئامارە سیستەمەکان و کورتەی چالاکییە دواکەوتووەکان"
    },
    "stats": {
      "totalConsultings": {
        "title": "کۆی ڕاوێژکارییەکان",
        "description": "داواکاریی ڕاوێژکاریی چالاک"
      },
      "pendingServiceProviderRequests": {
        "title": "داواکاریی چاوەڕوان",
        "description": "چاوەڕوانی پەسەندکردن"
      },
      "totalServiceProviders": {
        "title": "دابینکەرانی خزمەت",
        "description": "دابینکەر تۆمارکراوەکان"
      },
      "totalStaff": {
        "title": "کارمەندان",
        "description": "کارمەندی چالاک"
      }
    },
    "recentConsultings": {
      "title": "ڕاوێژکارییە دواکەوتووەکان",
      "viewAll": "بینینی هەموو",
      "empty": "هیچ داواکاریی ڕاوێژکارییەکی دواکەوتوو نییە",
      "table": {
        "customer": "خەریدار",
        "category": "هاوپۆل",
        "description": "پەسناس",
        "date": "بەروار"
      }
    },
    "recentRequests": {
      "title": "داواکارییەکانی دابینکەری خزمەت ـ دواکەوتوو",
      "viewAll": "بینینی هەموو",
      "empty": "هیچ داواکاریی دواکەوتوو نییە",
      "table": {
        "customer": "خەریدار",
        "serviceProvider": "دابینکەری خزمەت",
        "message": "پەیام",
        "status": {
          "title": "دۆخ",
          "Pending": "چاوەڕوان",
          "Approved": "پەسەندکراو",
          "Rejected": "ڕەتکراو"
        },
        "date": "بەروار"
      }
    },
    "quickActions": {
      "title": "کردارە خێراکان",
      "totalConsultings": {
        "title": "ڕاوێژکاری",
        "description": "بەڕێوەبردنی داواکاریی ڕاوێژکاری"
      },
      "totalServiceProviders": {
        "title": "دابینکەرانی خزمەت",
        "description": "بەڕێوەبردنی دابینکەرانی خزمەت"
      },
      "totalCategories": {
        "title": "هاوپۆلەکان",
        "description": "بەڕێوەبردنی هاوپۆلەکان"
      },
      "totalStaff": {
        "title": "کارمەندان",
        "description": "بەڕێوەبردنی کارمەندان"
      },
      "totalProviderTypes": {
        "title": "جۆری دابینکەر",
        "description": "بەڕێوەبردنی جۆرەکان"
      },
      "totalServiceDefinitions": {
        "title": "پەسناسی خزمەت",
        "description": "بەڕێوەبردنی پەسناسیەکان"
      }
    }
  },
  "Consulting": {
    "page": {
      "title": "داوای ڕاوێژکاری",
      "description": "بۆ پێویستی پزیشکی یان جوانکاری داوای ڕاوێژکاری بکە.",
      "adminTitle": "داواکارییەکانی ڕاوێژکاری",
      "adminDescription": "بەڕێوەبردنی هەموو داواکاریی ڕاوێژکاریی خەریداران."
    },
    "table": {
      "customer": "خەریدار",
      "email": "ئیمەیل",
      "description": "پەسناس",
      "category": "هاوپۆل"
    },
    "form": {
      "formTitle": "داوای ڕاوێژکاری",
      "formDescription": "تکایە وردەکاریی داواکاریی ڕاوێژکاریت بنووسە.",
      "categoryId": {
        "label": "هاوپۆل"
      },
      "categoryName": {
        "label": "ناوی هاوپۆل"
      },
      "description": {
        "label": "پەسناس"
      },
      "documentIds": {
        "label": "بەڵگەنامەی پەیوەندیدار"
      }
    },
    "placeholders": {
      "category": "هاوپۆلێك هەڵبژێرە",
      "searchCategory": "گەڕان لە هاوپۆلەکان...",
      "description": "تکایە پێویستەکانت بە وردی وەسف بکە..."
    },
    "descriptions": {
      "description": "زانیارییەکان بە هەندەیەک زیادە بنووسە، هەر کاتێك مێژووی پزیشکی یان نیگەرانی هەیە.",
      "documents": "ئەو بەڵگەیانە هەڵبژێرە کە پەیوەندی بە داواکاریی ڕاوێژکاریت هەیە."
    },
    "messages": {
      "createSuccess": "داواکاریی ڕاوێژکاری بە سەرکەوتوویی نێردرا",
      "noDocuments": "هێشتا هیچ بەڵگەیەکت بار نەکردووە. تکایە سەرەتا بەڵگە بار بکە.",
      "noCategories": "هیچ هاوپۆلێک نەدۆزرایەوە."
    },
    "errors": {
      "createFailed": "نەتوانرا داواکارییەکە نێردرێت"
    },
    "buttons": {
      "submit": "ناردنی داواکاری",
      "uploadDocuments": "بارکردنی بەڵگە"
    }
  },
  "Category": {
    "name": "هاوپۆل",
    "page": {
      "title": "هاوپۆلەکان",
      "description": "بەڕێوەبردنی هاوپۆلەکان و پۆلەژینەکان"
    },
    "add": {
      "page": {
        "title": "زیادکردنی هاوپۆل",
        "description": "دروستکردنی هاوپۆلی نوێ"
      },
      "title": "زیادکردنی هاوپۆلی نوێ",
      "childTitle": "زیادکردنی هاوپۆلی لاوەکی"
    },
    "update": {
      "page": {
        "title": "نوێکردنەوەی هاوپۆل",
        "description": "دەستکاری کردنی زانیاریی هاوپۆل"
      },
      "title": "نوێکردنەوەی هاوپۆل"
    },
    "form": {
      "name": {
        "label": "ناو",
        "translations": "ناوی هاوپۆل لانی کەم بە یەک زمان پێویستە"
      },
      "namePlaceholder": "ناوی هاوپۆل بنووسە",
      "description": {
        "label": "پەسناس",
        "translations": "پەسناسی هاوپۆل لانی کەم بە یەک زمان پێویستە"
      },
       "image": {
        "label": "Category image",
        "hint": "Upload an image for this category",
        "remove": "Remove image"
      },
      "descriptionPlaceholder": "پەسناسی هاوپۆل بنووسە",
      "parentId": "هاوپۆلی باوان",
      "parentIdPlaceholder": "هاوپۆلی باوان هەڵبژێرە",
      "displayOrder": "ڕیز",
      "displayOrderPlaceholder": "ژمارەی ڕیز بنووسە",
      "isActive": "چالاک",
      "create": "دروستکردنی هاوپۆل",
      "update": "نوێکردنەوەی هاوپۆل",
      "creating": "لە دروستکردنەدایە...",
      "updating": "لە نوێکردنەوەدایە...",
      "cancel": "هەڵوەشاندنەوە"
    },
    "table": {
      "name": "ناو",
      "description": "پەسناس",
      "parent": "باوان",
      "displayOrder": "ڕیز",
      "status": "دۆخ",
      "actions": "کردارەکان"
    },
    "actions": {
      "addCategory": "زیادکردنی هاوپۆل",
      "addChildCategory": "زیادکردنی هاوپۆلی لاوەکی",
      "editCategory": "دەستکاری هاوپۆل",
      "deleteCategory": "سڕینەوەی هاوپۆل",
      "deleteCategoryDescription": "دڵنیایت دەوێت ئەم هاوپۆلە بسڕیتەوە؟",
      "toggleActivation": "گۆڕینی دۆخی چالاکی"
    },
    "status": {
      "active": "چالاک",
      "inactive": "ناچالاک"
    },
    "messages": {
      "success": "کرداری هاوپۆل بە سەرکەوتوویی تەواو بوو",
      "error": "نەتوانرا کرداری هاوپۆل پێکبێت",
      "deleteConfirmation": "دڵنیایت دەوێت {name} بسڕیتەوە؟",
      "deleteSuccess": "هاوپۆل بە سەرکەوتوویی سڕایەوە",
      "deleteError": "نەتوانرا هاوپۆل بسڕدرێتەوە",
      "deleteErrorLog": "هەڵەی سڕینەوەی هاوپۆل:"
    }
  },
  "ServiceDefinition": {
    "name": "پەسناسی خزمەت",
    "page": {
      "title": "پەسناسییەکانی خزمەت",
      "description": "بەڕێوەبردنی پەسناسییەکانی خزمەت و ڕێکخستنەکانیان"
    },
    "add": {
      "page": {
        "title": "زیادکردنی پەسناسی خزمەت",
        "description": "دروستکردنی پەسناسی خزمەتی نوێ"
      },
      "title": "زیادکردنی پەسناسی خزمەتی نوێ"
    },
    "update": {
      "page": {
        "title": "نوێکردنەوەی پەسناسی خزمەت",
        "description": "دەستکاری کردنی پەسناسی خزمەت"
      },
      "title": "نوێکردنەوەی پەسناسی خزمەت"
    },
    "form": {
      "name": {
        "label": "ناو"
      },
      "description": {
        "label": "پەسناس"
      },
      "categoryId": {
        "label": "هاوپۆل",
        "placeholder": "هاوپۆل هەڵبژێرە"
      },
      "durationMinutes": {
        "label": "ماوە (خولەک)",
        "placeholder": "ماوەکە بە خولەک بنووسە"
      },
      "currency": {
        "label": "دراو",
        "placeholder": "جۆری دراو بنووسە"
      },
      "value": {
        "label": "نرخ",
        "placeholder": "بەهای نرخ بنووسە"
      },
      "pricingModel": {
        "label": "مۆدێلی نرخدان",
        "placeholder": "مۆدێل هەڵبژێرە"
      },
      "isActive": {
        "label": "چالاک"
      },
      "attributeDefinitions": "پەسناسی تایبەتمەندی",
      "requirements": "پێداویستییەکان",
      "create": "دروستکردنی پەسناسی خزمەت",
      "update": "نوێکردنەوەی پەسناسی خزمەت",
      "creating": "لە دروستکردنەدایە...",
      "updating": "لە نوێکردنەوەدایە...",
      "cancel": "هەڵوەشاندنەوە"
    },
    "table": {
      "name": "ناو",
      "category": "هاوپۆل",
      "description": "پەسناس",
      "duration": "ماوە",
      "price": "نرخ",
      "status": "دۆخ",
      "actions": "کردارەکان"
    },
    "actions": {
      "addServiceDefinition": "زیادکردنی پەسناسی خزمەت",
      "editServiceDefinition": "دەستکاری پەسناسی خزمەت",
      "deleteServiceDefinition": "سڕینەوەی پەسناسی خزمەت",
      "deleteServiceDefinitionDescription": "دڵنیایت دەوێت ئەم پەسناسە بسڕیتەوە؟",
      "toggleActivation": "گۆڕینی دۆخی چالاکی",
      "viewDetails": "بینینی وردەکاری",
      "removeAttribute": "سڕینەوەی تایبەتمەندی",
      "removeAttributeDescription": "دڵنیایت دەوێت ئەم تایبەتمەندییە بسڕیتەوە؟",
      "removeRequirement": "سڕینەوەی پێداویستی",
      "removeRequirementDescription": "دڵنیایت دەوێت ئەم پێداویستییە بسڕیتەوە؟",
      "retry": "هەوڵدانەوە",
      "cancel": "هەڵوەشاندنەوە",
      "save": "ناردنەوە",
      "saving": "لە ناردنەوەدایە..."
    },
    "status": {
      "active": "چالاک",
      "inactive": "ناچالاک"
    },
    "messages": {
      "success": "کرداری پەسناسی خزمەت بە سەرکەوتوویی تەواو بوو",
      "error": "نەتوانرا کرداری پەسناسی خزمەت پێکبێت",
      "updated": "پەسناسی خزمەت بە سەرکەوتوویی نوێ کرایەوە",
      "attributeAddSuccess": "تایبەتمەندی بە سەرکەوتوویی زیادکرا",
      "attributeRemoveSuccess": "تایبەتمەندی بە سەرکەوتوویی سڕایەوە",
      "requirementAddSuccess": "پێداویستی بە سەرکەوتوویی زیادکرا",
      "requirementRemoveSuccess": "پێداویستی بە سەرکەوتوویی سڕایەوە",
      "attributeUpdateSuccess": "تایبەتمەندی بە سەرکەوتوویی نوێ کرایەوە",
      "requirementUpdateSuccess": "پێداویستی بە سەرکەوتوویی نوێ کرایەوە",
      "fetchError": "نەتوانرا وردەکاریی پەسناسی خزمەت بهێنرێت"
    },
    "pricingModels": {
      "Fixed": "نرخی جێگیر",
      "Variable": "نرخی گۆڕاو",
      "Hourly": "نرخی کاتژمێری",
      "Package": "نرخیپاکەتی"
    },
    "attributes": {
      "title": "پەسناسی تایبەتمەندی",
      "description": "بەڕێوەبردنی پەسناسی تایبەتمەندییەکان و هەڵبژاردەکان",
      "addAttribute": "زیادکردنی تایبەتمەندی",
      "addNew": "زیادکردنی تایبەتمەندی نوێ",
      "noAttributes": "هیچ تایبەتمەندییەک دیارینەکراوە",
      "form": {
        "name": {
          "label": "ناوی تایبەتمەندی",
          "placeholder": "ناوی تایبەتمەندی بنووسە"
        },
        "description": {
          "label": "پەسناس",
          "placeholder": "پەسناسی تایبەتمەندی بنووسە"
        },
        "attributeType": "جۆری تایبەتمەندی",
        "attributeTypePlaceholder": "جۆر هەڵبژێرە",
        "isRequired": "پێویست",
        "affectsPricing": "کاریگەری لە نرخ",
        "displayOrder": "ڕیز",
        "options": "هەڵبژاردەکان",
        "addOption": "زیادکردنی هەڵبژاردە",
        "noOptions": "کرتە لە 'زیادکردنی هەڵبژاردە' بکە بۆ دروستکردنی هەڵبژاردەکان",
        "add": "زیادکردن",
        "adding": "لە زیادکردنەدایە...",
        "displayName": {
          "label": "ناوی نیشاندان",
          "placeholder": "ناوی نیشاندان بنووسە"
        },
        "value": "بەها",
        "extraPrice": "نرخی زیادە",
        "type": "جۆر",
        "required": "پێویست",
        "affectsPricingLabel": "کاریگەری لە نرخ",
        "yes": "بەڵێ",
        "no": "نەخێر"
      }
    },
    "requirements": {
      "title": "پێداویستییەکان",
      "description": "بەڕێوەبردنی پێداویستی و مەرجەکان",
      "addRequirement": "زیادکردنی پێداویستی",
      "addNew": "زیادکردنی پێداویستی نوێ",
      "noRequirements": "هیچ پێداویستییەک دیارینەکراوە",
      "mandatory": "پەیوەست",
      "optional": "ئەرەزی",
      "form": {
        "description": {
          "label": "پەسناسی پێداویستی",
          "placeholder": "پەسناسی پێداویستی بنووسە"
        },
        "isMandatory": "پێداویستی پەیوەست",
        "isMandatoryDescription": "ئایا ئەم پێداویستیه‌ بۆ خزمەتەکە پەیوەستە",
        "add": "زیادکردنی پێداویستی",
        "adding": "لە زیادکردنەدایە...",
        "update": "نوێکردنەوەی پێداویستی",
        "updating": "لە نوێکردنەوەدایە...",
        "cancel": "هەڵوەشاندنەوە"
      }
    },
    "details": {
      "title": "وردەکاریی پەسناسی خزمەت",
      "description": "دیاریکردنی وردەکاریی {name} بە بەڕێوەبردنی تایبەتمەندی و پێداویستی",
      "basicInfo": "زانیاریی بنەڕەتی",
      "pricingInfo": "زانیاریی نرخدان"
    },
    "tabs": {
      "overview": "کورتە",
      "attributes": "تایبەتمەندییەکان",
      "requirements": "پێداویستییەکان"
    },
    "search": {
      "placeholder": "گەڕان لە پەسناسی خزمەت...",
      "noResults": "هیچ پەسناسی خزمەتێک نەدۆزرایەوە."
    },
    "units": {
      "minutes": "خولەک",
      "minutesShort": "خولەک"
    }
  },
  "Staff": {
    "name": "کارمەند",
    "page": {
      "title": "کارمەندان",
      "description": "بەڕێوەبردنی کارمەندان و خولەکخستنەکانیان"
    },
    "add": {
      "page": {
        "title": "زیادکردنی کارمەند",
        "description": "دروستکردنی کارمەندی نوێ"
      },
      "title": "زیادکردنی کارمەندی نوێ"
    },
    "update": {
      "page": {
        "title": "نوێکردنەوەی کارمەند",
        "description": "دەستکاری کردنی زانیاریی کارمەند"
      },
      "title": "نوێکردنەوەی کارمەند"
    },
    "form": {
      "name": {
        "label": "ناوی تەواو",
        "placeholder": "ناوی تەواوی کارمەند بنووسە"
      },
      "biography": {
        "label": "ژیاننامە",
        "placeholder": "ژیاننامەی کارمەند بنووسە"
      },
      "title": {
        "label": "ناونیشان",
        "placeholder": "ناونیشانی کارمەند بنووسە"
      },
      "profileImageUrl": "URL ـی وێنەی پرۆفایل",
      "profileImageUrlPlaceholder": "URL ـی وێنەی پرۆفایل بنووسە",
      "isActive": "چالاک",
      "availabilities": "خشتەی دەستەبەردانی",
      "serviceAssignments": "هاوپێچکردنی خزمەت",
      "create": "دروستکردنی کارمەند",
      "update": "نوێکردنەوەی کارمەند",
      "creating": "لە دروستکردنەدایە...",
      "updating": "لە نوێکردنەوەدایە...",
      "cancel": "هەڵوەشاندنەوە"
    },
    "table": {
      "name": "ناو",
      "title": "ناونیشان",
      "status": "دۆخ",
      "services": "خزمەتەکان",
      "biography": "ژیاننامە",
      "actions": "کردارەکان"
    },
    "actions": {
      "addStaff": "زیادکردنی کارمەند",
      "editStaff": "دەستکاری کارمەند",
      "deleteStaff": "سڕینەوەی کارمەند",
      "deleteStaffDescription": "دڵنیایت دەوێت ئەم کارمەندە بسڕیتەوە؟",
      "viewDetails": "بینینی وردەکاری",
      "toggleActivation": "گۆڕینی دۆخی چالاکی",
      "retry": "هەوڵدانەوە",
      "cancel": "هەڵوەشاندنەوە",
      "save": "ناردنەوە",
      "saving": "لە ناردنەوەدایە..."
    },
    "status": {
      "active": "چالاک",
      "inactive": "ناچالاک"
    },
    "messages": {
      "success": "کرداری کارمەند بە سەرکەوتوویی تەواو بوو",
      "error": "نەتوانرا کرداری کارمەند پێکبێت",
      "fetchError": "نەتوانرا وردەکاریی کارمەند باربکرێت",
      "availabilityAddSuccess": "دەستەبەردان بە سەرکەوتوویی زیادکرا",
      "availabilityAddError": "زیادکردنی دەستەبەردان شکستی هێنا",
      "availabilityUpdateSuccess": "دەستەبەردان بە سەرکەوتوویی نوێکرایەوە",
      "availabilityUpdateError": "نوێکردنەوەی دەستەبەردان شکستی هێنا",
      "availabilityRemoveSuccess": "دەستەبەردان بە سەرکەوتوویی سڕایەوە",
      "availabilityRemoveError": "سڕینەوەی دەستەبەردان شکستی هێنا",
      "serviceAddSuccess": "خزمەت بە سەرکەوتوویی هاوپێچکرا",
      "serviceAddError": "هاوپێچکردنی خزمەت شکستی هێنا",
      "serviceUpdateSuccess": "خزمەت بە سەرکەوتوویی نوێکرایەوە",
      "serviceUpdateError": "نوێکردنەوەی خزمەت شکستی هێنا",
      "serviceRemoveSuccess": "خزمەت بە سەرکەوتوویی سڕایەوە",
      "serviceRemoveError": "سڕینەوەی خزمەت شکستی هێنا",
      "serviceSelectionRequired": "تکایە خزمەتێك هەڵبژێرە بۆ هاوپێچکردن"
    },
    "details": {
      "title": "وردەکاریی کارمەند",
      "description": "بینینی وردەکاری بۆ {name}",
      "basicInfo": "زانیاریی بنەڕەتی",
      "statsInfo": "ئامارەکان",
      "totalAvailabilities": "کۆی دەستەبەردانی",
      "totalServices": "کۆی خزمەتەکان",
      "activeServices": "خزمەتە چالاکەکان"
    },
    "tabs": {
      "overview": "کورتە",
      "availabilities": "دەستەبەردانی",
      "services": "خزمەتەکان"
    },
    "availability": {
      "title": "دەستەبەردانی کارمەند",
      "description": "بەڕێوەبردنی خشتەی دەستەبەردانی کارمەند",
      "noAvailabilities": "هیچ خولەکخستنێك دامەزراو نییە",
      "recurring": "دووبارەبوو",
      "specific": "بەرواری دیاریکراو",
      "specificDate": "بەرواری دیاریکراو",
      "add": {
        "title": "زیادکردنی دەستەبەردانی نوێ",
        "description": "ڕێکخستنی خولەکخستنێکی نوێ بۆ ئەم کارمەندە"
      },
      "form": {
        "dayOfWeek": "ڕۆژی هەفتە",
        "startTime": "کاتی دەستپێک",
        "endTime": "کاتی کۆتایی",
        "isRecurring": "هەفتانە دووبارە بێت",
        "specificDate": "بەرواری دیاریکراو",
        "status": "دۆخ",
        "selectStartTime": "کاتی دەستپێک هەڵبژێرە",
        "selectEndTime": "کاتی کۆتایی هەڵبژێرە"
      },
      "timePicker": {
        "selectTime": "کات هەڵبژێرە",
        "hour": "كاتژمێر",
        "minute": "خولەک",
        "selected": "هەڵبژێردرا"
      },
      "validation": {
        "startTimeAfterEnd": "کاتی دەستپێک پێویستە پێش کاتی کۆتایی بێت",
        "endTimeBeforeStart": "کاتی کۆتایی پێویستە دوای کاتی دەستپێک بێت",
        "endTimeMustBeAfterStartTime": "کاتی کۆتایی پێویستە دوای کاتی دەستپێک بێت",
        "timeAutoAdjusted": "کاتی کۆتایی خۆکارانە ڕێکخرایەوە"
      },
      "days": {
        "Sunday": "یەکشەممە",
        "Monday": "دووشەممە",
        "Tuesday": "سێشەممە",
        "Wednesday": "چوارشەممە",
        "Thursday": "پێنجشەممە",
        "Friday": "هەینی",
        "Saturday": "شەممە"
      },
      "status": {
        "available": "بەردەست",
        "busy": "سەرقاڵ",
        "onLeave": "سەرپەرشتی",
        "inactive": "ناچالاک"
      },
      "actions": {
        "add": "زیادکردنی دەستەبەردانی"
      },
      "removeDialog": {
        "title": "سڕینەوەی دەستەبەردانی",
        "description": "دڵنیایت دەوێت ئەم دەستەبەردانە بسڕیتەوە؟ ئەم کردارە پەسند نابێتەوە."
      },
      "badges": {
        "available": "بەردەست",
        "busy": "سەرقاڵ",
        "onLeave": "سەرپەرشتی",
        "inactive": "ناچالاک"
      }
    },
    "services": {
      "title": "خزمەتە هاوپێچکراوەکان",
      "description": "بەڕێوەبردنی ئەو خزمەتانەی ئەم کارمەندە دەتوانێت پێشکەش بکات",
      "noServices": "هیچ خزمەتێك بەم کارمەندە پێوەست نەکراوە",
      "allServicesAssigned": "هەموو خزمەتە بەردەستەکان بەم کارمەندە هاوپێچکراون",
      "add": {
        "title": "هاوپێچکردنی خزمەتی نوێ",
        "description": "خزمەتێك بەم کارمەندە پێوەست بکە"
      },
      "form": {
        "serviceDefinition": "خزمەت",
        "selectService": "خزمەت هەڵبژێرە",
        "notes": "تێبینییەکان",
        "notesPlaceholder": "هەر تێبینیی تایبەتی بنووسە"
      },
      "actions": {
        "add": "هاوپێچکردنی خزمەت"
      },
      "removeDialog": {
        "title": "لابردنی هاوپێچکردن",
        "description": "دڵنیایت دەوێت ئەم هاوپێچکردنە بسڕیتەوە؟ ئەم کردارە پەسند نابێتەوە."
      }
    },
    "units": {
      "minutes": "خولەک",
      "minutesShort": "خولەک"
    }
  },
  "ServiceProvider": {
    "name": "دابینکەری خزمەت",
    "contactProvider": "پەیوەندی بە دابینکەر بکە",
    "aboutProvider": "دەربارەی ئەم دابینکەرە",
    "availableServices": "خزمەتە بەردەستەکان",
    "viewGallery": "بینینی گەلەری",
    "images": "وێنەکان",
    "imagesCount": "{count} وێنە",
    "noDescription": "هیچ پەسناسیەک بەردەست نییە",
    "noServices": "هیچ خزمەتێک بەردەست نییە",
    "noPolicies": "هیچ سیاسەتیەک بەردەست نییە",
    "noImages": "هیچ وێنەیەک بەردەست نییە",
    "page": {
      "title": "دابینکەرانی خزمەت",
      "description": "بەڕێوەبردنی دابینکەری خزمەت و پرۆفایلە تەواوەکانیان"
    },
    "add": {
      "page": {
        "title": "زیادکردنی دابینکەری خزمەت",
        "description": "دروستکردنی دابینکەری نوێ"
      },
      "title": "زیادکردنی دابینکەری خزمەتی نوێ"
    },
    "update": {
      "page": {
        "title": "نوێکردنەوەی دابینکەری خزمەت",
        "description": "دەستکاری کردنی زانیاریی دابینکەر"
      },
      "title": "نوێکردنەوەی دابینکەری خزمەت"
    },
    "details": {
      "page": {
        "title": "وردەکاریی دابینکەری خزمەت",
        "description": "دیاریکردنی وردەکاریی بە گشتی بۆ بەڕێوەبردن"
      },
      "title": "وردەکاریی دابینکەری خزمەت",
      "basicInfo": "زانیاریی بنەڕەتی",
      "statsInfo": "ئامارەکان",
      "totalStaff": "کۆی کارمەندان",
      "totalServices": "کۆی خزمەتەکان",
      "totalPolicies": "کۆی سیاسەتەکان",
      "totalGalleryItems": "کۆی تۆمارە گەلەرییەکان",
      "totalAttributes": "کۆی تایبەتمەندییەکان",
      "tabs": {
        "info": "زانیاری",
        "staff": "کارمەندان",
        "services": "خزمەتەکان",
        "policies": "سیاسەتەکان",
        "gallery": "گەلەری",
        "attributes": "تایبەتمەندییەکان"
      }
    },
    "form": {
      "name": {
        "label": "ناوی دابینکەر",
        "placeholder": "ناوی دابینکەر بنووسە"
      },
      "description": {
        "label": "پەسناس",
        "placeholder": "پەسناسی دابینکەر بنووسە"
      },
      "providerTypeId": {
        "label": "جۆری دابینکەر",
        "placeholder": "جۆر هەڵبژێرە"
      },
      "grade": {
        "label": "پلە (ئارەزوومەندانە)",
        "placeholder": "پلە هەڵبژێرە",
        "none": "بێ پلە"
      },
      "country": {
        "label": "وڵات",
        "placeholder": "وڵات هەڵبژێرە"
      },
      "city": {
        "label": "شار",
        "placeholder": "شار هەڵبژێرە"
      },
      "coordinates": {
        "label": "هەماهنگان",
        "description": "هەماهنگان بنووسە"
      },
      "location": {
        "label": "شوێن",
        "description": "شوێن بنووسە"
      },
      "email": {
        "label": "ئیمەیل",
        "placeholder": "ئیمەیلی دابینکەر بنووسە"
      },
      "phoneNumber": {
        "label": "ژمارەی تەلەفۆن",
        "placeholder": "ژمارەی تەلەفۆن بنووسە"
      },
      "sections": {
        "basicInfo": "زانیاریی بنەڕەتی",
        "addressInfo": "زانیاریی ناونیشان",
        "contactInfo": "زانیاریی پەیوەندی"
      },
      "street": {
        "label": "سەردەمی",
        "placeholder": "ناونیشانی سەردەمی بنووسە"
      },
      "detail": {
        "label": "وردەکاریی ناونیشان",
        "placeholder": "وردەکاریی زیاتر بنووسە"
      },
      "zipCode": {
        "label": "کۆدی پۆستی",
        "placeholder": "کۆدی پۆستی بنووسە"
      },
      "selectCountryFirst": "سەرەتا وڵات هەڵبژێرە",
      "noCitiesAvailable": "بۆ ئەم وڵاتە هیچ شارێك بەردەست نییە",
      "actions": {
        "save": "پاشەکەوتکردنی گۆڕانکارییەکان",
        "saving": "لە پاشەکەوتکردنەدایە...",
        "cancel": "هەڵوەشاندنەوە"
      },
      "website": "ماڵپەڕ",
      "websitePlaceholder": "URL ـی ماڵپەڕ بنووسە",
      "address": "زانیاریی ناونیشان",
      "isActive": "چالاک",
      "staffAssignments": "هاوپێچکردنی کارمەند",
      "serviceOfferings": "پێشکەشکردنی خزمەت",
      "create": "دروستکردنی دابینکەری خزمەت",
      "update": "نوێکردنەوەی دابینکەری خزمەت",
      "creating": "لە دروستکردنەدایە...",
      "updating": "لە نوێکردنەوەدایە...",
      "cancel": "هەڵوەشاندنەوە"
    },
    "table": {
      "headers": {
        "name": "ناو",
        "description": "پەسناس",
        "providerType": "جۆری دابینکەر",
        "contactEmail": "ئیمەیل",
        "contactPhone": "تەلەفۆن",
        "address": "ناونیشان",
        "serviceCount": "خزمەتەکان",
        "staffCount": "کارمەندان",
        "status": "دۆخ",
        "createDate": "دروستکرا",
        "actions": "کردارەکان"
      },
      "filters": {
        "searchPlaceholder": "گەڕان لە دابینکەر...",
        "providerType": "جۆری دابینکەر",
        "status": "دۆخ",
        "active": "چالاک",
        "inactive": "ناچالاک",
        "reset": "ڕێستکردنەوەی پاڵاوتن"
      },
      "actions": {
        "title": "کردارەکان",
        "edit": "دەستکاری",
        "delete": "سڕینەوە",
        "add": "زیادکردنی دابینکەر"
      }
    },
    "actions": {
      "addServiceProvider": "زیادکردنی دابینکەری خزمەت",
      "editServiceProvider": "دەستکاری دابینکەری خزمەت",
      "deleteServiceProvider": "سڕینەوەی دابینکەری خزمەت",
      "deleteServiceProviderDescription": "دڵنیایت دەوێت ئەم دابینکەرە بسڕیتەوە؟",
      "viewDetails": "بینینی وردەکاری",
      "toggleActivation": "گۆڕینی دۆخی چالاکی",
      "add": "زیادکردن",
      "cancel": "هەڵوەشاندنەوە"
    },
    "status": {
      "label": "دۆخ",
      "active": "چالاک",
      "inactive": "ناچالاک"
    },
    "staff": {
      "title": "بەڕێوەبردنی کارمەند",
      "description": "هاوپێچکردنی کارمەند بۆ ئەم دابینکەرە",
      "noStaff": "هیچ کارمەندێك بەم دابینکەریە پێوەست نەکراوە",
      "add": {
        "title": "هاوپێچکردنی کارمەند",
        "description": "کارمەندێك بەم دابینکەرە پێوەست بکە"
      },
      "form": {
        "staffMember": "کارمەند",
        "selectStaff": "کارمەند هەڵبژێرە",
        "notes": "تێبینیی هاوپێچکردن",
        "notesPlaceholder": "هەر تێبینیی تایبەتی بنووسە (ئارەزوومەندانە)"
      },
      "actions": {
        "add": "هاوپێچکردنی کارمەند",
        "save": "پاشەکەوتکردن",
        "cancel": "هەڵوەشاندنەوە"
      },
      "messages": {
        "addSuccess": "کارمەند بە سەرکەوتوویی هاوپێچکرا",
        "addError": "هاوپێچکردن شکستی هێنا",
        "updateSuccess": "هاوپێچکردن بە سەرکەوتوویی نوێکرایەوە",
        "updateError": "نوێکردنەوەی هاوپێچکردن شکستی هێنا",
        "removeSuccess": "هاوپێچکردن بە سەرکەوتوویی سڕایەوە",
        "removeError": "نەتوانرا هاوپێچکردن بسڕدرێتەوە",
        "staffSelectionRequired": "تکایە کارمەندێك هەڵبژێرە"
      },
      "removeDialog": {
        "title": "لابردنی هاوپێچکردن",
        "description": "دڵنیایت دەوێت ئەم هاوپێچکردنە بسڕیتەوە؟ ئەم کردارە پەسند نابێتەوە."
      }
    },
    "gallery": {
      "title": "بەڕێوەبردنی گەلەری",
      "description": "بەڕێوەبردنی وێنە و مێدیا بۆ ئەم دابینکەرە",
      "noItems": "هێشتا هیچ تۆمارێکی گەلەری زیاد نەکراوە",
      "add": {
        "title": "بارکردنی تۆماری گەلەری",
        "description": "وێنە یان مێدیای نوێ بار بکە"
      },
      "form": {
        "title": "ناونیشان",
        "titlePlaceholder": "ناونیشانی وێنە بنووسە",
        "description": "پەسناس",
        "descriptionPlaceholder": "پەسناسی وێنە بنووسە (ئارەزوومەندانە)",
        "file": "دیاریکردنی پەڕگە",
        "filePlaceholder": "کرتە بکە بۆ بارکردن یان ڕاکێشە و دابنێ",
        "fileHint": "PNG, JPG, WEBP, GIF (زۆرترین 10MB)",
        "displayOrder": "ڕیز"
      },
      "actions": {
        "add": "بارکردن",
        "save": "پاشەکەوتکردن",
        "cancel": "هەڵوەشاندنەوە",
        "remove": "لابردن",
        "edit": "دەستکاری"
      },
      "messages": {
        "addSuccess": "تۆماری گەلەری بە سەرکەوتوویی بارکرا",
        "addError": "نەتوانرا بار بکرێت",
        "updateSuccess": "تۆماری گەلەری بە سەرکەوتوویی نوێکرایەوە",
        "updateError": "نوێکردنەوە شکستی هێنا",
        "removeSuccess": "تۆمار بە سەرکەوتوویی سڕایەوە",
        "removeError": "نەتوانرا تۆمار بسڕدرێتەوە",
        "titleRequired": "تکایە ناونیشان بنووسە",
        "descriptionRequired": "تکایە پەسناس بنووسە"
      },
      "errors": {
        "fileRequired": "تکایە پەڕگە هەڵبژێرە",
        "invalidFileType": "جۆری پەڕگە نادروستە. تەنها وێنە پاڵپشتی دەکرێت",
        "fileTooLarge": "پەڕگە گەورەیە زۆر. زۆرترین 10MB",
        "addFailed": "بارکردن شکستی هێنا",
        "removeFailed": "سڕینەوە شکستی هێنا"
      },
      "removeDialog": {
        "title": "سڕینەوەی تۆمار",
        "description": "دڵنیایت دەوێت ئەم تۆمارە بسڕیتەوە؟ ئەم کردارە پەسند نابێتەوە."
      }
    },
    "services": {
      "title": "خزمەتەکان",
      "description": "بەڕێوەبردنی خزمەتە پێشکەشکراوەکان",
      "noServices": "هیچ خزمەتێك بەردەست نییە",
      "add": {
        "title": "زیادکردنی خزمەت",
        "description": "زیادکردنی خزمەتی نوێ بۆ ئەم دابینکەرە"
      },
      "form": {
        "serviceDefinition": "پەسناسی خزمەت",
        "selectService": "خزمەت هەڵبژێرە",
        "serviceName": "ناوی خزمەت",
        "serviceDescription": "پەسناسی خزمەت",
        "price": "نرخ",
        "currency": "دراو",
        "selectCurrency": "جۆری دراو هەڵبژێرە",
        "duration": "ماوە",
        "notes": "تێبینییەکان",
        "notesPlaceholder": "تێبینیی زیاتر بۆ ئەم خزمەتە"
      },
      "actions": {
        "add": "زیادکردنی خزمەت",
        "save": "پاشەکەوتکردن",
        "cancel": "هەڵوەشاندنەوە"
      },
      "messages": {
        "addSuccess": "خزمەت بە سەرکەوتوویی زیادکرا",
        "addError": "زیادکردن شکستی هێنا",
        "updateSuccess": "خزمەت بە سەرکەوتوویی نوێکرایەوە",
        "updateError": "نوێکردنەوە شکستی هێنا",
        "removeSuccess": "خزمەت بە سەرکەوتوویی سڕایەوە",
        "removeError": "سڕینەوە شکستی هێنا",
        "serviceSelectionRequired": "تکایە پەسناسی خزمەت هەڵبژێرە",
        "priceRequired": "تکایە نرخ بنووسە",
        "currencyRequired": "تکایە دراو هەڵبژێرە",
        "durationRequired": "تکایە ماوە بنووسە"
      },
      "removeDialog": {
        "title": "سڕینەوەی خزمەت",
        "description": "دڵنیایت دەوێت ئەم خزمەتە بسڕیتەوە؟ ئەم کردارە پەسند نابێتەوە."
      },
      "units": {
        "minutesShort": "خولەک"
      }
    },
    "policies": {
      "title": "بەڕێوەبردنی سیاسەت",
      "description": "بەڕێوەبردنی سیاسەتەکان بۆ ئەم دابینکەرە",
      "noPolicies": "هیچ سیاسەتێك دابین نەکراوە",
      "add": {
        "title": "زیادکردنی سیاسەت",
        "description": "دیاریکردنی سیاسەتی نوێ بۆ ئەم دابینکەرە"
      },
      "form": {
        "type": "جۆری سیاسەت",
        "typePlaceholder": "جۆری سیاسەت بنووسە (وەک: سیاسەتی هەڵوەشاندن، پارەگێڕانەوە)",
        "description": "پەسناسی سیاسەت",
        "descriptionPlaceholder": "وردەکاریی سیاسەت بنووسە..."
      },
      "actions": {
        "add": "زیادکردنی سیاسەت",
        "save": "پاشەکەوتکردن",
        "cancel": "هەڵوەشاندنەوە"
      },
      "messages": {
        "addSuccess": "سیاسەت بە سەرکەوتوویی زیادکرا",
        "addError": "زیادکردنی سیاسەت شکستی هێنا",
        "updateSuccess": "سیاسەت بە سەرکەوتوویی نوێکرایەوە",
        "updateError": "نوێکردنەوەی سیاسەت شکستی هێنا",
        "removeSuccess": "سیاسەت بە سەرکەوتوویی سڕایەوە",
        "removeError": "سڕینەوەی سیاسەت شکستی هێنا",
        "typeRequired": "تکایە جۆری سیاسەت بنووسە",
        "descriptionRequired": "تکایە پەسناسی سیاسەت بنووسە",
        "duplicateType": "سیاسەتێك بە هەمان جۆر پێشتر هەیە"
      },
      "removeDialog": {
        "title": "لابردنی سیاسەت",
        "description": "دڵنیایت دەوێت ئەم سیاسەتە بسڕیتەوە؟ ئەم کردارە پەسند نابێتەوە."
      }
    },
    "attributes": {
      "title": "بەڕێوەبردنی تایبەتمەندی",
      "description": "بە ڕاستەوخۆیی بە پەسناسی جۆری دابینکەرەکاندا تایبەتمەندی تایبەتی دابین بکە",
      "noAttributes": "هیچ تایبەتمەندییەك دابین نەکراوە",
      "availableDefinitions": "پەسناسیە بەردەستەکان",
      "noAvailableDefinitions": "هەموو تایبەتمەندیە بەردەستەکان بۆ ئەم جۆرە دابینکەرە دابین کراون",
      "add": {
        "title": "زیادکردنی تایبەتمەندی",
        "description": "ڕێکخستنی بەهای تایبەتمەندیی نوێ بۆ ئەم دابینکەرە"
      },
      "form": {
        "attributeDefinition": "پەسناسی تایبەتمەندی",
        "selectAttribute": "تایبەتمەندی هەڵبژێرە",
        "selectedAttribute": "وردەکاریی تایبەتمەندی دیاریکراو",
        "name": "ناو",
        "type": "جۆر",
        "required": "پێویست",
        "value": "بەهای تایبەتمەندی",
        "valuePlaceholder": "بەهای ئەم تایبەتمەندییە بنووسە...",
        "selectValue": "بەهای هەڵبژێرە",
        "yes": "بەڵێ",
        "no": "نەخێر"
      },
      "actions": {
        "add": "زیادکردنی تایبەتمەندی",
        "save": "پاشەکەوتکردن",
        "cancel": "هەڵوەشاندنەوە",
        "retry": "هەوڵدانەوە"
      },
      "messages": {
        "addSuccess": "تایبەتمەندی بە سەرکەوتوویی زیادکرا",
        "addError": "زیادکردن شکستی هێنا",
        "updateSuccess": "تایبەتمەندی بە سەرکەوتوویی نوێکرایەوە",
        "updateError": "نوێکردنەوە شکستی هێنا",
        "removeSuccess": "تایبەتمەندی بە سەرکەوتوویی سڕایەوە",
        "removeError": "سڕینەوە شکستی هێنا",
        "attributeRequired": "تکایە تایبەتمەندی هەڵبژێرە",
        "valueRequired": "تکایە بەها بنووسە",
        "fetchError": "نەتوانرا پەسناسی تایبەتمەندیەکان بهێنرێت"
      },
      "removeDialog": {
        "title": "سڕینەوەی تایبەتمەندی",
        "description": "دڵنیایت دەوێت ئەم تایبەتمەندییە بسڕیتەوە؟ ئەم کردارە پەسند نابێتەوە."
      }
    },
    "search": {
      "placeholder": "گەڕان لە کارمەندان...",
      "noResults": "هیچ کارمەندێك نەدۆزرایەوە."
    },
    "messages": {
      "success": "کرداری دابینکەری خزمەت بە سەرکەوتوویی تەواو بوو",
      "error": "نەتوانرا کرداری دابینکەری خزمەت پێکبێت",
      "deleteSuccess": "دابینکەری خزمەت بە سەرکەوتوویی سڕایەوە",
      "deleteError": "سڕینەوە شکستی هێنا",
      "statusChanged": "دۆخ بە سەرکەوتوویی گۆڕدرا",
      "statusChangeError": "گۆڕینی دۆخ شکستی هێنا"
    },
    "errors": {
      "invalidPhone": "تکایە ژمارەی تەلەفۆنی دروست بنووسە",
      "createFailed": "نەتوانرا دابینکەر دروست بکرێت",
      "updateFailed": "نەتوانرا نوێ بکرێت",
      "gradeRequired": "پلە پێویستە",
      "gradeInvalid": "پلە پێویستە لە نێوان A تا E بێت",
      "gradeNotUnique": "دەستەواژەی ئەم پلەیە پێشتر بۆ ئەم جۆرە دابینکەرە لە ئەم شوێنە هەیە"
    },
    "delete": {
      "dialog": {
        "title": "سڕینەوەی دابینکەری خزمەت",
        "description": "دڵنیایت دەوێت ئەم دابینکەرە بسڕیتەوە؟ ئەم کردارە پەسند نابێتەوە.",
        "cancel": "هەڵوەشاندنەوە",
        "confirm": "سڕینەوە"
      }
    }
  },
  "ProviderType": {
    "name": "جۆری دابینکەر",
    "page": {
      "title": "جۆرەکانی دابینکەر",
      "description": "بەڕێوەبردنی جۆری دابینکەر و پەسناسی تایبەتمەندییان"
    },
    "add": {
      "page": {
        "title": "زیادکردنی جۆری دابینکەر",
        "description": "دروستکردنی جۆرێکی نوێ"
      },
      "title": "زیادکردنی جۆری دابینکەری نوێ"
    },
    "update": {
      "page": {
        "title": "نوێکردنەوەی جۆری دابینکەر",
        "description": "دەستکاری کردنی زانیاریی جۆر"
      },
      "title": "نوێکردنەوەی جۆری دابینکەر"
    },
    "form": {
      "name": {
        "label": "ناو"
      },
      "description": {
        "label": "پەسناس"
      },
      "isActive": "چالاک",
      "attributes": "پەسناسی تایبەتمەندی",
      "attributesPlaceholder": "تایبەتمەندی ({count} دیاریکراوە)",
      "create": "دروستکردنی جۆری دابینکەر",
      "update": "نوێکردنەوەی جۆر",
      "creating": "لە دروستکردنەدایە...",
      "updating": "لە نوێکردنەوەدایە...",
      "cancel": "هەڵوەشاندنەوە",
      "selectProviderType": "جۆر هەڵبژێرە",
      "iconUrl": {
        "label": "نیشانە",
        "placeholder": "نیشانە هەڵبژێرە"
      }
    },
    "table": {
      "name": "ناو",
      "description": "پەسناس",
      "icon": "نیشانە",
      "attributes": "تایبەتمەندییەکان",
      "status": "دۆخ",
      "actions": "کردارەکان"
    },
    "actions": {
      "addProviderType": "زیادکردنی جۆر",
      "editProviderType": "دەستکاری جۆر",
      "deleteProviderType": "سڕینەوەی جۆر",
      "deleteProviderTypeDescription": "دڵنیایت دەوێت ئەم جۆرە بسڕیتەوە؟",
      "activate": "چالاککردن",
      "deactivate": "ناچالاککردن",
      "toggleActivation": "گۆڕینی دۆخی چالاکی",
      "viewDetails": "بینینی وردەکاری",
      "removeAttribute": "سڕینەوەی تایبەتمەندی",
      "removeAttributeDescription": "دڵنیایت دەوێت ئەم تایبەتمەندییە بسڕیتەوە؟",
      "retry": "هەوڵدانەوە",
      "cancel": "هەڵوەشاندنەوە",
      "save": "ناردنەوە",
      "saving": "لە ناردنەوەدایە..."
    },
    "status": {
      "active": "چالاک",
      "inactive": "ناچالاک"
    },
    "messages": {
      "success": "کرداری جۆری دابینکەر بە سەرکەوتوویی تەواو بوو",
      "error": "نەتوانرا کرداری جۆری دابینکەر پێکبێت",
      "updated": "جۆر بە سەرکەوتوویی نوێ کرایەوە",
      "attributeAddSuccess": "پەسناسی تایبەتمەندی بە سەرکەوتوویی زیادکرا",
      "attributeRemoveSuccess": "پەسناسی تایبەتمەندی بە سەرکەوتوویی سڕایەوە",
      "attributeUpdateSuccess": "پەسناسی تایبەتمەندی بە سەرکەوتوویی نوێ کرایەوە"
    },
    "attributes": {
      "title": "پەسناسی تایبەتمەندی",
      "description": "بەڕێوەبردنی پەسناسی تایبەتمەندییەکان و هەڵبژاردەکانیان",
      "addAttribute": "زیادکردنی تایبەتمەندی",
      "addNew": "زیادکردنی تایبەتمەندی نوێ",
      "noAttributes": "هیچ تایبەتمەندییەک دیارینەکراوە",
      "form": {
        "name": {
          "label": "ناوی تایبەتمەندی"
        },
        "description": {
          "label": "پەسناس"
        },
        "attributeType": "جۆری تایبەتمەندی",
        "attributeTypePlaceholder": "جۆر هەڵبژێرە",
        "isRequired": "پێویست",
        "validationRules": "یاسای دڵنیاکردن",
        "validationRulesPlaceholder": "یاساکان بنووسە (ئارەزوومەندانە)",
        "options": "هەڵبژاردەکان",
        "addOption": "زیادکردنی هەڵبژاردە",
        "noOptions": "کرتە بکە لە 'زیادکردنی هەڵبژاردە' بۆ دروستکردن",
        "add": "زیادکردن",
        "adding": "لە زیادکردنەدایە...",
        "displayName": {
          "label": "ناوی نیشاندان"
        },
        "value": {
          "label": "بەها"
        },
        "type": "جۆر",
        "required": "پێویست",
        "rules": "یاساکان",
        "optionsCount": "هەڵبژاردەکان",
        "yes": "بەڵێ",
        "no": "نەخێر"
      }
    },
    "details": {
      "title": "وردەکاریی جۆری دابینکەر",
      "description": "بینینی وردەکاریی {name} بە بەڕێوەبردنی تایبەتمەندی",
      "basicInfo": "زانیاریی بنەڕەتی",
      "statistics": "ئامار",
      "created": "دروستکرا",
      "modified": "نوێکرایەوە",
      "attributeDefinitionsCount": "ژمارەی پەسناسی تایبەتمەندی"
    },
    "tabs": {
      "overview": "کورتە",
      "attributes": "تایبەتمەندییەکان"
    },
    "search": {
      "placeholder": "گەڕان لە جۆری دابینکەر...",
      "noResults": "هیچ جۆرێك نەدۆزرایەوە."
    }
  },
  "shared": {
    "selectOption": "هەڵبژاردەیەک هەڵبژێرە",
    "searchPlaceholder": "گەڕان...",
    "noResults": "هیچ ئەنجامێك نەدۆزرایەوە"
  },
  "LocalizedInput": {
    "placeholder": "تکایە {field} بە {language} بنووسە"
  },
  "List": {
    "loading": "لە بارکردنەدایە...",
    "loadMore": "زیاتر باربکە"
  }
};
export default messages;