import { normalizePortalLocale, type PortalLocale } from "@core/i18n/config";

type Copy = {
  moduleName: string; providerTitle: string; providerDescription: string; staffTitle: string; staffDescription: string;
  bookings: string; upcoming: string; assigned: string; paymentAttention: string; providerList: string; assignedBookings: string;
  booking: string; dateTime: string; status: string; payment: string; assignment: string; total: string; service: string; customer: string; provider: string;
  noBookings: string; noStaffBookings: string; noStaff: string; noResource: string; unassigned: string; notes: string; paymentUnknown: string;
  operations: string; assign: string; staff: string; resource: string; assignmentNote: string; assignAction: string;
  newStatus: string; providerNote: string; updateStatus: string; addInternalNote: string; note: string; addNote: string; processing: string;
  confirmed: string; inProgress: string; completed: string; cancelled: string; noShow: string; providerReview: string;
  invalidIdentifier: string; bookingNotFound: string; staffNotOwned: string; resourceNotOwned: string; assignmentTargetRequired: string;
  invalidStatus: string; invalidTransition: string; noteRequired: string; noteTooLong: string; staffBookingNotAssigned: string; providerRequired: string;
};

const en: Copy = {
  moduleName:"Booking Management", providerTitle:"Booking management", providerDescription:"Manage bookings for this provider, including staff/resource assignment, operational notes and safe status transitions.", staffTitle:"My assigned bookings", staffDescription:"See only bookings actively assigned to your approved staff profile and add internal operational notes.",
  bookings:"Bookings", upcoming:"Upcoming / open", assigned:"Assigned", paymentAttention:"Payment attention", providerList:"Provider booking list", assignedBookings:"Assigned bookings",
  booking:"Booking", dateTime:"Date / time", status:"Status", payment:"Payment", assignment:"Assignment", total:"Total", service:"Service", customer:"Customer", provider:"Provider",
  noBookings:"No bookings were found for this provider.", noStaffBookings:"No bookings are currently assigned to you.", noStaff:"No staff", noResource:"No resource", unassigned:"Unassigned", notes:"notes", paymentUnknown:"Payment unknown",
  operations:"Operations", assign:"Assign booking", staff:"Staff", resource:"Resource", assignmentNote:"Assignment note", assignAction:"Assign staff / resource",
  newStatus:"New status", providerNote:"Provider note", updateStatus:"Update booking status", addInternalNote:"Add internal service note", note:"Note", addNote:"Add note", processing:"Processing…",
  confirmed:"Confirmed", inProgress:"In progress", completed:"Completed", cancelled:"Cancelled", noShow:"No show", providerReview:"Provider review",
  invalidIdentifier:"One or more booking identifiers are invalid.", bookingNotFound:"Booking not found for this provider.", staffNotOwned:"Selected staff is not active for this provider.", resourceNotOwned:"Selected resource is not active for this provider.", assignmentTargetRequired:"Select staff, a resource, or both before assigning the booking.",
  invalidStatus:"The requested booking status is invalid.", invalidTransition:"This booking status transition is not allowed.", noteRequired:"Booking note cannot be empty.", noteTooLong:"Booking note is too long.", staffBookingNotAssigned:"This booking is not actively assigned to your staff profile.", providerRequired:"Your approved staff profile is not linked to a provider.",
};

const dictionaries: Record<PortalLocale, Copy> = {
  en,
  fa:{...en,moduleName:"مدیریت رزروها",providerTitle:"مدیریت رزروها",providerDescription:"رزروهای این ارائه‌دهنده، تخصیص پرسنل یا منبع، یادداشت‌های عملیاتی و تغییر وضعیت امن را مدیریت کنید.",staffTitle:"رزروهای منتسب به من",staffDescription:"فقط رزروهایی را ببینید که فعالانه به پروفایل پرسنلی تأییدشده شما منتسب شده‌اند و یادداشت داخلی ثبت کنید.",bookings:"رزروها",upcoming:"آینده / باز",assigned:"تخصیص‌یافته",paymentAttention:"نیازمند بررسی پرداخت",providerList:"فهرست رزروهای ارائه‌دهنده",assignedBookings:"رزروهای منتسب",booking:"رزرو",dateTime:"تاریخ / زمان",status:"وضعیت",payment:"پرداخت",assignment:"تخصیص",total:"مبلغ کل",service:"خدمت",customer:"مشتری",provider:"ارائه‌دهنده",noBookings:"رزروی برای این ارائه‌دهنده یافت نشد.",noStaffBookings:"در حال حاضر رزروی به شما تخصیص داده نشده است.",noStaff:"بدون پرسنل",noResource:"بدون منبع",unassigned:"تخصیص‌نیافته",notes:"یادداشت",paymentUnknown:"وضعیت پرداخت نامشخص",operations:"عملیات",assign:"تخصیص رزرو",staff:"پرسنل",resource:"منبع",assignmentNote:"یادداشت تخصیص",assignAction:"تخصیص پرسنل / منبع",newStatus:"وضعیت جدید",providerNote:"یادداشت ارائه‌دهنده",updateStatus:"به‌روزرسانی وضعیت رزرو",addInternalNote:"افزودن یادداشت داخلی",note:"یادداشت",addNote:"افزودن یادداشت",processing:"در حال انجام…",confirmed:"تأییدشده",inProgress:"در حال انجام",completed:"تکمیل‌شده",cancelled:"لغوشده",noShow:"عدم حضور",providerReview:"بررسی ارائه‌دهنده",invalidIdentifier:"یک یا چند شناسه رزرو نامعتبر است.",bookingNotFound:"رزرو برای این ارائه‌دهنده یافت نشد.",staffNotOwned:"پرسنل انتخاب‌شده برای این ارائه‌دهنده فعال نیست.",resourceNotOwned:"منبع انتخاب‌شده برای این ارائه‌دهنده فعال نیست.",assignmentTargetRequired:"پیش از تخصیص، پرسنل، منبع یا هر دو را انتخاب کنید.",invalidStatus:"وضعیت درخواستی رزرو نامعتبر است.",invalidTransition:"این تغییر وضعیت رزرو مجاز نیست.",noteRequired:"یادداشت رزرو نمی‌تواند خالی باشد.",noteTooLong:"یادداشت رزرو بیش از حد طولانی است.",staffBookingNotAssigned:"این رزرو به‌صورت فعال به پروفایل پرسنلی شما منتسب نیست.",providerRequired:"پروفایل پرسنلی تأییدشده شما به ارائه‌دهنده‌ای متصل نیست."},
  ar:{...en,moduleName:"إدارة الحجوزات",providerTitle:"إدارة الحجوزات",providerDescription:"أدر حجوزات مقدم الخدمة وتعيين الموظفين والموارد والملاحظات التشغيلية وتغييرات الحالة الآمنة.",staffTitle:"حجوزاتي المسندة",staffDescription:"اعرض فقط الحجوزات المسندة فعلياً إلى ملف الموظف المعتمد الخاص بك وأضف ملاحظات تشغيلية داخلية.",bookings:"الحجوزات",upcoming:"قادمة / مفتوحة",assigned:"مسندة",paymentAttention:"تحتاج مراجعة الدفع",providerList:"حجوزات مقدم الخدمة",assignedBookings:"الحجوزات المسندة",booking:"الحجز",dateTime:"التاريخ / الوقت",status:"الحالة",payment:"الدفع",assignment:"التعيين",total:"الإجمالي",service:"الخدمة",customer:"العميل",provider:"مقدم الخدمة",noBookings:"لا توجد حجوزات لمقدم الخدمة هذا.",noStaffBookings:"لا توجد حجوزات مسندة إليك حالياً.",noStaff:"بدون موظف",noResource:"بدون مورد",unassigned:"غير مسند",notes:"ملاحظات",paymentUnknown:"الدفع غير معروف",operations:"العمليات",assign:"تعيين الحجز",staff:"الموظف",resource:"المورد",assignmentNote:"ملاحظة التعيين",assignAction:"تعيين موظف / مورد",newStatus:"الحالة الجديدة",providerNote:"ملاحظة مقدم الخدمة",updateStatus:"تحديث حالة الحجز",addInternalNote:"إضافة ملاحظة داخلية",note:"الملاحظة",addNote:"إضافة ملاحظة",processing:"جارٍ التنفيذ…",confirmed:"مؤكد",inProgress:"قيد التنفيذ",completed:"مكتمل",cancelled:"ملغى",noShow:"لم يحضر",providerReview:"مراجعة مقدم الخدمة",invalidIdentifier:"معرّف حجز واحد أو أكثر غير صالح.",bookingNotFound:"الحجز غير موجود لدى مقدم الخدمة هذا.",staffNotOwned:"الموظف المحدد غير نشط لدى مقدم الخدمة هذا.",resourceNotOwned:"المورد المحدد غير نشط لدى مقدم الخدمة هذا.",assignmentTargetRequired:"اختر موظفاً أو مورداً أو كليهما قبل التعيين.",invalidStatus:"حالة الحجز المطلوبة غير صالحة.",invalidTransition:"تغيير حالة الحجز هذا غير مسموح.",noteRequired:"لا يمكن أن تكون ملاحظة الحجز فارغة.",noteTooLong:"ملاحظة الحجز طويلة جداً.",staffBookingNotAssigned:"هذا الحجز غير مسند فعلياً إلى ملف الموظف الخاص بك.",providerRequired:"ملف الموظف المعتمد الخاص بك غير مرتبط بمقدم خدمة."},
  tr:{...en,moduleName:"Rezervasyon Yönetimi",providerTitle:"Rezervasyon yönetimi",providerDescription:"Sağlayıcı rezervasyonlarını, personel/kaynak atamalarını, operasyon notlarını ve güvenli durum geçişlerini yönetin.",staffTitle:"Bana atanan rezervasyonlar",staffDescription:"Yalnızca onaylı personel profilinize aktif olarak atanmış rezervasyonları görün ve iç operasyon notları ekleyin.",bookings:"Rezervasyonlar",upcoming:"Yaklaşan / açık",assigned:"Atanmış",paymentAttention:"Ödeme kontrolü",providerList:"Sağlayıcı rezervasyonları",assignedBookings:"Atanan rezervasyonlar",booking:"Rezervasyon",dateTime:"Tarih / saat",status:"Durum",payment:"Ödeme",assignment:"Atama",total:"Toplam",service:"Hizmet",customer:"Müşteri",provider:"Sağlayıcı",noBookings:"Bu sağlayıcı için rezervasyon bulunamadı.",noStaffBookings:"Şu anda size atanmış rezervasyon yok.",noStaff:"Personel yok",noResource:"Kaynak yok",unassigned:"Atanmamış",notes:"not",paymentUnknown:"Ödeme bilinmiyor",operations:"İşlemler",assign:"Rezervasyon ata",staff:"Personel",resource:"Kaynak",assignmentNote:"Atama notu",assignAction:"Personel / kaynak ata",newStatus:"Yeni durum",providerNote:"Sağlayıcı notu",updateStatus:"Rezervasyon durumunu güncelle",addInternalNote:"İç hizmet notu ekle",note:"Not",addNote:"Not ekle",processing:"İşleniyor…",confirmed:"Onaylandı",inProgress:"Devam ediyor",completed:"Tamamlandı",cancelled:"İptal",noShow:"Gelmedi",providerReview:"Sağlayıcı incelemesi",invalidIdentifier:"Bir veya daha fazla rezervasyon kimliği geçersiz.",bookingNotFound:"Rezervasyon bu sağlayıcı için bulunamadı.",staffNotOwned:"Seçilen personel bu sağlayıcı için aktif değil.",resourceNotOwned:"Seçilen kaynak bu sağlayıcı için aktif değil.",assignmentTargetRequired:"Atamadan önce personel, kaynak veya ikisini seçin.",invalidStatus:"İstenen rezervasyon durumu geçersiz.",invalidTransition:"Bu rezervasyon durumu geçişine izin verilmiyor.",noteRequired:"Rezervasyon notu boş olamaz.",noteTooLong:"Rezervasyon notu çok uzun.",staffBookingNotAssigned:"Bu rezervasyon personel profilinize aktif olarak atanmamış.",providerRequired:"Onaylı personel profiliniz bir sağlayıcıya bağlı değil."},
  es:{...en,moduleName:"Gestión de reservas",providerTitle:"Gestión de reservas",providerDescription:"Gestiona reservas, asignación de personal/recursos, notas operativas y transiciones de estado seguras.",staffTitle:"Mis reservas asignadas",staffDescription:"Consulta solo reservas asignadas activamente a tu perfil de personal aprobado y añade notas internas.",bookings:"Reservas",upcoming:"Próximas / abiertas",assigned:"Asignadas",paymentAttention:"Revisar pago",providerList:"Reservas del proveedor",assignedBookings:"Reservas asignadas",booking:"Reserva",dateTime:"Fecha / hora",status:"Estado",payment:"Pago",assignment:"Asignación",total:"Total",service:"Servicio",customer:"Cliente",provider:"Proveedor",noBookings:"No se encontraron reservas para este proveedor.",noStaffBookings:"No tienes reservas asignadas actualmente.",noStaff:"Sin personal",noResource:"Sin recurso",unassigned:"Sin asignar",notes:"notas",paymentUnknown:"Pago desconocido",operations:"Operaciones",assign:"Asignar reserva",staff:"Personal",resource:"Recurso",assignmentNote:"Nota de asignación",assignAction:"Asignar personal / recurso",newStatus:"Nuevo estado",providerNote:"Nota del proveedor",updateStatus:"Actualizar estado",addInternalNote:"Añadir nota interna",note:"Nota",addNote:"Añadir nota",processing:"Procesando…",confirmed:"Confirmada",inProgress:"En curso",completed:"Completada",cancelled:"Cancelada",noShow:"No se presentó",providerReview:"Revisión del proveedor",invalidIdentifier:"Uno o más identificadores de reserva no son válidos.",bookingNotFound:"Reserva no encontrada para este proveedor.",staffNotOwned:"El personal seleccionado no está activo para este proveedor.",resourceNotOwned:"El recurso seleccionado no está activo para este proveedor.",assignmentTargetRequired:"Selecciona personal, recurso o ambos antes de asignar.",invalidStatus:"El estado solicitado no es válido.",invalidTransition:"Esta transición de estado no está permitida.",noteRequired:"La nota no puede estar vacía.",noteTooLong:"La nota es demasiado larga.",staffBookingNotAssigned:"Esta reserva no está asignada activamente a tu perfil.",providerRequired:"Tu perfil de personal aprobado no está vinculado a un proveedor."},
  ku:{...en,moduleName:"بەڕێوەبردنی رزێرڤ",providerTitle:"بەڕێوەبردنی رزێرڤ",providerDescription:"رزێرڤەکانی پێشکەشکار، دیاریکردنی ستاف/سەرچاوە، تێبینی کار و گۆڕینی سەلامەتی دۆخ بەڕێوەببە.",staffTitle:"رزێرڤە دیاریکراوەکانی من",staffDescription:"تەنها رزێرڤە چالاکان ببینە کە بە پرۆفایلی ستافی پەسەندکراوت دیاریکراون و تێبینی ناوخۆیی زیاد بکە.",bookings:"رزێرڤەکان",upcoming:"داهاتوو / کراوە",assigned:"دیاریکراو",paymentAttention:"پێویستی بە پشکنینی پارەدان",providerList:"رزێرڤەکانی پێشکەشکار",assignedBookings:"رزێرڤە دیاریکراوەکان",booking:"رزێرڤ",dateTime:"بەروار / کات",status:"دۆخ",payment:"پارەدان",assignment:"دیاریکردن",total:"کۆی گشتی",service:"خزمەت",customer:"کڕیار",provider:"پێشکەشکار",noBookings:"هیچ رزێرڤێک بۆ ئەم پێشکەشکارە نەدۆزرایەوە.",noStaffBookings:"ئێستا هیچ رزێرڤێکت پێ نەسپێردراوە.",noStaff:"بێ ستاف",noResource:"بێ سەرچاوە",unassigned:"دیارینەکراو",notes:"تێبینی",paymentUnknown:"پارەدان نەزانراو",operations:"کردارەکان",assign:"دیاریکردنی رزێرڤ",staff:"ستاف",resource:"سەرچاوە",assignmentNote:"تێبینی دیاریکردن",assignAction:"دیاریکردنی ستاف / سەرچاوە",newStatus:"دۆخی نوێ",providerNote:"تێبینی پێشکەشکار",updateStatus:"نوێکردنەوەی دۆخی رزێرڤ",addInternalNote:"زیادکردنی تێبینی ناوخۆیی",note:"تێبینی",addNote:"زیادکردنی تێبینی",processing:"جێبەجێ دەکرێت…",confirmed:"پەسەندکراو",inProgress:"لە جێبەجێکردندا",completed:"تەواو",cancelled:"هەڵوەشاوە",noShow:"نەهات",providerReview:"پشکنینی پێشکەشکار",invalidIdentifier:"یەک یان زیاتر لە ناسنامەکانی رزێرڤ نادروستن.",bookingNotFound:"رزێرڤ بۆ ئەم پێشکەشکارە نەدۆزرایەوە.",staffNotOwned:"ستافی هەڵبژێردراو بۆ ئەم پێشکەشکارە چالاک نییە.",resourceNotOwned:"سەرچاوەی هەڵبژێردراو بۆ ئەم پێشکەشکارە چالاک نییە.",assignmentTargetRequired:"پێش دیاریکردن ستاف یان سەرچاوە یان هەردووکیان هەڵبژێرە.",invalidStatus:"دۆخی داواکراوی رزێرڤ نادروستە.",invalidTransition:"ئەم گۆڕینی دۆخە ڕێگەپێدراو نییە.",noteRequired:"تێبینی رزێرڤ نابێت بەتاڵ بێت.",noteTooLong:"تێبینی رزێرڤ زۆر درێژە.",staffBookingNotAssigned:"ئەم رزێرڤە بە چالاکی بە پرۆفایلی ستافەکەت دیارینەکراوە.",providerRequired:"پرۆفایلی ستافی پەسەندکراوت بە پێشکەشکارێکەوە نەبەستراوە."},
  de:{...en,moduleName:"Buchungsverwaltung",providerTitle:"Buchungsverwaltung",providerDescription:"Verwalten Sie Anbieterbuchungen, Mitarbeiter-/Ressourcenzuweisungen, Betriebsnotizen und sichere Statuswechsel.",staffTitle:"Meine zugewiesenen Buchungen",staffDescription:"Sehen Sie nur Buchungen, die aktiv Ihrem bestätigten Mitarbeiterprofil zugewiesen sind, und ergänzen Sie interne Notizen.",bookings:"Buchungen",upcoming:"Bevorstehend / offen",assigned:"Zugewiesen",paymentAttention:"Zahlung prüfen",providerList:"Anbieterbuchungen",assignedBookings:"Zugewiesene Buchungen",booking:"Buchung",dateTime:"Datum / Zeit",status:"Status",payment:"Zahlung",assignment:"Zuweisung",total:"Gesamt",service:"Leistung",customer:"Kunde",provider:"Anbieter",noBookings:"Keine Buchungen für diesen Anbieter gefunden.",noStaffBookings:"Ihnen sind derzeit keine Buchungen zugewiesen.",noStaff:"Kein Mitarbeiter",noResource:"Keine Ressource",unassigned:"Nicht zugewiesen",notes:"Notizen",paymentUnknown:"Zahlung unbekannt",operations:"Vorgänge",assign:"Buchung zuweisen",staff:"Mitarbeiter",resource:"Ressource",assignmentNote:"Zuweisungsnotiz",assignAction:"Mitarbeiter / Ressource zuweisen",newStatus:"Neuer Status",providerNote:"Anbieternotiz",updateStatus:"Buchungsstatus aktualisieren",addInternalNote:"Interne Notiz hinzufügen",note:"Notiz",addNote:"Notiz hinzufügen",processing:"Wird verarbeitet…",confirmed:"Bestätigt",inProgress:"In Bearbeitung",completed:"Abgeschlossen",cancelled:"Storniert",noShow:"Nicht erschienen",providerReview:"Anbieterprüfung",invalidIdentifier:"Eine oder mehrere Buchungskennungen sind ungültig.",bookingNotFound:"Buchung für diesen Anbieter nicht gefunden.",staffNotOwned:"Der ausgewählte Mitarbeiter ist für diesen Anbieter nicht aktiv.",resourceNotOwned:"Die ausgewählte Ressource ist für diesen Anbieter nicht aktiv.",assignmentTargetRequired:"Wählen Sie vor der Zuweisung Mitarbeiter, Ressource oder beides.",invalidStatus:"Der gewünschte Buchungsstatus ist ungültig.",invalidTransition:"Dieser Statuswechsel ist nicht zulässig.",noteRequired:"Die Buchungsnotiz darf nicht leer sein.",noteTooLong:"Die Buchungsnotiz ist zu lang.",staffBookingNotAssigned:"Diese Buchung ist Ihrem Mitarbeiterprofil nicht aktiv zugewiesen.",providerRequired:"Ihr bestätigtes Mitarbeiterprofil ist keinem Anbieter zugeordnet."},
  fr:{...en,moduleName:"Gestion des réservations",providerTitle:"Gestion des réservations",providerDescription:"Gérez les réservations du prestataire, les affectations de personnel/ressources, les notes opérationnelles et les transitions d’état sûres.",staffTitle:"Mes réservations affectées",staffDescription:"Consultez uniquement les réservations activement affectées à votre profil de personnel approuvé et ajoutez des notes internes.",bookings:"Réservations",upcoming:"À venir / ouvertes",assigned:"Affectées",paymentAttention:"Paiement à vérifier",providerList:"Réservations du prestataire",assignedBookings:"Réservations affectées",booking:"Réservation",dateTime:"Date / heure",status:"Statut",payment:"Paiement",assignment:"Affectation",total:"Total",service:"Service",customer:"Client",provider:"Prestataire",noBookings:"Aucune réservation trouvée pour ce prestataire.",noStaffBookings:"Aucune réservation ne vous est actuellement affectée.",noStaff:"Aucun personnel",noResource:"Aucune ressource",unassigned:"Non affectée",notes:"notes",paymentUnknown:"Paiement inconnu",operations:"Opérations",assign:"Affecter la réservation",staff:"Personnel",resource:"Ressource",assignmentNote:"Note d’affectation",assignAction:"Affecter personnel / ressource",newStatus:"Nouveau statut",providerNote:"Note du prestataire",updateStatus:"Mettre à jour le statut",addInternalNote:"Ajouter une note interne",note:"Note",addNote:"Ajouter la note",processing:"Traitement…",confirmed:"Confirmée",inProgress:"En cours",completed:"Terminée",cancelled:"Annulée",noShow:"Absent",providerReview:"Revue du prestataire",invalidIdentifier:"Un ou plusieurs identifiants de réservation sont invalides.",bookingNotFound:"Réservation introuvable pour ce prestataire.",staffNotOwned:"Le membre du personnel sélectionné n’est pas actif pour ce prestataire.",resourceNotOwned:"La ressource sélectionnée n’est pas active pour ce prestataire.",assignmentTargetRequired:"Sélectionnez du personnel, une ressource ou les deux avant l’affectation.",invalidStatus:"Le statut demandé est invalide.",invalidTransition:"Cette transition de statut n’est pas autorisée.",noteRequired:"La note de réservation ne peut pas être vide.",noteTooLong:"La note de réservation est trop longue.",staffBookingNotAssigned:"Cette réservation n’est pas activement affectée à votre profil.",providerRequired:"Votre profil de personnel approuvé n’est lié à aucun prestataire."},
};

export function bookingManagementCopy(locale?: string | null) { return dictionaries[normalizePortalLocale(locale).locale] ?? en; }
export type BookingManagementCopy = Copy;

export function bookingStatusLabel(copy: Copy, status?: string | null) {
  const key: Record<string, keyof Copy> = { Confirmed:"confirmed", InProgress:"inProgress", Completed:"completed", Cancelled:"cancelled", NoShow:"noShow", ProviderReview:"providerReview" };
  return status && key[status] ? copy[key[status]] : (status || copy.unassigned);
}
