<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <Content Include="identity.appsettings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="identity.appsettings.Development.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="identity.appsettings.Production.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\BuildingBlocks\BuildingBlocks.Core\BuildingBlocks.Core.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\BuildingBlocks.Persistence.EfCore.Postgres\BuildingBlocks.Persistence.EfCore.Postgres.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\BuildingBlocks.Web\BuildingBlocks.Web.csproj" />
    <ProjectReference Include="..\..\Common\LSevin.Modules.Common\LSevin.Modules.Common.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" />
    <PackageReference Include="Duende.IdentityServer" />
    <PackageReference Include="Duende.IdentityServer.Storage" />
    <PackageReference Include="Duende.IdentityServer.AspNetIdentity" />
    <PackageReference Include="Duende.IdentityServer.EntityFramework" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Update="Resources\IdentityResource.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>IdentityResource.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\IdentityResource.*.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
  </ItemGroup>
  <PropertyGroup Condition="'$(Configuration)'=='Debug'">
    <DebugType>portable</DebugType>
    <DebugSymbols>true</DebugSymbols>
    <Optimize>false</Optimize>
  </PropertyGroup>
</Project>
