import { Badge } from "@core/ui/Badge";
import { Button } from "@core/ui/Button";
import { Card, CardContent, CardHeader, CardTitle } from "@core/ui/Card";
import { CurrencySelect } from "@core/ui/CurrencySelect";
import { Field } from "@core/ui/Field";
import { LocalizedDateInput } from "@core/ui/LocalizedDateInput";
import { StatCard } from "@core/ui/StatCard";
import { Banknote, CalendarDays, HandCoins, WalletCards } from "lucide-react";
import { formatDate, formatMoney } from "@core/lib/format";
import type { BookingEarningRow, BookingEarningsSummary } from "../types";

export function StaffEarningsDashboard({ staffName, providerName, from, to, currencyCode, rows, summary, locale = "fa-IR", timeZone = "Asia/Tehran" }: { staffName: string; providerName: string; from: string; to: string; currencyCode: string; rows: BookingEarningRow[]; summary: BookingEarningsSummary; locale?: string; timeZone?: string }) {
  return <div className="space-y-5">
    <Card><CardHeader><CardTitle>My earnings · {staffName}</CardTitle></CardHeader><CardContent className="space-y-4"><p className="text-sm text-muted-foreground">Provider: {providerName}. Compensation shown here is based on your provider-defined rule and the canonical paid booking assignment. It does not expose the provider’s full finance workspace.</p><form method="get" className="grid gap-3 md:grid-cols-[1fr_1fr_1fr_auto]"><Field label="From"><LocalizedDateInput name="from" value={from} locale={locale} timeZone={timeZone} /></Field><Field label="To"><LocalizedDateInput name="to" value={to} locale={locale} timeZone={timeZone} /></Field><Field label="Currency"><CurrencySelect name="currencyCode" value={currencyCode}/></Field><div className="flex items-end"><Button type="submit" variant="secondary">Apply</Button></div></form></CardContent></Card>
    <div className="grid gap-4 md:grid-cols-4"><StatCard icon={CalendarDays} label="Assigned bookings" value={summary.bookingsCount}/><StatCard icon={HandCoins} label="Estimated compensation" value={formatMoney(summary.staffCompensationEstimated,currencyCode)}/><StatCard icon={Banknote} label="Paid" value={formatMoney(summary.staffCompensationPaid,currencyCode)}/><StatCard icon={WalletCards} label="Outstanding" value={formatMoney(summary.staffCompensationOutstanding,currencyCode)}/></div>
    <Card className="overflow-hidden"><CardHeader><CardTitle>Booking compensation</CardTitle></CardHeader><CardContent className="overflow-x-auto p-0"><table className="min-w-[820px] w-full text-sm"><thead className="bg-muted text-left text-xs text-muted-foreground"><tr><th className="p-3">Booking</th><th className="p-3">Date</th><th className="p-3">Booking state</th><th className="p-3">Rule</th><th className="p-3">Estimated</th><th className="p-3">Payment</th></tr></thead><tbody>{rows.map(row=><tr key={row.bookingId} className="border-t border-border"><td className="p-3 font-mono text-xs">{row.bookingId}</td><td className="p-3">{formatDate(row.bookingDate, locale, timeZone)}</td><td className="p-3"><Badge>{row.bookingStatus}</Badge></td><td className="p-3 text-xs">{row.compensationMode ? `${row.compensationMode} · ${row.compensationPercent}% + ${formatMoney(row.compensationFixedAmount,currencyCode)}` : "No active rule"}</td><td className="p-3 font-semibold">{formatMoney(row.estimatedStaffCompensation,currencyCode)}</td><td className="p-3">{row.staffPaymentStatus === "paid" ? <Badge variant="success">Paid {formatMoney(row.staffPaymentAmount,currencyCode)}</Badge> : Number(row.estimatedStaffCompensation)>0 ? <Badge variant="warning">Outstanding</Badge> : <Badge>Not payable</Badge>}</td></tr>)}{!rows.length?<tr><td colSpan={6} className="p-6 text-center text-muted-foreground">No assigned bookings in this period/currency.</td></tr>:null}</tbody></table></CardContent></Card>
  </div>;
}
