// <auto-generated />
using System;
using System.Collections.Generic;
using LSevin.Modules.Category.Infrastructure.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LSevin.Modules.Category.Infrastructure.Data.Migrations
{
    [DbContext(typeof(CategoryContext))]
    [Migration("20250520090402_AddProviderAndStaff")]
    partial class AddProviderAndStaff
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("category")
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "uuid-ossp");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BuildingBlocks.Core.Persistence.MessagePersistence.Inbox.Idempotency.InboxMessageConsumer", b =>
                {
                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<string>("Name")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("name");

                    b.HasKey("MessageId", "Name")
                        .HasName("pk_inbox_message_consumers");

                    b.HasIndex("MessageId", "Name")
                        .HasDatabaseName("inbox_message_consumers_message_id_name");

                    b.ToTable("inbox_message_consumers", "category");
                });

            modelBuilder.Entity("BuildingBlocks.Core.Persistence.MessagePersistence.Inbox.InboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("jsonb")
                        .HasColumnName("content");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_on_utc");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_on_utc");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_inbox_messages");

                    b.HasIndex("OccurredOnUtc")
                        .HasDatabaseName("idx_inbox_messages_occurred_on");

                    b.HasIndex("ProcessedOnUtc")
                        .HasDatabaseName("idx_inbox_messages_processed_on");

                    b.HasIndex("OccurredOnUtc", "ProcessedOnUtc")
                        .HasDatabaseName("idx_inbox_messages_unprocessed")
                        .HasFilter("processed_on_utc IS NULL");

                    NpgsqlIndexBuilderExtensions.IncludeProperties(b.HasIndex("OccurredOnUtc", "ProcessedOnUtc"), new[] { "Id", "Type", "Content" });

                    b.HasIndex("ProcessedOnUtc", "OccurredOnUtc")
                        .HasDatabaseName("idx_inbox_messages_processed_occurred");

                    b.ToTable("inbox_messages", "category");
                });

            modelBuilder.Entity("BuildingBlocks.Core.Persistence.MessagePersistence.InternalCommand.Idempotency.InternalCommandMessageConsumer", b =>
                {
                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<string>("Name")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("name");

                    b.HasKey("MessageId", "Name")
                        .HasName("pk_internal_command_message_consumers");

                    b.HasIndex("MessageId", "Name")
                        .HasDatabaseName("internal_command_message_consumers_message_id_name");

                    b.ToTable("internal_command_message_consumers", "category");
                });

            modelBuilder.Entity("BuildingBlocks.Core.Persistence.MessagePersistence.InternalCommand.InternalCommandMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("jsonb")
                        .HasColumnName("content");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_on_utc");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_on_utc");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_internal_command_messages");

                    b.HasIndex("OccurredOnUtc")
                        .HasDatabaseName("idx_internal_command_messages_occurred_on");

                    b.HasIndex("ProcessedOnUtc")
                        .HasDatabaseName("idx_internal_command_messages_processed_on");

                    b.HasIndex("OccurredOnUtc", "ProcessedOnUtc")
                        .HasDatabaseName("idx_internal_command_messages_unprocessed")
                        .HasFilter("processed_on_utc IS NULL");

                    NpgsqlIndexBuilderExtensions.IncludeProperties(b.HasIndex("OccurredOnUtc", "ProcessedOnUtc"), new[] { "Id", "Type", "Content" });

                    b.HasIndex("ProcessedOnUtc", "OccurredOnUtc")
                        .HasDatabaseName("idx_internal_command_messages_processed_occurred");

                    b.ToTable("internal_command_messages", "category");
                });

            modelBuilder.Entity("BuildingBlocks.Core.Persistence.MessagePersistence.Outbox.Idempotency.OutboxMessageConsumer", b =>
                {
                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<string>("Name")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("name");

                    b.HasKey("MessageId", "Name")
                        .HasName("pk_outbox_message_consumers");

                    b.HasIndex("MessageId", "Name")
                        .HasDatabaseName("outbox_message_consumers_message_id_name");

                    b.ToTable("outbox_message_consumers", "category");
                });

            modelBuilder.Entity("BuildingBlocks.Core.Persistence.MessagePersistence.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("jsonb")
                        .HasColumnName("content");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_on_utc");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_on_utc");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("OccurredOnUtc")
                        .HasDatabaseName("idx_outbox_messages_occurred_on");

                    b.HasIndex("ProcessedOnUtc")
                        .HasDatabaseName("idx_outbox_messages_processed_on");

                    b.HasIndex("OccurredOnUtc", "ProcessedOnUtc")
                        .HasDatabaseName("idx_outbox_messages_unprocessed")
                        .HasFilter("processed_on_utc IS NULL");

                    NpgsqlIndexBuilderExtensions.IncludeProperties(b.HasIndex("OccurredOnUtc", "ProcessedOnUtc"), new[] { "Id", "Type", "Content" });

                    b.HasIndex("ProcessedOnUtc", "OccurredOnUtc")
                        .HasDatabaseName("idx_outbox_messages_processed_occurred");

                    b.ToTable("outbox_messages", "category");
                });

            modelBuilder.Entity("LSevin.Modules.Category.Category.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_date")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("display_order");

                    b.Property<string>("IconUrl")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("icon_url");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified_date")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("name");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("ParentId");

                    b.HasKey("Id")
                        .HasName("pk_categories");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_categories_parent_id");

                    b.ToTable("categories", "category");
                });

            modelBuilder.Entity("LSevin.Modules.Category.ProviderType.Entities.ProviderAttributeDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("is_required");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("ProviderTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("provider_type_id");

                    b.Property<string>("ValidationRules")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("validation_rules");

                    b.Property<int>("_attributeTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("_attribute_type_id");

                    b.HasKey("Id")
                        .HasName("pk_provider_attribute_definitions");

                    b.HasIndex("ProviderTypeId")
                        .HasDatabaseName("ix_provider_attribute_definitions_provider_type_id");

                    b.HasIndex("_attributeTypeId")
                        .HasDatabaseName("ix_provider_attribute_definitions__attribute_type_id");

                    b.ToTable("provider_attribute_definitions", "category");
                });

            modelBuilder.Entity("LSevin.Modules.Category.ProviderType.Entities.ProviderType", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_date")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified_date")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_provider_types");

                    b.ToTable("provider_types", "category");
                });

            modelBuilder.Entity("LSevin.Modules.Category.ServiceDefinition.Entities.ServiceAttributeDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("AffectsPricing")
                        .HasColumnType("boolean")
                        .HasColumnName("affects_pricing");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("is_required");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid?>("ServiceDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_definition_id");

                    b.Property<int>("_attributeTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("_attribute_type_id");

                    b.HasKey("Id")
                        .HasName("pk_service_attribute_definitions");

                    b.HasIndex("ServiceDefinitionId")
                        .HasDatabaseName("ix_service_attribute_definitions_service_definition_id");

                    b.HasIndex("_attributeTypeId")
                        .HasDatabaseName("ix_service_attribute_definitions__attribute_type_id");

                    b.ToTable("service_attribute_definitions", "category");
                });

            modelBuilder.Entity("LSevin.Modules.Category.ServiceDefinition.Entities.ServiceDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_date")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("duration_minutes");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified_date")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("PricingModel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("pricing_model");

                    b.ComplexProperty<Dictionary<string, object>>("BasePrice", "LSevin.Modules.Category.ServiceDefinition.Entities.ServiceDefinition.BasePrice#MoneyValue", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(15)
                                .HasColumnType("character varying(15)")
                                .HasColumnName("currency");

                            b1.Property<decimal>("Value")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("value");
                        });

                    b.HasKey("Id")
                        .HasName("pk_service_definitions");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_service_definitions_category_id");

                    b.ToTable("service_definitions", "category");
                });

            modelBuilder.Entity("LSevin.Modules.Category.ServiceProvider.Entities.ProviderAttribute", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AttributeDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("attribute_definition_id");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_date");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified_date");

                    b.Property<Guid>("ServiceProviderId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_provider_id");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_provider_attributes");

                    b.HasIndex("AttributeDefinitionId")
                        .HasDatabaseName("ix_provider_attributes_attribute_definition_id");

                    b.HasIndex("ServiceProviderId", "AttributeDefinitionId")
                        .IsUnique()
                        .HasDatabaseName("ix_provider_attributes_service_provider_id_attribute_definitio");

                    b.ToTable("provider_attributes", "category");
                });

            modelBuilder.Entity("LSevin.Modules.Category.ServiceProvider.Entities.ProviderGalleryItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified_date");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("media_type");

                    b.Property<Guid>("ServiceProviderId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_provider_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("title");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_provider_gallery_items");

                    b.HasIndex("DisplayOrder")
                        .HasDatabaseName("ix_provider_gallery_items_display_order");

                    b.HasIndex("ServiceProviderId")
                        .HasDatabaseName("ix_provider_gallery_items_service_provider_id");

                    b.ToTable("provider_gallery_items", "category");
                });

            modelBuilder.Entity("LSevin.Modules.Category.ServiceProvider.Entities.ProviderPolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified_date");

                    b.Property<Guid>("ServiceProviderId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_provider_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_provider_policies");

                    b.HasIndex("Type")
                        .HasDatabaseName("ix_provider_policies_type");

                    b.HasIndex("ServiceProviderId", "Type")
                        .IsUnique()
                        .HasDatabaseName("ix_provider_policies_service_provider_id_type");

                    b.ToTable("provider_policies", "category");
                });

            modelBuilder.Entity("LSevin.Modules.Category.ServiceProvider.Entities.ProviderService", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified_date");

                    b.Property<Guid>("ServiceDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_definition_id");

                    b.Property<Guid>("ServiceProviderId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_provider_id");

                    b.ComplexProperty<Dictionary<string, object>>("Price", "LSevin.Modules.Category.ServiceProvider.Entities.ProviderService.Price#MoneyValue", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(15)
                                .HasColumnType("character varying(15)")
                                .HasColumnName("currency");

                            b1.Property<decimal>("Value")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("value");
                        });

                    b.HasKey("Id")
                        .HasName("pk_provider_services");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_provider_services_is_active");

                    b.HasIndex("ServiceDefinitionId")
                        .HasDatabaseName("ix_provider_services_service_definition_id");

                    b.HasIndex("ServiceProviderId", "ServiceDefinitionId")
                        .IsUnique()
                        .HasDatabaseName("ix_provider_services_service_provider_id_service_definition_id");

                    b.ToTable("provider_services", "category");
                });

            modelBuilder.Entity("LSevin.Modules.Category.ServiceProvider.Entities.ProviderStaff", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified_date");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("notes");

                    b.Property<Guid>("ServiceProviderId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_provider_id");

                    b.Property<Guid>("StaffId")
                        .HasColumnType("uuid")
                        .HasColumnName("staff_id");

                    b.HasKey("Id")
                        .HasName("pk_provider_staffs");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_provider_staffs_is_active");

                    b.HasIndex("StaffId")
                        .HasDatabaseName("ix_provider_staffs_staff_id");

                    b.HasIndex("ServiceProviderId", "StaffId")
                        .IsUnique()
                        .HasDatabaseName("ix_provider_staffs_service_provider_id_staff_id");

                    b.ToTable("provider_staffs", "category");
                });

            modelBuilder.Entity("LSevin.Modules.Category.ServiceProvider.Entities.ServiceAttributeValue", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AttributeDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("attribute_definition_id");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_date");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified_date");

                    b.Property<Guid>("ProviderServiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("provider_service_id");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_service_attribute_values");

                    b.HasIndex("AttributeDefinitionId")
                        .HasDatabaseName("ix_service_attribute_values_attribute_definition_id");

                    b.HasIndex("ProviderServiceId", "AttributeDefinitionId")
                        .IsUnique()
                        .HasDatabaseName("ix_service_attribute_values_provider_service_id_attribute_defi");

                    b.ToTable("service_attribute_values", "category");
                });

            modelBuilder.Entity("LSevin.Modules.Category.ServiceProvider.Entities.ServiceProvider", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_date")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified_date")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("ProviderTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("provider_type_id");

                    b.ComplexProperty<Dictionary<string, object>>("Address", "LSevin.Modules.Category.ServiceProvider.Entities.ServiceProvider.Address#Address", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(15)
                                .HasColumnType("character varying(15)")
                                .HasColumnName("city");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(15)
                                .HasColumnType("character varying(15)")
                                .HasColumnName("country");

                            b1.Property<string>("Detail")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("detail");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("street");

                            b1.Property<string>("ZipCode")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("zip_code");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("ContactEmail", "LSevin.Modules.Category.ServiceProvider.Entities.ServiceProvider.ContactEmail#Email", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(250)
                                .HasColumnType("character varying(250)")
                                .HasColumnName("email");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("ContactPhone", "LSevin.Modules.Category.ServiceProvider.Entities.ServiceProvider.ContactPhone#PhoneNumber", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("CountryCode")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("phone_number_country_code");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(15)
                                .HasColumnType("character varying(15)")
                                .HasColumnName("phone_number");
                        });

                    b.HasKey("Id")
                        .HasName("pk_service_providers");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_service_providers_is_active");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_service_providers_name");

                    b.HasIndex("ProviderTypeId")
                        .HasDatabaseName("ix_service_providers_provider_type_id");

                    b.ToTable("service_providers", "category");
                });

            modelBuilder.Entity("LSevin.Modules.Category.SharedKernel.Enumerations.AttributeType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_attribute_types");

                    b.ToTable("attribute_types", "category");
                });

            modelBuilder.Entity("LSevin.Modules.Category.Staff.Entities.Staff", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Biography")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("biography");

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_date")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified_date")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("ProfileImageUrl")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("profile_image_url");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_staff");

                    b.ToTable("staff", "category");
                });

            modelBuilder.Entity("LSevin.Modules.Category.Staff.Entities.StaffAvailability", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_date");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer")
                        .HasColumnName("day_of_week");

                    b.Property<bool>("IsRecurring")
                        .HasColumnType("boolean")
                        .HasColumnName("is_recurring");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified_date");

                    b.Property<DateTime?>("SpecificDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("specific_date");

                    b.Property<Guid>("StaffId")
                        .HasColumnType("uuid")
                        .HasColumnName("staff_id");

                    b.Property<int>("_availabilityStatusId")
                        .HasColumnType("integer")
                        .HasColumnName("_availability_status_id");

                    b.ComplexProperty<Dictionary<string, object>>("TimeRange", "LSevin.Modules.Category.Staff.Entities.StaffAvailability.TimeRange#TimeRange", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<TimeSpan>("EndTime")
                                .HasColumnType("interval")
                                .HasColumnName("end_time");

                            b1.Property<TimeSpan>("StartTime")
                                .HasColumnType("interval")
                                .HasColumnName("start_time");
                        });

                    b.HasKey("Id")
                        .HasName("pk_staff_availabilities");

                    b.HasIndex("StaffId")
                        .HasDatabaseName("ix_staff_availabilities_staff_id");

                    b.HasIndex("_availabilityStatusId")
                        .HasDatabaseName("ix_staff_availabilities__availability_status_id");

                    b.HasIndex("StaffId", "DayOfWeek")
                        .HasDatabaseName("ix_staff_availabilities_staff_id_day_of_week");

                    b.ToTable("staff_availabilities", "category");
                });

            modelBuilder.Entity("LSevin.Modules.Category.Staff.Entities.StaffService", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified_date");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("notes");

                    b.Property<Guid>("ServiceDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_definition_id");

                    b.Property<Guid>("StaffId")
                        .HasColumnType("uuid")
                        .HasColumnName("staff_id");

                    b.HasKey("Id")
                        .HasName("pk_staff_services");

                    b.HasIndex("StaffId")
                        .HasDatabaseName("ix_staff_services_staff_id");

                    b.HasIndex("StaffId", "ServiceDefinitionId")
                        .IsUnique()
                        .HasDatabaseName("ix_staff_services_staff_id_service_definition_id");

                    b.ToTable("staff_services", "category");
                });

            modelBuilder.Entity("LSevin.Modules.Category.Staff.Enumerations.StaffAvailabilityStatus", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_staff_availability_statuses");

                    b.ToTable("staff_availability_statuses", "category");
                });

            modelBuilder.Entity("LSevin.Modules.Category.Category.Entities.Category", b =>
                {
                    b.HasOne("LSevin.Modules.Category.Category.Entities.Category", null)
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("fk_categories_categories_parent_id");
                });

            modelBuilder.Entity("LSevin.Modules.Category.ProviderType.Entities.ProviderAttributeDefinition", b =>
                {
                    b.HasOne("LSevin.Modules.Category.ProviderType.Entities.ProviderType", null)
                        .WithMany("AttributeDefinitions")
                        .HasForeignKey("ProviderTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_provider_attribute_definitions_provider_types_provider_type");

                    b.HasOne("LSevin.Modules.Category.SharedKernel.Enumerations.AttributeType", "AttributeType")
                        .WithMany()
                        .HasForeignKey("_attributeTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_provider_attribute_definitions_attribute_types__attribute_t");

                    b.OwnsMany("LSevin.Modules.Category.ProviderType.ValueObjects.AttributeOption", "Options", b1 =>
                        {
                            b1.Property<Guid>("ProviderAttributeDefinitionId")
                                .HasColumnType("uuid")
                                .HasColumnName("provider_attribute_definition_id");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("DisplayName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("display_name");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("value");

                            b1.HasKey("ProviderAttributeDefinitionId", "Id")
                                .HasName("pk_provider_attribute_definition_domain_options");

                            b1.ToTable("provider_attribute_definition_domain_options", "category");

                            b1.WithOwner()
                                .HasForeignKey("ProviderAttributeDefinitionId")
                                .HasConstraintName("fk_provider_attribute_definition_domain_options_provider_attri");
                        });

                    b.Navigation("AttributeType");

                    b.Navigation("Options");
                });

            modelBuilder.Entity("LSevin.Modules.Category.ServiceDefinition.Entities.ServiceAttributeDefinition", b =>
                {
                    b.HasOne("LSevin.Modules.Category.ServiceDefinition.Entities.ServiceDefinition", null)
                        .WithMany("AttributeDefinitions")
                        .HasForeignKey("ServiceDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_service_attribute_definitions_service_definitions_service_d");

                    b.HasOne("LSevin.Modules.Category.SharedKernel.Enumerations.AttributeType", "AttributeType")
                        .WithMany()
                        .HasForeignKey("_attributeTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_service_attribute_definitions_attribute_types__attribute_ty");

                    b.OwnsMany("LSevin.Modules.Category.ServiceDefinition.ValueObjects.AttributeOption", "Options", b1 =>
                        {
                            b1.Property<Guid>("ServiceAttributeDefinitionId")
                                .HasColumnType("uuid")
                                .HasColumnName("service_attribute_definition_id");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<decimal?>("AdditionalPrice")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("additional_price");

                            b1.Property<string>("DisplayName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("display_name");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("value");

                            b1.HasKey("ServiceAttributeDefinitionId", "Id")
                                .HasName("pk_service_attribute_definition_options");

                            b1.ToTable("service_attribute_definition_options", "category");

                            b1.WithOwner()
                                .HasForeignKey("ServiceAttributeDefinitionId")
                                .HasConstraintName("fk_service_attribute_definition_options_service_attribute_defi");
                        });

                    b.Navigation("AttributeType");

                    b.Navigation("Options");
                });

            modelBuilder.Entity("LSevin.Modules.Category.ServiceDefinition.Entities.ServiceDefinition", b =>
                {
                    b.HasOne("LSevin.Modules.Category.Category.Entities.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_service_definitions_categories_category_id");

                    b.OwnsMany("LSevin.Modules.Category.ServiceDefinition.ValueObjects.ServiceRequirement", "Requirements", b1 =>
                        {
                            b1.Property<Guid>("ServiceDefinitionId")
                                .HasColumnType("uuid")
                                .HasColumnName("service_definition_id");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)")
                                .HasColumnName("description");

                            b1.Property<bool>("IsMandatory")
                                .HasColumnType("boolean")
                                .HasColumnName("is_mandatory");

                            b1.HasKey("ServiceDefinitionId", "Id")
                                .HasName("pk_service_definition_domain_requirements");

                            b1.ToTable("service_definition_domain_requirements", "category");

                            b1.WithOwner()
                                .HasForeignKey("ServiceDefinitionId")
                                .HasConstraintName("fk_service_definition_domain_requirements_service_definitions_");
                        });

                    b.Navigation("Requirements");
                });

            modelBuilder.Entity("LSevin.Modules.Category.ServiceProvider.Entities.ProviderAttribute", b =>
                {
                    b.HasOne("LSevin.Modules.Category.ServiceProvider.Entities.ServiceProvider", null)
                        .WithMany("Attributes")
                        .HasForeignKey("ServiceProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_provider_attributes_service_providers_service_provider_id");
                });

            modelBuilder.Entity("LSevin.Modules.Category.ServiceProvider.Entities.ProviderGalleryItem", b =>
                {
                    b.HasOne("LSevin.Modules.Category.ServiceProvider.Entities.ServiceProvider", null)
                        .WithMany("GalleryItems")
                        .HasForeignKey("ServiceProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_provider_gallery_items_service_providers_service_provider_id");
                });

            modelBuilder.Entity("LSevin.Modules.Category.ServiceProvider.Entities.ProviderPolicy", b =>
                {
                    b.HasOne("LSevin.Modules.Category.ServiceProvider.Entities.ServiceProvider", null)
                        .WithMany("Policies")
                        .HasForeignKey("ServiceProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_provider_policies_service_providers_service_provider_id");
                });

            modelBuilder.Entity("LSevin.Modules.Category.ServiceProvider.Entities.ProviderService", b =>
                {
                    b.HasOne("LSevin.Modules.Category.ServiceDefinition.Entities.ServiceDefinition", null)
                        .WithMany()
                        .HasForeignKey("ServiceDefinitionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_provider_services_service_definitions_service_definition_id");

                    b.HasOne("LSevin.Modules.Category.ServiceProvider.Entities.ServiceProvider", null)
                        .WithMany("Services")
                        .HasForeignKey("ServiceProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_provider_services_service_providers_service_provider_id");
                });

            modelBuilder.Entity("LSevin.Modules.Category.ServiceProvider.Entities.ProviderStaff", b =>
                {
                    b.HasOne("LSevin.Modules.Category.ServiceProvider.Entities.ServiceProvider", null)
                        .WithMany("StaffMembers")
                        .HasForeignKey("ServiceProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_provider_staffs_service_providers_service_provider_id");

                    b.HasOne("LSevin.Modules.Category.Staff.Entities.Staff", null)
                        .WithMany()
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_provider_staffs_staffs_staff_id");
                });

            modelBuilder.Entity("LSevin.Modules.Category.ServiceProvider.Entities.ServiceAttributeValue", b =>
                {
                    b.HasOne("LSevin.Modules.Category.ServiceProvider.Entities.ProviderService", null)
                        .WithMany("AttributeValues")
                        .HasForeignKey("ProviderServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_service_attribute_values_provider_services_provider_service");
                });

            modelBuilder.Entity("LSevin.Modules.Category.ServiceProvider.Entities.ServiceProvider", b =>
                {
                    b.HasOne("LSevin.Modules.Category.ProviderType.Entities.ProviderType", null)
                        .WithMany()
                        .HasForeignKey("ProviderTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_service_providers_provider_types_provider_type_id");
                });

            modelBuilder.Entity("LSevin.Modules.Category.Staff.Entities.StaffAvailability", b =>
                {
                    b.HasOne("LSevin.Modules.Category.Staff.Entities.Staff", null)
                        .WithMany("Availabilities")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_staff_availabilities_staffs_staff_id");

                    b.HasOne("LSevin.Modules.Category.Staff.Enumerations.StaffAvailabilityStatus", "Status")
                        .WithMany()
                        .HasForeignKey("_availabilityStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_staff_availabilities_staff_availability_statuses__availabil");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("LSevin.Modules.Category.Staff.Entities.StaffService", b =>
                {
                    b.HasOne("LSevin.Modules.Category.Staff.Entities.Staff", null)
                        .WithMany("Services")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_staff_services_staffs_staff_id");
                });

            modelBuilder.Entity("LSevin.Modules.Category.Category.Entities.Category", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("LSevin.Modules.Category.ProviderType.Entities.ProviderType", b =>
                {
                    b.Navigation("AttributeDefinitions");
                });

            modelBuilder.Entity("LSevin.Modules.Category.ServiceDefinition.Entities.ServiceDefinition", b =>
                {
                    b.Navigation("AttributeDefinitions");
                });

            modelBuilder.Entity("LSevin.Modules.Category.ServiceProvider.Entities.ProviderService", b =>
                {
                    b.Navigation("AttributeValues");
                });

            modelBuilder.Entity("LSevin.Modules.Category.ServiceProvider.Entities.ServiceProvider", b =>
                {
                    b.Navigation("Attributes");

                    b.Navigation("GalleryItems");

                    b.Navigation("Policies");

                    b.Navigation("Services");

                    b.Navigation("StaffMembers");
                });

            modelBuilder.Entity("LSevin.Modules.Category.Staff.Entities.Staff", b =>
                {
                    b.Navigation("Availabilities");

                    b.Navigation("Services");
                });
#pragma warning restore 612, 618
        }
    }
}
