import type { PortalLocale } from "@core/i18n/config";
import { normalizePortalLocale } from "@core/i18n/config";
import { mediaPickerCopy } from "@core/ui/mediaPickerCopy";

export type ServicesCopy = {
  provider: {
    title: string; description: string; newService: string; noServices: string; addService: string;
    newTitle: string; newDescription: string; editTitle: string; formNew: string; formEdit: string;
    definition: string; currency: string; displayName: string; serviceDescription: string; price: string;
    duration: string; slotInterval: string; image: string; active: string; inactive: string; popular: string;
    save: string; selectService: string; searchService: string; noServiceResults: string; loading: string;
    loadFailed: string; service: string; status: string; edit: string; remove: string; untitled: string;
  };
  admin: {
    title: string; description: string; adminCenter: string; services: string; active: string; inactive: string;
    popular: string; inactiveProvider: string; searchPlaceholder: string; allStatuses: string; allProviders: string;
    searchProviders: string; filter: string; service: string; provider: string; commercial: string; scheduling: string;
    reputation: string; updated: string; controls: string; providerInactive: string; edit: string; deactivate: string;
    activate: string; unfeature: string; feature: string; noMatches: string; noMatchesDescription: string;
    recentAdministration: string; noActions: string; reason: string; loading: string; loadFailed: string;
    noProviderResults: string; durationMinutes: (value: string | number) => string; slotMinutes: (value: string | number) => string;
    reviews: (value: string | number) => string; actionLabels: Record<string, string>;
  };
};

const en: ServicesCopy = {
  provider: {
    title:"Services",description:"Provider-specific prices, names, durations and booking settings.",newService:"New service",noServices:"No services yet",addService:"Add service",newTitle:"New service",newDescription:"Attach a global LSevin service definition to this provider.",editTitle:"Edit service",formNew:"New service",formEdit:"Edit service",definition:"Global service definition",currency:"Currency",displayName:"Service display name",serviceDescription:"Service description",price:"Price",duration:"Duration (minutes)",slotInterval:"Slot interval (minutes)",image:"Service image",active:"Active",inactive:"Inactive",popular:"Popular",save:"Save service",selectService:"Select service",searchService:"Search services",noServiceResults:"No matching services.",loading:"Loading…",loadFailed:"Could not load services.",service:"Service",status:"Status",edit:"Edit",remove:"Remove",untitled:"Untitled service"
  },
  admin: {
    title:"Provider service catalog",description:"Moderate every provider service without changing provider ownership or the stable LSevin service-definition contract.",adminCenter:"Admin control center",services:"Services",active:"Active",inactive:"Inactive",popular:"Popular",inactiveProvider:"On inactive provider",searchPlaceholder:"Service, definition or provider",allStatuses:"All statuses",allProviders:"All providers",searchProviders:"Search providers",filter:"Filter",service:"Service",provider:"Provider",commercial:"Commercial",scheduling:"Scheduling",reputation:"Reputation",updated:"Updated",controls:"Controls",providerInactive:"Provider inactive",edit:"Edit",deactivate:"Deactivate",activate:"Activate",unfeature:"Unfeature",feature:"Feature",noMatches:"No matching services",noMatchesDescription:"Change the filters or ask a provider to add a service.",recentAdministration:"Recent service administration",noActions:"No service administration actions recorded yet.",reason:"Reason",loading:"Loading…",loadFailed:"Could not load providers.",noProviderResults:"No matching providers.",durationMinutes:(v)=>`${v} minutes`,slotMinutes:(v)=>`${v} minute slots`,reviews:(v)=>`${v} reviews`,actionLabels:{set_is_active:"Service status changed",set_is_popular:"Featured status changed"}
  }
};

const fa: ServicesCopy = {
  provider: {
    title:"خدمات",description:"قیمت، نام، مدت‌زمان و تنظیمات رزرو اختصاصی ارائه‌دهنده.",newService:"خدمت جدید",noServices:"هنوز خدمتی ثبت نشده است",addService:"افزودن خدمت",newTitle:"خدمت جدید",newDescription:"یک تعریف خدمت سراسری السوین را به این ارائه‌دهنده متصل کنید.",editTitle:"ویرایش خدمت",formNew:"خدمت جدید",formEdit:"ویرایش خدمت",definition:"تعریف اصلی خدمت",currency:"ارز",displayName:"نام نمایشی خدمت",serviceDescription:"توضیحات خدمت",price:"قیمت",duration:"مدت‌زمان (دقیقه)",slotInterval:"فاصله نوبت‌ها (دقیقه)",image:"تصویر خدمت",active:"فعال",inactive:"غیرفعال",popular:"محبوب",save:"ذخیره خدمت",selectService:"انتخاب خدمت",searchService:"جستجوی خدمت",noServiceResults:"خدمتی مطابق جستجو پیدا نشد.",loading:"در حال بارگذاری…",loadFailed:"دریافت خدمات ناموفق بود.",service:"خدمت",status:"وضعیت",edit:"ویرایش",remove:"حذف",untitled:"خدمت بدون عنوان"
  },
  admin: {
    title:"مدیریت کاتالوگ خدمات ارائه‌دهندگان",description:"خدمات هر ارائه‌دهنده را بدون تغییر مالکیت یا قرارداد پایدار تعریف خدمت السوین بررسی و مدیریت کنید.",adminCenter:"مرکز کنترل مدیریت",services:"خدمات",active:"فعال",inactive:"غیرفعال",popular:"محبوب",inactiveProvider:"روی ارائه‌دهنده غیرفعال",searchPlaceholder:"خدمت، تعریف یا ارائه‌دهنده",allStatuses:"همه وضعیت‌ها",allProviders:"همه ارائه‌دهندگان",searchProviders:"جستجوی ارائه‌دهنده",filter:"فیلتر",service:"خدمت",provider:"ارائه‌دهنده",commercial:"مالی",scheduling:"زمان‌بندی",reputation:"اعتبار",updated:"به‌روزرسانی",controls:"کنترل‌ها",providerInactive:"ارائه‌دهنده غیرفعال",edit:"ویرایش",deactivate:"غیرفعال‌سازی",activate:"فعال‌سازی",unfeature:"حذف از محبوب‌ها",feature:"محبوب‌کردن",noMatches:"خدمت مطابقی پیدا نشد",noMatchesDescription:"فیلترها را تغییر دهید یا از ارائه‌دهنده بخواهید خدمتی اضافه کند.",recentAdministration:"آخرین اقدامات مدیریت خدمات",noActions:"هنوز اقدام مدیریتی برای خدمات ثبت نشده است.",reason:"دلیل",loading:"در حال بارگذاری…",loadFailed:"دریافت ارائه‌دهندگان ناموفق بود.",noProviderResults:"ارائه‌دهنده‌ای پیدا نشد.",durationMinutes:(v)=>`${v} دقیقه`,slotMinutes:(v)=>`بازه‌های ${v} دقیقه‌ای`,reviews:(v)=>`${v} نظر`,actionLabels:{set_is_active:"وضعیت خدمت تغییر کرد",set_is_popular:"وضعیت محبوب‌بودن تغییر کرد"}
  }
};

const ar: ServicesCopy = {
  provider: {
    title:"الخدمات",description:"الأسعار والأسماء والمدد وإعدادات الحجز الخاصة بمزوّد الخدمة.",newService:"خدمة جديدة",noServices:"لا توجد خدمات بعد",addService:"إضافة خدمة",newTitle:"خدمة جديدة",newDescription:"اربط تعريف خدمة عام في LSevin بهذا المزوّد.",editTitle:"تعديل الخدمة",formNew:"خدمة جديدة",formEdit:"تعديل الخدمة",definition:"تعريف الخدمة العام",currency:"العملة",displayName:"الاسم الظاهر للخدمة",serviceDescription:"وصف الخدمة",price:"السعر",duration:"المدة بالدقائق",slotInterval:"فاصل المواعيد بالدقائق",image:"صورة الخدمة",active:"نشطة",inactive:"غير نشطة",popular:"مميزة",save:"حفظ الخدمة",selectService:"اختر خدمة",searchService:"ابحث عن خدمة",noServiceResults:"لا توجد خدمات مطابقة.",loading:"جارٍ التحميل…",loadFailed:"تعذر تحميل الخدمات.",service:"الخدمة",status:"الحالة",edit:"تعديل",remove:"حذف",untitled:"خدمة بلا عنوان"
  },
  admin: {
    title:"كتالوج خدمات المزوّدين",description:"راجع كل خدمة دون تغيير ملكية المزوّد أو عقد تعريف الخدمة الثابت في LSevin.",adminCenter:"مركز التحكم الإداري",services:"الخدمات",active:"نشطة",inactive:"غير نشطة",popular:"مميزة",inactiveProvider:"على مزوّد غير نشط",searchPlaceholder:"الخدمة أو التعريف أو المزوّد",allStatuses:"كل الحالات",allProviders:"كل المزوّدين",searchProviders:"ابحث عن مزوّد",filter:"تصفية",service:"الخدمة",provider:"المزوّد",commercial:"التجاري",scheduling:"الجدولة",reputation:"السمعة",updated:"آخر تحديث",controls:"التحكم",providerInactive:"المزوّد غير نشط",edit:"تعديل",deactivate:"تعطيل",activate:"تفعيل",unfeature:"إلغاء التمييز",feature:"تمييز",noMatches:"لا توجد خدمات مطابقة",noMatchesDescription:"غيّر عوامل التصفية أو اطلب من المزوّد إضافة خدمة.",recentAdministration:"أحدث إدارة للخدمات",noActions:"لم تُسجل إجراءات إدارة خدمات بعد.",reason:"السبب",loading:"جارٍ التحميل…",loadFailed:"تعذر تحميل المزوّدين.",noProviderResults:"لا يوجد مزوّد مطابق.",durationMinutes:(v)=>`${v} دقيقة`,slotMinutes:(v)=>`فترات ${v} دقيقة`,reviews:(v)=>`${v} مراجعات`,actionLabels:{set_is_active:"تغيرت حالة الخدمة",set_is_popular:"تغيرت حالة التمييز"}
  }
};

const tr: ServicesCopy = {
  provider: {
    title:"Hizmetler",description:"Sağlayıcıya özel fiyatlar, adlar, süreler ve rezervasyon ayarları.",newService:"Yeni hizmet",noServices:"Henüz hizmet yok",addService:"Hizmet ekle",newTitle:"Yeni hizmet",newDescription:"Genel bir LSevin hizmet tanımını bu sağlayıcıya bağlayın.",editTitle:"Hizmeti düzenle",formNew:"Yeni hizmet",formEdit:"Hizmeti düzenle",definition:"Genel hizmet tanımı",currency:"Para birimi",displayName:"Hizmet görünen adı",serviceDescription:"Hizmet açıklaması",price:"Fiyat",duration:"Süre (dakika)",slotInterval:"Randevu aralığı (dakika)",image:"Hizmet görseli",active:"Aktif",inactive:"Pasif",popular:"Öne çıkan",save:"Hizmeti kaydet",selectService:"Hizmet seç",searchService:"Hizmet ara",noServiceResults:"Eşleşen hizmet yok.",loading:"Yükleniyor…",loadFailed:"Hizmetler yüklenemedi.",service:"Hizmet",status:"Durum",edit:"Düzenle",remove:"Sil",untitled:"Adsız hizmet"
  },
  admin: {
    title:"Sağlayıcı hizmet kataloğu",description:"Sağlayıcı sahipliğini veya kararlı LSevin hizmet tanımı sözleşmesini değiştirmeden tüm hizmetleri yönetin.",adminCenter:"Yönetici kontrol merkezi",services:"Hizmetler",active:"Aktif",inactive:"Pasif",popular:"Öne çıkan",inactiveProvider:"Pasif sağlayıcıda",searchPlaceholder:"Hizmet, tanım veya sağlayıcı",allStatuses:"Tüm durumlar",allProviders:"Tüm sağlayıcılar",searchProviders:"Sağlayıcı ara",filter:"Filtrele",service:"Hizmet",provider:"Sağlayıcı",commercial:"Ticari",scheduling:"Planlama",reputation:"İtibar",updated:"Güncellendi",controls:"Kontroller",providerInactive:"Sağlayıcı pasif",edit:"Düzenle",deactivate:"Pasifleştir",activate:"Etkinleştir",unfeature:"Öne çıkarmayı kaldır",feature:"Öne çıkar",noMatches:"Eşleşen hizmet yok",noMatchesDescription:"Filtreleri değiştirin veya sağlayıcıdan hizmet eklemesini isteyin.",recentAdministration:"Son hizmet yönetimi",noActions:"Henüz hizmet yönetimi işlemi kaydedilmedi.",reason:"Gerekçe",loading:"Yükleniyor…",loadFailed:"Sağlayıcılar yüklenemedi.",noProviderResults:"Eşleşen sağlayıcı yok.",durationMinutes:(v)=>`${v} dakika`,slotMinutes:(v)=>`${v} dakikalık aralıklar`,reviews:(v)=>`${v} değerlendirme`,actionLabels:{set_is_active:"Hizmet durumu değişti",set_is_popular:"Öne çıkarma durumu değişti"}
  }
};

const es: ServicesCopy = {
  provider: {
    title:"Servicios",description:"Precios, nombres, duraciones y ajustes de reserva específicos del proveedor.",newService:"Nuevo servicio",noServices:"Aún no hay servicios",addService:"Añadir servicio",newTitle:"Nuevo servicio",newDescription:"Vincule una definición global de servicio de LSevin a este proveedor.",editTitle:"Editar servicio",formNew:"Nuevo servicio",formEdit:"Editar servicio",definition:"Definición global del servicio",currency:"Moneda",displayName:"Nombre visible del servicio",serviceDescription:"Descripción del servicio",price:"Precio",duration:"Duración (minutos)",slotInterval:"Intervalo de citas (minutos)",image:"Imagen del servicio",active:"Activo",inactive:"Inactivo",popular:"Destacado",save:"Guardar servicio",selectService:"Seleccionar servicio",searchService:"Buscar servicio",noServiceResults:"No hay servicios coincidentes.",loading:"Cargando…",loadFailed:"No se pudieron cargar los servicios.",service:"Servicio",status:"Estado",edit:"Editar",remove:"Eliminar",untitled:"Servicio sin título"
  },
  admin: {
    title:"Catálogo de servicios de proveedores",description:"Modere cada servicio sin cambiar la propiedad del proveedor ni el contrato estable de definición de servicios de LSevin.",adminCenter:"Centro de control administrativo",services:"Servicios",active:"Activos",inactive:"Inactivos",popular:"Destacados",inactiveProvider:"En proveedor inactivo",searchPlaceholder:"Servicio, definición o proveedor",allStatuses:"Todos los estados",allProviders:"Todos los proveedores",searchProviders:"Buscar proveedores",filter:"Filtrar",service:"Servicio",provider:"Proveedor",commercial:"Comercial",scheduling:"Programación",reputation:"Reputación",updated:"Actualizado",controls:"Controles",providerInactive:"Proveedor inactivo",edit:"Editar",deactivate:"Desactivar",activate:"Activar",unfeature:"Quitar destacado",feature:"Destacar",noMatches:"No hay servicios coincidentes",noMatchesDescription:"Cambie los filtros o pida al proveedor que añada un servicio.",recentAdministration:"Administración reciente de servicios",noActions:"Aún no se registraron acciones de administración.",reason:"Motivo",loading:"Cargando…",loadFailed:"No se pudieron cargar los proveedores.",noProviderResults:"No hay proveedores coincidentes.",durationMinutes:(v)=>`${v} minutos`,slotMinutes:(v)=>`intervalos de ${v} minutos`,reviews:(v)=>`${v} reseñas`,actionLabels:{set_is_active:"Cambió el estado del servicio",set_is_popular:"Cambió el estado destacado"}
  }
};

const ku: ServicesCopy = {
  provider: {
    title:"خزمەتگوزارییەکان",description:"نرخ، ناو، ماوە و ڕێکخستنەکانی حجز بۆ پێشکەشکەر.",newService:"خزمەتگوزاری نوێ",noServices:"هێشتا خزمەتگوزاری نییە",addService:"زیادکردنی خزمەتگوزاری",newTitle:"خزمەتگوزاری نوێ",newDescription:"پێناسەی گشتی خزمەتگوزاری LSevin بە پێشکەشکەرەکەوە ببەستە.",editTitle:"دەستکاری خزمەتگوزاری",formNew:"خزمەتگوزاری نوێ",formEdit:"دەستکاری خزمەتگوزاری",definition:"پێناسەی گشتی خزمەتگوزاری",currency:"دراو",displayName:"ناوی پیشاندراوی خزمەتگوزاری",serviceDescription:"وەسفی خزمەتگوزاری",price:"نرخ",duration:"ماوە (خولەک)",slotInterval:"ماوەی نێوان کاتەکان (خولەک)",image:"وێنەی خزمەتگوزاری",active:"چالاک",inactive:"ناچالاک",popular:"دیار",save:"پاشەکەوتکردن",selectService:"خزمەتگوزاری هەڵبژێرە",searchService:"گەڕان لە خزمەتگوزاری",noServiceResults:"هیچ خزمەتگوزارییەک نەدۆزرایەوە.",loading:"بارکردن…",loadFailed:"خزمەتگوزارییەکان بارنەکران.",service:"خزمەتگوزاری",status:"دۆخ",edit:"دەستکاری",remove:"لابردن",untitled:"خزمەتگوزاری بێ ناونیشان"
  },
  admin: {
    title:"کاتەلۆگی خزمەتگوزاری پێشکەشکەران",description:"هەموو خزمەتگوزارییەکان بەبێ گۆڕینی خاوەنداری یان پەیمانی جێگیری پێناسەی LSevin بەڕێوەببە.",adminCenter:"ناوەندی کۆنترۆڵی بەڕێوەبردن",services:"خزمەتگوزارییەکان",active:"چالاک",inactive:"ناچالاک",popular:"دیار",inactiveProvider:"لە پێشکەشکەری ناچالاک",searchPlaceholder:"خزمەتگوزاری، پێناسە یان پێشکەشکەر",allStatuses:"هەموو دۆخەکان",allProviders:"هەموو پێشکەشکەران",searchProviders:"گەڕان لە پێشکەشکەر",filter:"فلتەر",service:"خزمەتگوزاری",provider:"پێشکەشکەر",commercial:"بازرگانی",scheduling:"خشتە",reputation:"ناوبانگ",updated:"نوێکراوەتەوە",controls:"کۆنترۆڵ",providerInactive:"پێشکەشکەر ناچالاکە",edit:"دەستکاری",deactivate:"ناچالاککردن",activate:"چالاککردن",unfeature:"لابردن لە دیارکراو",feature:"دیارکردن",noMatches:"هیچ خزمەتگوزارییەک نەدۆزرایەوە",noMatchesDescription:"فلتەرەکان بگۆڕە یان داوا لە پێشکەشکەر بکە خزمەتگوزاری زیاد بکات.",recentAdministration:"دوایین بەڕێوەبردنی خزمەتگوزاری",noActions:"هێشتا کردارێکی بەڕێوەبردن تۆمار نەکراوە.",reason:"هۆکار",loading:"بارکردن…",loadFailed:"پێشکەشکەران بارنەکران.",noProviderResults:"پێشکەشکەر نەدۆزرایەوە.",durationMinutes:(v)=>`${v} خولەک`,slotMinutes:(v)=>`کاتەکانی ${v} خولەکی`,reviews:(v)=>`${v} هەڵسەنگاندن`,actionLabels:{set_is_active:"دۆخی خزمەتگوزاری گۆڕا",set_is_popular:"دۆخی دیارکراو گۆڕا"}
  }
};

const de: ServicesCopy = {
  provider: {
    title:"Leistungen",description:"Anbieterspezifische Preise, Namen, Dauer und Buchungseinstellungen.",newService:"Neue Leistung",noServices:"Noch keine Leistungen",addService:"Leistung hinzufügen",newTitle:"Neue Leistung",newDescription:"Verknüpfen Sie eine globale LSevin-Leistungsdefinition mit diesem Anbieter.",editTitle:"Leistung bearbeiten",formNew:"Neue Leistung",formEdit:"Leistung bearbeiten",definition:"Globale Leistungsdefinition",currency:"Währung",displayName:"Anzeigename der Leistung",serviceDescription:"Leistungsbeschreibung",price:"Preis",duration:"Dauer (Minuten)",slotInterval:"Terminintervall (Minuten)",image:"Leistungsbild",active:"Aktiv",inactive:"Inaktiv",popular:"Hervorgehoben",save:"Leistung speichern",selectService:"Leistung auswählen",searchService:"Leistungen suchen",noServiceResults:"Keine passenden Leistungen.",loading:"Wird geladen…",loadFailed:"Leistungen konnten nicht geladen werden.",service:"Leistung",status:"Status",edit:"Bearbeiten",remove:"Entfernen",untitled:"Unbenannte Leistung"
  },
  admin: {
    title:"Anbieter-Leistungskatalog",description:"Verwalten Sie jede Anbieterleistung, ohne die Anbietereigentümerschaft oder den stabilen LSevin-Definitionsvertrag zu ändern.",adminCenter:"Admin-Kontrollzentrum",services:"Leistungen",active:"Aktiv",inactive:"Inaktiv",popular:"Hervorgehoben",inactiveProvider:"Bei inaktivem Anbieter",searchPlaceholder:"Leistung, Definition oder Anbieter",allStatuses:"Alle Status",allProviders:"Alle Anbieter",searchProviders:"Anbieter suchen",filter:"Filtern",service:"Leistung",provider:"Anbieter",commercial:"Kommerziell",scheduling:"Planung",reputation:"Reputation",updated:"Aktualisiert",controls:"Steuerung",providerInactive:"Anbieter inaktiv",edit:"Bearbeiten",deactivate:"Deaktivieren",activate:"Aktivieren",unfeature:"Hervorhebung entfernen",feature:"Hervorheben",noMatches:"Keine passenden Leistungen",noMatchesDescription:"Ändern Sie die Filter oder bitten Sie den Anbieter, eine Leistung hinzuzufügen.",recentAdministration:"Letzte Leistungsadministration",noActions:"Noch keine Administrationsaktionen erfasst.",reason:"Begründung",loading:"Wird geladen…",loadFailed:"Anbieter konnten nicht geladen werden.",noProviderResults:"Keine passenden Anbieter.",durationMinutes:(v)=>`${v} Minuten`,slotMinutes:(v)=>`${v}-Minuten-Intervalle`,reviews:(v)=>`${v} Bewertungen`,actionLabels:{set_is_active:"Leistungsstatus geändert",set_is_popular:"Hervorhebungsstatus geändert"}
  }
};

const fr: ServicesCopy = {
  provider: {
    title:"Services",description:"Prix, noms, durées et paramètres de réservation propres au prestataire.",newService:"Nouveau service",noServices:"Aucun service pour le moment",addService:"Ajouter un service",newTitle:"Nouveau service",newDescription:"Associez une définition globale de service LSevin à ce prestataire.",editTitle:"Modifier le service",formNew:"Nouveau service",formEdit:"Modifier le service",definition:"Définition globale du service",currency:"Devise",displayName:"Nom affiché du service",serviceDescription:"Description du service",price:"Prix",duration:"Durée (minutes)",slotInterval:"Intervalle des créneaux (minutes)",image:"Image du service",active:"Actif",inactive:"Inactif",popular:"Mis en avant",save:"Enregistrer le service",selectService:"Choisir un service",searchService:"Rechercher un service",noServiceResults:"Aucun service correspondant.",loading:"Chargement…",loadFailed:"Impossible de charger les services.",service:"Service",status:"Statut",edit:"Modifier",remove:"Supprimer",untitled:"Service sans titre"
  },
  admin: {
    title:"Catalogue des services prestataires",description:"Modérez chaque service sans modifier la propriété du prestataire ni le contrat stable de définition LSevin.",adminCenter:"Centre de contrôle administratif",services:"Services",active:"Actifs",inactive:"Inactifs",popular:"Mis en avant",inactiveProvider:"Chez un prestataire inactif",searchPlaceholder:"Service, définition ou prestataire",allStatuses:"Tous les statuts",allProviders:"Tous les prestataires",searchProviders:"Rechercher des prestataires",filter:"Filtrer",service:"Service",provider:"Prestataire",commercial:"Commercial",scheduling:"Planification",reputation:"Réputation",updated:"Mis à jour",controls:"Contrôles",providerInactive:"Prestataire inactif",edit:"Modifier",deactivate:"Désactiver",activate:"Activer",unfeature:"Retirer de la sélection",feature:"Mettre en avant",noMatches:"Aucun service correspondant",noMatchesDescription:"Modifiez les filtres ou demandez au prestataire d’ajouter un service.",recentAdministration:"Administration récente des services",noActions:"Aucune action administrative n’a encore été enregistrée.",reason:"Motif",loading:"Chargement…",loadFailed:"Impossible de charger les prestataires.",noProviderResults:"Aucun prestataire correspondant.",durationMinutes:(v)=>`${v} minutes`,slotMinutes:(v)=>`créneaux de ${v} minutes`,reviews:(v)=>`${v} avis`,actionLabels:{set_is_active:"Statut du service modifié",set_is_popular:"Mise en avant modifiée"}
  }
};

const dictionary: Record<PortalLocale, ServicesCopy> = { fa, en, ar, tr, es, ku, de, fr };
export function servicesCopy(value?: string | null) { return dictionary[normalizePortalLocale(value).locale] ?? en; }
export function serviceAdminActionLabel(copy: ServicesCopy, action: string) { return copy.admin.actionLabels[action] || action.replaceAll("_", " "); }
export { mediaPickerCopy };
