<?xml version="1.0" encoding="utf-8"?>
<Project>
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <NoWarn>CS1587,CS1591,CS1998,NU5105</NoWarn>
  </PropertyGroup>
  <PropertyGroup>
    <AnalysisLevel>latest-All</AnalysisLevel>
    <AnalysisMode>All</AnalysisMode>
    <AnalysisModeGlobalization>None</AnalysisModeGlobalization>
    <AnalysisModeSecurity>All</AnalysisModeSecurity>
    <RunAnalyzersDuringBuild>true</RunAnalyzersDuringBuild>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <CodeAnalysisTreatWarningsAsErrors>false</CodeAnalysisTreatWarningsAsErrors>
  </PropertyGroup>
  <PropertyGroup>
    <ErrorOnDuplicatePublishOutputFiles>false</ErrorOnDuplicatePublishOutputFiles>
  </PropertyGroup>
  <ItemGroup Label="Implicit usings">
    <Using Include="FluentAssertions" />
    <Using Include="NSubstitute" />
    <Using Include="Xunit" />
  </ItemGroup>
</Project>
