//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuildingBlocks.Core.Resources
{
    using System;


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedResource
    {

        private static System.Resources.ResourceManager resourceMan;

        private static System.Globalization.CultureInfo resourceCulture;

        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResource()
        {
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.Equals(null, resourceMan))
                {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("BuildingBlocks.Core.Resources.SharedResource", typeof(SharedResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        public static string Email_Uniqueness_Error_Message
        {
            get
            {
                return ResourceManager.GetString("Email_Uniqueness_Error_Message", resourceCulture);
            }
        }

        public static string Not_Found
        {
            get
            {
                return ResourceManager.GetString("Not_Found", resourceCulture);
            }
        }

        public static string Not_Found_Error_Message
        {
            get
            {
                return ResourceManager.GetString("Not_Found_Error_Message", resourceCulture);
            }
        }

        public static string Application_Error
        {
            get
            {
                return ResourceManager.GetString("Application_Error", resourceCulture);
            }
        }

        public static string Required_Error_Message
        {
            get
            {
                return ResourceManager.GetString("Required_Error_Message", resourceCulture);
            }
        }

        public static string Greater_Than_Zero_Error_Message
        {
            get
            {
                return ResourceManager.GetString("Greater_Than_Zero_Error_Message", resourceCulture);
            }
        }

        public static string Greater_Or_Equal_Error_Message
        {
            get
            {
                return ResourceManager.GetString("Greater_Or_Equal_Error_Message", resourceCulture);
            }
        }

        public static string Less_Or_Equal_Error_Message
        {
            get
            {
                return ResourceManager.GetString("Less_Or_Equal_Error_Message", resourceCulture);
            }
        }

        public static string Validation_Error_Message
        {
            get
            {
                return ResourceManager.GetString("Validation_Error_Message", resourceCulture);
            }
        }

        public static string Greater_Length_Error_Message
        {
            get
            {
                return ResourceManager.GetString("Greater_Length_Error_Message", resourceCulture);
            }
        }

        public static string Less_Length_Error_Message
        {
            get
            {
                return ResourceManager.GetString("Less_Length_Error_Message", resourceCulture);
            }
        }

        public static string First_Name
        {
            get
            {
                return ResourceManager.GetString("First_Name", resourceCulture);
            }
        }

        public static string Last_Name
        {
            get
            {
                return ResourceManager.GetString("Last Name", resourceCulture);
            }
        }

        public static string Phone_Number
        {
            get
            {
                return ResourceManager.GetString("Phone_Number", resourceCulture);
            }
        }

        public static string Email
        {
            get
            {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }

        public static string Access_Denied_Error
        {
            get
            {
                return ResourceManager.GetString("Access_Denied_Error", resourceCulture);
            }
        }

        public static string Access_Denied_Message
        {
            get
            {
                return ResourceManager.GetString("Access_Denied_Message", resourceCulture);
            }
        }

        public static string Business_Rule_Error
        {
            get
            {
                return ResourceManager.GetString("Business_Rule_Error", resourceCulture);
            }
        }

        public static string Unknown_Error
        {
            get
            {
                return ResourceManager.GetString("Unknown_Error", resourceCulture);
            }
        }

        public static string Validation_Error
        {
            get
            {
                return ResourceManager.GetString("Validation_Error", resourceCulture);
            }
        }

        public static string Authentication_Error
        {
            get
            {
                return ResourceManager.GetString("Authentication_Error", resourceCulture);
            }
        }

        public static string Invalid_Credentials_Message
        {
            get
            {
                return ResourceManager.GetString("Invalid_Credentials_Message", resourceCulture);
            }
        }

        public static string Page_Size
        {
            get
            {
                return ResourceManager.GetString("Page_Size", resourceCulture);
            }
        }

        public static string Page
        {
            get
            {
                return ResourceManager.GetString("Page", resourceCulture);
            }
        }

        public static string User
        {
            get
            {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }

        public static string Username
        {
            get
            {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }

        public static string Password
        {
            get
            {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }

        public static string Code
        {
            get
            {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }

        public static string Birth_Date
        {
            get
            {
                return ResourceManager.GetString("Birth_Date", resourceCulture);
            }
        }

        public static string Phone_Number_Uniqueness_Error_Message
        {
            get
            {
                return ResourceManager.GetString("Phone_Number_Uniqueness_Error_Message", resourceCulture);
            }
        }

        public static string Country
        {
            get
            {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }

        public static string Address
        {
            get
            {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }

        public static string City
        {
            get
            {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }

        public static string State
        {
            get
            {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }

        public static string Street
        {
            get
            {
                return ResourceManager.GetString("Street", resourceCulture);
            }
        }

        public static string Zip_Code
        {
            get
            {
                return ResourceManager.GetString("Zip_Code", resourceCulture);
            }
        }

        public static string Today
        {
            get
            {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }

        public static string Invalid_Data_Error_Message
        {
            get
            {
                return ResourceManager.GetString("Invalid_Data_Error_Message", resourceCulture);
            }
        }

        public static string Gender
        {
            get
            {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }

        public static string Document
        {
            get
            {
                return ResourceManager.GetString("Document", resourceCulture);
            }
        }

        public static string File_Upload_Error_Message
        {
            get
            {
                return ResourceManager.GetString("File_Upload_Error_Message", resourceCulture);
            }
        }

        public static string Description
        {
            get
            {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }

        public static string Start_Date
        {
            get
            {
                return ResourceManager.GetString("Start_Date", resourceCulture);
            }
        }

        public static string End_Date
        {
            get
            {
                return ResourceManager.GetString("End_Date", resourceCulture);
            }
        }

        public static string Localized_String_Must_Have_Translations_Error_Message
        {
            get
            {
                return ResourceManager.GetString("Localized_String_Must_Have_Translations_Error_Message", resourceCulture);
            }
        }
        public static string Localized_String_Translations_Must_Not_Be_Empty_Error_Message
        {
            get
            {
                return ResourceManager.GetString("Localized_String_Translations_Must_Not_Be_Empty_Error_Message", resourceCulture);
            }
        }
    }
}
