import type { PortalLocale } from "@core/i18n/config";

export type ModuleDescriptionRow = { en: string; fa: string };

// Exact descriptions for the 24 published LSevin-backed modules.
export const moduleDescriptions: Record<string, ModuleDescriptionRow> = {
  "admin-governance": {
    en: "Controls the administration layer of the portal. Superadmins use it to manage administrative users and roles, inspect audit history, and enable or disable installed modules without deleting their data.",
    fa: "مرکز کنترل مدیریتی سامانه است. مدیر ارشد از این بخش برای ساخت و مدیریت کاربران ادمین، تعیین نقش و دسترسی، دیدن سابقه تغییرات و فعال یا غیرفعال‌کردن ماژول‌ها بدون حذف اطلاعات استفاده می‌کند.",
  },
  "provider-availability": {
    en: "Defines when a provider, staff member, room, device, or other resource is available. It manages weekly schedules, date-specific exceptions, capacity, slot length, and the services that can be booked in each period.",
    fa: "مشخص می‌کند ارائه‌دهنده، کارمند، اتاق، دستگاه یا هر منبع دیگر چه زمان‌هایی قابل رزرو است. برنامه هفتگی، استثناهای روزهای خاص، ظرفیت، طول هر نوبت و خدمات قابل ارائه در هر بازه از این بخش تنظیم می‌شود.",
  },
  "booking-management": {
    en: "Provides the operational workspace for bookings. Provider teams can assign staff, change booking status, add internal notes, view assigned work, and export calendar information.",
    fa: "محیط عملیاتی مدیریت رزروهاست. تیم ارائه‌دهنده می‌تواند هر رزرو را به کارمند مشخص واگذار کند، وضعیت آن را تغییر دهد، یادداشت داخلی ثبت کند، کارهای ارجاع‌شده را ببیند و اطلاعات تقویم را خروجی بگیرد.",
  },
  "provider-bookings": {
    en: "Shows the provider’s core booking list and booking details. It is the simple day-to-day view used to see upcoming, active, completed, or cancelled reservations for the current provider.",
    fa: "فهرست اصلی رزروهای ارائه‌دهنده و جزئیات هر رزرو را نشان می‌دهد. این همان نمای روزمره‌ای است که برای دیدن رزروهای آینده، درحال انجام، تکمیل‌شده یا لغوشده استفاده می‌شود.",
  },
  "provider-dashboard": {
    en: "Shows the most important information for the signed-in user. Providers see profile readiness, upcoming work, bookings, alerts, and operational metrics; administrators see system-level status and items needing attention.",
    fa: "مهم‌ترین اطلاعات موردنیاز کاربر را در یک نگاه نشان می‌دهد. ارائه‌دهنده وضعیت تکمیل پروفایل، رزروها، کارهای نزدیک، هشدارها و آمار اصلی را می‌بیند و ادمین نیز وضعیت کلی سامانه و موارد نیازمند رسیدگی را بررسی می‌کند.",
  },
  "provider-finance-legacy": {
    en: "Keeps the original provider finance screen for compatibility with older workflows. It provides legacy financial information while newer wallet, settlement, and analytics operations live in Provider Finance & Analytics.",
    fa: "صفحه مالی قدیمی را برای سازگاری با فرایندهای قبلی نگه می‌دارد. اطلاعات مالی قدیمی از این بخش قابل مشاهده است، اما عملیات جدید کیف پول، تسویه و گزارش‌ها در ماژول «مالی و تحلیل ارائه‌دهنده» انجام می‌شود.",
  },
  "provider-management-hub": {
    en: "Acts as the central management menu for a provider workspace. It brings the main profile, services, staff, media, availability, bookings, offers, reviews, finance, and support areas into one starting point.",
    fa: "صفحه شروع مدیریت یک ارائه‌دهنده است. لینک بخش‌های اصلی مانند پروفایل، خدمات، کارکنان، رسانه، زمان‌بندی، رزروها، پیشنهادها، نظرات، مالی و پشتیبانی را در یک محل جمع می‌کند.",
  },
  "provider-media": {
    en: "Provides the simple provider gallery used by the core profile workflow. It lets a provider view and select the media explicitly owned by that provider without exposing files from another provider.",
    fa: "گالری ساده رسانه‌های متعلق به ارائه‌دهنده را در اختیار بخش‌های اصلی پروفایل می‌گذارد. کاربر فقط تصاویر و فایل‌های همان ارائه‌دهنده را می‌بیند و می‌تواند آن‌ها را برای پروفایل یا محتوای مربوط انتخاب کند.",
  },
  "media-library": {
    en: "Provides the full media-asset workflow for provider content. Users upload provider-owned files, attach them to profiles or services, order them, localize alternative text, and send them through moderation before public use.",
    fa: "چرخه کامل مدیریت فایل‌های تصویری و رسانه‌ای ارائه‌دهنده است. فایل‌ها بارگذاری می‌شوند، به پروفایل یا خدمت متصل و مرتب می‌شوند، متن جایگزین چندزبانه می‌گیرند و قبل از نمایش عمومی برای بررسی ارسال می‌شوند.",
  },
  "notifications-module": {
    en: "Centralizes portal notifications. Administrators manage multilingual templates and delivery channels, while providers and users receive inbox messages generated by bookings, payments, support, campaigns, and other modules.",
    fa: "مرکز اعلان‌های سامانه است. ادمین قالب‌های چندزبانه و کانال ارسال را مدیریت می‌کند و ارائه‌دهنده یا کاربر پیام‌های مربوط به رزرو، پرداخت، پشتیبانی، کمپین و سایر رویدادهای سامانه را در صندوق اعلان می‌گیرد.",
  },
  "provider-offers": {
    en: "Manages the provider’s standard discounts and promotional offers. Providers choose a service, set discount rules, validity dates, code and usage limits, then activate or deactivate the offer without deleting its history.",
    fa: "تخفیف‌ها و پیشنهادهای معمول ارائه‌دهنده را مدیریت می‌کند. ارائه‌دهنده خدمت، میزان تخفیف، تاریخ اعتبار، کد و سقف استفاده را تعیین می‌کند و پیشنهاد را بدون حذف سابقه فعال یا غیرفعال می‌کند.",
  },
  "provider-onboarding": {
    en: "Handles provider and staff registration from public application to administrative approval. Applicants submit identity, contact, location, profile, and role information; administrators review, request changes, reject, attach to an existing provider, or approve a new workspace.",
    fa: "ثبت‌نام ارائه‌دهنده و کارمند را از درخواست اولیه تا تأیید ادمین مدیریت می‌کند. متقاضی اطلاعات هویتی، تماس، موقعیت، پروفایل و نقش را می‌فرستد و ادمین می‌تواند اصلاح بخواهد، رد کند، به ارائه‌دهنده موجود متصل کند یا فضای کاری جدید بسازد.",
  },
  "payment-billing": {
    en: "Handles invoices and payment operations. It issues standard, tax, proforma, and international invoices, starts payment attempts, accepts manual receipts, verifies them, reconciles bank records, and prevents duplicate payment completion.",
    fa: "صورتحساب و عملیات پرداخت را مدیریت می‌کند. فاکتور عادی، مالیاتی، پیش‌فاکتور و ارزی صادر می‌شود، پرداخت شروع می‌شود، رسید دستی دریافت و بررسی می‌گردد، گردش بانکی تطبیق داده می‌شود و ثبت تکراری پرداخت جلوگیری می‌شود.",
  },
  "provider-access": {
    en: "Controls which provider workspaces the signed-in user can access. Users see their approved providers, choose the current workspace, and manage account-level settings without gaining access to unrelated providers.",
    fa: "مشخص می‌کند کاربر واردشده به کدام فضای ارائه‌دهنده دسترسی دارد. کاربر ارائه‌دهندگان تأییدشده خود را می‌بیند، فضای فعلی را انتخاب می‌کند و تنظیمات حساب را انجام می‌دهد، بدون اینکه به اطلاعات ارائه‌دهندگان دیگر دسترسی پیدا کند.",
  },
  "provider-finance-analytics": {
    en: "Provides the modern provider finance workspace. It covers wallet balance, money moving between LSevin, provider, and customer, settlement requests, payouts, financial statistics, and administrative control of settlements and reports.",
    fa: "محیط مالی اصلی و جدید ارائه‌دهنده است. موجودی کیف پول، گردش پول بین السوین، ارائه‌دهنده و مشتری، درخواست تسویه، پرداخت خروجی، آمار مالی و کنترل ادمین بر تسویه‌ها و گزارش‌ها در این بخش انجام می‌شود.",
  },
  "provider-portal": {
    en: "Coordinates the overall provider workspace and launch-readiness lifecycle. It manages profile claims and ownership, content drafts and moderation, operational readiness checks, and the command-center pages used before a provider becomes fully publishable.",
    fa: "هسته هماهنگ‌کننده فضای کاری ارائه‌دهنده و آماده‌سازی برای انتشار است. مالکیت و ادعای پروفایل، پیش‌نویس و بررسی محتوا، چک‌های آمادگی و صفحات کنترل مرکزی قبل از انتشار کامل ارائه‌دهنده از این بخش مدیریت می‌شوند.",
  },
  "provider-profile": {
    en: "Stores and edits the provider’s public profile. It covers multilingual name and description, provider type, contact information, location, address, coordinates, profile media, and the administration list of providers.",
    fa: "اطلاعات پروفایل عمومی ارائه‌دهنده را نگه می‌دارد و ویرایش می‌کند. نام و توضیح چندزبانه، نوع ارائه‌دهنده، تماس، کشور و شهر، نشانی، مختصات و تصویر پروفایل در این بخش ثبت می‌شوند و ادمین نیز فهرست ارائه‌دهندگان را می‌بیند.",
  },
  "reporting-analytics": {
    en: "Builds provider and administration reports from operational data. It shows dashboards, creates dated report snapshots, exports approved formats, and lets administrators compare performance across providers without changing source transactions.",
    fa: "از داده‌های عملیاتی گزارش و تحلیل می‌سازد. داشبوردهای ارائه‌دهنده و ادمین، ذخیره نسخه گزارش در یک تاریخ مشخص، خروجی فایل و مقایسه عملکرد ارائه‌دهندگان را فراهم می‌کند، بدون اینکه تراکنش‌های اصلی را تغییر دهد.",
  },
  "provider-reviews": {
    en: "Shows the provider’s basic review list inside the core provider workspace. It is the lightweight view for reading customer ratings and comments and handling the provider’s normal reply workflow.",
    fa: "فهرست ساده نظرات مشتریان را در فضای اصلی ارائه‌دهنده نشان می‌دهد. ارائه‌دهنده امتیازها و متن نظرات را می‌خواند و پاسخ معمول خود را مدیریت می‌کند؛ امکانات پیشرفته بررسی در ماژول «نظرات و پاسخ‌ها» قرار دارد.",
  },
  "reviews-standalone": {
    en: "Provides the full review and reply workflow. Customers can leave reviews and images, providers reply, users vote on usefulness, and administrators approve, hide, or reject reviews and replies with an auditable reason.",
    fa: "چرخه کامل نظر و پاسخ را مدیریت می‌کند. مشتری نظر و تصویر ثبت می‌کند، ارائه‌دهنده پاسخ می‌دهد، کاربران مفیدبودن نظر را مشخص می‌کنند و ادمین می‌تواند نظر یا پاسخ را با دلیل تأیید، مخفی یا رد کند.",
  },
  "provider-services": {
    en: "Creates and maintains the services a provider sells or books. It manages multilingual titles and descriptions, price and currency, duration, slot interval, active status, media, and the administration service catalog.",
    fa: "خدمات قابل فروش یا رزرو ارائه‌دهنده را می‌سازد و نگه می‌دارد. عنوان و توضیح چندزبانه، قیمت و ارز، مدت انجام، فاصله نوبت‌ها، وضعیت فعال و تصاویر خدمت در این بخش تنظیم می‌شوند و ادمین فهرست خدمات را کنترل می‌کند.",
  },
  "provider-staff": {
    en: "Manages people who work for a provider. It stores multilingual staff profiles, title, specialty, biography, profile image, provider relationship, and self-service access for an approved staff owner.",
    fa: "افرادی را که برای ارائه‌دهنده کار می‌کنند مدیریت می‌کند. پروفایل چندزبانه، سمت، تخصص، معرفی، تصویر و ارتباط هر فرد با ارائه‌دهنده ثبت می‌شود و کارمند تأییدشده می‌تواند اطلاعات پروفایل خودش را مدیریت کند.",
  },
  "provider-support": {
    en: "Provides the simple provider support request flow. Providers submit a request, choose priority, follow its status, and receive a response from LSevin support for routine portal or account issues.",
    fa: "مسیر ساده درخواست پشتیبانی ارائه‌دهنده است. ارائه‌دهنده موضوع و اولویت را ثبت می‌کند، وضعیت رسیدگی را می‌بیند و برای مشکلات معمول پرتال یا حساب از تیم پشتیبانی السوین پاسخ می‌گیرد.",
  },
  "ticketing": {
    en: "Provides the full support ticket workspace. It supports threaded replies, assignment to support agents, internal notes, attachments, priorities, service-level tracking, and closing or reopening tickets.",
    fa: "سامانه کامل تیکت پشتیبانی است. پاسخ‌های زنجیره‌ای، ارجاع به کارشناس، یادداشت داخلی، فایل پیوست، اولویت، زمان پاسخ و بستن یا بازکردن مجدد تیکت را مدیریت می‌کند.",
  },
};

export function getModuleDescriptionText(moduleId: string, locale: PortalLocale) {
  const row = moduleDescriptions[moduleId];
  if (!row) return null;
  return locale === "fa" ? row.fa : row.en;
}
