lsevin_jenkins_source_dir: "{{ playbook_dir }}/../../jenkins"
lsevin_jenkins_controller_dir: /opt/lsevin/app/jenkins-controller
lsevin_jenkins_home_dir: /var/lib/lsevin/app/jenkins
lsevin_jenkins_secret_dir: /etc/lsevin/app/jenkins
lsevin_jenkins_backup_dir: /var/backups/lsevin/app/jenkins
lsevin_jenkins_network: lsevin-network
lsevin_jenkins_admin_user: admin
lsevin_jenkins_admin_email: admin@lsevin.com
lsevin_jenkins_domain: devops.lsevin.com
lsevin_jenkins_repository_url: "https://github.com/raminmansouri/lsevin"
lsevin_jenkins_repository_source_dir: /opt/lsevin/app
lsevin_jenkins_deploy_branch: Lsevin-New
lsevin_jenkins_github_credentials_id: github-lsevin
lsevin_jenkins_portal_branch: main
lsevin_jenkins_shop_branch: main
lsevin_jenkins_crm_branch: main
lsevin_jenkins_caddy_paths:
  - /opt/lsevin/app/deployments/docker/Caddyfile.server
lsevin_jenkins_docker_dir: /opt/lsevin/app/deployments/docker
lsevin_jenkins_docker_env: /opt/lsevin/app/deployments/docker/.env
lsevin_jenkins_compose_project: docker
