import { getCartView } from "@/features/shop/api/cart.repository";
import { sql } from "@/features/shop/lib/db";
export default async function CheckoutPage() {
  const cart = await getCartView();
  const deliveryMethods = await sql<any[]>`select id::text as id, common.get_translation_t(name_translations, 'en', 'en') as name, base_fee::float as base_fee from shop.delivery_methods where is_active = true order by base_fee asc`;
  const paymentMethods = await sql<any[]>`select id::text as id, common.get_translation_t(name_translations, 'en', 'en') as name from shop.payment_methods where is_active = true order by sort_order asc`;
  return (
    <div className="min-h-screen bg-gray-50 px-5 py-6">
      <h1 className="text-2xl font-bold text-gray-900">Checkout</h1>
      <div className="mt-6 grid gap-6 lg:grid-cols-[1fr,380px]">
        <section className="space-y-6">
          <div className="rounded-2xl border border-gray-100 bg-white p-5 shadow-sm"><h2 className="text-lg font-bold text-gray-900">Contact</h2><input className="mt-4 w-full rounded-xl border border-gray-200 px-4 py-3" placeholder="Email" /></div>
          <div className="rounded-2xl border border-gray-100 bg-white p-5 shadow-sm"><h2 className="text-lg font-bold text-gray-900">Shipping address</h2><div className="mt-4 grid gap-3 md:grid-cols-2"><input className="rounded-xl border border-gray-200 px-4 py-3" placeholder="Full name" /><input className="rounded-xl border border-gray-200 px-4 py-3" placeholder="Phone" /><input className="rounded-xl border border-gray-200 px-4 py-3" placeholder="Country" /><input className="rounded-xl border border-gray-200 px-4 py-3" placeholder="City" /><input className="rounded-xl border border-gray-200 px-4 py-3 md:col-span-2" placeholder="Address line 1" /></div></div>
          <div className="rounded-2xl border border-gray-100 bg-white p-5 shadow-sm"><h2 className="text-lg font-bold text-gray-900">Delivery method</h2><div className="mt-4 space-y-3">{deliveryMethods.map((method) => <label key={method.id} className="flex items-center justify-between rounded-xl border border-gray-200 px-4 py-3"><div className="flex items-center gap-3"><input type="radio" name="deliveryMethod" /><span>{method.name}</span></div><span className="font-medium">{cart.totals.currency} {Number(method.base_fee).toFixed(2)}</span></label>)}</div></div>
          <div className="rounded-2xl border border-gray-100 bg-white p-5 shadow-sm"><h2 className="text-lg font-bold text-gray-900">Payment method</h2><div className="mt-4 space-y-3">{paymentMethods.map((method) => <label key={method.id} className="flex items-center gap-3 rounded-xl border border-gray-200 px-4 py-3"><input type="radio" name="paymentMethod" /><span>{method.name}</span></label>)}</div></div>
        </section>
        <aside className="rounded-2xl border border-gray-100 bg-white p-5 shadow-sm"><h2 className="text-lg font-bold text-gray-900">Order summary</h2><div className="mt-4 space-y-3">{cart.items.filter((x) => !x.savedForLater).map((item) => <div key={item.id} className="flex items-center justify-between gap-3"><div className="min-w-0"><div className="line-clamp-1 text-sm font-medium text-gray-900">{item.name}</div><div className="text-xs text-gray-500">Qty {item.quantity}</div></div><div className="text-sm font-medium">{item.currency} {(item.unitPrice * item.quantity).toFixed(2)}</div></div>)}</div><div className="mt-5 space-y-2 border-t pt-4 text-sm"><div className="flex justify-between"><span>Subtotal</span><span>{cart.totals.currency} {cart.totals.subtotal.toFixed(2)}</span></div><div className="flex justify-between"><span>Discount</span><span>- {cart.totals.currency} {cart.totals.discountTotal.toFixed(2)}</span></div><div className="flex justify-between"><span>Shipping</span><span>{cart.totals.currency} {cart.totals.shippingTotal.toFixed(2)}</span></div><div className="flex justify-between"><span>Tax</span><span>{cart.totals.currency} {cart.totals.taxTotal.toFixed(2)}</span></div><div className="flex justify-between border-t pt-3 text-base font-bold"><span>Total</span><span>{cart.totals.currency} {cart.totals.grandTotal.toFixed(2)}</span></div></div><button className="mt-5 w-full rounded-xl bg-[#083f30] px-4 py-3 font-semibold text-white">Place order</button></aside>
      </div>
    </div>
  );
}
