import type { PortalLocale } from "@core/i18n/config";
import { normalizePortalLocale } from "@core/i18n/config";
import type { MediaPickerCopy } from "@core/ui/MediaPicker";

const en: MediaPickerCopy = { media: "Media", change: "Change media", choose: "Choose from library", remove: "Remove selection", providerShared: "Shared by provider", providerOwned: "Provider-owned", personal: "Personal media", public: "Public LSevin media", libraryTitle: "LSevin media library", staffScopeHelp: "Only your personal media and files explicitly shared by the provider are shown.", userScopeHelp: "Only this user's personal media is shown.", providerScopeHelp: "Only public media or media owned by this provider can be selected.", searchPlaceholder: "Search filename or title", uploading: "Uploading", upload: "Upload file", loadFailed: "Could not load the media library.", uploadFailed: "File upload failed.", providerShare: "Provider share", providerMedia: "Provider media", publicMedia: "Public media" };
const fa: MediaPickerCopy = { media: "رسانه", change: "تغییر رسانه", choose: "انتخاب از کتابخانه", remove: "حذف انتخاب", providerShared: "اشتراک‌گذاری شده توسط ارائه‌دهنده", providerOwned: "متعلق به ارائه‌دهنده", personal: "رسانه شخصی", public: "رسانه عمومی السوین", libraryTitle: "کتابخانه رسانه السوین", staffScopeHelp: "فقط رسانه شخصی شما و فایل‌هایی که ارائه‌دهنده صریحاً به اشتراک گذاشته نمایش داده می‌شود.", userScopeHelp: "فقط رسانه‌های شخصی همین کاربر نمایش داده می‌شود.", providerScopeHelp: "فقط رسانه عمومی یا متعلق به این ارائه‌دهنده قابل انتخاب است.", searchPlaceholder: "جستجوی نام فایل یا عنوان", uploading: "در حال بارگذاری", upload: "بارگذاری فایل", loadFailed: "بارگذاری کتابخانه رسانه ناموفق بود.", uploadFailed: "بارگذاری فایل ناموفق بود.", providerShare: "اشتراک ارائه‌دهنده", providerMedia: "رسانه ارائه‌دهنده", publicMedia: "رسانه عمومی" };
const ar: MediaPickerCopy = { media: "الوسائط", change: "تغيير الوسائط", choose: "اختيار من المكتبة", remove: "إزالة الاختيار", providerShared: "مشارك من المزوّد", providerOwned: "مملوك للمزوّد", personal: "وسائط شخصية", public: "وسائط LSevin العامة", libraryTitle: "مكتبة وسائط LSevin", staffScopeHelp: "تظهر وسائطك الشخصية والملفات التي شاركها المزوّد معك صراحة فقط.", userScopeHelp: "تظهر الوسائط الشخصية لهذا المستخدم فقط.", providerScopeHelp: "يمكن اختيار الوسائط العامة أو المملوكة لهذا المزوّد فقط.", searchPlaceholder: "البحث باسم الملف أو العنوان", uploading: "جارٍ الرفع", upload: "رفع ملف", loadFailed: "تعذر تحميل مكتبة الوسائط.", uploadFailed: "فشل رفع الملف.", providerShare: "مشاركة المزوّد", providerMedia: "وسائط المزوّد", publicMedia: "وسائط عامة" };
const tr: MediaPickerCopy = { media: "Medya", change: "Medyayı değiştir", choose: "Kütüphaneden seç", remove: "Seçimi kaldır", providerShared: "Sağlayıcı tarafından paylaşıldı", providerOwned: "Sağlayıcıya ait", personal: "Kişisel medya", public: "Genel LSevin medyası", libraryTitle: "LSevin medya kütüphanesi", staffScopeHelp: "Yalnızca kişisel medyanız ve sağlayıcının açıkça paylaştığı dosyalar gösterilir.", userScopeHelp: "Yalnızca bu kullanıcının kişisel medyası gösterilir.", providerScopeHelp: "Yalnızca genel veya bu sağlayıcıya ait medya seçilebilir.", searchPlaceholder: "Dosya adı veya başlık ara", uploading: "Yükleniyor", upload: "Dosya yükle", loadFailed: "Medya kütüphanesi yüklenemedi.", uploadFailed: "Dosya yükleme başarısız.", providerShare: "Sağlayıcı paylaşımı", providerMedia: "Sağlayıcı medyası", publicMedia: "Genel medya" };
const es: MediaPickerCopy = { media: "Medios", change: "Cambiar medio", choose: "Elegir de la biblioteca", remove: "Quitar selección", providerShared: "Compartido por el proveedor", providerOwned: "Del proveedor", personal: "Medio personal", public: "Medio público de LSevin", libraryTitle: "Biblioteca de medios de LSevin", staffScopeHelp: "Solo se muestran tus medios personales y los archivos compartidos expresamente por el proveedor.", userScopeHelp: "Solo se muestran los medios personales de este usuario.", providerScopeHelp: "Solo se pueden elegir medios públicos o del proveedor.", searchPlaceholder: "Buscar nombre de archivo o título", uploading: "Subiendo", upload: "Subir archivo", loadFailed: "No se pudo cargar la biblioteca de medios.", uploadFailed: "Falló la carga del archivo.", providerShare: "Compartido por proveedor", providerMedia: "Medio del proveedor", publicMedia: "Medio público" };
const ku: MediaPickerCopy = { media: "میدیا", change: "گۆڕینی میدیا", choose: "هەڵبژاردن لە کتێبخانە", remove: "لابردنی هەڵبژاردن", providerShared: "لە پێشکەشکەرەوە هاوبەشکراو", providerOwned: "هی پێشکەشکەر", personal: "میدیای کەسی", public: "میدیای گشتی LSevin", libraryTitle: "کتێبخانەی میدیای LSevin", staffScopeHelp: "تەنها میدیای کەسی و فایلە هاوبەشکراوەکان پیشان دەدرێن.", userScopeHelp: "تەنها میدیای کەسی ئەم بەکارهێنەرە پیشان دەدرێت.", providerScopeHelp: "تەنها میدیای گشتی یان هی پێشکەشکەر هەڵدەبژێردرێت.", searchPlaceholder: "گەڕان بە ناوی فایل یان ناونیشان", uploading: "بارکردن", upload: "بارکردنی فایل", loadFailed: "کتێبخانەی میدیا بارنەکرا.", uploadFailed: "بارکردنی فایل سەرکەوتوو نەبوو.", providerShare: "هاوبەشی پێشکەشکەر", providerMedia: "میدیای پێشکەشکەر", publicMedia: "میدیای گشتی" };
const de: MediaPickerCopy = { media: "Medien", change: "Medium ändern", choose: "Aus Bibliothek wählen", remove: "Auswahl entfernen", providerShared: "Vom Anbieter geteilt", providerOwned: "Anbietereigen", personal: "Persönliches Medium", public: "Öffentliches LSevin-Medium", libraryTitle: "LSevin-Medienbibliothek", staffScopeHelp: "Nur persönliche Medien und ausdrücklich geteilte Dateien werden angezeigt.", userScopeHelp: "Nur persönliche Medien dieses Benutzers werden angezeigt.", providerScopeHelp: "Nur öffentliche oder diesem Anbieter gehörende Medien können gewählt werden.", searchPlaceholder: "Dateiname oder Titel suchen", uploading: "Wird hochgeladen", upload: "Datei hochladen", loadFailed: "Medienbibliothek konnte nicht geladen werden.", uploadFailed: "Datei-Upload fehlgeschlagen.", providerShare: "Anbieterfreigabe", providerMedia: "Anbietermedium", publicMedia: "Öffentliches Medium" };
const fr: MediaPickerCopy = { media: "Médias", change: "Changer le média", choose: "Choisir dans la bibliothèque", remove: "Supprimer la sélection", providerShared: "Partagé par le prestataire", providerOwned: "Appartient au prestataire", personal: "Média personnel", public: "Média public LSevin", libraryTitle: "Bibliothèque de médias LSevin", staffScopeHelp: "Seuls vos médias personnels et les fichiers explicitement partagés sont affichés.", userScopeHelp: "Seuls les médias personnels de cet utilisateur sont affichés.", providerScopeHelp: "Seuls les médias publics ou appartenant à ce prestataire peuvent être choisis.", searchPlaceholder: "Rechercher un nom de fichier ou un titre", uploading: "Téléversement", upload: "Téléverser un fichier", loadFailed: "Impossible de charger la bibliothèque de médias.", uploadFailed: "Échec du téléversement.", providerShare: "Partage prestataire", providerMedia: "Média prestataire", publicMedia: "Média public" };

const dictionary: Record<PortalLocale, MediaPickerCopy> = { fa, en, ar, tr, es, ku, de, fr };
export function mediaPickerCopy(value?: string | null) { return dictionary[normalizePortalLocale(value).locale] ?? en; }
