apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - ../../database/postgres.yaml
patches:
  - path: configmap-patch.yaml
images:
  - name: lsevin-providers
    newName: lsevin-providers
    newTag: local
  - name: lsevin-providers-db
    newName: lsevin-providers-db
    newTag: local
