#----------------------------------------------------------------------------------------------------------------------------------------
# If you want to run all the clients and services and their dependencies without                                                         |
# needing to debug them, you can run the below commands through CLI:                                                                     |                                                                                                               |
#                                                                                                                                        |
# For the first time:                                                                                                                    |
# WINDOWS directory> docker-compose -f .\docker-compose.yml -f .\docker-compose.override.yml -f .\infrastructure.yml up -d               |
# MACOS directory> docker-compose -f docker-compose.yml -f docker-compose.override.yml -f infrastructure.yml up -d                       |
#                                                                                                                                        |
# After make changes:                                                                                                                    |
# WINDOWS directory> docker-compose -f .\docker-compose.yml -f .\docker-compose.override.yml -f .\infrastructure.yml up --build          |
# MACOS directory> docker-compose -f docker-compose.yml -f docker-compose.override.yml -f infrastructure.yml up --build                  |
#                                                                                                                                        |
# For down:                                                                                                                              |
# WINDOWS directory> docker-compose -f .\docker-compose.yml -f .\docker-compose.override.yml -f .\infrastructure.yml down                |
# MACOS directory> docker-compose -f docker-compose.yml -f docker-compose.override.yml -f infrastructure.yml down                        |
#                                                                                                                                        |
# But, if you need to do this in Visual Studio and debug some services, then you                                                         |
# can modify the launchSettings and set the desired services to StartDebugging and                                                       |
# then select docker-compose in the debug items and click on DockerCompose                                                               |
#----------------------------------------------------------------------------------------------------------------------------------------

services:
  lsevin-api:
    image: ${DOCKER_REGISTRY-}lsevinapi
    build:
      context: ../../
      dockerfile: src/API/LSevin.Api/Dockerfile

  lsevin-apigateway:
    image: ${DOCKER_REGISTRY-}lsevinapigateway
    build:
      context: ../../
      dockerfile: src/API/LSevin.ApiGateway.Yarp/Dockerfile

  lsevin-webapp:
    build:
      context: ../../frontend/webapp
      dockerfile: Dockerfile
    image: lsevin-webapp:latest
    networks:
      - lsevin-network

  postgres:
    image: postgres:latest

  redis:
    image: redis:latest

  eventstore:
    image: eventstore/eventstore:latest

  jaeger:
    image: jaegertracing/all-in-one:latest

  seq:
    image: datalust/seq:latest

volumes:
  postgres-data:
  redis-data:
  eventstore-data:

networks:
  lsevin-network:
    name: lsevin-network
    driver: bridge
