services:

  lsevin-apigateway:
    build:
      context: ../../
      dockerfile: src/API/LSevin.ApiGateway.Yarp/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://+:8080
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
      Services__lsevin-api__http: http://lsevin-api:8080
    expose:
      - "8080"
    networks:
      - lsevin-network

volumes:
  postgres_data:
  redis_data:
  eventstore_data:
  uploads:
  caddy_data:
  caddy_config:

networks:
  lsevin-network:
    external: true
