---
#----------------------------------------------------------------------------------
# If you want to run or debug some clients or services you need to first make the  |
# environment ready because they have some dependencies like SQL, etc.             |
#                                                                                  |
# Just run the below command through CLI and then the environment is ready:        |
#                                                                                  |
# directory> docker-compose -f Infrastructure.yml up -d                            |
#----------------------------------------------------------------------------------

services:
  postgres:
    container_name: postgres
    environment:
      - POSTGRES_DB=lsevin
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: on-failure
    ports:
      - 5432:5432
    networks:
      - lsevin-network
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  redis:
    container_name: redis
    restart: on-failure
    ports:
      - "6379:6379"
    networks:
      - lsevin-network
    volumes:
      - ./redis-data:/data

  eventstore:
    container_name: eventstore
    restart: on-failure
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=True
      - EVENTSTORE_HTTP_PORT=2113
      - EVENTSTORE_INSECURE=True
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=True
    ports:
      - "2113:2113"
    networks:
      - lsevin-network
    volumes:
      - ./eventstore-data:/var/lib/eventstore

  jaeger:
    container_name: jaeger
    restart: on-failure
    ports:
      - "4317:4317"
      - "4318:4318"
      - "16686:16686"
      - "14268:14268"
    networks:
      - lsevin-network

  seq:
    container_name: seq
    restart: on-failure
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5341:5341
      - 8079:80
    networks:
      - lsevin-network
