<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>true</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" />
    <PackageReference Include="EFCore.NamingConventions" />
    <PackageReference Include="Microsoft.Extensions.Configuration" />
    <PackageReference Include="Microsoft.Extensions.Http.Resilience" />
    <PackageReference Include="Microsoft.Extensions.Http.Polly" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Serilog.AspNetCore" />
    <PackageReference Include="Serilog.Exceptions" />
    <PackageReference Include="Serilog.Exceptions.EntityFrameworkCore" />
    <PackageReference Include="Serilog.Enrichers.Environment" />
    <PackageReference Include="Serilog.Enrichers.Thread" />
    <PackageReference Include="Serilog.Sinks.Seq" />
    <PackageReference Include="Serilog.Sinks.Async" />
    <PackageReference Include="Serilog.Sinks.Console" />
    <PackageReference Include="Serilog.Enrichers.Process" />
    <PackageReference Include="Serilog.Enrichers.Span" />
    <PackageReference Include="Serilog.Enrichers.CorrelationId" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Ulid" />
    <PackageReference Include="Polly" />
    <PackageReference Include="Scrutor" />
    <PackageReference Include="Humanizer" />
    <PackageReference Include="Humanizer.Core" />
    <PackageReference Include="libphonenumber-csharp" />
    <PackageReference Include="Ardalis.GuardClauses" />
    <PackageReference Include="Ardalis.Specification" />
    <PackageReference Include="Ardalis.Specification.EntityFrameworkCore" />
    <PackageReference Include="AutoMapper" />
    <PackageReference Include="MediatR" />
    <PackageReference Include="Quartz" />
    <PackageReference Include="Quartz.Extensions.Hosting" />
    <PackageReference Include="Dapper" />
    <PackageReference Include="SixLabors.ImageSharp" />
    <PackageReference Include="AWSSDK.S3" />
    <PackageReference Include="Sieve" />
    <PackageReference Include="System.Linq.Async" />
    <PackageReference Include="System.Linq.Async.Queryable" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Nito.AsyncEx" />
    <PackageReference Include="Nito.AsyncEx.Context" />
    <PackageReference Include="Nito.AsyncEx.Tasks" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Resources\SharedResource.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>SharedResource.resx</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Update="Resources\SharedResource.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>SharedResource.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\SharedResource.*.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
  </ItemGroup>
</Project>
