<Project Sdk="Microsoft.NET.Sdk">
  <Sdk Name="Aspire.AppHost.Sdk" Version="$(AspireVersion)" />
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsAspireHost>true</IsAspireHost>
    <UserSecretsId>9a808aef-dd38-4611-993a-01b5067a190a</UserSecretsId>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.AppHost" />
    <PackageReference Include="Aspire.Hosting.PostgreSQL" />
    <PackageReference Include="Aspire.Hosting.Redis" />
    <PackageReference Include="Aspire.Hosting.NodeJs" />
    <PackageReference Include="CommunityToolkit.Aspire.Hosting.EventStore" />
    <PackageReference Include="CommunityToolkit.Aspire.Hosting.NodeJS.Extensions" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\src\API\LSevin.ApiGateway.Yarp\LSevin.ApiGateway.Yarp.csproj" />
    <ProjectReference Include="..\..\..\src\API\LSevin.Api\LSevin.Api.csproj" />
  </ItemGroup>
</Project>
