import type { PortalLocale } from "@core/i18n/config";

type Copy = {
  newProviderTitle: string; newProviderDescription: string; applicationsTitle: string; applicationsDescription: string;
  newApplication: string; noApplications: string; noApplicationsDescription: string; start: string; resume: string; open: string;
  providerRequest: string; providerType: string; chooseType: string; legalName: string; displayName: string; contactPerson: string;
  email: string; phoneCode: string; phone: string; website: string; address: string; notes: string;
  businessLicense: string; identityEvidence: string; additionalEvidence: string; evidenceHelp: string;
  saveDraft: string; submitApplication: string; draftSaved: string; correctionRequested: string;
  draft: string; submitted: string; inReview: string; approved: string; rejected: string; disabled: string; changesRequested: string;
};

export const applicationCopy: Record<PortalLocale, Copy> = {
  en: { newProviderTitle:"Become a provider",newProviderDescription:"Save a draft, attach evidence, and submit it for LSevin review when ready.",applicationsTitle:"Provider applications",applicationsDescription:"Applications started by your LSevin account.",newApplication:"New application",noApplications:"No applications",noApplicationsDescription:"Start onboarding to create or claim a provider workspace.",start:"Start",resume:"Resume",open:"Open",providerRequest:"Provider application",providerType:"Provider type",chooseType:"Choose provider type",legalName:"Legal name",displayName:"Public display name",contactPerson:"Contact person",email:"Email",phoneCode:"Country code",phone:"Phone",website:"Website",address:"Address",notes:"Additional notes",businessLicense:"Business / operating license",identityEvidence:"Owner or representative identity evidence",additionalEvidence:"Additional evidence",evidenceHelp:"At least one applicant-owned file is required before submission. Files remain private until reviewed by authorized LSevin administrators.",saveDraft:"Save draft",submitApplication:"Submit application",draftSaved:"Draft saved.",correctionRequested:"Changes requested by LSevin. Update the requested information and resubmit.",draft:"Draft",submitted:"Submitted",inReview:"In review",approved:"Approved",rejected:"Rejected",disabled:"Disabled",changesRequested:"Changes requested" },
  fa: { newProviderTitle:"پیوستن به‌عنوان ارائه‌دهنده",newProviderDescription:"پیش‌نویس را ذخیره کنید، مدارک را پیوست کنید و پس از تکمیل برای بررسی السوین ارسال کنید.",applicationsTitle:"درخواست‌های ارائه‌دهنده",applicationsDescription:"درخواست‌هایی که با حساب السوین شما ایجاد شده‌اند.",newApplication:"درخواست جدید",noApplications:"درخواستی وجود ندارد",noApplicationsDescription:"برای ایجاد یا مالکیت فضای ارائه‌دهنده، فرایند ثبت را شروع کنید.",start:"شروع",resume:"ادامه",open:"باز کردن",providerRequest:"درخواست ارائه‌دهنده",providerType:"نوع ارائه‌دهنده",chooseType:"انتخاب نوع ارائه‌دهنده",legalName:"نام قانونی",displayName:"نام نمایشی عمومی",contactPerson:"شخص رابط",email:"ایمیل",phoneCode:"پیش‌شماره",phone:"تلفن",website:"وب‌سایت",address:"نشانی",notes:"توضیحات تکمیلی",businessLicense:"مجوز فعالیت",identityEvidence:"مدرک هویتی مالک یا نماینده",additionalEvidence:"مدرک تکمیلی",evidenceHelp:"پیش از ارسال نهایی حداقل یک فایل متعلق به متقاضی لازم است. فایل‌ها تا زمان بررسی مدیر مجاز السوین خصوصی می‌مانند.",saveDraft:"ذخیره پیش‌نویس",submitApplication:"ارسال درخواست",draftSaved:"پیش‌نویس ذخیره شد.",correctionRequested:"السوین درخواست اصلاح داده است. اطلاعات خواسته‌شده را اصلاح و دوباره ارسال کنید.",draft:"پیش‌نویس",submitted:"ارسال‌شده",inReview:"در حال بررسی",approved:"تأییدشده",rejected:"ردشده",disabled:"غیرفعال",changesRequested:"نیازمند اصلاح" },
  ar: { newProviderTitle:"الانضمام كمزوّد خدمة",newProviderDescription:"احفظ مسودة وأرفق المستندات ثم أرسل الطلب إلى LSevin عند اكتماله.",applicationsTitle:"طلبات مزوّد الخدمة",applicationsDescription:"الطلبات التي بدأتها بحساب LSevin الخاص بك.",newApplication:"طلب جديد",noApplications:"لا توجد طلبات",noApplicationsDescription:"ابدأ التسجيل لإنشاء أو امتلاك مساحة مزوّد.",start:"ابدأ",resume:"متابعة",open:"فتح",providerRequest:"طلب مزوّد",providerType:"نوع المزوّد",chooseType:"اختر نوع المزوّد",legalName:"الاسم القانوني",displayName:"الاسم العام",contactPerson:"جهة الاتصال",email:"البريد الإلكتروني",phoneCode:"رمز الدولة",phone:"الهاتف",website:"الموقع",address:"العنوان",notes:"ملاحظات إضافية",businessLicense:"ترخيص النشاط",identityEvidence:"هوية المالك أو الممثل",additionalEvidence:"مستند إضافي",evidenceHelp:"يلزم ملف واحد على الأقل يملكه مقدم الطلب قبل الإرسال. تبقى الملفات خاصة حتى يراجعها مدير LSevin مخوّل.",saveDraft:"حفظ المسودة",submitApplication:"إرسال الطلب",draftSaved:"تم حفظ المسودة.",correctionRequested:"طلبت LSevin تعديلات. حدّث المعلومات المطلوبة وأعد الإرسال.",draft:"مسودة",submitted:"مُرسل",inReview:"قيد المراجعة",approved:"مقبول",rejected:"مرفوض",disabled:"معطّل",changesRequested:"تعديلات مطلوبة" },
  tr: { newProviderTitle:"Sağlayıcı olun",newProviderDescription:"Taslağı kaydedin, kanıtları ekleyin ve hazır olduğunda LSevin incelemesine gönderin.",applicationsTitle:"Sağlayıcı başvuruları",applicationsDescription:"LSevin hesabınızla başlattığınız başvurular.",newApplication:"Yeni başvuru",noApplications:"Başvuru yok",noApplicationsDescription:"Sağlayıcı çalışma alanı oluşturmak veya sahiplenmek için başlayın.",start:"Başla",resume:"Devam et",open:"Aç",providerRequest:"Sağlayıcı başvurusu",providerType:"Sağlayıcı türü",chooseType:"Sağlayıcı türünü seçin",legalName:"Yasal ad",displayName:"Genel görünen ad",contactPerson:"İrtibat kişisi",email:"E-posta",phoneCode:"Ülke kodu",phone:"Telefon",website:"Web sitesi",address:"Adres",notes:"Ek notlar",businessLicense:"Faaliyet ruhsatı",identityEvidence:"Sahip veya temsilci kimliği",additionalEvidence:"Ek kanıt",evidenceHelp:"Göndermeden önce başvuru sahibine ait en az bir dosya gereklidir. Dosyalar yetkili LSevin yöneticisi inceleyene kadar özeldir.",saveDraft:"Taslağı kaydet",submitApplication:"Başvuruyu gönder",draftSaved:"Taslak kaydedildi.",correctionRequested:"LSevin değişiklik istedi. İstenen bilgileri güncelleyip yeniden gönderin.",draft:"Taslak",submitted:"Gönderildi",inReview:"İncelemede",approved:"Onaylandı",rejected:"Reddedildi",disabled:"Devre dışı",changesRequested:"Değişiklik istendi" },
  es: { newProviderTitle:"Convertirse en proveedor",newProviderDescription:"Guarda un borrador, adjunta pruebas y envíalo a revisión de LSevin cuando esté listo.",applicationsTitle:"Solicitudes de proveedor",applicationsDescription:"Solicitudes iniciadas con tu cuenta de LSevin.",newApplication:"Nueva solicitud",noApplications:"No hay solicitudes",noApplicationsDescription:"Inicia el alta para crear o reclamar un espacio de proveedor.",start:"Empezar",resume:"Continuar",open:"Abrir",providerRequest:"Solicitud de proveedor",providerType:"Tipo de proveedor",chooseType:"Seleccionar tipo",legalName:"Nombre legal",displayName:"Nombre público",contactPerson:"Persona de contacto",email:"Correo",phoneCode:"Código de país",phone:"Teléfono",website:"Sitio web",address:"Dirección",notes:"Notas adicionales",businessLicense:"Licencia de actividad",identityEvidence:"Identidad del titular o representante",additionalEvidence:"Prueba adicional",evidenceHelp:"Se requiere al menos un archivo propiedad del solicitante antes de enviar. Los archivos permanecen privados hasta la revisión autorizada de LSevin.",saveDraft:"Guardar borrador",submitApplication:"Enviar solicitud",draftSaved:"Borrador guardado.",correctionRequested:"LSevin solicitó cambios. Actualiza la información indicada y vuelve a enviar.",draft:"Borrador",submitted:"Enviado",inReview:"En revisión",approved:"Aprobado",rejected:"Rechazado",disabled:"Deshabilitado",changesRequested:"Cambios solicitados" },
  ku: { newProviderTitle:"ببە بە دابینکەر",newProviderDescription:"ڕەشنووسەکە پاشەکەوت بکە، بەڵگەکان زیاد بکە و کاتێک تەواو بوو بۆ پێداچوونەوەی LSevin بنێرە.",applicationsTitle:"داواکارییەکانی دابینکەر",applicationsDescription:"ئەو داواکارییانەی بە هەژماری LSevin ـی تۆ دەستپێکراون.",newApplication:"داواکاری نوێ",noApplications:"هیچ داواکارییەک نییە",noApplicationsDescription:"بۆ دروستکردن یان خاوەندارێتی شوێنی کاری دابینکەر دەست پێ بکە.",start:"دەستپێکردن",resume:"بەردەوامبوون",open:"کردنەوە",providerRequest:"داواکاری دابینکەر",providerType:"جۆری دابینکەر",chooseType:"جۆر هەڵبژێرە",legalName:"ناوی یاسایی",displayName:"ناوی پیشاندانی گشتی",contactPerson:"کەسی پەیوەندی",email:"ئیمەیڵ",phoneCode:"کۆدی وڵات",phone:"تەلەفۆن",website:"ماڵپەڕ",address:"ناونیشان",notes:"تێبینی زیاتر",businessLicense:"مۆڵەتی کار",identityEvidence:"ناسنامەی خاوەن یان نوێنەر",additionalEvidence:"بەڵگەی زیاتر",evidenceHelp:"پێش ناردن پێویستە لانیکەم یەک فایل لەلایەن داواکەرەوە بارکرابێت. فایلەکان تا پێداچوونەوەی بەڕێوەبەری ڕێپێدراوی LSevin تایبەت دەمێنن.",saveDraft:"پاشەکەوتی ڕەشنووس",submitApplication:"ناردنی داواکاری",draftSaved:"ڕەشنووس پاشەکەوت کرا.",correctionRequested:"LSevin داوای گۆڕانکاری کردووە. زانیارییە داواکراوەکان نوێ بکەرەوە و دووبارە بنێرە.",draft:"ڕەشنووس",submitted:"نێردراو",inReview:"لە پێداچوونەوەدا",approved:"پەسەندکراو",rejected:"ڕەتکراو",disabled:"ناچالاک",changesRequested:"گۆڕانکاری داواکراوە" },
  de: { newProviderTitle:"Anbieter werden",newProviderDescription:"Entwurf speichern, Nachweise anhängen und bei Vollständigkeit zur LSevin-Prüfung einreichen.",applicationsTitle:"Anbieteranträge",applicationsDescription:"Anträge, die mit Ihrem LSevin-Konto begonnen wurden.",newApplication:"Neuer Antrag",noApplications:"Keine Anträge",noApplicationsDescription:"Starten Sie das Onboarding, um einen Anbieter-Arbeitsbereich zu erstellen oder zu beanspruchen.",start:"Starten",resume:"Fortsetzen",open:"Öffnen",providerRequest:"Anbieterantrag",providerType:"Anbietertyp",chooseType:"Anbietertyp wählen",legalName:"Rechtlicher Name",displayName:"Öffentlicher Anzeigename",contactPerson:"Kontaktperson",email:"E-Mail",phoneCode:"Ländervorwahl",phone:"Telefon",website:"Website",address:"Adresse",notes:"Zusätzliche Hinweise",businessLicense:"Betriebs-/Gewerbelizenz",identityEvidence:"Identitätsnachweis des Inhabers oder Vertreters",additionalEvidence:"Zusätzlicher Nachweis",evidenceHelp:"Vor dem Absenden ist mindestens eine vom Antragsteller hochgeladene Datei erforderlich. Dateien bleiben bis zur Prüfung durch autorisierte LSevin-Administratoren privat.",saveDraft:"Entwurf speichern",submitApplication:"Antrag absenden",draftSaved:"Entwurf gespeichert.",correctionRequested:"LSevin hat Änderungen angefordert. Aktualisieren Sie die Angaben und senden Sie erneut.",draft:"Entwurf",submitted:"Eingereicht",inReview:"In Prüfung",approved:"Genehmigt",rejected:"Abgelehnt",disabled:"Deaktiviert",changesRequested:"Änderungen angefordert" },
  fr: { newProviderTitle:"Devenir prestataire",newProviderDescription:"Enregistrez un brouillon, joignez les justificatifs puis soumettez-le à LSevin lorsqu'il est complet.",applicationsTitle:"Demandes prestataire",applicationsDescription:"Demandes commencées avec votre compte LSevin.",newApplication:"Nouvelle demande",noApplications:"Aucune demande",noApplicationsDescription:"Commencez l'inscription pour créer ou revendiquer un espace prestataire.",start:"Commencer",resume:"Reprendre",open:"Ouvrir",providerRequest:"Demande prestataire",providerType:"Type de prestataire",chooseType:"Choisir le type",legalName:"Nom légal",displayName:"Nom public",contactPerson:"Contact",email:"E-mail",phoneCode:"Indicatif",phone:"Téléphone",website:"Site web",address:"Adresse",notes:"Notes complémentaires",businessLicense:"Licence d'activité",identityEvidence:"Identité du propriétaire ou représentant",additionalEvidence:"Justificatif supplémentaire",evidenceHelp:"Au moins un fichier appartenant au demandeur est requis avant soumission. Les fichiers restent privés jusqu'à leur examen par un administrateur LSevin autorisé.",saveDraft:"Enregistrer le brouillon",submitApplication:"Soumettre la demande",draftSaved:"Brouillon enregistré.",correctionRequested:"LSevin a demandé des modifications. Mettez à jour les informations demandées et soumettez à nouveau.",draft:"Brouillon",submitted:"Soumise",inReview:"En cours d'examen",approved:"Approuvée",rejected:"Rejetée",disabled:"Désactivée",changesRequested:"Modifications demandées" },
};

export function applicationStatusLabel(locale: PortalLocale, status: string) {
  const c = applicationCopy[locale];
  return ({ draft:c.draft, submitted:c.submitted, in_review:c.inReview, approved:c.approved, rejected:c.rejected, disabled:c.disabled, changes_requested:c.changesRequested } as Record<string,string>)[status] || status;
}
