//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LSevin.Modules.Identity.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class IdentityResource {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal IdentityResource() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("LSevin.Modules.Identity.Resources.IdentityResource", typeof(IdentityResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string Not_Confirmed_Error_Message {
            get {
                return ResourceManager.GetString("Not_Confirmed_Error_Message", resourceCulture);
            }
        }
        
        public static string User_Locked_Error_Message {
            get {
                return ResourceManager.GetString("User_Locked_Error_Message", resourceCulture);
            }
        }
        
        public static string Requires_Two_Factor_Error_Message {
            get {
                return ResourceManager.GetString("Requires_Two_Factor_Error_Message", resourceCulture);
            }
        }
        
        public static string Invalid_Credentials_Error_Message {
            get {
                return ResourceManager.GetString("Invalid_Credentials_Error_Message", resourceCulture);
            }
        }
        
        public static string Token {
            get {
                return ResourceManager.GetString("Token", resourceCulture);
            }
        }
        
        public static string Email_Already_Confirmed_Error_Message {
            get {
                return ResourceManager.GetString("Email_Already_Confirmed_Error_Message", resourceCulture);
            }
        }
        
        public static string Email_Verification_Invalid_Error_Message {
            get {
                return ResourceManager.GetString("Email_Verification_Invalid_Error_Message", resourceCulture);
            }
        }
        
        public static string Verification_Code_Expired_Error_Message {
            get {
                return ResourceManager.GetString("Verification_Code_Expired_Error_Message", resourceCulture);
            }
        }
        
        public static string User_State_Cannot_Be_Changed {
            get {
                return ResourceManager.GetString("User_State_Cannot_Be_Changed", resourceCulture);
            }
        }
        
        public static string Cannot_Update_State_Of_Admin {
            get {
                return ResourceManager.GetString("Cannot_Update_State_Of_Admin", resourceCulture);
            }
        }
        
        public static string Password_Match_Error_Message {
            get {
                return ResourceManager.GetString("Password_Match_Error_Message", resourceCulture);
            }
        }

        public static string Otp_Verification_Message {
            get {
                return ResourceManager.GetString("Otp_Verification_Message", resourceCulture);
            }
        }
    }
}
