import { normalizePortalLocale } from "@core/i18n/config";

const copy = {
  fa: {
    title:"مدیریت رزروها",description:"رزروهای مرکز، تخصیص پرسنل، اسناد، یادداشت‌ها و تغییرات زمان یا لغو را مدیریت کنید.",bookings:"رزروها",open:"باز/آینده",assigned:"تخصیص‌یافته",paymentAttention:"نیازمند بررسی پرداخت",providerList:"فهرست رزروهای مرکز",booking:"رزرو",dateTime:"تاریخ/ساعت",status:"وضعیت",total:"مبلغ",documents:"اسناد رزرو",noDocuments:"برای رزروهای فعلی سندی ثبت نشده است.",openDocument:"مشاهده سند",operations:"عملیات",staff:"پرسنل",resource:"منبع",assignmentNote:"یادداشت تخصیص",assign:"تخصیص پرسنل/منبع",newStatus:"وضعیت جدید",providerNote:"یادداشت مرکز",updateStatus:"به‌روزرسانی وضعیت",visibility:"نمایش",internal:"داخلی",customerVisible:"قابل مشاهده برای مشتری",note:"یادداشت",addNote:"افزودن یادداشت",reschedule:"تغییر زمان رزرو",requestedDate:"تاریخ جدید",requestedTime:"ساعت جدید",reason:"دلیل",rescheduleNow:"ثبت تغییر زمان",cancel:"لغو رزرو",cancelNow:"لغو رزرو",changeRequests:"درخواست‌های تغییر",approve:"تأیید",reject:"رد",reviewNote:"یادداشت بررسی",noRequests:"درخواست تغییر بازی وجود ندارد.",myBookings:"رزروهای تخصیص‌یافته من",myDescription:"فقط رزروهایی که به پروفایل تأییدشده شما تخصیص داده شده‌اند نمایش داده می‌شوند.",myDocuments:"اسناد رزروهای من",requestChange:"درخواست تغییر رزرو",requestType:"نوع درخواست",requestReschedule:"درخواست تغییر زمان",requestCancel:"درخواست لغو",submitRequest:"ارسال درخواست",requestHistory:"سوابق درخواست‌های من",noBookings:"رزروی به شما تخصیص داده نشده است.",selectBooking:"انتخاب رزرو",noStaff:"بدون پرسنل",noResource:"بدون منبع",unassigned:"بدون تخصیص",notes:"یادداشت",customer:"مشتری",paymentUnknown:"وضعیت پرداخت نامشخص",fixedSlotHelp:"تغییر زمان فقط برای رزروهای دارای اسلات ثابت انجام می‌شود و پیش از ثبت، ساعات کاری و تداخل/ظرفیت مرکز، خدمت، پرسنل، منبع و رزروهای مشتری بررسی می‌شود."},
  en: {
    title:"Booking Management",description:"Manage provider bookings, staff assignment, documents, notes, rescheduling and cancellations.",bookings:"Bookings",open:"Upcoming/open",assigned:"Assigned",paymentAttention:"Payment attention",providerList:"Provider booking list",booking:"Booking",dateTime:"Date/time",status:"Status",total:"Total",documents:"Booking documents",noDocuments:"No documents are attached to the current bookings.",openDocument:"Open document",operations:"Operations",staff:"Staff",resource:"Resource",assignmentNote:"Assignment note",assign:"Assign staff/resource",newStatus:"New status",providerNote:"Provider note",updateStatus:"Update safe status",visibility:"Visibility",internal:"Internal",customerVisible:"Customer visible",note:"Note",addNote:"Add note",reschedule:"Reschedule booking",requestedDate:"New date",requestedTime:"New time",reason:"Reason",rescheduleNow:"Reschedule booking",cancel:"Cancel booking",cancelNow:"Cancel booking",changeRequests:"Change requests",approve:"Approve",reject:"Reject",reviewNote:"Review note",noRequests:"No open booking-change requests.",myBookings:"My assigned bookings",myDescription:"Only bookings assigned to your approved staff profile are shown.",myDocuments:"Documents for my assigned bookings",requestChange:"Request booking change",requestType:"Request type",requestReschedule:"Request reschedule",requestCancel:"Request cancellation",submitRequest:"Submit request",requestHistory:"My request history",noBookings:"No assigned bookings yet.",selectBooking:"Select booking",noStaff:"No staff",noResource:"No resource",unassigned:"Unassigned",notes:"notes",customer:"Customer",paymentUnknown:"payment unknown",fixedSlotHelp:"Rescheduling is limited to fixed-slot bookings and validates operating hours plus provider, service, staff, resource and customer conflicts/capacity before commit."},
  ar: {
    title:"إدارة الحجوزات",description:"إدارة حجوزات المزوّد وتعيين الموظفين والمستندات والملاحظات وإعادة الجدولة والإلغاء.",bookings:"الحجوزات",open:"القادمة/المفتوحة",assigned:"المعيّنة",paymentAttention:"بحاجة لمراجعة الدفع",providerList:"قائمة حجوزات المزوّد",booking:"الحجز",dateTime:"التاريخ/الوقت",status:"الحالة",total:"الإجمالي",documents:"مستندات الحجز",noDocuments:"لا توجد مستندات مرفقة بالحجوزات الحالية.",openDocument:"فتح المستند",operations:"العمليات",staff:"الموظف",resource:"المورد",assignmentNote:"ملاحظة التعيين",assign:"تعيين موظف/مورد",newStatus:"الحالة الجديدة",providerNote:"ملاحظة المزوّد",updateStatus:"تحديث الحالة",visibility:"الظهور",internal:"داخلي",customerVisible:"مرئي للعميل",note:"ملاحظة",addNote:"إضافة ملاحظة",reschedule:"إعادة جدولة الحجز",requestedDate:"التاريخ الجديد",requestedTime:"الوقت الجديد",reason:"السبب",rescheduleNow:"إعادة الجدولة",cancel:"إلغاء الحجز",cancelNow:"إلغاء الحجز",changeRequests:"طلبات التغيير",approve:"موافقة",reject:"رفض",reviewNote:"ملاحظة المراجعة",noRequests:"لا توجد طلبات تغيير مفتوحة.",myBookings:"حجوزاتي المعيّنة",myDescription:"تظهر فقط الحجوزات المعيّنة إلى ملف الموظف المعتمد الخاص بك.",myDocuments:"مستندات حجوزاتي",requestChange:"طلب تغيير الحجز",requestType:"نوع الطلب",requestReschedule:"طلب إعادة الجدولة",requestCancel:"طلب الإلغاء",submitRequest:"إرسال الطلب",requestHistory:"سجل طلباتي",noBookings:"لا توجد حجوزات معيّنة بعد.",selectBooking:"اختر الحجز",noStaff:"بدون موظف",noResource:"بدون مورد",unassigned:"غير معيّن",notes:"ملاحظات",customer:"العميل",paymentUnknown:"حالة الدفع غير معروفة",fixedSlotHelp:"إعادة الجدولة مخصّصة للحجوزات ذات الموعد الثابت، ويتم قبل الحفظ التحقق من ساعات العمل وتعارض/سعة المزوّد والخدمة والموظف والمورد وحجوزات العميل."},
  tr: {
    title:"Rezervasyon Yönetimi",description:"Sağlayıcı rezervasyonlarını, personel atamalarını, belgeleri, notları, yeniden planlama ve iptalleri yönetin.",bookings:"Rezervasyonlar",open:"Yaklaşan/açık",assigned:"Atanmış",paymentAttention:"Ödeme incelemesi",providerList:"Sağlayıcı rezervasyon listesi",booking:"Rezervasyon",dateTime:"Tarih/saat",status:"Durum",total:"Toplam",documents:"Rezervasyon belgeleri",noDocuments:"Mevcut rezervasyonlara eklenmiş belge yok.",openDocument:"Belgeyi aç",operations:"İşlemler",staff:"Personel",resource:"Kaynak",assignmentNote:"Atama notu",assign:"Personel/kaynak ata",newStatus:"Yeni durum",providerNote:"Sağlayıcı notu",updateStatus:"Durumu güncelle",visibility:"Görünürlük",internal:"Dahili",customerVisible:"Müşteriye görünür",note:"Not",addNote:"Not ekle",reschedule:"Rezervasyonu yeniden planla",requestedDate:"Yeni tarih",requestedTime:"Yeni saat",reason:"Gerekçe",rescheduleNow:"Yeniden planla",cancel:"Rezervasyonu iptal et",cancelNow:"İptal et",changeRequests:"Değişiklik talepleri",approve:"Onayla",reject:"Reddet",reviewNote:"İnceleme notu",noRequests:"Açık değişiklik talebi yok.",myBookings:"Atanmış rezervasyonlarım",myDescription:"Yalnızca onaylı personel profilinize atanmış rezervasyonlar gösterilir.",myDocuments:"Rezervasyon belgelerim",requestChange:"Rezervasyon değişikliği iste",requestType:"Talep türü",requestReschedule:"Yeniden planlama iste",requestCancel:"İptal iste",submitRequest:"Talebi gönder",requestHistory:"Talep geçmişim",noBookings:"Henüz atanmış rezervasyon yok.",selectBooking:"Rezervasyon seç",noStaff:"Personel yok",noResource:"Kaynak yok",unassigned:"Atanmamış",notes:"not",customer:"Müşteri",paymentUnknown:"ödeme bilinmiyor",fixedSlotHelp:"Yeniden planlama sabit zamanlı rezervasyonlarla sınırlıdır; kaydetmeden önce çalışma saatleri ile sağlayıcı, hizmet, personel, kaynak ve müşteri çakışma/kapasitesi doğrulanır."},
  es: {
    title:"Gestión de reservas",description:"Gestiona reservas del proveedor, asignaciones, documentos, notas, reprogramaciones y cancelaciones.",bookings:"Reservas",open:"Próximas/abiertas",assigned:"Asignadas",paymentAttention:"Revisión de pago",providerList:"Lista de reservas del proveedor",booking:"Reserva",dateTime:"Fecha/hora",status:"Estado",total:"Total",documents:"Documentos de reserva",noDocuments:"No hay documentos adjuntos a las reservas actuales.",openDocument:"Abrir documento",operations:"Operaciones",staff:"Personal",resource:"Recurso",assignmentNote:"Nota de asignación",assign:"Asignar personal/recurso",newStatus:"Nuevo estado",providerNote:"Nota del proveedor",updateStatus:"Actualizar estado",visibility:"Visibilidad",internal:"Interno",customerVisible:"Visible al cliente",note:"Nota",addNote:"Añadir nota",reschedule:"Reprogramar reserva",requestedDate:"Nueva fecha",requestedTime:"Nueva hora",reason:"Motivo",rescheduleNow:"Reprogramar",cancel:"Cancelar reserva",cancelNow:"Cancelar",changeRequests:"Solicitudes de cambio",approve:"Aprobar",reject:"Rechazar",reviewNote:"Nota de revisión",noRequests:"No hay solicitudes de cambio abiertas.",myBookings:"Mis reservas asignadas",myDescription:"Solo se muestran reservas asignadas a tu perfil de personal aprobado.",myDocuments:"Documentos de mis reservas",requestChange:"Solicitar cambio",requestType:"Tipo de solicitud",requestReschedule:"Solicitar reprogramación",requestCancel:"Solicitar cancelación",submitRequest:"Enviar solicitud",requestHistory:"Historial de solicitudes",noBookings:"Aún no hay reservas asignadas.",selectBooking:"Seleccionar reserva",noStaff:"Sin personal",noResource:"Sin recurso",unassigned:"Sin asignar",notes:"notas",customer:"Cliente",paymentUnknown:"pago desconocido",fixedSlotHelp:"La reprogramación se limita a reservas con horario fijo y, antes de guardar, valida horarios y conflictos/capacidad del proveedor, servicio, personal, recurso y cliente."},
  ku: {
    title:"بەڕێوەبردنی حجز",description:"حجزەکانی دابینکەر، دیاریکردنی ستاف، بەڵگەنامە، تێبینی، گۆڕینی کات و هەڵوەشاندنەوە بەڕێوەببە.",bookings:"حجزەکان",open:"داهاتوو/کراوە",assigned:"دیاریکراو",paymentAttention:"پێویستی بە پشکنینی پارەدان",providerList:"لیستی حجزەکانی دابینکەر",booking:"حجز",dateTime:"بەروار/کات",status:"دۆخ",total:"کۆی گشتی",documents:"بەڵگەنامەکانی حجز",noDocuments:"هیچ بەڵگەنامەیەک پەیوەست نەکراوە.",openDocument:"کردنەوەی بەڵگەنامە",operations:"کردارەکان",staff:"ستاف",resource:"سەرچاوە",assignmentNote:"تێبینی دیاریکردن",assign:"دیاریکردنی ستاف/سەرچاوە",newStatus:"دۆخی نوێ",providerNote:"تێبینی دابینکەر",updateStatus:"نوێکردنەوەی دۆخ",visibility:"بینراوی",internal:"ناوخۆیی",customerVisible:"بینراو بۆ کڕیار",note:"تێبینی",addNote:"زیادکردنی تێبینی",reschedule:"گۆڕینی کاتی حجز",requestedDate:"بەرواری نوێ",requestedTime:"کاتی نوێ",reason:"هۆکار",rescheduleNow:"گۆڕینی کات",cancel:"هەڵوەشاندنەوەی حجز",cancelNow:"هەڵوەشاندنەوە",changeRequests:"داواکارییەکانی گۆڕان",approve:"پەسەندکردن",reject:"ڕەتکردنەوە",reviewNote:"تێبینی پشکنین",noRequests:"داواکاری گۆڕانی کراوە نییە.",myBookings:"حجزە دیاریکراوەکانم",myDescription:"تەنها حجزەکانی دیاریکراو بۆ پرۆفایلی پەسەندکراوی تۆ پیشان دەدرێن.",myDocuments:"بەڵگەنامەکانی حجزەکانم",requestChange:"داوای گۆڕینی حجز",requestType:"جۆری داواکاری",requestReschedule:"داوای گۆڕینی کات",requestCancel:"داوای هەڵوەشاندنەوە",submitRequest:"ناردنی داواکاری",requestHistory:"مێژووی داواکارییەکانم",noBookings:"هێشتا حجزێک دیاری نەکراوە.",selectBooking:"هەڵبژاردنی حجز",noStaff:"بێ ستاف",noResource:"بێ سەرچاوە",unassigned:"دیاری نەکراو",notes:"تێبینی",customer:"کڕیار",paymentUnknown:"دۆخی پارەدان نادیارە",fixedSlotHelp:"گۆڕینی کات تەنها بۆ حجزە کاتی دیاریکراوەکانە و پێش تۆمارکردن کاتی کار و تێکچوون/ظرفیتی دابینکەر، خزمەتگوزاری، ستاف، سەرچاوە و حجزەکانی کڕیار پشکنین دەکرێت."},
  de: {
    title:"Buchungsverwaltung",description:"Verwalten Sie Anbieterbuchungen, Personalzuweisungen, Dokumente, Notizen, Umbuchungen und Stornierungen.",bookings:"Buchungen",open:"Bevorstehend/offen",assigned:"Zugewiesen",paymentAttention:"Zahlung prüfen",providerList:"Buchungsliste des Anbieters",booking:"Buchung",dateTime:"Datum/Uhrzeit",status:"Status",total:"Gesamt",documents:"Buchungsdokumente",noDocuments:"Den aktuellen Buchungen sind keine Dokumente beigefügt.",openDocument:"Dokument öffnen",operations:"Aktionen",staff:"Personal",resource:"Ressource",assignmentNote:"Zuweisungsnotiz",assign:"Personal/Ressource zuweisen",newStatus:"Neuer Status",providerNote:"Anbieternotiz",updateStatus:"Status aktualisieren",visibility:"Sichtbarkeit",internal:"Intern",customerVisible:"Für Kunden sichtbar",note:"Notiz",addNote:"Notiz hinzufügen",reschedule:"Buchung verschieben",requestedDate:"Neues Datum",requestedTime:"Neue Uhrzeit",reason:"Grund",rescheduleNow:"Umbuchen",cancel:"Buchung stornieren",cancelNow:"Stornieren",changeRequests:"Änderungsanfragen",approve:"Genehmigen",reject:"Ablehnen",reviewNote:"Prüfnotiz",noRequests:"Keine offenen Änderungsanfragen.",myBookings:"Meine zugewiesenen Buchungen",myDescription:"Es werden nur Buchungen angezeigt, die Ihrem genehmigten Mitarbeiterprofil zugewiesen sind.",myDocuments:"Dokumente meiner Buchungen",requestChange:"Buchungsänderung anfragen",requestType:"Anfragetyp",requestReschedule:"Umbuchung anfragen",requestCancel:"Stornierung anfragen",submitRequest:"Anfrage senden",requestHistory:"Meine Anfragehistorie",noBookings:"Noch keine Buchungen zugewiesen.",selectBooking:"Buchung auswählen",noStaff:"Kein Personal",noResource:"Keine Ressource",unassigned:"Nicht zugewiesen",notes:"Notizen",customer:"Kunde",paymentUnknown:"Zahlung unbekannt",fixedSlotHelp:"Umbuchungen sind auf Buchungen mit festem Zeitfenster beschränkt und prüfen vor dem Speichern Öffnungszeiten sowie Anbieter-, Service-, Personal-, Ressourcen- und Kundenkonflikte/Kapazitäten."},
  fr: {
    title:"Gestion des réservations",description:"Gérez les réservations du prestataire, les affectations, documents, notes, replanifications et annulations.",bookings:"Réservations",open:"À venir/ouvertes",assigned:"Affectées",paymentAttention:"Paiement à vérifier",providerList:"Liste des réservations du prestataire",booking:"Réservation",dateTime:"Date/heure",status:"Statut",total:"Total",documents:"Documents de réservation",noDocuments:"Aucun document n’est joint aux réservations actuelles.",openDocument:"Ouvrir le document",operations:"Opérations",staff:"Personnel",resource:"Ressource",assignmentNote:"Note d’affectation",assign:"Affecter personnel/ressource",newStatus:"Nouveau statut",providerNote:"Note du prestataire",updateStatus:"Mettre à jour le statut",visibility:"Visibilité",internal:"Interne",customerVisible:"Visible par le client",note:"Note",addNote:"Ajouter une note",reschedule:"Replanifier la réservation",requestedDate:"Nouvelle date",requestedTime:"Nouvelle heure",reason:"Motif",rescheduleNow:"Replanifier",cancel:"Annuler la réservation",cancelNow:"Annuler",changeRequests:"Demandes de modification",approve:"Approuver",reject:"Refuser",reviewNote:"Note de validation",noRequests:"Aucune demande de modification ouverte.",myBookings:"Mes réservations affectées",myDescription:"Seules les réservations affectées à votre profil de personnel approuvé sont affichées.",myDocuments:"Documents de mes réservations",requestChange:"Demander une modification",requestType:"Type de demande",requestReschedule:"Demander une replanification",requestCancel:"Demander une annulation",submitRequest:"Envoyer la demande",requestHistory:"Historique de mes demandes",noBookings:"Aucune réservation affectée pour le moment.",selectBooking:"Sélectionner une réservation",noStaff:"Aucun personnel",noResource:"Aucune ressource",unassigned:"Non affectée",notes:"notes",customer:"Client",paymentUnknown:"paiement inconnu",fixedSlotHelp:"La replanification est limitée aux réservations à créneau fixe et vérifie avant validation les horaires ainsi que les conflits/capacités du prestataire, service, personnel, ressource et client."},
} as const;

const statusCopy: Record<string, Partial<Record<keyof typeof copy, string>>> = {
  Confirmed:{fa:"تأییدشده",ar:"مؤكد",tr:"Onaylandı",es:"Confirmada",ku:"پەسەندکراو",de:"Bestätigt",fr:"Confirmée"},
  InProgress:{fa:"در حال انجام",ar:"قيد التنفيذ",tr:"Devam ediyor",es:"En curso",ku:"لە جێبەجێکردندا",de:"In Bearbeitung",fr:"En cours"},
  Completed:{fa:"تکمیل‌شده",ar:"مكتمل",tr:"Tamamlandı",es:"Completada",ku:"تەواوبوو",de:"Abgeschlossen",fr:"Terminée"},
  Cancelled:{fa:"لغوشده",ar:"ملغي",tr:"İptal edildi",es:"Cancelada",ku:"هەڵوەشاوەتەوە",de:"Storniert",fr:"Annulée"},
  NoShow:{fa:"عدم مراجعه",ar:"لم يحضر",tr:"Gelmedi",es:"No se presentó",ku:"ئامادە نەبوو",de:"Nicht erschienen",fr:"Absent"},
  ProviderReview:{fa:"بررسی مرکز",ar:"مراجعة المزوّد",tr:"Sağlayıcı incelemesi",es:"Revisión del proveedor",ku:"پشکنینی دابینکەر",de:"Anbieterprüfung",fr:"Revue prestataire"},
  Draft:{fa:"پیش‌نویس",ar:"مسودة",tr:"Taslak",es:"Borrador",ku:"ڕەشنووس",de:"Entwurf",fr:"Brouillon"},
};

export function bookingManagementCopy(locale?: string) {
  return copy[normalizePortalLocale(locale).locale];
}

export function bookingStatusLabel(status: string | null | undefined, locale?: string) {
  const normalized = normalizePortalLocale(locale).locale;
  if (!status) return "—";
  if (normalized === "en") return status;
  return statusCopy[status]?.[normalized] || status;
}
