import type { AdminEntityConfig, MarketingLoyaltyEntityKey } from "./types";

export const MARKETING_LOYALTY_TRANSLATION_KEY = "MarketingLoyaltyAdmin";

export const DISCOUNT_TYPE_OPTIONS = [
  { value: "Percent", label: "Percent" },
  { value: "Fixed", label: "Fixed amount" },
  { value: "Cashback", label: "Cashback" },
  { value: "FreeService", label: "Free service" },
];

export const CUSTOMER_COUPON_STATUS_OPTIONS = [
  { value: "Available", label: "Available" },
  { value: "Redeemed", label: "Redeemed" },
  { value: "Expired", label: "Expired" },
  { value: "Cancelled", label: "Cancelled" },
];

export const LEDGER_ENTRY_TYPE_OPTIONS = [
  { value: "Earn", label: "Earn" },
  { value: "Redeem", label: "Redeem" },
  { value: "Refund", label: "Refund" },
  { value: "Adjustment", label: "Manual adjustment" },
  { value: "Referral", label: "Referral reward" },
  { value: "Cashback", label: "Cashback" },
];

export const REFERRAL_STATUS_OPTIONS = [
  { value: "Pending", label: "Pending" },
  { value: "Qualified", label: "Qualified" },
  { value: "Rewarded", label: "Rewarded" },
  { value: "Rejected", label: "Rejected" },
  { value: "Cancelled", label: "Cancelled" },
];

export const ENTITY_CONFIGS: Record<MarketingLoyaltyEntityKey, AdminEntityConfig> = {
  "marketing-offers": {
    key: "marketing-offers",
    title: "Marketing offers",
    description: "Manage service-specific offers, featured campaigns, promo codes, usage limits, and expiry windows.",
    routeBase: "/admin/marketing/offers",
    schemaName: "marketing",
    tableName: "offers",
    primaryKey: "id",
    primaryKeyKind: "integer",
    createTitle: "Create marketing offer",
    updateTitle: "Update marketing offer",
    searchableColumns: ["title", "subtitle", "code"],
    updateTimestampColumn: undefined,
    listColumns: [
      { key: "title", label: "Offer" },
      { key: "providerServiceLabel", label: "Service" },
      { key: "discountPercent", label: "Discount", type: "percent" },
      { key: "validUntil", label: "Valid until", type: "datetime" },
      { key: "code", label: "Code", type: "badge" },
      { key: "usedCount", label: "Used", type: "number" },
      { key: "isFeatured", label: "Featured", type: "boolean" },
      { key: "isActive", label: "Active", type: "boolean" },
    ],
    fields: [
      { name: "providerServiceId", column: "provider_service_id", label: "Provider service", kind: "select", optionsKey: "providerServices", lookupType: "providerServices", required: true },
      { name: "title", column: "title", label: "Title", kind: "text", required: true, placeholder: "Summer beauty offer" },
      { name: "subtitle", column: "subtitle", label: "Subtitle", kind: "richtext", placeholder: "Short campaign message", helperText: "Stored as text. If the value is Lexical JSON, lists render it with LexicalRenderer." },
      { name: "discountPercent", column: "discount_percent", label: "Discount percent", kind: "number", required: true, min: 0, max: 100, step: 0.01, defaultValue: 0 },
      { name: "validUntil", column: "valid_until", label: "Valid until", kind: "datetime", required: true },
      { name: "code", column: "code", label: "Promo code", kind: "text", placeholder: "LSEVIN20" },
      { name: "usageLimit", column: "usage_limit", label: "Usage limit", kind: "integer", min: 0, placeholder: "Leave empty for unlimited" },
      { name: "usedCount", column: "used_count", label: "Used count", kind: "integer", min: 0, defaultValue: 0 },
      { name: "isFeatured", column: "is_featured", label: "Featured offer", kind: "boolean", defaultValue: false },
      { name: "isActive", column: "is_active", label: "Active", kind: "boolean", defaultValue: true },
    ],
  },
  "loyalty-tiers": {
    key: "loyalty-tiers",
    title: "Loyalty tiers",
    description: "Define member tiers, minimum points, cashback percent, colors, icons, and benefit JSON.",
    routeBase: "/admin/loyalty/tiers",
    schemaName: "loyalty",
    tableName: "tiers",
    primaryKey: "id",
    primaryKeyKind: "uuid",
    createTitle: "Create loyalty tier",
    updateTitle: "Update loyalty tier",
    searchableColumns: ["name", "icon"],
    updateTimestampColumn: "last_modified_date",
    listColumns: [
      { key: "name", label: "Tier" },
      { key: "minPoints", label: "Min points", type: "number" },
      { key: "cashbackPercent", label: "Cashback", type: "percent" },
      { key: "icon", label: "Icon" },
      { key: "accountCount", label: "Accounts", type: "number" },
      { key: "lastModifiedDate", label: "Updated", type: "datetime" },
    ],
    fields: [
      { name: "name", column: "name", label: "Name", kind: "text", required: true, placeholder: "Gold" },
      { name: "minPoints", column: "min_points", label: "Minimum points", kind: "integer", required: true, min: 0, defaultValue: 0 },
      { name: "cashbackPercent", column: "cashback_percent", label: "Cashback percent", kind: "number", required: true, min: 0, max: 100, step: 0.01, defaultValue: 0 },
      { name: "benefits", column: "benefits", label: "Benefits JSON", kind: "json", required: true, defaultValue: ["Priority support"], helperText: "JSON array. Example: [\"VIP support\", \"5% cashback\"]" },
      { name: "colorFrom", column: "color_from", label: "Gradient color from", kind: "color", placeholder: "#084132" },
      { name: "colorTo", column: "color_to", label: "Gradient color to", kind: "color", placeholder: "#eac074" },
      { name: "icon", column: "icon", label: "Icon", kind: "text", placeholder: "Crown" },
    ],
  },
  "loyalty-accounts": {
    key: "loyalty-accounts",
    title: "Loyalty accounts",
    description: "Manage each customer’s point balance, lifetime points, current tier, and referral code.",
    routeBase: "/admin/loyalty/accounts",
    schemaName: "loyalty",
    tableName: "accounts",
    primaryKey: "customer_id",
    primaryKeyKind: "uuid",
    createTitle: "Create loyalty account",
    updateTitle: "Update loyalty account",
    searchableColumns: ["referral_code"],
    updateTimestampColumn: "last_modified_date",
    listColumns: [
      { key: "customerLabel", label: "Customer" },
      { key: "pointsBalance", label: "Balance", type: "number" },
      { key: "lifetimePoints", label: "Lifetime", type: "number" },
      { key: "tierName", label: "Tier", type: "badge" },
      { key: "referralCode", label: "Referral code", type: "badge" },
      { key: "lastModifiedDate", label: "Updated", type: "datetime" },
    ],
    fields: [
      { name: "customerId", column: "customer_id", label: "Customer", kind: "select", optionsKey: "customers", lookupType: "customers", required: true, hiddenOnUpdate: true },
      { name: "pointsBalance", column: "points_balance", label: "Points balance", kind: "integer", required: true, defaultValue: 0 },
      { name: "lifetimePoints", column: "lifetime_points", label: "Lifetime points", kind: "integer", required: true, min: 0, defaultValue: 0 },
      { name: "currentTierId", column: "current_tier_id", label: "Current tier", kind: "select", optionsKey: "tiers", lookupType: "loyaltyTiers" },
      { name: "referralCode", column: "referral_code", label: "Referral code", kind: "text", required: true, placeholder: "DANIAL2026" },
    ],
  },
  "loyalty-coupons": {
    key: "loyalty-coupons",
    title: "Loyalty coupons",
    description: "Create loyalty coupons with discount rules, optional provider service targeting, and usage limits.",
    routeBase: "/admin/loyalty/coupons",
    schemaName: "loyalty",
    tableName: "coupons",
    primaryKey: "id",
    primaryKeyKind: "uuid",
    createTitle: "Create loyalty coupon",
    updateTitle: "Update loyalty coupon",
    searchableColumns: ["code", "title", "description", "discount_type"],
    updateTimestampColumn: "last_modified_date",
    listColumns: [
      { key: "code", label: "Code", type: "badge" },
      { key: "title", label: "Title" },
      { key: "discountType", label: "Type", type: "badge" },
      { key: "discountValue", label: "Value", type: "number" },
      { key: "minPurchase", label: "Min purchase", type: "currency" },
      { key: "providerServiceLabel", label: "Service" },
      { key: "expiresAt", label: "Expires", type: "datetime" },
      { key: "isActive", label: "Active", type: "boolean" },
    ],
    fields: [
      { name: "code", column: "code", label: "Coupon code", kind: "text", required: true, placeholder: "LOYALTY25" },
      { name: "title", column: "title", label: "Title", kind: "text", required: true },
      { name: "description", column: "description", label: "Description", kind: "richtext", helperText: "Stored as text. If the value is Lexical JSON, lists render it with LexicalRenderer." },
      { name: "discountType", column: "discount_type", label: "Discount type", kind: "select", staticOptions: DISCOUNT_TYPE_OPTIONS, required: true },
      { name: "discountValue", column: "discount_value", label: "Discount value", kind: "number", required: true, min: 0, step: 0.01, defaultValue: 0 },
      { name: "minPurchase", column: "min_purchase", label: "Minimum purchase", kind: "number", min: 0, step: 0.01, defaultValue: 0 },
      { name: "startsAt", column: "starts_at", label: "Starts at", kind: "datetime" },
      { name: "expiresAt", column: "expires_at", label: "Expires at", kind: "datetime" },
      { name: "usageLimit", column: "usage_limit", label: "Usage limit", kind: "integer", min: 0 },
      { name: "providerServiceId", column: "provider_service_id", label: "Provider service", kind: "select", optionsKey: "providerServices", lookupType: "providerServices", helperText: "Optional. Leave empty to make this coupon global." },
      { name: "isActive", column: "is_active", label: "Active", kind: "boolean", defaultValue: true },
    ],
  },
  "loyalty-customer-coupons": {
    key: "loyalty-customer-coupons",
    title: "Customer coupons",
    description: "Assign coupons to customers and track availability, redemption date, and booking linkage.",
    routeBase: "/admin/loyalty/customer-coupons",
    schemaName: "loyalty",
    tableName: "customer_coupons",
    primaryKey: "id",
    primaryKeyKind: "uuid",
    createTitle: "Assign coupon to customer",
    updateTitle: "Update assigned coupon",
    searchableColumns: ["status"],
    updateTimestampColumn: undefined,
    listColumns: [
      { key: "customerLabel", label: "Customer" },
      { key: "couponLabel", label: "Coupon" },
      { key: "status", label: "Status", type: "badge" },
      { key: "assignedAt", label: "Assigned", type: "datetime" },
      { key: "redeemedAt", label: "Redeemed", type: "datetime" },
      { key: "bookingLabel", label: "Booking" },
    ],
    fields: [
      { name: "customerId", column: "customer_id", label: "Customer", kind: "select", optionsKey: "customers", lookupType: "customers", required: true },
      { name: "couponId", column: "coupon_id", label: "Coupon", kind: "select", optionsKey: "loyaltyCoupons", lookupType: "loyaltyCoupons", required: true },
      { name: "status", column: "status", label: "Status", kind: "select", staticOptions: CUSTOMER_COUPON_STATUS_OPTIONS, required: true, defaultValue: "Available" },
      { name: "assignedAt", column: "assigned_at", label: "Assigned at", kind: "datetime", defaultValue: "now" },
      { name: "redeemedAt", column: "redeemed_at", label: "Redeemed at", kind: "datetime" },
      { name: "bookingId", column: "booking_id", label: "Booking", kind: "select", optionsKey: "bookings", lookupType: "bookings" },
    ],
  },
  "loyalty-ledger": {
    key: "loyalty-ledger",
    title: "Loyalty ledger",
    description: "Append-only points and reward-money history. New entries automatically update the account balance.",
    routeBase: "/admin/loyalty/ledger",
    schemaName: "loyalty",
    tableName: "ledger",
    primaryKey: "id",
    primaryKeyKind: "uuid",
    createTitle: "Create ledger entry",
    updateTitle: "Ledger entry",
    appendOnly: true,
    editable: false,
    deletable: false,
    searchableColumns: ["entry_type", "description"],
    listColumns: [
      { key: "customerLabel", label: "Customer" },
      { key: "entryType", label: "Type", type: "badge" },
      { key: "pointsDelta", label: "Points", type: "number" },
      { key: "moneyDelta", label: "Money", type: "currency" },
      { key: "description", label: "Description", type: "richtext" },
      { key: "bookingLabel", label: "Booking" },
      { key: "createDate", label: "Created", type: "datetime" },
    ],
    fields: [
      { name: "customerId", column: "customer_id", label: "Customer", kind: "select", optionsKey: "customers", lookupType: "customers", required: true },
      { name: "bookingId", column: "booking_id", label: "Booking", kind: "select", optionsKey: "bookings", lookupType: "bookings" },
      { name: "entryType", column: "entry_type", label: "Entry type", kind: "select", staticOptions: LEDGER_ENTRY_TYPE_OPTIONS, required: true, defaultValue: "Adjustment" },
      { name: "pointsDelta", column: "points_delta", label: "Points delta", kind: "integer", required: true, defaultValue: 0, helperText: "Use positive values to grant points and negative values to redeem/deduct." },
      { name: "moneyDelta", column: "money_delta", label: "Money delta", kind: "number", step: 0.01 },
      { name: "description", column: "description", label: "Description", kind: "richtext", required: true, helperText: "Stored as text. If the value is Lexical JSON, lists render it with LexicalRenderer." },
      { name: "metadata", column: "metadata", label: "Metadata JSON", kind: "json", defaultValue: {}, helperText: "Optional JSON object for audit details." },
    ],
  },
  "loyalty-referrals": {
    key: "loyalty-referrals",
    title: "Referrals",
    description: "Track referral invitations, referred customers, qualification status, and reward values.",
    routeBase: "/admin/loyalty/referrals",
    schemaName: "loyalty",
    tableName: "referrals",
    primaryKey: "id",
    primaryKeyKind: "uuid",
    createTitle: "Create referral",
    updateTitle: "Update referral",
    searchableColumns: ["referral_code", "status"],
    listColumns: [
      { key: "referrerLabel", label: "Referrer" },
      { key: "referredLabel", label: "Referred" },
      { key: "referralCode", label: "Code", type: "badge" },
      { key: "status", label: "Status", type: "badge" },
      { key: "rewardAmount", label: "Reward", type: "currency" },
      { key: "rewardPoints", label: "Reward points", type: "number" },
      { key: "qualifiedAt", label: "Qualified", type: "datetime" },
      { key: "createDate", label: "Created", type: "datetime" },
    ],
    fields: [
      { name: "referrerCustomerId", column: "referrer_customer_id", label: "Referrer customer", kind: "select", optionsKey: "customers", lookupType: "customers", required: true },
      { name: "referredCustomerId", column: "referred_customer_id", label: "Referred customer", kind: "select", optionsKey: "customers", lookupType: "customers" },
      { name: "referralCode", column: "referral_code", label: "Referral code", kind: "text", required: true },
      { name: "status", column: "status", label: "Status", kind: "select", staticOptions: REFERRAL_STATUS_OPTIONS, required: true, defaultValue: "Pending" },
      { name: "rewardAmount", column: "reward_amount", label: "Reward amount", kind: "number", min: 0, step: 0.01, defaultValue: 0 },
      { name: "rewardPoints", column: "reward_points", label: "Reward points", kind: "integer", min: 0, defaultValue: 0 },
      { name: "qualifiedAt", column: "qualified_at", label: "Qualified at", kind: "datetime" },
    ],
  },
};

export const ENTITY_KEYS = [
  "marketing-offers",
  "loyalty-tiers",
  "loyalty-accounts",
  "loyalty-coupons",
  "loyalty-customer-coupons",
  "loyalty-ledger",
  "loyalty-referrals",
] as const;

export function getEntityConfig(entityKey: MarketingLoyaltyEntityKey) {
  const config = ENTITY_CONFIGS[entityKey];
  if (!config) {
    throw new Error(`Unknown marketing/loyalty admin entity: ${entityKey}`);
  }
  return config;
}
