import { Badge } from "@core/ui/Badge";
import { Button, LinkButton } from "@core/ui/Button";
import type { ModulePageProps } from "@core/modules/types";
import { Card, CardContent, CardHeader, CardTitle } from "@core/ui/Card";
import { Field, Input, Select, Textarea } from "@core/ui/Field";
import { PageHeader } from "@core/ui/PageHeader";
import { LocalizedField } from "@core/ui/LocalizedField";
import { formatDateTime } from "@core/lib/format";
import { testNotificationAction, upsertTemplateAction } from "../actions";
import { getBridgeSummary, getModuleSummary, listBridgeEvents, listDeliveryLogs, listTemplates } from "../repository";

export async function AdminPage({ searchParams }: ModulePageProps) {
  const [summary, templates, logs, bridgeSummary, bridgeEvents] = await Promise.all([
    getModuleSummary(),
    listTemplates(),
    listDeliveryLogs(undefined, 50),
    getBridgeSummary(),
    listBridgeEvents(50),
  ]);
  const selectedKey = Array.isArray(searchParams.template) ? searchParams.template[0] : searchParams.template;
  const selectedTemplate = templates.find((template) => template.templateKey === selectedKey) ?? templates[0];
  return (
    <div className="space-y-6">
      <PageHeader title="Notification Templates" description="Configure templates for claim, payment, booking, review, ticket, and content events across fa/en/ar/tr with delivery logs." />
      <div className="grid gap-4 md:grid-cols-4"><Card><CardContent><div className="text-sm font-bold text-slate-950">Templates</div><p className="mt-1 text-2xl font-bold">{summary.templatesCount}</p></CardContent></Card><Card><CardContent><div className="text-sm font-bold text-slate-950">Active</div><p className="mt-1 text-2xl font-bold">{summary.activeTemplatesCount}</p></CardContent></Card><Card><CardContent><div className="text-sm font-bold text-slate-950">Delivery logs</div><p className="mt-1 text-2xl font-bold">{summary.deliveryCount}</p></CardContent></Card><Card><CardContent><div className="text-sm font-bold text-slate-950">Unread inbox</div><p className="mt-1 text-2xl font-bold">{summary.unreadCount}</p></CardContent></Card></div>
      <div className="grid gap-5 xl:grid-cols-[1.35fr_0.65fr]">
        <Card><CardHeader><CardTitle>Templates</CardTitle></CardHeader><CardContent>{templates.length ? <div className="space-y-3">{templates.map((template) => <div key={template.id} className={`rounded-lg border p-3 text-sm ${selectedTemplate?.id === template.id ? "border-primary bg-primary/5" : "border-border"}`}><div className="flex items-start justify-between gap-3"><div><div className="font-semibold">{template.templateKey}</div><div className="text-xs text-muted-foreground">Channels: {template.channels.join(", ")}</div><div className="text-xs text-muted-foreground">Variables: {template.variables.join(", ") || "—"}</div></div><div className="flex items-center gap-2"><Badge variant={template.isActive ? "success" : "warning"}>{template.isActive ? "active" : "disabled"}</Badge><LinkButton size="sm" variant="secondary" href={`/admin/notifications?template=${encodeURIComponent(template.templateKey)}`}>Edit</LinkButton></div></div></div>)}</div> : <p className="rounded-lg bg-muted p-4 text-sm text-muted-foreground">No templates found. Run migrations.</p>}</CardContent></Card>
        <Card><CardHeader><CardTitle>Edit template / test send</CardTitle></CardHeader><CardContent className="space-y-5"><form action={upsertTemplateAction} className="space-y-3"><Field label="Template key"><Input name="templateKey" defaultValue={selectedTemplate?.templateKey ?? "claim.submitted"} required /></Field><Field label="Channels CSV"><Input name="channels" defaultValue={selectedTemplate?.channels.join(",") ?? "in_app,email"} /></Field><Field label="Variables CSV"><Input name="variables" defaultValue={selectedTemplate?.variables.join(",") ?? "claimId,targetType"} /></Field><LocalizedField name="title" label="Localized title" value={selectedTemplate?.titleTranslations} requiredLocale="fa-IR" /><LocalizedField name="body" label="Localized body" value={selectedTemplate?.bodyTranslations} mode="textarea" requiredLocale="fa-IR" /><label className="flex items-center gap-2 text-sm"><input type="checkbox" name="isActive" defaultChecked={selectedTemplate?.isActive ?? true} /> Active</label><Button type="submit" className="w-full">Save template</Button></form><form action={testNotificationAction} className="space-y-3 border-t border-border pt-5"><Field label="Template key"><Input name="templateKey" defaultValue={selectedTemplate?.templateKey ?? "manual.test"} /></Field><Field label="Recipient type"><Select name="recipientEntityType" defaultValue="provider"><option value="provider">Provider</option><option value="staff">Staff</option><option value="admin">Admin</option></Select></Field><Field label="Recipient ID"><Input name="recipientEntityId" required /></Field><Field label="Channel"><Select name="channel" defaultValue="in_app"><option value="in_app">In-app</option><option value="email">Email</option><option value="sms">SMS</option><option value="push">Push</option></Select></Field><Field label="Title"><Input name="title" /></Field><Field label="Body"><Textarea name="body" /></Field><Button type="submit" variant="secondary" className="w-full">Create test notification</Button></form></CardContent></Card>
      </div>
      <Card><CardHeader><CardTitle>Delivery logs</CardTitle></CardHeader><CardContent>{logs.length ? <div className="overflow-hidden rounded-lg border border-border"><table className="w-full text-sm"><thead className="bg-muted text-left text-xs uppercase text-muted-foreground"><tr><th className="p-3">Template</th><th className="p-3">Recipient</th><th className="p-3">Channel</th><th className="p-3">Status</th><th className="p-3">Created</th></tr></thead><tbody>{logs.map((log) => <tr key={log.id} className="border-t border-border"><td className="p-3">{log.templateKey || "manual"}</td><td className="p-3"><div>{log.recipientEntityType}</div><div className="font-mono text-xs text-muted-foreground">{log.recipientEntityId}</div></td><td className="p-3">{log.channel}</td><td className="p-3"><Badge variant={log.status === "sent" ? "success" : "warning"}>{log.status}</Badge></td><td className="p-3">{formatDateTime(log.createdAt)}</td></tr>)}</tbody></table></div> : <p className="rounded-lg bg-muted p-4 text-sm text-muted-foreground">No delivery logs yet.</p>}</CardContent></Card>
    <Card><CardHeader><CardTitle>LSevin platform notification bridge</CardTitle></CardHeader><CardContent><div className="grid gap-4 md:grid-cols-3"><div><div className="text-xs text-muted-foreground">Bridge events</div><div className="text-2xl font-black">{bridgeSummary.events}</div></div><div><div className="text-xs text-muted-foreground">Processed</div><div className="text-2xl font-black">{bridgeSummary.processed}</div></div><div><div className="text-xs text-muted-foreground">Subscriptions</div><div className="text-2xl font-black">{bridgeSummary.subscriptions}</div></div></div><div className="mt-4 space-y-2">{bridgeEvents.slice(0, 8).map((event) => <div key={event.id} className="rounded-lg border p-3 text-sm"><div className="font-semibold">{event.eventName}</div><div className="text-xs text-muted-foreground">{event.recipientEntityType} {event.recipientEntityId} · {event.sourceModule} · {event.status}</div></div>)}</div></CardContent></Card></div>
  );
}
