// Generated by https://quicktype.io

namespace QuickType
{
    using System;
    using System.Collections.Generic;

    using System.Text.Json;
    using System.Text.Json.Serialization;

    public partial class GetRewardsPageResponse
    {
        [JsonPropertyName("user")]
        public User User { get; set; }

        [JsonPropertyName("tiers")]
        public Tier[] Tiers { get; set; }

        [JsonPropertyName("coupons")]
        public Coupon[] Coupons { get; set; }

        [JsonPropertyName("usedCoupons")]
        public UsedCoupon[] UsedCoupons { get; set; }

        [JsonPropertyName("recentActivity")]
        public RecentActivity[] RecentActivity { get; set; }
    }

    public partial class Coupon
    {
        [JsonPropertyName("id")]
        public long Id { get; set; }

        [JsonPropertyName("code")]
        public string Code { get; set; }

        [JsonPropertyName("title")]
        public string Title { get; set; }

        [JsonPropertyName("description")]
        public string Description { get; set; }

        [JsonPropertyName("discount")]
        public string Discount { get; set; }

        [JsonPropertyName("expiresAt")]
        public DateOnly ExpiresAt { get; set; }

        [JsonPropertyName("minPurchase")]
        public long MinPurchase { get; set; }

        [JsonPropertyName("status")]
        public string Status { get; set; }

        [JsonPropertyName("type")]
        public string Type { get; set; }
    }

    public partial class RecentActivity
    {
        [JsonPropertyName("type")]
        public string Type { get; set; }

        [JsonPropertyName("points")]
        public long Points { get; set; }

        [JsonPropertyName("description")]
        public string Description { get; set; }

        [JsonPropertyName("date")]
        public DateOnly Date { get; set; }
    }

    public partial class Tier
    {
        [JsonPropertyName("name")]
        public string Name { get; set; }

        [JsonPropertyName("minPoints")]
        public long MinPoints { get; set; }

        [JsonPropertyName("color")]
        public string Color { get; set; }

        [JsonPropertyName("icon")]
        public string Icon { get; set; }

        [JsonPropertyName("benefits")]
        public string[] Benefits { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("current")]
        public bool? Current { get; set; }
    }

    public partial class UsedCoupon
    {
        [JsonPropertyName("id")]
        public long Id { get; set; }

        [JsonPropertyName("code")]
        public string Code { get; set; }

        [JsonPropertyName("title")]
        public string Title { get; set; }

        [JsonPropertyName("discount")]
        public string Discount { get; set; }

        [JsonPropertyName("usedAt")]
        public DateOnly UsedAt { get; set; }

        [JsonPropertyName("status")]
        public string Status { get; set; }
    }

    public partial class User
    {
        [JsonPropertyName("points")]
        public long Points { get; set; }

        [JsonPropertyName("tier")]
        public string Tier { get; set; }

        [JsonPropertyName("tierProgress")]
        public long TierProgress { get; set; }

        [JsonPropertyName("nextTier")]
        public string NextTier { get; set; }

        [JsonPropertyName("pointsToNext")]
        public long PointsToNext { get; set; }

        [JsonPropertyName("totalSpent")]
        public long TotalSpent { get; set; }

        [JsonPropertyName("referrals")]
        public long Referrals { get; set; }

        [JsonPropertyName("referralEarnings")]
        public long ReferralEarnings { get; set; }
    }

    public partial class GetRewardsPageResponse
    {

        public const string SampleJson = "{\"favorites\":[{\"id\":1,\"type\":\"clinic\",\"name\":\"Dubai Healthcare City Clinic\",\"location\":\"Healthcare City, Dubai\",\"rating\":4.9,\"reviews\":1248,\"image\":\"/unsplash_images/photo-1519494026892-80bbd2d6fd0d__w=400.jpg\"},{\"id\":2,\"type\":\"doctor\",\"name\":\"Dr. Sarah Johnson\",\"specialty\":\"Cardiologist\",\"location\":\"Jumeirah, Dubai\",\"rating\":4.8,\"reviews\":892,\"image\":\"/unsplash_images/photo-1559839734-2b71ea197ec2__w=400.jpg\"},{\"id\":3,\"type\":\"salon\",\"name\":\"Elegance Beauty Spa\",\"location\":\"Marina, Dubai\",\"rating\":4.9,\"reviews\":654,\"image\":\"/unsplash_images/photo-1560066984-138dadb4c035__w=400.jpg\"},{\"id\":4,\"type\":\"gym\",\"name\":\"FitZone Wellness Center\",\"location\":\"Downtown, Dubai\",\"rating\":4.7,\"reviews\":432,\"image\":\"/unsplash_images/photo-1534438327276-14e5300c3a48__w=400.jpg\"}],\"tabs\":[{\"id\":\"all\",\"label\":\"All\"},{\"id\":\"clinic\",\"label\":\"Clinics\"},{\"id\":\"doctor\",\"label\":\"Doctors\"},{\"id\":\"salon\",\"label\":\"Salons\"},{\"id\":\"gym\",\"label\":\"Gyms\"}]}\r\n";
        public static GetRewardsPageResponse FromJson(string json) => JsonSerializer.Deserialize<GetRewardsPageResponse>(json, QuickType.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this GetRewardsPageResponse self) => JsonSerializer.Serialize(self, QuickType.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerOptions Settings = new(JsonSerializerDefaults.Web)
        {
            Converters =
            {
                new DateOnlyConverter(),
                new TimeOnlyConverter(),
            },
        };
    }
    
    public class DateOnlyConverter : JsonConverter<DateOnly>
    {
        private readonly string serializationFormat;
        public DateOnlyConverter() : this(null) { }

        public DateOnlyConverter(string? serializationFormat)
        {
            this.serializationFormat = serializationFormat ?? "yyyy-MM-dd";
        }

        public override DateOnly Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            var value = reader.GetString();
            return DateOnly.Parse(value!);
        }

        public override void Write(Utf8JsonWriter writer, DateOnly value, JsonSerializerOptions options)
            => writer.WriteStringValue(value.ToString(serializationFormat));
    }
    public class TimeOnlyConverter : JsonConverter<TimeOnly>
    {
        private readonly string serializationFormat;

        public TimeOnlyConverter() : this(null) { }

        public TimeOnlyConverter(string? serializationFormat)
        {
            this.serializationFormat = serializationFormat ?? "HH:mm:ss.fff";
        }

        public override TimeOnly Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            var value = reader.GetString();
            return TimeOnly.Parse(value!);
        }

        public override void Write(Utf8JsonWriter writer, TimeOnly value, JsonSerializerOptions options)
            => writer.WriteStringValue(value.ToString(serializationFormat));
    }
}
