---
- name: Restart Jenkins controller
  ansible.builtin.command:
    argv:
      - docker
      - compose
      - --env-file
      - "{{ lsevin_jenkins_controller_dir }}/controller.env"
      - -f
      - "{{ lsevin_jenkins_controller_dir }}/docker-compose.yml"
      - up
      - -d
      - --build
      - jenkins
  changed_when: true
