apiVersion: v1
kind: ConfigMap
metadata:
  name: providers-portal-config
  namespace: lsevin-providers
data:
  PROVIDER_PORTAL_DB_MODE: "split"
  PGHOST: "postgres"
  PGPORT: "5432"
  PGDATABASE: "lsevin"
  POSTGRES_POOL_MAX: "10"
  POSTGRES_IDLE_TIMEOUT: "20"
  POSTGRES_MAX_LIFETIME: "1800"
  POSTGRES_CONNECT_TIMEOUT: "10"
  POSTGRES_PREPARE: "true"

  NEXT_PUBLIC_APP_NAME: "LSevin Providers Portal"
  NEXT_PUBLIC_APP_URL: "http://localhost:3000"
  NEXT_PUBLIC_DEFAULT_LOCALE: "fa-IR"
  NEXT_PUBLIC_DEFAULT_DIRECTION: "rtl"
  NEXT_PUBLIC_DEFAULT_TIMEZONE: "Asia/Tehran"
  NEXT_PUBLIC_LOCALE_COOKIE_DOMAIN: ""

  PROVIDER_PORTAL_LOCAL_AUTH: "false"
  LSEVIN_USER_ID_COOKIE: "lsevin_user_id"
  LSEVIN_USER_ID_HEADER: "x-lsevin-user-id"
  ALLOW_TRUSTED_USER_HEADER: "false"
  TRUSTED_PROXY_ENFORCED: "false"

  PRIVATE_FILE_STORAGE_ROOT: "/var/lib/lsevin/private-files"
  PROVIDER_MEDIA_STORAGE_ROOT: "/app/public"
  PROVIDER_MEDIA_PUBLIC_BASE_URL: ""
  ALLOW_LEGACY_MEDIA_URLS: "true"
  PAYMENT_GATEWAYS_ENABLED: "none"
