apiVersion: v1
kind: Service
metadata:
  name: providers-portal
  namespace: lsevin-providers
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: lsevin-providers-portal
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
