apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: providers-private-files
  namespace: lsevin-providers
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: providers-media-files
  namespace: lsevin-providers
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 20Gi
