apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - ingress.yaml
patches:
  - path: configmap-patch.yaml
images:
  - name: lsevin-providers
    newName: registry.example.com/lsevin/providers-portal
    newTag: latest
  - name: lsevin-providers-db
    newName: registry.example.com/lsevin/providers-portal-db
    newTag: latest
