import type { PortalLocale } from "./config";

const labels: Record<Exclude<PortalLocale, "en">, Record<string, string>> = {
  fa: {
    "portal.dashboard":"داشبورد","portal.providers":"ارائه‌دهندگان من","portal.applications.new":"درخواست ارائه‌دهندگی","portal.applications.new-staff":"درخواست پروفایل کارمند","portal.applications":"درخواست‌ها",
    "provider.settings":"دسترسی‌ها","provider.manage":"مدیریت","provider.profile":"پروفایل","provider.services":"خدمات و قیمت‌ها","provider.staff":"کارکنان","provider.media":"رسانه‌ها","provider.availability":"زمان‌های در دسترس","booking-management.provider":"رزروها","provider.reviews":"نظرها","provider.finance.overview":"مالی","provider.finance.wallet":"کیف پول","provider.finance.settlements":"تسویه‌ها","provider.reports":"گزارش‌ها","payment-billing.provider":"صورتحساب","ticketing.provider":"تیکت‌ها","notifications-module.provider":"اعلان‌ها",
    "admin.dashboard":"نمای کلی مدیریت","admin-governance.overview":"حاکمیت دسترسی","admin-governance.audit":"ممیزی مدیریت","admin.applications":"درخواست‌ها","providers.admin":"ارائه‌دهندگان","services.admin":"خدمات","staff.admin":"کارکنان","availability.admin":"دسترسی زمانی","booking-management.admin":"عملیات رزرو","admin.finance.overview":"کنترل مالی","admin.finance.settlements":"کنترل تسویه","admin.reports":"گزارش‌ها","payment-billing.admin":"پرداخت و صورتحساب","ticketing.admin":"صندوق تیکت‌ها","notifications-module.admin":"الگوهای اعلان",
  },
  ar: {
    "portal.dashboard":"لوحة التحكم","portal.providers":"مزوّدو الخدمة لدي","portal.applications.new":"طلب الانضمام كمزوّد","portal.applications.new-staff":"طلب ملف موظف","portal.applications":"الطلبات",
    "provider.settings":"الوصول","provider.manage":"الإدارة","provider.profile":"الملف","provider.services":"الخدمات والأسعار","provider.staff":"الموظفون","provider.media":"الوسائط","provider.availability":"المواعيد المتاحة","booking-management.provider":"الحجوزات","provider.reviews":"التقييمات","provider.finance.overview":"المالية","provider.finance.wallet":"المحفظة","provider.finance.settlements":"التسويات","provider.reports":"التقارير","payment-billing.provider":"الفوترة","ticketing.provider":"التذاكر","notifications-module.provider":"الإشعارات",
    "admin.dashboard":"نظرة الإدارة","admin-governance.overview":"حوكمة الوصول","admin-governance.audit":"تدقيق الإدارة","admin.applications":"الطلبات","providers.admin":"مزوّدو الخدمة","services.admin":"الخدمات","staff.admin":"الموظفون","availability.admin":"إدارة المواعيد","booking-management.admin":"عمليات الحجز","admin.finance.overview":"الرقابة المالية","admin.finance.settlements":"رقابة التسويات","admin.reports":"التقارير","payment-billing.admin":"الدفع والفوترة","ticketing.admin":"صندوق التذاكر","notifications-module.admin":"قوالب الإشعارات",
  },
  tr: {
    "portal.dashboard":"Kontrol paneli","portal.providers":"Sağlayıcılarım","portal.applications.new":"Sağlayıcı başvurusu","portal.applications.new-staff":"Personel profili başvurusu","portal.applications":"Başvurular",
    "provider.settings":"Erişim","provider.manage":"Yönetim","provider.profile":"Profil","provider.services":"Hizmetler ve fiyatlar","provider.staff":"Personel","provider.media":"Medya","provider.availability":"Uygunluk","booking-management.provider":"Rezervasyonlar","provider.reviews":"Yorumlar","provider.finance.overview":"Finans","provider.finance.wallet":"Cüzdan","provider.finance.settlements":"Mutabakatlar","provider.reports":"Raporlar","payment-billing.provider":"Faturalama","ticketing.provider":"Destek talepleri","notifications-module.provider":"Bildirimler",
    "admin.dashboard":"Yönetim özeti","admin-governance.overview":"Erişim yönetişimi","admin-governance.audit":"Yönetim denetimi","admin.applications":"Başvurular","providers.admin":"Sağlayıcılar","services.admin":"Hizmetler","staff.admin":"Personel","availability.admin":"Uygunluk yönetimi","booking-management.admin":"Rezervasyon işlemleri","admin.finance.overview":"Finans kontrolü","admin.finance.settlements":"Mutabakat kontrolü","admin.reports":"Raporlar","payment-billing.admin":"Ödeme ve faturalama","ticketing.admin":"Talep kutusu","notifications-module.admin":"Bildirim şablonları",
  },
  es: {
    "portal.dashboard":"Panel","portal.providers":"Mis proveedores","portal.applications.new":"Solicitud de proveedor","portal.applications.new-staff":"Solicitud de perfil del personal","portal.applications":"Solicitudes",
    "provider.settings":"Acceso","provider.manage":"Gestión","provider.profile":"Perfil","provider.services":"Servicios y precios","provider.staff":"Personal","provider.media":"Multimedia","provider.availability":"Disponibilidad","booking-management.provider":"Reservas","provider.reviews":"Reseñas","provider.finance.overview":"Finanzas","provider.finance.wallet":"Cartera","provider.finance.settlements":"Liquidaciones","provider.reports":"Informes","payment-billing.provider":"Facturación","ticketing.provider":"Soporte","notifications-module.provider":"Notificaciones",
    "admin.dashboard":"Resumen administrativo","admin-governance.overview":"Gobernanza de acceso","admin-governance.audit":"Auditoría administrativa","admin.applications":"Solicitudes","providers.admin":"Proveedores","services.admin":"Servicios","staff.admin":"Personal","availability.admin":"Gestión de disponibilidad","booking-management.admin":"Operaciones de reserva","admin.finance.overview":"Control financiero","admin.finance.settlements":"Control de liquidaciones","admin.reports":"Informes","payment-billing.admin":"Pagos y facturación","ticketing.admin":"Bandeja de soporte","notifications-module.admin":"Plantillas de notificación",
  },
  ku: {
    "portal.dashboard":"داشبۆرد","portal.providers":"پێشکەشکارەکانی من","portal.applications.new":"داواکاری پێشکەشکار","portal.applications.new-staff":"داواکاری پڕۆفایلی ستاف","portal.applications":"داواکارییەکان",
    "provider.settings":"دەسەڵات","provider.manage":"بەڕێوەبردن","provider.profile":"پڕۆفایل","provider.services":"خزمەتگوزاری و نرخ","provider.staff":"ستاف","provider.media":"میدیا","provider.availability":"کاتی بەردەست","booking-management.provider":"حجزەکان","provider.reviews":"هەڵسەنگاندن","provider.finance.overview":"دارایی","provider.finance.wallet":"جزدان","provider.finance.settlements":"تسویەکان","provider.reports":"ڕاپۆرتەکان","payment-billing.provider":"پسووڵە","ticketing.provider":"پشتیوانی","notifications-module.provider":"ئاگادارکردنەوە",
    "admin.dashboard":"پوختەی بەڕێوەبەر","admin-governance.overview":"بەڕێوەبردنی دەسەڵات","admin-governance.audit":"پشکنینی بەڕێوەبەر","admin.applications":"داواکارییەکان","providers.admin":"پێشکەشکاران","services.admin":"خزمەتگوزارییەکان","staff.admin":"ستاف","availability.admin":"بەڕێوەبردنی کاتی بەردەست","booking-management.admin":"کردارەکانی حجز","admin.finance.overview":"کۆنترۆڵی دارایی","admin.finance.settlements":"کۆنترۆڵی تسویە","admin.reports":"ڕاپۆرتەکان","payment-billing.admin":"پارەدان و پسووڵە","ticketing.admin":"سندوقی پشتیوانی","notifications-module.admin":"قاڵبەکانی ئاگادارکردنەوە",
  },
  de: {
    "portal.dashboard":"Übersicht","portal.providers":"Meine Anbieter","portal.applications.new":"Anbieterantrag","portal.applications.new-staff":"Mitarbeiterprofil beantragen","portal.applications":"Anträge",
    "provider.settings":"Zugriff","provider.manage":"Verwaltung","provider.profile":"Profil","provider.services":"Leistungen und Preise","provider.staff":"Mitarbeiter","provider.media":"Medien","provider.availability":"Verfügbarkeit","booking-management.provider":"Buchungen","provider.reviews":"Bewertungen","provider.finance.overview":"Finanzen","provider.finance.wallet":"Wallet","provider.finance.settlements":"Abrechnungen","provider.reports":"Berichte","payment-billing.provider":"Abrechnung","ticketing.provider":"Support","notifications-module.provider":"Benachrichtigungen",
    "admin.dashboard":"Administrationsübersicht","admin-governance.overview":"Zugriffsverwaltung","admin-governance.audit":"Administrationsprüfung","admin.applications":"Anträge","providers.admin":"Anbieter","services.admin":"Leistungen","staff.admin":"Mitarbeiter","availability.admin":"Verfügbarkeitsverwaltung","booking-management.admin":"Buchungsbetrieb","admin.finance.overview":"Finanzkontrolle","admin.finance.settlements":"Abrechnungskontrolle","admin.reports":"Berichte","payment-billing.admin":"Zahlung und Abrechnung","ticketing.admin":"Support-Postfach","notifications-module.admin":"Benachrichtigungsvorlagen",
  },
  fr: {
    "portal.dashboard":"Tableau de bord","portal.providers":"Mes prestataires","portal.applications.new":"Demande de prestataire","portal.applications.new-staff":"Demande de profil du personnel","portal.applications":"Demandes",
    "provider.settings":"Accès","provider.manage":"Gestion","provider.profile":"Profil","provider.services":"Services et prix","provider.staff":"Personnel","provider.media":"Médias","provider.availability":"Disponibilités","booking-management.provider":"Réservations","provider.reviews":"Avis","provider.finance.overview":"Finances","provider.finance.wallet":"Portefeuille","provider.finance.settlements":"Règlements","provider.reports":"Rapports","payment-billing.provider":"Facturation","ticketing.provider":"Assistance","notifications-module.provider":"Notifications",
    "admin.dashboard":"Vue d’ensemble administrative","admin-governance.overview":"Gouvernance des accès","admin-governance.audit":"Audit administratif","admin.applications":"Demandes","providers.admin":"Prestataires","services.admin":"Services","staff.admin":"Personnel","availability.admin":"Gestion des disponibilités","booking-management.admin":"Opérations de réservation","admin.finance.overview":"Contrôle financier","admin.finance.settlements":"Contrôle des règlements","admin.reports":"Rapports","payment-billing.admin":"Paiement et facturation","ticketing.admin":"Boîte d’assistance","notifications-module.admin":"Modèles de notification",
  },
};

const additionalLabels: Record<Exclude<PortalLocale, "en">, Record<string, string>> = {
  fa: {
    "portal.support":"پشتیبانی","provider.support":"پشتیبانی","provider.offers":"پیشنهادها","offers.admin":"مدیریت پیشنهادها","provider.bookings":"رزروها","reviews-standalone.provider":"اعتبار و بازخورد","reviews-standalone.admin":"مدیریت اعتبار و بازخورد","reporting-analytics.provider":"تحلیل و گزارش","reporting-analytics.admin":"تحلیل مدیریتی","provider-portal.provider":"پرتال ارائه‌دهنده","provider-portal.admin":"مدیریت پرتال ارائه‌دهنده","provider-portal.moderation":"بررسی محتوا","provider.dashboard":"نمای کلی","staff.finance.hub":"درآمد من","media-library.provider":"کتابخانه رسانه","media-library.admin":"مدیریت کتابخانه رسانه",
  },
  ar: {
    "portal.support":"الدعم","provider.support":"الدعم","provider.offers":"العروض","offers.admin":"إدارة العروض","provider.bookings":"الحجوزات","reviews-standalone.provider":"السمعة والتقييمات","reviews-standalone.admin":"إدارة السمعة","reporting-analytics.provider":"التحليلات والتقارير","reporting-analytics.admin":"تحليلات الإدارة","provider-portal.provider":"بوابة مزوّد الخدمة","provider-portal.admin":"إدارة بوابة المزوّد","provider-portal.moderation":"مراجعة المحتوى","provider.dashboard":"نظرة عامة","staff.finance.hub":"أرباحي","media-library.provider":"مكتبة الوسائط","media-library.admin":"إدارة مكتبة الوسائط",
  },
  tr: {
    "portal.support":"Destek","provider.support":"Destek","provider.offers":"Teklifler","offers.admin":"Teklif yönetimi","provider.bookings":"Rezervasyonlar","reviews-standalone.provider":"İtibar ve yorumlar","reviews-standalone.admin":"İtibar yönetimi","reporting-analytics.provider":"Analiz ve raporlar","reporting-analytics.admin":"Yönetim analizi","provider-portal.provider":"Sağlayıcı portalı","provider-portal.admin":"Sağlayıcı portalı yönetimi","provider-portal.moderation":"İçerik inceleme","provider.dashboard":"Genel bakış","staff.finance.hub":"Kazançlarım","media-library.provider":"Medya kütüphanesi","media-library.admin":"Medya kütüphanesi yönetimi",
  },
  es: {
    "portal.support":"Soporte","provider.support":"Soporte","provider.offers":"Ofertas","offers.admin":"Gestión de ofertas","provider.bookings":"Reservas","reviews-standalone.provider":"Reputación y reseñas","reviews-standalone.admin":"Gestión de reputación","reporting-analytics.provider":"Analítica e informes","reporting-analytics.admin":"Analítica administrativa","provider-portal.provider":"Portal del proveedor","provider-portal.admin":"Gestión del portal del proveedor","provider-portal.moderation":"Moderación de contenido","provider.dashboard":"Resumen","staff.finance.hub":"Mis ingresos","media-library.provider":"Biblioteca multimedia","media-library.admin":"Gestión de biblioteca multimedia",
  },
  ku: {
    "portal.support":"پشتیوانی","provider.support":"پشتیوانی","provider.offers":"ئۆفەرەکان","offers.admin":"بەڕێوەبردنی ئۆفەرەکان","provider.bookings":"حجزەکان","reviews-standalone.provider":"ناوبانگ و هەڵسەنگاندن","reviews-standalone.admin":"بەڕێوەبردنی ناوبانگ","reporting-analytics.provider":"شیکاری و ڕاپۆرت","reporting-analytics.admin":"شیکاری بەڕێوەبەر","provider-portal.provider":"پۆرتاڵی پێشکەشکار","provider-portal.admin":"بەڕێوەبردنی پۆرتاڵی پێشکەشکار","provider-portal.moderation":"پشکنینی ناوەڕۆک","provider.dashboard":"پوختە","staff.finance.hub":"داهاتی من","media-library.provider":"کتێبخانەی میدیا","media-library.admin":"بەڕێوەبردنی کتێبخانەی میدیا",
  },
  de: {
    "portal.support":"Support","provider.support":"Support","provider.offers":"Angebote","offers.admin":"Angebotsverwaltung","provider.bookings":"Buchungen","reviews-standalone.provider":"Reputation und Bewertungen","reviews-standalone.admin":"Reputationsverwaltung","reporting-analytics.provider":"Analysen und Berichte","reporting-analytics.admin":"Admin-Analysen","provider-portal.provider":"Anbieterportal","provider-portal.admin":"Anbieterportal-Verwaltung","provider-portal.moderation":"Inhaltsprüfung","provider.dashboard":"Überblick","staff.finance.hub":"Meine Einnahmen","media-library.provider":"Medienbibliothek","media-library.admin":"Medienbibliothek-Verwaltung",
  },
  fr: {
    "portal.support":"Assistance","provider.support":"Assistance","provider.offers":"Offres","offers.admin":"Gestion des offres","provider.bookings":"Réservations","reviews-standalone.provider":"Réputation et avis","reviews-standalone.admin":"Gestion de la réputation","reporting-analytics.provider":"Analyses et rapports","reporting-analytics.admin":"Analyses administratives","provider-portal.provider":"Portail prestataire","provider-portal.admin":"Gestion du portail prestataire","provider-portal.moderation":"Modération du contenu","provider.dashboard":"Vue d’ensemble","staff.finance.hub":"Mes revenus","media-library.provider":"Médiathèque","media-library.admin":"Gestion de la médiathèque",
  },
};

export function navigationLabel(locale: PortalLocale, routeKey: string, fallback: string) {
  return locale === "en" ? fallback : labels[locale]?.[routeKey] || additionalLabels[locale]?.[routeKey] || fallback;
}
