@startuml

!theme plain
top to bottom direction
skinparam linetype ortho

class LocationType {
   name: varchar(50)
   id: integer
}
class __EFMigrationsHistory {
   product_version: varchar(32)
   migration_id: varchar(150)
}
class attribute_types {
   name: varchar(25)
   id: integer
}
class categories {
   name: varchar(250)
   description: varchar(2000)
   parent_id: uuid
   display_order: integer
   is_active: boolean
   icon_url: varchar(250)
   create_date: timestamp with time zone
   last_modified_date: timestamp with time zone
   id: uuid
}
class inbox_message_consumers {
   message_id: uuid
   name: varchar(500)
}
class inbox_messages {
   type: varchar(250)
   content: jsonb
   occurred_on_utc: timestamp with time zone
   processed_on_utc: timestamp with time zone
   error: text
   id: uuid
}
class internal_command_message_consumers {
   message_id: uuid
   name: varchar(500)
}
class internal_command_messages {
   type: varchar(250)
   content: jsonb
   occurred_on_utc: timestamp with time zone
   processed_on_utc: timestamp with time zone
   error: text
   id: uuid
}
class locations {
   code: varchar(10)
   value: varchar(100)
   location_type_id: integer
   parent_id: uuid
   create_date: timestamp with time zone
   last_modified_date: timestamp with time zone
   id: uuid
}
class outbox_message_consumers {
   message_id: uuid
   name: varchar(500)
}
class outbox_messages {
   type: varchar(250)
   content: jsonb
   occurred_on_utc: timestamp with time zone
   processed_on_utc: timestamp with time zone
   error: text
   id: uuid
}
class provider_attribute_definition_domain_options {
   display_name: varchar(100)
   value: varchar(100)
   provider_attribute_definition_id: uuid
   id: integer
}
class provider_attribute_definitions {
   name: varchar(100)
   description: varchar(2000)
   attribute_type_id: integer
   is_required: boolean
   validation_rules: varchar(250)
   provider_type_id: uuid
   create_date: timestamp with time zone
   last_modified_date: timestamp with time zone
   id: uuid
}
class provider_attributes {
   attribute_definition_id: uuid
   value: varchar(250)
   service_provider_id: uuid
   create_date: timestamp with time zone
   last_modified_date: timestamp with time zone
   id: uuid
}
class provider_gallery_items {
   title: varchar(100)
   description: varchar(2000)
   url: varchar(250)
   media_type: varchar(50)
   display_order: integer
   service_provider_id: uuid
   create_date: timestamp with time zone
   last_modified_date: timestamp with time zone
   id: uuid
}
class provider_policies {
   type: varchar(50)
   description: varchar(2000)
   service_provider_id: uuid
   create_date: timestamp with time zone
   last_modified_date: timestamp with time zone
   id: uuid
}
class provider_services {
   service_definition_id: uuid
   display_name: varchar(100)
   description: varchar(2000)
   is_active: boolean
   service_provider_id: uuid
   currency: varchar(15)
   value: numeric(18,2)
   create_date: timestamp with time zone
   last_modified_date: timestamp with time zone
   id: uuid
}
class provider_staffs {
   staff_id: uuid
   notes: varchar(2000)
   is_active: boolean
   service_provider_id: uuid
   create_date: timestamp with time zone
   last_modified_date: timestamp with time zone
   id: uuid
}
class provider_types {
   name: varchar(100)
   description: varchar(2000)
   is_active: boolean
   create_date: timestamp with time zone
   last_modified_date: timestamp with time zone
   id: uuid
}
class request_statuses {
   name: varchar(25)
   id: integer
}
class service_attribute_definition_options {
   display_name: varchar(100)
   value: varchar(100)
   additional_price: numeric(18,2)
   service_attribute_definition_id: uuid
   id: integer
}
class service_attribute_definitions {
   name: varchar(100)
   description: varchar(2000)
   attribute_type_id: integer
   is_required: boolean
   affects_pricing: boolean
   display_order: integer
   service_definition_id: uuid
   create_date: timestamp with time zone
   last_modified_date: timestamp with time zone
   id: uuid
}
class service_attribute_values {
   attribute_definition_id: uuid
   value: varchar(250)
   provider_service_id: uuid
   create_date: timestamp with time zone
   last_modified_date: timestamp with time zone
   id: uuid
}
class service_definition_domain_requirements {
   description: varchar(2000)
   is_mandatory: boolean
   service_definition_id: uuid
   id: integer
}
class service_definitions {
   name: varchar(100)
   description: varchar(2000)
   category_id: uuid
   duration_minutes: integer
   pricing_model: varchar(100)
   is_active: boolean
   currency: varchar(15)
   value: numeric(18,2)
   create_date: timestamp with time zone
   last_modified_date: timestamp with time zone
   id: uuid
}
class service_provider_requests {
   service_provider_id: uuid
   customer_id: uuid
   customer_email: varchar(256)
   customer_full_name: varchar(256)
   message: varchar(2000)
   request_status_id: integer
   create_date: timestamp with time zone
   last_modified_date: timestamp with time zone
   id: uuid
}
class service_providers {
   name: varchar(100)
   description: varchar(2000)
   is_active: boolean
   provider_type_id: uuid
   city: varchar(15)
   country: varchar(15)
   detail: varchar(500)
   street: varchar(100)
   zip_code: varchar(50)
   email: varchar(250)
   phone_number_country_code: varchar(3)
   phone_number: varchar(15)
   create_date: timestamp with time zone
   last_modified_date: timestamp with time zone
   id: uuid
}
class staff {
   name: varchar(100)
   biography: varchar(2000)
   title: varchar(100)
   profile_image_url: varchar(250)
   is_active: boolean
   create_date: timestamp with time zone
   last_modified_date: timestamp with time zone
   id: uuid
}
class staff_availabilities {
   day_of_week: integer
   is_recurring: boolean
   availability_status_id: integer
   specific_date: timestamp with time zone
   staff_id: uuid
   end_time: interval
   start_time: interval
   create_date: timestamp with time zone
   last_modified_date: timestamp with time zone
   id: uuid
}
class staff_availability_statuses {
   name: varchar(25)
   id: integer
}
class staff_services {
   service_definition_id: uuid
   is_active: boolean
   notes: varchar(250)
   staff_id: uuid
   create_date: timestamp with time zone
   last_modified_date: timestamp with time zone
   id: uuid
}

categories                                    -[#595959,plain]-^  categories                                   : "parent_id:id"
locations                                     -[#595959,plain]-^  LocationType                                 : "location_type_id:id"
locations                                     -[#595959,plain]-^  locations                                    : "parent_id:id"
provider_attribute_definition_domain_options  -[#595959,plain]-^  provider_attribute_definitions               : "provider_attribute_definition_id:id"
provider_attribute_definitions                -[#595959,plain]-^  attribute_types                              : "attribute_type_id:id"
provider_attribute_definitions                -[#595959,plain]-^  provider_types                               : "provider_type_id:id"
provider_attributes                           -[#595959,plain]-^  service_providers                            : "service_provider_id:id"
provider_gallery_items                        -[#595959,plain]-^  service_providers                            : "service_provider_id:id"
provider_policies                             -[#595959,plain]-^  service_providers                            : "service_provider_id:id"
provider_services                             -[#595959,plain]-^  service_definitions                          : "service_definition_id:id"
provider_services                             -[#595959,plain]-^  service_providers                            : "service_provider_id:id"
provider_staffs                               -[#595959,plain]-^  service_providers                            : "service_provider_id:id"
provider_staffs                               -[#595959,plain]-^  staff                                        : "staff_id:id"
service_attribute_definition_options          -[#595959,plain]-^  service_attribute_definitions                : "service_attribute_definition_id:id"
service_attribute_definitions                 -[#595959,plain]-^  attribute_types                              : "attribute_type_id:id"
service_attribute_definitions                 -[#595959,plain]-^  service_definitions                          : "service_definition_id:id"
service_attribute_values                      -[#595959,plain]-^  provider_services                            : "provider_service_id:id"
service_definition_domain_requirements        -[#595959,plain]-^  service_definitions                          : "service_definition_id:id"
service_definitions                           -[#595959,plain]-^  categories                                   : "category_id:id"
service_provider_requests                     -[#595959,plain]-^  request_statuses                             : "request_status_id:id"
service_provider_requests                     -[#595959,plain]-^  service_providers                            : "service_provider_id:id"
service_providers                             -[#595959,plain]-^  provider_types                               : "provider_type_id:id"
staff_availabilities                          -[#595959,plain]-^  staff                                        : "staff_id:id"
staff_availabilities                          -[#595959,plain]-^  staff_availability_statuses                  : "availability_status_id:id"
staff_services                                -[#595959,plain]-^  service_definitions                          : "service_definition_id:id"
staff_services                                -[#595959,plain]-^  staff                                        : "staff_id:id"
@enduml
