import type { ProviderPortalPermission } from "./lib/permissions";

export type ProviderResourceFieldType =
  | "text"
  | "textarea"
  | "number"
  | "boolean"
  | "date"
  | "datetime"
  | "time"
  | "select"
  | "translations"
  | "csv"
  | "json";

export type ProviderResourceOptionSource =
  | "provider-services"
  | "service-definitions"
  | "provider-staff"
  | "all-staff"
  | "addons"
  | "policy-types"
  | "availability-statuses"
  | "currencies";

export type ProviderResourceField = {
  name: string;
  label: string;
  type: ProviderResourceFieldType;
  required?: boolean;
  readOnly?: boolean;
  placeholder?: string;
  help?: string;
  options?: Array<{ value: string; label: string }>;
  optionSource?: ProviderResourceOptionSource;
  list?: boolean;
};

export type ProviderResourceOwnership =
  | { kind: "provider"; providerColumn: string }
  | { kind: "providerService"; serviceColumn: string }
  | { kind: "staff"; staffColumn: string }
  | { kind: "booking"; providerColumn: string }
  | { kind: "none" };

export type ProviderResourceConfig = {
  key: string;
  label: string;
  pluralLabel: string;
  description: string;
  group: "Profile" | "Services" | "Staff" | "Scheduling" | "Commercial" | "Support" | "Customer";
  table: string;
  idColumn: string;
  idType?: "uuid" | "text" | "integer";
  ownership: ProviderResourceOwnership;
  permission: ProviderPortalPermission;
  createPermission?: ProviderPortalPermission;
  updatePermission?: ProviderPortalPermission;
  deletePermission?: ProviderPortalPermission;
  create?: boolean;
  update?: boolean;
  delete?: boolean;
  softDeleteColumn?: string;
  fields: ProviderResourceField[];
  listColumns?: string[];
  orderBy?: string;
};

const commonTranslationHelp = "Use JSON translations, e.g. {\"en-US\":\"Name\",\"fa-IR\":\"نام\"}.";

export const providerResourceConfigs: ProviderResourceConfig[] = [
  {
    key: "provider-certifications",
    label: "Provider certification",
    pluralLabel: "Provider certifications",
    description: "Licenses, awards and visible certifications for the provider page.",
    group: "Profile",
    table: "category.provider_certifications",
    idColumn: "id",
    ownership: { kind: "provider", providerColumn: "service_provider_id" },
    permission: "manageProfile",
    create: true,
    update: true,
    delete: true,
    fields: [
      { name: "name", label: "Certification name", type: "text", required: true, list: true },
      { name: "is_verified", label: "Verified", type: "boolean", list: true, help: "Usually LSevin admin should verify this; providers can submit/update the record." },
    ],
    orderBy: "name asc",
  },
  {
    key: "provider-policies",
    label: "Provider policy",
    pluralLabel: "Provider policies",
    description: "Cancellation, refund, visit, safety and booking policy content.",
    group: "Profile",
    table: "category.provider_policies",
    idColumn: "id",
    ownership: { kind: "provider", providerColumn: "service_provider_id" },
    permission: "manageProfile",
    create: true,
    update: true,
    delete: true,
    fields: [
      { name: "provider_policy_type_id", label: "Policy type", type: "select", optionSource: "policy-types", list: true },
      { name: "type_translations", label: "Policy title translations", type: "translations", required: true, help: commonTranslationHelp, list: true },
      { name: "description_translations", label: "Policy description translations", type: "translations", required: true, help: commonTranslationHelp },
    ],
    orderBy: "create_date desc",
  },
  {
    key: "provider-gallery",
    label: "Provider media item",
    pluralLabel: "Provider gallery",
    description: "Gallery images/videos shown on the provider page.",
    group: "Profile",
    table: "category.provider_gallery_items",
    idColumn: "id",
    ownership: { kind: "provider", providerColumn: "service_provider_id" },
    permission: "manageMedia",
    create: true,
    update: true,
    delete: true,
    fields: [
      { name: "title_translations", label: "Title translations", type: "translations", required: true, help: commonTranslationHelp, list: true },
      { name: "description_translations", label: "Description translations", type: "translations", required: true, help: commonTranslationHelp },
      { name: "url", label: "Media URL", type: "text", required: true, list: true, help: "Use the URL returned by the media picker/upload endpoint." },
      { name: "media_type", label: "Media type", type: "select", required: true, list: true, options: [{ value: "image", label: "Image" }, { value: "video", label: "Video" }, { value: "file", label: "File" }] },
      { name: "display_order", label: "Display order", type: "number", list: true },
    ],
    orderBy: "display_order asc, create_date desc",
  },
  {
    key: "provider-attributes",
    label: "Provider attribute value",
    pluralLabel: "Provider attributes",
    description: "Provider type specific attribute values shown on the provider profile.",
    group: "Profile",
    table: "category.provider_attributes",
    idColumn: "id",
    ownership: { kind: "provider", providerColumn: "service_provider_id" },
    permission: "manageProfile",
    create: true,
    update: true,
    delete: true,
    fields: [
      { name: "attribute_definition_id", label: "Attribute definition ID", type: "text", required: true, list: true },
      { name: "value_translations", label: "Value translations", type: "translations", required: true, help: commonTranslationHelp, list: true },
    ],
    orderBy: "create_date desc",
  },
  {
    key: "services",
    label: "Service",
    pluralLabel: "Services",
    description: "Provider-owned services, pricing, timing, image and merchandising metadata.",
    group: "Services",
    table: "category.provider_services",
    idColumn: "id",
    ownership: { kind: "provider", providerColumn: "service_provider_id" },
    permission: "manageServices",
    create: true,
    update: true,
    delete: true,
    softDeleteColumn: "is_active",
    fields: [
      { name: "service_definition_id", label: "Service definition", type: "select", optionSource: "service-definitions", required: true, list: true },
      { name: "display_name_translations", label: "Display name translations", type: "translations", required: true, help: commonTranslationHelp, list: true },
      { name: "description_translations", label: "Description translations", type: "translations", required: true, help: commonTranslationHelp },
      { name: "currency", label: "Currency", type: "select", optionSource: "currencies", required: true, list: true },
      { name: "value", label: "Price", type: "number", required: true, list: true },
      { name: "duration_minutes", label: "Duration minutes", type: "number", list: true },
      { name: "slot_interval_minutes", label: "Slot interval minutes", type: "number" },
      { name: "image_url", label: "Image URL", type: "text", list: true },
      { name: "recovery", label: "Recovery", type: "text" },
      { name: "anesthesia", label: "Anesthesia", type: "text" },
      { name: "stay_required", label: "Stay required", type: "text" },
      { name: "success_rate", label: "Success rate", type: "text" },
      { name: "satisfaction", label: "Satisfaction", type: "text" },
      { name: "tags", label: "Tags", type: "csv", help: "Comma separated values." },
      { name: "is_popular", label: "Popular", type: "boolean", list: true },
      { name: "is_active", label: "Active", type: "boolean", list: true },
    ],
    orderBy: "create_date desc",
  },
  {
    key: "service-gallery",
    label: "Service gallery item",
    pluralLabel: "Service gallery",
    description: "Images/videos belonging to individual provider services.",
    group: "Services",
    table: "category.provider_service_gallery_items",
    idColumn: "id",
    ownership: { kind: "providerService", serviceColumn: "provider_service_id" },
    permission: "manageServices",
    create: true,
    update: true,
    delete: true,
    fields: [
      { name: "provider_service_id", label: "Provider service", type: "select", optionSource: "provider-services", required: true, list: true },
      { name: "title_translations", label: "Title translations", type: "translations", help: commonTranslationHelp, list: true },
      { name: "description_translations", label: "Description translations", type: "translations", help: commonTranslationHelp },
      { name: "url", label: "Media URL", type: "text", required: true, list: true },
      { name: "media_type", label: "Media type", type: "select", required: true, list: true, options: [{ value: "image", label: "Image" }, { value: "video", label: "Video" }, { value: "file", label: "File" }] },
      { name: "is_primary", label: "Primary", type: "boolean", list: true },
      { name: "display_order", label: "Display order", type: "number", list: true },
    ],
    orderBy: "display_order asc, create_date desc",
  },
  {
    key: "service-included",
    label: "Included item",
    pluralLabel: "Service included items",
    description: "What is included in each provider service.",
    group: "Services",
    table: "category.service_included",
    idColumn: "id",
    ownership: { kind: "providerService", serviceColumn: "service_id" },
    permission: "manageServices",
    create: true,
    update: true,
    delete: true,
    fields: [
      { name: "service_id", label: "Provider service", type: "select", optionSource: "provider-services", required: true, list: true },
      { name: "item", label: "Included item", type: "text", required: true, list: true },
    ],
    orderBy: "item asc",
  },
  {
    key: "service-process",
    label: "Process step",
    pluralLabel: "Service process steps",
    description: "Timeline/process steps displayed on service detail pages.",
    group: "Services",
    table: "category.service_process",
    idColumn: "id",
    ownership: { kind: "providerService", serviceColumn: "service_id" },
    permission: "manageServices",
    create: true,
    update: true,
    delete: true,
    fields: [
      { name: "service_id", label: "Provider service", type: "select", optionSource: "provider-services", required: true, list: true },
      { name: "step", label: "Step", type: "number", required: true, list: true },
      { name: "title", label: "Title", type: "text", list: true },
      { name: "description", label: "Description", type: "textarea" },
      { name: "duration", label: "Duration", type: "text", list: true },
    ],
    orderBy: "step asc",
  },
  {
    key: "service-faqs",
    label: "Service FAQ",
    pluralLabel: "Service FAQs",
    description: "Questions and answers displayed on service detail pages.",
    group: "Services",
    table: "category.service_faqs",
    idColumn: "id",
    ownership: { kind: "providerService", serviceColumn: "service_id" },
    permission: "manageServices",
    create: true,
    update: true,
    delete: true,
    fields: [
      { name: "service_id", label: "Provider service", type: "select", optionSource: "provider-services", required: true, list: true },
      { name: "question", label: "Question", type: "text", required: true, list: true },
      { name: "answer", label: "Answer", type: "textarea" },
    ],
    orderBy: "question asc",
  },
  {
    key: "service-attribute-values",
    label: "Service attribute value",
    pluralLabel: "Service attribute values",
    description: "Service-specific dynamic attributes and values.",
    group: "Services",
    table: "category.service_attribute_values",
    idColumn: "id",
    ownership: { kind: "providerService", serviceColumn: "provider_service_id" },
    permission: "manageServices",
    create: true,
    update: true,
    delete: true,
    fields: [
      { name: "provider_service_id", label: "Provider service", type: "select", optionSource: "provider-services", required: true, list: true },
      { name: "attribute_definition_id", label: "Attribute definition ID", type: "text", required: true, list: true },
      { name: "value_translations", label: "Value translations", type: "translations", required: true, help: commonTranslationHelp, list: true },
    ],
    orderBy: "create_date desc",
  },
  {
    key: "provider-staff-links",
    label: "Provider staff link",
    pluralLabel: "Provider staff links",
    description: "Links staff/specialists to this provider.",
    group: "Staff",
    table: "category.provider_staffs",
    idColumn: "id",
    ownership: { kind: "provider", providerColumn: "service_provider_id" },
    permission: "manageStaff",
    create: true,
    update: true,
    delete: true,
    softDeleteColumn: "is_active",
    fields: [
      { name: "staff_id", label: "Staff", type: "select", optionSource: "all-staff", required: true, list: true },
      { name: "notes_translations", label: "Provider notes translations", type: "translations", required: true, help: commonTranslationHelp },
      { name: "is_active", label: "Active", type: "boolean", list: true },
    ],
    orderBy: "create_date desc",
  },
  {
    key: "staff-profiles",
    label: "Staff profile",
    pluralLabel: "Staff profiles",
    description: "Staff/specialist profile fields. Only staff linked to this provider are visible/editable.",
    group: "Staff",
    table: "category.staff",
    idColumn: "id",
    ownership: { kind: "staff", staffColumn: "id" },
    permission: "manageStaff",
    create: false,
    update: true,
    delete: false,
    fields: [
      { name: "name_translations", label: "Name translations", type: "translations", required: true, help: commonTranslationHelp, list: true },
      { name: "title_translations", label: "Title translations", type: "translations", required: true, help: commonTranslationHelp, list: true },
      { name: "biography_translations", label: "Biography translations", type: "translations", required: true, help: commonTranslationHelp },
      { name: "profile_image_url", label: "Profile image URL", type: "text", list: true },
      { name: "specialty", label: "Specialty", type: "text", list: true },
      { name: "specialty_translations", label: "Specialty translations", type: "translations", help: commonTranslationHelp },
      { name: "experience", label: "Experience label", type: "text" },
      { name: "experience_years", label: "Experience years", type: "number", list: true },
      { name: "consultation_fee", label: "Consultation fee", type: "number", list: true },
      { name: "success_rate", label: "Success rate", type: "text" },
      { name: "is_active", label: "Active", type: "boolean", list: true },
    ],
    orderBy: "create_date desc",
  },
  {
    key: "staff-certifications",
    label: "Staff certification",
    pluralLabel: "Staff certifications",
    description: "Certifications connected to provider staff.",
    group: "Staff",
    table: "category.staff_certifications",
    idColumn: "id",
    ownership: { kind: "staff", staffColumn: "staff_id" },
    permission: "manageStaff",
    create: true,
    update: true,
    delete: true,
    fields: [
      { name: "staff_id", label: "Staff", type: "select", optionSource: "provider-staff", required: true, list: true },
      { name: "name", label: "Certification name", type: "text", required: true, list: true },
      { name: "issuer", label: "Issuer", type: "text", list: true },
      { name: "is_verified", label: "Verified", type: "boolean", list: true },
    ],
    orderBy: "create_date desc",
  },
  {
    key: "staff-credentials",
    label: "Staff credential",
    pluralLabel: "Staff credentials",
    description: "Staff credentials displayed on staff profiles.",
    group: "Staff",
    table: "category.staff_credentials",
    idColumn: "id",
    ownership: { kind: "staff", staffColumn: "staff_id" },
    permission: "manageStaff",
    create: true,
    update: true,
    delete: true,
    fields: [
      { name: "staff_id", label: "Staff", type: "select", optionSource: "provider-staff", required: true, list: true },
      { name: "credential", label: "Credential", type: "text", required: true, list: true },
      { name: "is_verified", label: "Verified", type: "boolean", list: true },
    ],
    orderBy: "credential asc",
  },
  {
    key: "staff-education",
    label: "Staff education",
    pluralLabel: "Staff education",
    description: "Education records connected to provider staff.",
    group: "Staff",
    table: "category.staff_education",
    idColumn: "id",
    ownership: { kind: "staff", staffColumn: "staff_id" },
    permission: "manageStaff",
    create: true,
    update: true,
    delete: true,
    fields: [
      { name: "staff_id", label: "Staff", type: "select", optionSource: "provider-staff", required: true, list: true },
      { name: "degree", label: "Degree", type: "text", required: true, list: true },
      { name: "institution", label: "Institution", type: "text", required: true, list: true },
      { name: "year", label: "Year", type: "number", list: true },
    ],
    orderBy: "year desc nulls last, create_date desc",
  },
  {
    key: "staff-achievements",
    label: "Staff achievement",
    pluralLabel: "Staff achievements",
    description: "Achievements/awards for provider staff.",
    group: "Staff",
    table: "category.staff_achievements",
    idColumn: "id",
    ownership: { kind: "staff", staffColumn: "staff_id" },
    permission: "manageStaff",
    create: true,
    update: true,
    delete: true,
    fields: [
      { name: "staff_id", label: "Staff", type: "select", optionSource: "provider-staff", required: true, list: true },
      { name: "icon", label: "Icon", type: "text" },
      { name: "title", label: "Title", type: "text", required: true, list: true },
      { name: "organization", label: "Organization", type: "text", list: true },
      { name: "display_order", label: "Display order", type: "number", list: true },
    ],
    orderBy: "display_order asc, create_date desc",
  },
  {
    key: "staff-gallery",
    label: "Staff gallery item",
    pluralLabel: "Staff gallery",
    description: "Media attached to provider staff profiles.",
    group: "Staff",
    table: "category.staff_gallery_items",
    idColumn: "id",
    ownership: { kind: "staff", staffColumn: "staff_id" },
    permission: "manageStaff",
    create: true,
    update: true,
    delete: true,
    fields: [
      { name: "staff_id", label: "Staff", type: "select", optionSource: "provider-staff", required: true, list: true },
      { name: "title_translations", label: "Title translations", type: "translations", help: commonTranslationHelp, list: true },
      { name: "description_translations", label: "Description translations", type: "translations", help: commonTranslationHelp },
      { name: "url", label: "Media URL", type: "text", required: true, list: true },
      { name: "media_type", label: "Media type", type: "select", options: [{ value: "image", label: "Image" }, { value: "video", label: "Video" }, { value: "file", label: "File" }], list: true },
      { name: "is_primary", label: "Primary", type: "boolean", list: true },
      { name: "display_order", label: "Display order", type: "number", list: true },
    ],
    orderBy: "display_order asc, create_date desc",
  },
  {
    key: "staff-before-after",
    label: "Before/after item",
    pluralLabel: "Staff before/after gallery",
    description: "Before/after media shown under provider staff profiles.",
    group: "Staff",
    table: "category.staff_before_after",
    idColumn: "id",
    ownership: { kind: "staff", staffColumn: "staff_id" },
    permission: "manageStaff",
    create: true,
    update: true,
    delete: true,
    fields: [
      { name: "staff_id", label: "Staff", type: "select", optionSource: "provider-staff", required: true, list: true },
      { name: "before_image", label: "Before image URL", type: "text", required: true, list: true },
      { name: "after_image", label: "After image URL", type: "text", required: true, list: true },
      { name: "procedure", label: "Procedure", type: "text", list: true },
      { name: "months", label: "Months", type: "number" },
      { name: "display_order", label: "Display order", type: "number", list: true },
    ],
    orderBy: "display_order asc, create_date desc",
  },
  {
    key: "staff-availability",
    label: "Staff availability",
    pluralLabel: "Staff availability",
    description: "Recurring or date-specific availability for provider staff.",
    group: "Scheduling",
    table: "category.staff_availabilities",
    idColumn: "id",
    ownership: { kind: "staff", staffColumn: "staff_id" },
    permission: "manageAvailability",
    create: true,
    update: true,
    delete: true,
    fields: [
      { name: "staff_id", label: "Staff", type: "select", optionSource: "provider-staff", required: true, list: true },
      { name: "day_of_week", label: "Day of week", type: "number", required: true, list: true, help: "1 = Monday, 7 = Sunday." },
      { name: "is_recurring", label: "Recurring", type: "boolean", list: true },
      { name: "availability_status_id", label: "Availability status", type: "select", optionSource: "availability-statuses", required: true, list: true },
      { name: "specific_date", label: "Specific date", type: "datetime", list: true },
      { name: "start_time", label: "Start time interval", type: "text", required: true, help: "Postgres interval format, e.g. 09:00:00." },
      { name: "end_time", label: "End time interval", type: "text", required: true, help: "Postgres interval format, e.g. 17:00:00." },
    ],
    orderBy: "day_of_week asc, start_time asc",
  },
  {
    key: "staff-services",
    label: "Staff service link",
    pluralLabel: "Staff service links",
    description: "Services each staff member can provide.",
    group: "Staff",
    table: "category.staff_services",
    idColumn: "id",
    ownership: { kind: "staff", staffColumn: "staff_id" },
    permission: "manageStaff",
    create: true,
    update: true,
    delete: true,
    softDeleteColumn: "is_active",
    fields: [
      { name: "staff_id", label: "Staff", type: "select", optionSource: "provider-staff", required: true, list: true },
      { name: "service_definition_id", label: "Service definition", type: "select", optionSource: "service-definitions", required: true, list: true },
      { name: "notes_translations", label: "Notes translations", type: "translations", required: true, help: commonTranslationHelp },
      { name: "is_active", label: "Active", type: "boolean", list: true },
    ],
    orderBy: "create_date desc",
  },
  {
    key: "operating-hours",
    label: "Operating hour",
    pluralLabel: "Provider operating hours",
    description: "Opening hours and slot interval for the provider location.",
    group: "Scheduling",
    table: "provider_portal.provider_operating_hours",
    idColumn: "id",
    ownership: { kind: "provider", providerColumn: "service_provider_id" },
    permission: "manageAvailability",
    create: true,
    update: true,
    delete: true,
    fields: [
      { name: "day_of_week", label: "Day of week", type: "number", required: true, list: true, help: "1 = Monday, 7 = Sunday." },
      { name: "opens_at", label: "Opens at", type: "time", list: true },
      { name: "closes_at", label: "Closes at", type: "time", list: true },
      { name: "is_closed", label: "Closed", type: "boolean", list: true },
      { name: "slot_interval_minutes", label: "Slot interval minutes", type: "number", list: true },
      { name: "metadata", label: "Metadata", type: "json" },
    ],
    orderBy: "day_of_week asc",
  },
  {
    key: "offers",
    label: "Offer",
    pluralLabel: "Offers",
    description: "Promotional offers for provider services.",
    group: "Commercial",
    table: "marketing.offers",
    idColumn: "id",
    idType: "integer",
    ownership: { kind: "providerService", serviceColumn: "provider_service_id" },
    permission: "manageOffers",
    create: true,
    update: true,
    delete: true,
    softDeleteColumn: "is_active",
    fields: [
      { name: "provider_service_id", label: "Provider service", type: "select", optionSource: "provider-services", required: true, list: true },
      { name: "title", label: "Title", type: "text", required: true, list: true },
      { name: "subtitle", label: "Subtitle", type: "text", list: true },
      { name: "description_translations", label: "Description translations", type: "translations", help: commonTranslationHelp },
      { name: "discount_percent", label: "Discount percent", type: "number", required: true, list: true },
      { name: "valid_until", label: "Valid until", type: "datetime", required: true, list: true },
      { name: "code", label: "Code", type: "text", list: true },
      { name: "usage_limit", label: "Usage limit", type: "number" },
      { name: "is_featured", label: "Featured", type: "boolean", list: true },
      { name: "is_active", label: "Active", type: "boolean", list: true },
    ],
    orderBy: "created_at desc",
  },
  {
    key: "payout-accounts",
    label: "Payout account",
    pluralLabel: "Payout accounts",
    description: "Provider bank/payout accounts.",
    group: "Commercial",
    table: "provider_portal.payout_accounts",
    idColumn: "id",
    ownership: { kind: "provider", providerColumn: "service_provider_id" },
    permission: "managePayouts",
    create: true,
    update: true,
    delete: true,
    fields: [
      { name: "account_holder_name", label: "Account holder name", type: "text", required: true, list: true },
      { name: "bank_name", label: "Bank name", type: "text", list: true },
      { name: "iban", label: "IBAN", type: "text" },
      { name: "swift_code", label: "SWIFT code", type: "text" },
      { name: "account_number_last4", label: "Account number last 4", type: "text", list: true },
      { name: "country", label: "Country", type: "text", list: true },
      { name: "currency_code", label: "Currency", type: "select", optionSource: "currencies", required: true, list: true },
      { name: "is_default", label: "Default", type: "boolean", list: true },
      { name: "metadata", label: "Metadata", type: "json" },
    ],
    orderBy: "is_default desc, create_date desc",
  },
  {
    key: "support-tickets",
    label: "Support ticket",
    pluralLabel: "Support tickets",
    description: "Provider support tickets with LSevin operations.",
    group: "Support",
    table: "provider_portal.support_tickets",
    idColumn: "id",
    ownership: { kind: "provider", providerColumn: "service_provider_id" },
    permission: "manageSupport",
    create: true,
    update: true,
    delete: true,
    fields: [
      { name: "subject", label: "Subject", type: "text", required: true, list: true },
      { name: "message", label: "Message", type: "textarea", required: true },
      { name: "status", label: "Status", type: "select", list: true, options: [{ value: "open", label: "Open" }, { value: "in_progress", label: "In progress" }, { value: "resolved", label: "Resolved" }, { value: "closed", label: "Closed" }] },
      { name: "priority", label: "Priority", type: "select", list: true, options: [{ value: "low", label: "Low" }, { value: "normal", label: "Normal" }, { value: "high", label: "High" }, { value: "urgent", label: "Urgent" }] },
      { name: "metadata", label: "Metadata", type: "json" },
    ],
    orderBy: "create_date desc",
  },
  {
    key: "bookings",
    label: "Booking",
    pluralLabel: "Bookings",
    description: "Provider-owned bookings. Providers can update status/notes, not create customer bookings.",
    group: "Customer",
    table: "booking.bookings",
    idColumn: "id",
    ownership: { kind: "booking", providerColumn: "provider_id" },
    permission: "manageBookings",
    create: false,
    update: true,
    delete: false,
    fields: [
      { name: "booking_status", label: "Booking status", type: "select", list: true, options: [{ value: "Pending", label: "Pending" }, { value: "Confirmed", label: "Confirmed" }, { value: "Cancelled", label: "Cancelled" }, { value: "Completed", label: "Completed" }] },
      { name: "payment_status", label: "Payment status", type: "text", list: true, readOnly: true },
      { name: "provider_notes", label: "Provider notes", type: "textarea" },
      { name: "selected_date", label: "Selected date", type: "date", list: true, readOnly: true },
      { name: "selected_time", label: "Selected time", type: "time", list: true, readOnly: true },
      { name: "total_amount", label: "Total amount", type: "number", list: true, readOnly: true },
      { name: "currency_code", label: "Currency", type: "text", list: true, readOnly: true },
    ],
    orderBy: "create_date desc",
  },
  {
    key: "reviews",
    label: "Review",
    pluralLabel: "Provider reviews",
    description: "Provider reviews/comments. Provider can moderate public visibility if allowed.",
    group: "Customer",
    table: "category.service_provider_comments",
    idColumn: "id",
    ownership: { kind: "provider", providerColumn: "service_provider_id" },
    permission: "viewReviews",
    create: false,
    update: true,
    delete: false,
    fields: [
      { name: "customer_name", label: "Customer", type: "text", list: true, readOnly: true },
      { name: "comment_text", label: "Comment", type: "textarea", readOnly: true, list: true },
      { name: "rating", label: "Rating", type: "number", list: true, readOnly: true },
      { name: "country", label: "Country", type: "text", list: true, readOnly: true },
      { name: "treatment", label: "Treatment", type: "text", list: true, readOnly: true },
      { name: "is_public", label: "Public", type: "boolean", list: true },
      { name: "is_verified", label: "Verified", type: "boolean", list: true, readOnly: true },
    ],
    orderBy: "create_date desc",
  },
  {
    key: "customer-requests",
    label: "Customer request",
    pluralLabel: "Customer requests",
    description: "Incoming provider requests/leads from customers.",
    group: "Customer",
    table: "category.service_provider_requests",
    idColumn: "id",
    ownership: { kind: "provider", providerColumn: "service_provider_id" },
    permission: "manageBookings",
    create: false,
    update: true,
    delete: false,
    fields: [
      { name: "customer_full_name", label: "Customer", type: "text", list: true, readOnly: true },
      { name: "customer_email", label: "Email", type: "text", list: true, readOnly: true },
      { name: "message", label: "Message", type: "textarea", readOnly: true },
      { name: "request_status_id", label: "Request status ID", type: "number", list: true },
    ],
    orderBy: "create_date desc",
  },
  {
    key: "provider-ledger",
    label: "Ledger entry",
    pluralLabel: "Provider ledger",
    description: "Provider earning/payout ledger. Financial rows are read-only for providers.",
    group: "Commercial",
    table: "commercial.provider_ledgers",
    idColumn: "id",
    ownership: { kind: "provider", providerColumn: "provider_id" },
    permission: "viewBilling",
    create: false,
    update: false,
    delete: false,
    fields: [
      { name: "entry_type", label: "Type", type: "text", list: true, readOnly: true },
      { name: "amount", label: "Amount", type: "number", list: true, readOnly: true },
      { name: "currency_code", label: "Currency", type: "text", list: true, readOnly: true },
      { name: "status", label: "Status", type: "text", list: true, readOnly: true },
      { name: "notes", label: "Notes", type: "textarea", readOnly: true },
    ],
    orderBy: "created_at desc",
  },
  {
    key: "invoices",
    label: "Invoice",
    pluralLabel: "Provider invoices",
    description: "Provider portal invoices. Read-only for providers.",
    group: "Commercial",
    table: "provider_portal.portal_invoices",
    idColumn: "id",
    ownership: { kind: "provider", providerColumn: "service_provider_id" },
    permission: "viewBilling",
    create: false,
    update: false,
    delete: false,
    fields: [
      { name: "billing_period_start", label: "Period start", type: "date", list: true, readOnly: true },
      { name: "billing_period_end", label: "Period end", type: "date", list: true, readOnly: true },
      { name: "currency_code", label: "Currency", type: "text", list: true, readOnly: true },
      { name: "subtotal", label: "Subtotal", type: "number", list: true, readOnly: true },
      { name: "tax_total", label: "Tax", type: "number", list: true, readOnly: true },
      { name: "total", label: "Total", type: "number", list: true, readOnly: true },
      { name: "status", label: "Status", type: "text", list: true, readOnly: true },
      { name: "pdf_url", label: "PDF URL", type: "text", list: true, readOnly: true },
    ],
    orderBy: "create_date desc",
  },
  {
    key: "provider-languages",
    label: "Provider language",
    pluralLabel: "Provider languages",
    description: "Languages spoken by the provider/team and shown on the provider page.",
    group: "Profile",
    table: "category.provider_languages",
    idColumn: "id",
    ownership: { kind: "provider", providerColumn: "service_provider_id" },
    permission: "manageProfile",
    create: true,
    update: true,
    delete: true,
    fields: [{ name: "language", label: "Language", type: "text", required: true, list: true }],
    orderBy: "language asc",
  },
  {
    key: "service-addons",
    label: "Service add-on setting",
    pluralLabel: "Service add-ons",
    description: "Enable/disable service add-ons and override provider-specific add-on price/config.",
    group: "Services",
    table: "provider_portal.provider_service_addon_settings",
    idColumn: "id",
    ownership: { kind: "providerService", serviceColumn: "provider_service_id" },
    permission: "manageServices",
    create: true,
    update: true,
    delete: true,
    fields: [
      { name: "provider_service_id", label: "Provider service", type: "select", optionSource: "provider-services", required: true, list: true },
      { name: "addon_id", label: "Add-on", type: "select", optionSource: "addons", required: true, list: true },
      { name: "is_enabled", label: "Enabled", type: "boolean", list: true },
      { name: "custom_price", label: "Custom price", type: "number", list: true },
      { name: "custom_config", label: "Custom config", type: "json" },
    ],
    orderBy: "create_date desc",
  },
  {
    key: "staff-languages",
    label: "Staff language",
    pluralLabel: "Staff languages",
    description: "Languages spoken by provider staff/specialists.",
    group: "Staff",
    table: "category.staff_languages",
    idColumn: "id",
    ownership: { kind: "staff", staffColumn: "staff_id" },
    permission: "manageStaff",
    create: true,
    update: true,
    delete: true,
    fields: [
      { name: "staff_id", label: "Staff", type: "select", optionSource: "provider-staff", required: true, list: true },
      { name: "language", label: "Language", type: "text", required: true, list: true },
    ],
    orderBy: "language asc",
  },
  {
    key: "staff-specializations",
    label: "Staff specialization",
    pluralLabel: "Staff specializations",
    description: "Specialization tags for provider staff/specialists.",
    group: "Staff",
    table: "category.staff_specializations",
    idColumn: "id",
    ownership: { kind: "staff", staffColumn: "staff_id" },
    permission: "manageStaff",
    create: true,
    update: true,
    delete: true,
    fields: [
      { name: "staff_id", label: "Staff", type: "select", optionSource: "provider-staff", required: true, list: true },
      { name: "specialty", label: "Specialty", type: "text", required: true, list: true },
    ],
    orderBy: "specialty asc",
  },
];

export function getProviderResourceConfig(resourceKey: string) {
  return providerResourceConfigs.find((resource) => resource.key === resourceKey) ?? null;
}

export function getProviderResourceGroups() {
  return providerResourceConfigs.reduce<Record<string, ProviderResourceConfig[]>>((acc, resource) => {
    acc[resource.group] ||= [];
    acc[resource.group].push(resource);
    return acc;
  }, {});
}
