/* tslint:disable */
/* eslint-disable */


/**
 * AUTO-GENERATED FILE - DO NOT EDIT!
 *
 * This file was automatically generated by pg-to-ts v.4.1.1
 * $ pg-to-ts generate -c postgres://username:password@62.60.212.187:5432/lsevin -t __EFMigrationsHistory -t addon_details -t addons -t attribute_types -t categories -t category_groups -t currencies -t Currency -t inbox_message_consumers -t inbox_messages -t internal_command_message_consumers -t internal_command_messages -t locations -t LocationType -t outbox_message_consumers -t outbox_messages -t provider_attribute_definition_domain_options -t provider_attribute_definitions -t provider_attributes -t provider_certifications -t provider_gallery_items -t provider_languages -t provider_policies -t provider_recommendations -t provider_service_addons -t provider_service_gallery_items -t provider_services -t provider_staffs -t provider_types -t review_images -t service_attribute_definition_options -t service_attribute_definitions -t service_attribute_values -t service_definition_domain_requirements -t service_definitions -t service_faqs -t service_included -t service_process -t service_provider_comments -t service_provider_grades -t service_provider_request_statuses -t service_provider_requests -t service_providers -t service_upload_file_requirements -t staff -t staff_achievements -t staff_availabilities -t staff_availability_statuses -t staff_before_after -t staff_certifications -t staff_credentials -t staff_education -t staff_gallery_items -t staff_languages -t staff_services -t staff_specializations -s category
 *
 */


export type Json = unknown;

// Table __EFMigrationsHistory
export interface EFMigrationsHistory {
  migration_id: string;
  product_version: string;
}
export interface EFMigrationsHistoryInput {
  migration_id: string;
  product_version: string;
}
const __EFMigrationsHistory = {
  tableName: '__EFMigrationsHistory',
  columns: ['migration_id', 'product_version'],
  requiredForInsert: ['migration_id', 'product_version'],
  primaryKey: 'migration_id',
  foreignKeys: {},
  $type: null as unknown as EFMigrationsHistory,
  $input: null as unknown as EFMigrationsHistoryInput
} as const;

// Table addon_details
export interface AddonDetails {
  id: string;
  addon_id: string;
  detail: string;
  display_order: number;
}
export interface AddonDetailsInput {
  id?: string;
  addon_id: string;
  detail: string;
  display_order?: number;
}
const addon_details = {
  tableName: 'addon_details',
  columns: ['id', 'addon_id', 'detail', 'display_order'],
  requiredForInsert: ['addon_id', 'detail'],
  primaryKey: 'id',
  foreignKeys: { addon_id: { table: 'addons', column: 'id', $type: null as unknown as Addons }, },
  $type: null as unknown as AddonDetails,
  $input: null as unknown as AddonDetailsInput
} as const;

// Table addons
export interface Addons {
  id: string;
  name: string;
  description: string;
  price: number;
  icon: string;
  popular: boolean | null;
  create_date: Date;
  last_modified_date: Date | null;
}
export interface AddonsInput {
  id: string;
  name: string;
  description?: string;
  price?: number;
  icon?: string;
  popular?: boolean | null;
  create_date?: Date;
  last_modified_date?: Date | null;
}
const addons = {
  tableName: 'addons',
  columns: ['id', 'name', 'description', 'price', 'icon', 'popular', 'create_date', 'last_modified_date'],
  requiredForInsert: ['id', 'name'],
  primaryKey: 'id',
  foreignKeys: {},
  $type: null as unknown as Addons,
  $input: null as unknown as AddonsInput
} as const;

// Table attribute_types
export interface AttributeTypes {
  id: number;
  name: string;
}
export interface AttributeTypesInput {
  id: number;
  name: string;
}
const attribute_types = {
  tableName: 'attribute_types',
  columns: ['id', 'name'],
  requiredForInsert: ['id', 'name'],
  primaryKey: 'id',
  foreignKeys: {},
  $type: null as unknown as AttributeTypes,
  $input: null as unknown as AttributeTypesInput
} as const;

// Table categories
export interface Categories {
  id: string;
  name_translations: Json;
  description_translations: Json;
  parent_id: string | null;
  display_order: number;
  is_active: boolean;
  icon_url: string | null;
  create_date: Date;
  last_modified_date: Date | null;
  group_id: number | null;
  image_url: string | null;
  gradient: string | null;
  icon: string | null;
}
export interface CategoriesInput {
  id: string;
  name_translations: Json;
  description_translations: Json;
  parent_id?: string | null;
  display_order?: number;
  is_active: boolean;
  icon_url?: string | null;
  create_date?: Date;
  last_modified_date?: Date | null;
  group_id?: number | null;
  image_url?: string | null;
  gradient?: string | null;
  icon?: string | null;
}
const categories = {
  tableName: 'categories',
  columns: ['id', 'name_translations', 'description_translations', 'parent_id', 'display_order', 'is_active', 'icon_url', 'create_date', 'last_modified_date', 'group_id', 'image_url', 'gradient', 'icon'],
  requiredForInsert: ['id', 'name_translations', 'description_translations', 'is_active'],
  primaryKey: 'id',
  foreignKeys: {
    parent_id: { table: 'categories', column: 'id', $type: null as unknown as Categories },
    group_id: { table: 'category_groups', column: 'id', $type: null as unknown as CategoryGroups },
  },
  $type: null as unknown as Categories,
  $input: null as unknown as CategoriesInput
} as const;

// Table category_groups
export interface CategoryGroups {
  id: number;
  title: string;
}
export interface CategoryGroupsInput {
  id?: number;
  title: string;
}
const category_groups = {
  tableName: 'category_groups',
  columns: ['id', 'title'],
  requiredForInsert: ['title'],
  primaryKey: 'id',
  foreignKeys: {},
  $type: null as unknown as CategoryGroups,
  $input: null as unknown as CategoryGroupsInput
} as const;

// Table currencies
export interface Currencies {
  symbol: string;
  name: string;
  create_date: Date;
  last_modified_date: Date | null;
  id: string;
  price: number;
}
export interface CurrenciesInput {
  symbol: string;
  name?: string;
  create_date?: Date;
  last_modified_date?: Date | null;
  id?: string;
  price?: number;
}
const currencies = {
  tableName: 'currencies',
  columns: ['symbol', 'name', 'create_date', 'last_modified_date', 'id', 'price'],
  requiredForInsert: ['symbol'],
  primaryKey: 'id',
  foreignKeys: {},
  $type: null as unknown as Currencies,
  $input: null as unknown as CurrenciesInput
} as const;

// Table Currency
export interface Currency {
  Id: number;
  Price: number | null;
  Symbol: string | null;
}
export interface CurrencyInput {
  Id: number;
  Price?: number | null;
  Symbol?: string | null;
}
const Currency = {
  tableName: 'Currency',
  columns: ['Id', 'Price', 'Symbol'],
  requiredForInsert: ['Id'],
  primaryKey: null,
  foreignKeys: {},
  $type: null as unknown as Currency,
  $input: null as unknown as CurrencyInput
} as const;

// Table inbox_message_consumers
export interface InboxMessageConsumers {
  message_id: string;
  name: string;
}
export interface InboxMessageConsumersInput {
  message_id: string;
  name: string;
}
const inbox_message_consumers = {
  tableName: 'inbox_message_consumers',
  columns: ['message_id', 'name'],
  requiredForInsert: ['message_id', 'name'],
  primaryKey: 'message_id',
  foreignKeys: {},
  $type: null as unknown as InboxMessageConsumers,
  $input: null as unknown as InboxMessageConsumersInput
} as const;

// Table inbox_messages
export interface InboxMessages {
  id: string;
  type: string;
  content: Json;
  occurred_on_utc: Date;
  processed_on_utc: Date | null;
  error: string | null;
}
export interface InboxMessagesInput {
  id: string;
  type: string;
  content: Json;
  occurred_on_utc: Date;
  processed_on_utc?: Date | null;
  error?: string | null;
}
const inbox_messages = {
  tableName: 'inbox_messages',
  columns: ['id', 'type', 'content', 'occurred_on_utc', 'processed_on_utc', 'error'],
  requiredForInsert: ['id', 'type', 'content', 'occurred_on_utc'],
  primaryKey: 'id',
  foreignKeys: {},
  $type: null as unknown as InboxMessages,
  $input: null as unknown as InboxMessagesInput
} as const;

// Table internal_command_message_consumers
export interface InternalCommandMessageConsumers {
  message_id: string;
  name: string;
}
export interface InternalCommandMessageConsumersInput {
  message_id: string;
  name: string;
}
const internal_command_message_consumers = {
  tableName: 'internal_command_message_consumers',
  columns: ['message_id', 'name'],
  requiredForInsert: ['message_id', 'name'],
  primaryKey: 'message_id',
  foreignKeys: {},
  $type: null as unknown as InternalCommandMessageConsumers,
  $input: null as unknown as InternalCommandMessageConsumersInput
} as const;

// Table internal_command_messages
export interface InternalCommandMessages {
  id: string;
  type: string;
  content: Json;
  occurred_on_utc: Date;
  processed_on_utc: Date | null;
  error: string | null;
}
export interface InternalCommandMessagesInput {
  id: string;
  type: string;
  content: Json;
  occurred_on_utc: Date;
  processed_on_utc?: Date | null;
  error?: string | null;
}
const internal_command_messages = {
  tableName: 'internal_command_messages',
  columns: ['id', 'type', 'content', 'occurred_on_utc', 'processed_on_utc', 'error'],
  requiredForInsert: ['id', 'type', 'content', 'occurred_on_utc'],
  primaryKey: 'id',
  foreignKeys: {},
  $type: null as unknown as InternalCommandMessages,
  $input: null as unknown as InternalCommandMessagesInput
} as const;

// Table locations
export interface Locations {
  id: string;
  code: string;
  value_translations: Json;
  location_type_id: number;
  parent_id: string | null;
  create_date: Date;
  last_modified_date: Date | null;
  display_order: number | null;
}
export interface LocationsInput {
  id: string;
  code: string;
  value_translations: Json;
  location_type_id: number;
  parent_id?: string | null;
  create_date?: Date;
  last_modified_date?: Date | null;
  display_order?: number | null;
}
const locations = {
  tableName: 'locations',
  columns: ['id', 'code', 'value_translations', 'location_type_id', 'parent_id', 'create_date', 'last_modified_date', 'display_order'],
  requiredForInsert: ['id', 'code', 'value_translations', 'location_type_id'],
  primaryKey: 'id',
  foreignKeys: {
    location_type_id: { table: 'LocationType', column: 'id', $type: null as unknown as LocationType },
    parent_id: { table: 'locations', column: 'id', $type: null as unknown as Locations },
  },
  $type: null as unknown as Locations,
  $input: null as unknown as LocationsInput
} as const;

// Table LocationType
export interface LocationType {
  id: number;
  name: string;
}
export interface LocationTypeInput {
  id: number;
  name: string;
}
const LocationType = {
  tableName: 'LocationType',
  columns: ['id', 'name'],
  requiredForInsert: ['id', 'name'],
  primaryKey: 'id',
  foreignKeys: {},
  $type: null as unknown as LocationType,
  $input: null as unknown as LocationTypeInput
} as const;

// Table outbox_message_consumers
export interface OutboxMessageConsumers {
  message_id: string;
  name: string;
}
export interface OutboxMessageConsumersInput {
  message_id: string;
  name: string;
}
const outbox_message_consumers = {
  tableName: 'outbox_message_consumers',
  columns: ['message_id', 'name'],
  requiredForInsert: ['message_id', 'name'],
  primaryKey: 'message_id',
  foreignKeys: {},
  $type: null as unknown as OutboxMessageConsumers,
  $input: null as unknown as OutboxMessageConsumersInput
} as const;

// Table outbox_messages
export interface OutboxMessages {
  id: string;
  type: string;
  content: Json;
  occurred_on_utc: Date;
  processed_on_utc: Date | null;
  error: string | null;
}
export interface OutboxMessagesInput {
  id: string;
  type: string;
  content: Json;
  occurred_on_utc: Date;
  processed_on_utc?: Date | null;
  error?: string | null;
}
const outbox_messages = {
  tableName: 'outbox_messages',
  columns: ['id', 'type', 'content', 'occurred_on_utc', 'processed_on_utc', 'error'],
  requiredForInsert: ['id', 'type', 'content', 'occurred_on_utc'],
  primaryKey: 'id',
  foreignKeys: {},
  $type: null as unknown as OutboxMessages,
  $input: null as unknown as OutboxMessagesInput
} as const;

// Table provider_attribute_definition_domain_options
export interface ProviderAttributeDefinitionDomainOptions {
  provider_attribute_definition_id: string;
  id: number;
  display_name_translations: Json;
  value_translations: Json;
}
export interface ProviderAttributeDefinitionDomainOptionsInput {
  provider_attribute_definition_id: string;
  id: number;
  display_name_translations: Json;
  value_translations: Json;
}
const provider_attribute_definition_domain_options = {
  tableName: 'provider_attribute_definition_domain_options',
  columns: ['provider_attribute_definition_id', 'id', 'display_name_translations', 'value_translations'],
  requiredForInsert: ['provider_attribute_definition_id', 'id', 'display_name_translations', 'value_translations'],
  primaryKey: 'provider_attribute_definition_id',
  foreignKeys: { provider_attribute_definition_id: { table: 'provider_attribute_definitions', column: 'id', $type: null as unknown as ProviderAttributeDefinitions }, },
  $type: null as unknown as ProviderAttributeDefinitionDomainOptions,
  $input: null as unknown as ProviderAttributeDefinitionDomainOptionsInput
} as const;

// Table provider_attribute_definitions
export interface ProviderAttributeDefinitions {
  id: string;
  name_translations: Json;
  description_translations: Json;
  attribute_type_id: number;
  is_required: boolean;
  validation_rules: string;
  provider_type_id: string;
  create_date: Date;
  last_modified_date: Date | null;
}
export interface ProviderAttributeDefinitionsInput {
  id: string;
  name_translations: Json;
  description_translations: Json;
  attribute_type_id: number;
  is_required: boolean;
  validation_rules: string;
  provider_type_id: string;
  create_date: Date;
  last_modified_date?: Date | null;
}
const provider_attribute_definitions = {
  tableName: 'provider_attribute_definitions',
  columns: ['id', 'name_translations', 'description_translations', 'attribute_type_id', 'is_required', 'validation_rules', 'provider_type_id', 'create_date', 'last_modified_date'],
  requiredForInsert: ['id', 'name_translations', 'description_translations', 'attribute_type_id', 'is_required', 'validation_rules', 'provider_type_id', 'create_date'],
  primaryKey: 'id',
  foreignKeys: {
    attribute_type_id: { table: 'attribute_types', column: 'id', $type: null as unknown as AttributeTypes },
    provider_type_id: { table: 'provider_types', column: 'id', $type: null as unknown as ProviderTypes },
  },
  $type: null as unknown as ProviderAttributeDefinitions,
  $input: null as unknown as ProviderAttributeDefinitionsInput
} as const;

// Table provider_attributes
export interface ProviderAttributes {
  id: string;
  attribute_definition_id: string;
  value_translations: Json;
  service_provider_id: string;
  create_date: Date;
  last_modified_date: Date | null;
}
export interface ProviderAttributesInput {
  id: string;
  attribute_definition_id: string;
  value_translations: Json;
  service_provider_id: string;
  create_date: Date;
  last_modified_date?: Date | null;
}
const provider_attributes = {
  tableName: 'provider_attributes',
  columns: ['id', 'attribute_definition_id', 'value_translations', 'service_provider_id', 'create_date', 'last_modified_date'],
  requiredForInsert: ['id', 'attribute_definition_id', 'value_translations', 'service_provider_id', 'create_date'],
  primaryKey: 'id',
  foreignKeys: { service_provider_id: { table: 'service_providers', column: 'id', $type: null as unknown as ServiceProviders }, },
  $type: null as unknown as ProviderAttributes,
  $input: null as unknown as ProviderAttributesInput
} as const;

// Table provider_certifications
export interface ProviderCertifications {
  id: string;
  service_provider_id: string;
  name: string;
  is_verified: boolean | null;
}
export interface ProviderCertificationsInput {
  id?: string;
  service_provider_id: string;
  name: string;
  is_verified?: boolean | null;
}
const provider_certifications = {
  tableName: 'provider_certifications',
  columns: ['id', 'service_provider_id', 'name', 'is_verified'],
  requiredForInsert: ['service_provider_id', 'name'],
  primaryKey: 'id',
  foreignKeys: {},
  $type: null as unknown as ProviderCertifications,
  $input: null as unknown as ProviderCertificationsInput
} as const;

// Table provider_gallery_items
export interface ProviderGalleryItems {
  id: string;
  title_translations: Json;
  description_translations: Json;
  url: string;
  media_type: string;
  display_order: number;
  service_provider_id: string;
  create_date: Date;
  last_modified_date: Date | null;
}
export interface ProviderGalleryItemsInput {
  id: string;
  title_translations: Json;
  description_translations: Json;
  url: string;
  media_type: string;
  display_order: number;
  service_provider_id: string;
  create_date: Date;
  last_modified_date?: Date | null;
}
const provider_gallery_items = {
  tableName: 'provider_gallery_items',
  columns: ['id', 'title_translations', 'description_translations', 'url', 'media_type', 'display_order', 'service_provider_id', 'create_date', 'last_modified_date'],
  requiredForInsert: ['id', 'title_translations', 'description_translations', 'url', 'media_type', 'display_order', 'service_provider_id', 'create_date'],
  primaryKey: 'id',
  foreignKeys: { service_provider_id: { table: 'service_providers', column: 'id', $type: null as unknown as ServiceProviders }, },
  $type: null as unknown as ProviderGalleryItems,
  $input: null as unknown as ProviderGalleryItemsInput
} as const;

// Table provider_languages
export interface ProviderLanguages {
  service_provider_id: string;
  language: string;
  create_date: Date;
}
export interface ProviderLanguagesInput {
  service_provider_id: string;
  language: string;
  create_date?: Date;
}
const provider_languages = {
  tableName: 'provider_languages',
  columns: ['service_provider_id', 'language', 'create_date'],
  requiredForInsert: ['service_provider_id', 'language'],
  primaryKey: 'service_provider_id',
  foreignKeys: { service_provider_id: { table: 'service_providers', column: 'id', $type: null as unknown as ServiceProviders }, },
  $type: null as unknown as ProviderLanguages,
  $input: null as unknown as ProviderLanguagesInput
} as const;

// Table provider_policies
export interface ProviderPolicies {
  id: string;
  type_translations: Json;
  description_translations: Json;
  service_provider_id: string;
  create_date: Date;
  last_modified_date: Date | null;
}
export interface ProviderPoliciesInput {
  id: string;
  type_translations: Json;
  description_translations: Json;
  service_provider_id: string;
  create_date: Date;
  last_modified_date?: Date | null;
}
const provider_policies = {
  tableName: 'provider_policies',
  columns: ['id', 'type_translations', 'description_translations', 'service_provider_id', 'create_date', 'last_modified_date'],
  requiredForInsert: ['id', 'type_translations', 'description_translations', 'service_provider_id', 'create_date'],
  primaryKey: 'id',
  foreignKeys: { service_provider_id: { table: 'service_providers', column: 'id', $type: null as unknown as ServiceProviders }, },
  $type: null as unknown as ProviderPolicies,
  $input: null as unknown as ProviderPoliciesInput
} as const;

// Table provider_recommendations
export interface ProviderRecommendations {
  id: string;
  source_provider_id: string;
  target_provider_id: string;
  type: string;
  create_date: Date | null;
}
export interface ProviderRecommendationsInput {
  id?: string;
  source_provider_id: string;
  target_provider_id: string;
  type: string;
  create_date?: Date | null;
}
const provider_recommendations = {
  tableName: 'provider_recommendations',
  columns: ['id', 'source_provider_id', 'target_provider_id', 'type', 'create_date'],
  requiredForInsert: ['source_provider_id', 'target_provider_id', 'type'],
  primaryKey: 'id',
  foreignKeys: {},
  $type: null as unknown as ProviderRecommendations,
  $input: null as unknown as ProviderRecommendationsInput
} as const;

// Table provider_service_addons
export interface ProviderServiceAddons {
  provider_service_id: string;
  addon_id: string;
}
export interface ProviderServiceAddonsInput {
  provider_service_id: string;
  addon_id: string;
}
const provider_service_addons = {
  tableName: 'provider_service_addons',
  columns: ['provider_service_id', 'addon_id'],
  requiredForInsert: ['provider_service_id', 'addon_id'],
  primaryKey: 'provider_service_id',
  foreignKeys: {
    provider_service_id: { table: 'provider_services', column: 'id', $type: null as unknown as ProviderServices },
    addon_id: { table: 'addons', column: 'id', $type: null as unknown as Addons },
  },
  $type: null as unknown as ProviderServiceAddons,
  $input: null as unknown as ProviderServiceAddonsInput
} as const;

// Table provider_service_gallery_items
export interface ProviderServiceGalleryItems {
  id: string;
  title_translations: Json;
  description_translations: Json;
  url: string;
  media_type: string;
  display_order: number;
  is_primary: boolean;
  provider_service_id: string;
  create_date: Date;
  last_modified_date: Date | null;
}
export interface ProviderServiceGalleryItemsInput {
  id?: string;
  title_translations?: Json;
  description_translations?: Json;
  url: string;
  media_type?: string;
  display_order?: number;
  is_primary?: boolean;
  provider_service_id: string;
  create_date?: Date;
  last_modified_date?: Date | null;
}
const provider_service_gallery_items = {
  tableName: 'provider_service_gallery_items',
  columns: ['id', 'title_translations', 'description_translations', 'url', 'media_type', 'display_order', 'is_primary', 'provider_service_id', 'create_date', 'last_modified_date'],
  requiredForInsert: ['url', 'provider_service_id'],
  primaryKey: 'id',
  foreignKeys: { provider_service_id: { table: 'provider_services', column: 'id', $type: null as unknown as ProviderServices }, },
  $type: null as unknown as ProviderServiceGalleryItems,
  $input: null as unknown as ProviderServiceGalleryItemsInput
} as const;

// Table provider_services
export interface ProviderServices {
  id: string;
  service_definition_id: string;
  display_name_translations: Json;
  description_translations: Json;
  is_active: boolean;
  service_provider_id: string;
  currency: string;
  value: number;
  create_date: Date;
  last_modified_date: Date | null;
  duration_minutes: number;
  rating: number | null;
  review_count: number | null;
  recovery: string | null;
  image_url: string | null;
  is_popular: boolean | null;
  anesthesia: string | null;
  stay_required: string | null;
  success_rate: string | null;
  satisfaction: string | null;
  trending_score: number | null;
  growth: string | null;
  search_vector: any | null;
  tags: string[] | null;
  slot_interval_minutes: number;
}
export interface ProviderServicesInput {
  id: string;
  service_definition_id: string;
  display_name_translations: Json;
  description_translations: Json;
  is_active: boolean;
  service_provider_id: string;
  currency: string;
  value: number;
  create_date: Date;
  last_modified_date?: Date | null;
  duration_minutes?: number;
  rating?: number | null;
  review_count?: number | null;
  recovery?: string | null;
  image_url?: string | null;
  is_popular?: boolean | null;
  anesthesia?: string | null;
  stay_required?: string | null;
  success_rate?: string | null;
  satisfaction?: string | null;
  trending_score?: number | null;
  growth?: string | null;
  search_vector?: any | null;
  tags?: string[] | null;
  slot_interval_minutes?: number;
}
const provider_services = {
  tableName: 'provider_services',
  columns: ['id', 'service_definition_id', 'display_name_translations', 'description_translations', 'is_active', 'service_provider_id', 'currency', 'value', 'create_date', 'last_modified_date', 'duration_minutes', 'rating', 'review_count', 'recovery', 'image_url', 'is_popular', 'anesthesia', 'stay_required', 'success_rate', 'satisfaction', 'trending_score', 'growth', 'search_vector', 'tags', 'slot_interval_minutes'],
  requiredForInsert: ['id', 'service_definition_id', 'display_name_translations', 'description_translations', 'is_active', 'service_provider_id', 'currency', 'value', 'create_date'],
  primaryKey: 'id',
  foreignKeys: {
    service_definition_id: { table: 'service_definitions', column: 'id', $type: null as unknown as ServiceDefinitions },
    service_provider_id: { table: 'service_providers', column: 'id', $type: null as unknown as ServiceProviders },
  },
  $type: null as unknown as ProviderServices,
  $input: null as unknown as ProviderServicesInput
} as const;

// Table provider_staffs
export interface ProviderStaffs {
  id: string;
  staff_id: string;
  notes_translations: Json;
  is_active: boolean;
  service_provider_id: string;
  create_date: Date;
  last_modified_date: Date | null;
}
export interface ProviderStaffsInput {
  id: string;
  staff_id: string;
  notes_translations: Json;
  is_active: boolean;
  service_provider_id: string;
  create_date: Date;
  last_modified_date?: Date | null;
}
const provider_staffs = {
  tableName: 'provider_staffs',
  columns: ['id', 'staff_id', 'notes_translations', 'is_active', 'service_provider_id', 'create_date', 'last_modified_date'],
  requiredForInsert: ['id', 'staff_id', 'notes_translations', 'is_active', 'service_provider_id', 'create_date'],
  primaryKey: 'id',
  foreignKeys: {
    staff_id: { table: 'staff', column: 'id', $type: null as unknown as Staff },
    service_provider_id: { table: 'service_providers', column: 'id', $type: null as unknown as ServiceProviders },
  },
  $type: null as unknown as ProviderStaffs,
  $input: null as unknown as ProviderStaffsInput
} as const;

// Table provider_types
export interface ProviderTypes {
  id: string;
  name_translations: Json;
  description_translations: Json;
  is_active: boolean;
  create_date: Date;
  last_modified_date: Date | null;
  icon_url: string | null;
}
export interface ProviderTypesInput {
  id: string;
  name_translations: Json;
  description_translations: Json;
  is_active: boolean;
  create_date?: Date;
  last_modified_date?: Date | null;
  icon_url?: string | null;
}
const provider_types = {
  tableName: 'provider_types',
  columns: ['id', 'name_translations', 'description_translations', 'is_active', 'create_date', 'last_modified_date', 'icon_url'],
  requiredForInsert: ['id', 'name_translations', 'description_translations', 'is_active'],
  primaryKey: 'id',
  foreignKeys: {},
  $type: null as unknown as ProviderTypes,
  $input: null as unknown as ProviderTypesInput
} as const;

// Table review_images
export interface ReviewImages {
  id: string;
  review_id: string;
  image_url: string | null;
}
export interface ReviewImagesInput {
  id?: string;
  review_id: string;
  image_url?: string | null;
}
const review_images = {
  tableName: 'review_images',
  columns: ['id', 'review_id', 'image_url'],
  requiredForInsert: ['review_id'],
  primaryKey: 'id',
  foreignKeys: { review_id: { table: 'service_provider_comments', column: 'id', $type: null as unknown as ServiceProviderComments }, },
  $type: null as unknown as ReviewImages,
  $input: null as unknown as ReviewImagesInput
} as const;

// Table service_attribute_definition_options
export interface ServiceAttributeDefinitionOptions {
  service_attribute_definition_id: string;
  id: number;
  display_name_translations: Json;
  value_translations: Json;
  additional_price: number | null;
}
export interface ServiceAttributeDefinitionOptionsInput {
  service_attribute_definition_id: string;
  id: number;
  display_name_translations: Json;
  value_translations: Json;
  additional_price?: number | null;
}
const service_attribute_definition_options = {
  tableName: 'service_attribute_definition_options',
  columns: ['service_attribute_definition_id', 'id', 'display_name_translations', 'value_translations', 'additional_price'],
  requiredForInsert: ['service_attribute_definition_id', 'id', 'display_name_translations', 'value_translations'],
  primaryKey: 'service_attribute_definition_id',
  foreignKeys: { service_attribute_definition_id: { table: 'service_attribute_definitions', column: 'id', $type: null as unknown as ServiceAttributeDefinitions }, },
  $type: null as unknown as ServiceAttributeDefinitionOptions,
  $input: null as unknown as ServiceAttributeDefinitionOptionsInput
} as const;

// Table service_attribute_definitions
export interface ServiceAttributeDefinitions {
  id: string;
  name_translations: Json;
  description_translations: Json;
  attribute_type_id: number;
  is_required: boolean;
  affects_pricing: boolean;
  display_order: number;
  service_definition_id: string | null;
  create_date: Date;
  last_modified_date: Date | null;
}
export interface ServiceAttributeDefinitionsInput {
  id: string;
  name_translations: Json;
  description_translations: Json;
  attribute_type_id: number;
  is_required: boolean;
  affects_pricing: boolean;
  display_order: number;
  service_definition_id?: string | null;
  create_date: Date;
  last_modified_date?: Date | null;
}
const service_attribute_definitions = {
  tableName: 'service_attribute_definitions',
  columns: ['id', 'name_translations', 'description_translations', 'attribute_type_id', 'is_required', 'affects_pricing', 'display_order', 'service_definition_id', 'create_date', 'last_modified_date'],
  requiredForInsert: ['id', 'name_translations', 'description_translations', 'attribute_type_id', 'is_required', 'affects_pricing', 'display_order', 'create_date'],
  primaryKey: 'id',
  foreignKeys: {
    attribute_type_id: { table: 'attribute_types', column: 'id', $type: null as unknown as AttributeTypes },
    service_definition_id: { table: 'service_definitions', column: 'id', $type: null as unknown as ServiceDefinitions },
  },
  $type: null as unknown as ServiceAttributeDefinitions,
  $input: null as unknown as ServiceAttributeDefinitionsInput
} as const;

// Table service_attribute_values
export interface ServiceAttributeValues {
  id: string;
  attribute_definition_id: string;
  value_translations: Json;
  provider_service_id: string;
  create_date: Date;
  last_modified_date: Date | null;
}
export interface ServiceAttributeValuesInput {
  id: string;
  attribute_definition_id: string;
  value_translations: Json;
  provider_service_id: string;
  create_date: Date;
  last_modified_date?: Date | null;
}
const service_attribute_values = {
  tableName: 'service_attribute_values',
  columns: ['id', 'attribute_definition_id', 'value_translations', 'provider_service_id', 'create_date', 'last_modified_date'],
  requiredForInsert: ['id', 'attribute_definition_id', 'value_translations', 'provider_service_id', 'create_date'],
  primaryKey: 'id',
  foreignKeys: { provider_service_id: { table: 'provider_services', column: 'id', $type: null as unknown as ProviderServices }, },
  $type: null as unknown as ServiceAttributeValues,
  $input: null as unknown as ServiceAttributeValuesInput
} as const;

// Table service_definition_domain_requirements
export interface ServiceDefinitionDomainRequirements {
  service_definition_id: string;
  id: number;
  description_translations: Json;
  is_mandatory: boolean;
}
export interface ServiceDefinitionDomainRequirementsInput {
  service_definition_id: string;
  id: number;
  description_translations: Json;
  is_mandatory: boolean;
}
const service_definition_domain_requirements = {
  tableName: 'service_definition_domain_requirements',
  columns: ['service_definition_id', 'id', 'description_translations', 'is_mandatory'],
  requiredForInsert: ['service_definition_id', 'id', 'description_translations', 'is_mandatory'],
  primaryKey: 'service_definition_id',
  foreignKeys: { service_definition_id: { table: 'service_definitions', column: 'id', $type: null as unknown as ServiceDefinitions }, },
  $type: null as unknown as ServiceDefinitionDomainRequirements,
  $input: null as unknown as ServiceDefinitionDomainRequirementsInput
} as const;

// Table service_definitions
export interface ServiceDefinitions {
  id: string;
  name_translations: Json;
  description_translations: Json;
  category_id: string;
  duration_minutes: number;
  pricing_model: string;
  is_active: boolean;
  currency: string;
  value: number;
  create_date: Date;
  last_modified_date: Date | null;
}
export interface ServiceDefinitionsInput {
  id: string;
  name_translations: Json;
  description_translations: Json;
  category_id: string;
  duration_minutes: number;
  pricing_model: string;
  is_active: boolean;
  currency: string;
  value: number;
  create_date?: Date;
  last_modified_date?: Date | null;
}
const service_definitions = {
  tableName: 'service_definitions',
  columns: ['id', 'name_translations', 'description_translations', 'category_id', 'duration_minutes', 'pricing_model', 'is_active', 'currency', 'value', 'create_date', 'last_modified_date'],
  requiredForInsert: ['id', 'name_translations', 'description_translations', 'category_id', 'duration_minutes', 'pricing_model', 'is_active', 'currency', 'value'],
  primaryKey: 'id',
  foreignKeys: { category_id: { table: 'categories', column: 'id', $type: null as unknown as Categories }, },
  $type: null as unknown as ServiceDefinitions,
  $input: null as unknown as ServiceDefinitionsInput
} as const;

// Table service_faqs
export interface ServiceFaqs {
  id: string;
  service_id: string;
  question: string | null;
  answer: string | null;
}
export interface ServiceFaqsInput {
  id?: string;
  service_id: string;
  question?: string | null;
  answer?: string | null;
}
const service_faqs = {
  tableName: 'service_faqs',
  columns: ['id', 'service_id', 'question', 'answer'],
  requiredForInsert: ['service_id'],
  primaryKey: 'id',
  foreignKeys: {},
  $type: null as unknown as ServiceFaqs,
  $input: null as unknown as ServiceFaqsInput
} as const;

// Table service_included
export interface ServiceIncluded {
  id: string;
  service_id: string;
  item: string;
}
export interface ServiceIncludedInput {
  id?: string;
  service_id: string;
  item: string;
}
const service_included = {
  tableName: 'service_included',
  columns: ['id', 'service_id', 'item'],
  requiredForInsert: ['service_id', 'item'],
  primaryKey: 'id',
  foreignKeys: {},
  $type: null as unknown as ServiceIncluded,
  $input: null as unknown as ServiceIncludedInput
} as const;

// Table service_process
export interface ServiceProcess {
  id: string;
  service_id: string;
  step: number;
  title: string | null;
  description: string | null;
  duration: string | null;
}
export interface ServiceProcessInput {
  id?: string;
  service_id: string;
  step: number;
  title?: string | null;
  description?: string | null;
  duration?: string | null;
}
const service_process = {
  tableName: 'service_process',
  columns: ['id', 'service_id', 'step', 'title', 'description', 'duration'],
  requiredForInsert: ['service_id', 'step'],
  primaryKey: 'id',
  foreignKeys: {},
  $type: null as unknown as ServiceProcess,
  $input: null as unknown as ServiceProcessInput
} as const;

// Table service_provider_comments
export interface ServiceProviderComments {
  id: string;
  service_provider_id: string;
  customer_id: string;
  customer_name: string;
  comment_text: string;
  rating: number | null;
  is_public: boolean;
  create_date: Date;
  last_modified_date: Date | null;
  country: string | null;
  treatment: string | null;
  is_verified: boolean | null;
  helpful_count: number | null;
}
export interface ServiceProviderCommentsInput {
  id: string;
  service_provider_id: string;
  customer_id: string;
  customer_name: string;
  comment_text: string;
  rating?: number | null;
  is_public?: boolean;
  create_date: Date;
  last_modified_date?: Date | null;
  country?: string | null;
  treatment?: string | null;
  is_verified?: boolean | null;
  helpful_count?: number | null;
}
const service_provider_comments = {
  tableName: 'service_provider_comments',
  columns: ['id', 'service_provider_id', 'customer_id', 'customer_name', 'comment_text', 'rating', 'is_public', 'create_date', 'last_modified_date', 'country', 'treatment', 'is_verified', 'helpful_count'],
  requiredForInsert: ['id', 'service_provider_id', 'customer_id', 'customer_name', 'comment_text', 'create_date'],
  primaryKey: 'id',
  foreignKeys: { service_provider_id: { table: 'service_providers', column: 'id', $type: null as unknown as ServiceProviders }, },
  $type: null as unknown as ServiceProviderComments,
  $input: null as unknown as ServiceProviderCommentsInput
} as const;

// Table service_provider_grades
export interface ServiceProviderGrades {
  id: number;
  name: string;
}
export interface ServiceProviderGradesInput {
  id: number;
  name: string;
}
const service_provider_grades = {
  tableName: 'service_provider_grades',
  columns: ['id', 'name'],
  requiredForInsert: ['id', 'name'],
  primaryKey: 'id',
  foreignKeys: {},
  $type: null as unknown as ServiceProviderGrades,
  $input: null as unknown as ServiceProviderGradesInput
} as const;

// Table service_provider_request_statuses
export interface ServiceProviderRequestStatuses {
  id: number;
  name: string;
}
export interface ServiceProviderRequestStatusesInput {
  id: number;
  name: string;
}
const service_provider_request_statuses = {
  tableName: 'service_provider_request_statuses',
  columns: ['id', 'name'],
  requiredForInsert: ['id', 'name'],
  primaryKey: 'id',
  foreignKeys: {},
  $type: null as unknown as ServiceProviderRequestStatuses,
  $input: null as unknown as ServiceProviderRequestStatusesInput
} as const;

// Table service_provider_requests
export interface ServiceProviderRequests {
  id: string;
  service_provider_id: string;
  customer_id: string;
  customer_email: string;
  customer_full_name: string;
  message: string;
  request_status_id: number;
  create_date: Date;
  last_modified_date: Date | null;
}
export interface ServiceProviderRequestsInput {
  id: string;
  service_provider_id: string;
  customer_id: string;
  customer_email: string;
  customer_full_name: string;
  message: string;
  request_status_id: number;
  create_date?: Date;
  last_modified_date?: Date | null;
}
const service_provider_requests = {
  tableName: 'service_provider_requests',
  columns: ['id', 'service_provider_id', 'customer_id', 'customer_email', 'customer_full_name', 'message', 'request_status_id', 'create_date', 'last_modified_date'],
  requiredForInsert: ['id', 'service_provider_id', 'customer_id', 'customer_email', 'customer_full_name', 'message', 'request_status_id'],
  primaryKey: 'id',
  foreignKeys: {
    service_provider_id: { table: 'service_providers', column: 'id', $type: null as unknown as ServiceProviders },
    request_status_id: { table: 'service_provider_request_statuses', column: 'id', $type: null as unknown as ServiceProviderRequestStatuses },
  },
  $type: null as unknown as ServiceProviderRequests,
  $input: null as unknown as ServiceProviderRequestsInput
} as const;

// Table service_providers
export interface ServiceProviders {
  id: string;
  name_translations: Json;
  description_translations: Json;
  is_active: boolean;
  provider_type_id: string;
  city: string;
  country: string;
  detail_translations: Json | null;
  street_translations: Json | null;
  zip_code: string | null;
  email: string;
  phone_number_country_code: string;
  phone_number: string;
  create_date: Date;
  last_modified_date: Date | null;
  grade_id: number | null;
  latitude: number | null;
  longitude: number | null;
  rating: number | null;
  review_count: number | null;
  accredited: boolean | null;
  response_time: string | null;
  established_year: number | null;
  total_patients: string | null;
  success_rate: string | null;
  languages: string[] | null;
  is_sponsored: boolean | null;
  sponsored_tag: string | null;
  specialties: string[] | null;
  featured_score: number | null;
  search_vector: any | null;
  image_url: string | null;
  timezone_id: string;
}
export interface ServiceProvidersInput {
  id: string;
  name_translations: Json;
  description_translations: Json;
  is_active: boolean;
  provider_type_id: string;
  city: string;
  country: string;
  detail_translations?: Json | null;
  street_translations?: Json | null;
  zip_code?: string | null;
  email: string;
  phone_number_country_code: string;
  phone_number: string;
  create_date?: Date;
  last_modified_date?: Date | null;
  grade_id?: number | null;
  latitude?: number | null;
  longitude?: number | null;
  rating?: number | null;
  review_count?: number | null;
  accredited?: boolean | null;
  response_time?: string | null;
  established_year?: number | null;
  total_patients?: string | null;
  success_rate?: string | null;
  languages?: string[] | null;
  is_sponsored?: boolean | null;
  sponsored_tag?: string | null;
  specialties?: string[] | null;
  featured_score?: number | null;
  search_vector?: any | null;
  image_url?: string | null;
  timezone_id?: string;
}
const service_providers = {
  tableName: 'service_providers',
  columns: ['id', 'name_translations', 'description_translations', 'is_active', 'provider_type_id', 'city', 'country', 'detail_translations', 'street_translations', 'zip_code', 'email', 'phone_number_country_code', 'phone_number', 'create_date', 'last_modified_date', 'grade_id', 'latitude', 'longitude', 'rating', 'review_count', 'accredited', 'response_time', 'established_year', 'total_patients', 'success_rate', 'languages', 'is_sponsored', 'sponsored_tag', 'specialties', 'featured_score', 'search_vector', 'image_url', 'timezone_id'],
  requiredForInsert: ['id', 'name_translations', 'description_translations', 'is_active', 'provider_type_id', 'city', 'country', 'email', 'phone_number_country_code', 'phone_number'],
  primaryKey: 'id',
  foreignKeys: {
    provider_type_id: { table: 'provider_types', column: 'id', $type: null as unknown as ProviderTypes },
    grade_id: { table: 'service_provider_grades', column: 'id', $type: null as unknown as ServiceProviderGrades },
  },
  $type: null as unknown as ServiceProviders,
  $input: null as unknown as ServiceProvidersInput
} as const;

// Table service_upload_file_requirements
export interface ServiceUploadFileRequirements {
  id: string;
  service_definition_id: string;
  title_translations: Json;
  description_translations: Json;
  is_required: boolean;
  max_file_size_bytes: number;
  allowed_extensions: string[];
  allowed_mime_types: string[];
  max_files: number;
  display_order: number;
  example_file_url: string | null;
  create_date: Date;
  last_modified_date: Date | null;
}
export interface ServiceUploadFileRequirementsInput {
  id?: string;
  service_definition_id: string;
  title_translations: Json;
  description_translations: Json;
  is_required?: boolean;
  max_file_size_bytes?: number;
  allowed_extensions?: string[];
  allowed_mime_types?: string[];
  max_files?: number;
  display_order?: number;
  example_file_url?: string | null;
  create_date?: Date;
  last_modified_date?: Date | null;
}
const service_upload_file_requirements = {
  tableName: 'service_upload_file_requirements',
  columns: ['id', 'service_definition_id', 'title_translations', 'description_translations', 'is_required', 'max_file_size_bytes', 'allowed_extensions', 'allowed_mime_types', 'max_files', 'display_order', 'example_file_url', 'create_date', 'last_modified_date'],
  requiredForInsert: ['service_definition_id', 'title_translations', 'description_translations'],
  primaryKey: 'id',
  foreignKeys: { service_definition_id: { table: 'service_definitions', column: 'id', $type: null as unknown as ServiceDefinitions }, },
  $type: null as unknown as ServiceUploadFileRequirements,
  $input: null as unknown as ServiceUploadFileRequirementsInput
} as const;

// Table staff
export interface Staff {
  id: string;
  name_translations: Json;
  biography_translations: Json;
  title_translations: Json;
  profile_image_url: string | null;
  is_active: boolean;
  create_date: Date;
  last_modified_date: Date | null;
  experience: string | null;
  patients: string | null;
  rating: number | null;
  specialty: string | null;
  consultation_fee: number | null;
  next_available_label: string | null;
  review_count: number | null;
  specialty_translations: Json | null;
  experience_years: number | null;
  success_rate: string | null;
}
export interface StaffInput {
  id: string;
  name_translations: Json;
  biography_translations: Json;
  title_translations: Json;
  profile_image_url?: string | null;
  is_active: boolean;
  create_date?: Date;
  last_modified_date?: Date | null;
  experience?: string | null;
  patients?: string | null;
  rating?: number | null;
  specialty?: string | null;
  consultation_fee?: number | null;
  next_available_label?: string | null;
  review_count?: number | null;
  specialty_translations?: Json | null;
  experience_years?: number | null;
  success_rate?: string | null;
}
const staff = {
  tableName: 'staff',
  columns: ['id', 'name_translations', 'biography_translations', 'title_translations', 'profile_image_url', 'is_active', 'create_date', 'last_modified_date', 'experience', 'patients', 'rating', 'specialty', 'consultation_fee', 'next_available_label', 'review_count', 'specialty_translations', 'experience_years', 'success_rate'],
  requiredForInsert: ['id', 'name_translations', 'biography_translations', 'title_translations', 'is_active'],
  primaryKey: 'id',
  foreignKeys: {},
  $type: null as unknown as Staff,
  $input: null as unknown as StaffInput
} as const;

// Table staff_achievements
export interface StaffAchievements {
  id: string;
  staff_id: string;
  icon: string | null;
  title: string;
  organization: string | null;
  display_order: number;
  create_date: Date;
  last_modified_date: Date | null;
}
export interface StaffAchievementsInput {
  id?: string;
  staff_id: string;
  icon?: string | null;
  title: string;
  organization?: string | null;
  display_order?: number;
  create_date?: Date;
  last_modified_date?: Date | null;
}
const staff_achievements = {
  tableName: 'staff_achievements',
  columns: ['id', 'staff_id', 'icon', 'title', 'organization', 'display_order', 'create_date', 'last_modified_date'],
  requiredForInsert: ['staff_id', 'title'],
  primaryKey: 'id',
  foreignKeys: { staff_id: { table: 'staff', column: 'id', $type: null as unknown as Staff }, },
  $type: null as unknown as StaffAchievements,
  $input: null as unknown as StaffAchievementsInput
} as const;

// Table staff_availabilities
export interface StaffAvailabilities {
  id: string;
  day_of_week: number;
  is_recurring: boolean;
  availability_status_id: number;
  specific_date: Date | null;
  staff_id: string;
  end_time: string;
  start_time: string;
  create_date: Date;
  last_modified_date: Date | null;
}
export interface StaffAvailabilitiesInput {
  id: string;
  day_of_week: number;
  is_recurring: boolean;
  availability_status_id: number;
  specific_date?: Date | null;
  staff_id: string;
  end_time: string;
  start_time: string;
  create_date: Date;
  last_modified_date?: Date | null;
}
const staff_availabilities = {
  tableName: 'staff_availabilities',
  columns: ['id', 'day_of_week', 'is_recurring', 'availability_status_id', 'specific_date', 'staff_id', 'end_time', 'start_time', 'create_date', 'last_modified_date'],
  requiredForInsert: ['id', 'day_of_week', 'is_recurring', 'availability_status_id', 'staff_id', 'end_time', 'start_time', 'create_date'],
  primaryKey: 'id',
  foreignKeys: {
    availability_status_id: { table: 'staff_availability_statuses', column: 'id', $type: null as unknown as StaffAvailabilityStatuses },
    staff_id: { table: 'staff', column: 'id', $type: null as unknown as Staff },
  },
  $type: null as unknown as StaffAvailabilities,
  $input: null as unknown as StaffAvailabilitiesInput
} as const;

// Table staff_availability_statuses
export interface StaffAvailabilityStatuses {
  id: number;
  name: string;
}
export interface StaffAvailabilityStatusesInput {
  id: number;
  name: string;
}
const staff_availability_statuses = {
  tableName: 'staff_availability_statuses',
  columns: ['id', 'name'],
  requiredForInsert: ['id', 'name'],
  primaryKey: 'id',
  foreignKeys: {},
  $type: null as unknown as StaffAvailabilityStatuses,
  $input: null as unknown as StaffAvailabilityStatusesInput
} as const;

// Table staff_before_after
export interface StaffBeforeAfter {
  id: string;
  staff_id: string;
  before_image: string;
  after_image: string;
  procedure: string | null;
  months: number | null;
  display_order: number;
  create_date: Date;
  last_modified_date: Date | null;
}
export interface StaffBeforeAfterInput {
  id?: string;
  staff_id: string;
  before_image: string;
  after_image: string;
  procedure?: string | null;
  months?: number | null;
  display_order?: number;
  create_date?: Date;
  last_modified_date?: Date | null;
}
const staff_before_after = {
  tableName: 'staff_before_after',
  columns: ['id', 'staff_id', 'before_image', 'after_image', 'procedure', 'months', 'display_order', 'create_date', 'last_modified_date'],
  requiredForInsert: ['staff_id', 'before_image', 'after_image'],
  primaryKey: 'id',
  foreignKeys: { staff_id: { table: 'staff', column: 'id', $type: null as unknown as Staff }, },
  $type: null as unknown as StaffBeforeAfter,
  $input: null as unknown as StaffBeforeAfterInput
} as const;

// Table staff_certifications
export interface StaffCertifications {
  id: string;
  staff_id: string;
  name: string;
  issuer: string | null;
  is_verified: boolean;
  create_date: Date;
  last_modified_date: Date | null;
}
export interface StaffCertificationsInput {
  id?: string;
  staff_id: string;
  name: string;
  issuer?: string | null;
  is_verified?: boolean;
  create_date?: Date;
  last_modified_date?: Date | null;
}
const staff_certifications = {
  tableName: 'staff_certifications',
  columns: ['id', 'staff_id', 'name', 'issuer', 'is_verified', 'create_date', 'last_modified_date'],
  requiredForInsert: ['staff_id', 'name'],
  primaryKey: 'id',
  foreignKeys: { staff_id: { table: 'staff', column: 'id', $type: null as unknown as Staff }, },
  $type: null as unknown as StaffCertifications,
  $input: null as unknown as StaffCertificationsInput
} as const;

// Table staff_credentials
export interface StaffCredentials {
  id: string;
  staff_id: string;
  credential: string;
  is_verified: boolean;
}
export interface StaffCredentialsInput {
  id?: string;
  staff_id: string;
  credential: string;
  is_verified?: boolean;
}
const staff_credentials = {
  tableName: 'staff_credentials',
  columns: ['id', 'staff_id', 'credential', 'is_verified'],
  requiredForInsert: ['staff_id', 'credential'],
  primaryKey: 'id',
  foreignKeys: { staff_id: { table: 'staff', column: 'id', $type: null as unknown as Staff }, },
  $type: null as unknown as StaffCredentials,
  $input: null as unknown as StaffCredentialsInput
} as const;

// Table staff_education
export interface StaffEducation {
  id: string;
  staff_id: string;
  degree: string;
  institution: string;
  year: number | null;
  create_date: Date;
  last_modified_date: Date | null;
}
export interface StaffEducationInput {
  id?: string;
  staff_id: string;
  degree: string;
  institution: string;
  year?: number | null;
  create_date?: Date;
  last_modified_date?: Date | null;
}
const staff_education = {
  tableName: 'staff_education',
  columns: ['id', 'staff_id', 'degree', 'institution', 'year', 'create_date', 'last_modified_date'],
  requiredForInsert: ['staff_id', 'degree', 'institution'],
  primaryKey: 'id',
  foreignKeys: { staff_id: { table: 'staff', column: 'id', $type: null as unknown as Staff }, },
  $type: null as unknown as StaffEducation,
  $input: null as unknown as StaffEducationInput
} as const;

// Table staff_gallery_items
export interface StaffGalleryItems {
  id: string;
  title_translations: Json;
  description_translations: Json;
  url: string;
  media_type: string;
  display_order: number;
  is_primary: boolean;
  staff_id: string;
  create_date: Date;
  last_modified_date: Date | null;
}
export interface StaffGalleryItemsInput {
  id?: string;
  title_translations?: Json;
  description_translations?: Json;
  url: string;
  media_type?: string;
  display_order?: number;
  is_primary?: boolean;
  staff_id: string;
  create_date?: Date;
  last_modified_date?: Date | null;
}
const staff_gallery_items = {
  tableName: 'staff_gallery_items',
  columns: ['id', 'title_translations', 'description_translations', 'url', 'media_type', 'display_order', 'is_primary', 'staff_id', 'create_date', 'last_modified_date'],
  requiredForInsert: ['url', 'staff_id'],
  primaryKey: 'id',
  foreignKeys: { staff_id: { table: 'staff', column: 'id', $type: null as unknown as Staff }, },
  $type: null as unknown as StaffGalleryItems,
  $input: null as unknown as StaffGalleryItemsInput
} as const;

// Table staff_languages
export interface StaffLanguages {
  staff_id: string;
  language: string;
  create_date: Date;
}
export interface StaffLanguagesInput {
  staff_id: string;
  language: string;
  create_date?: Date;
}
const staff_languages = {
  tableName: 'staff_languages',
  columns: ['staff_id', 'language', 'create_date'],
  requiredForInsert: ['staff_id', 'language'],
  primaryKey: 'staff_id',
  foreignKeys: { staff_id: { table: 'staff', column: 'id', $type: null as unknown as Staff }, },
  $type: null as unknown as StaffLanguages,
  $input: null as unknown as StaffLanguagesInput
} as const;

// Table staff_services
export interface StaffServices {
  id: string;
  service_definition_id: string;
  is_active: boolean;
  notes_translations: Json;
  staff_id: string;
  create_date: Date;
  last_modified_date: Date | null;
}
export interface StaffServicesInput {
  id: string;
  service_definition_id: string;
  is_active: boolean;
  notes_translations: Json;
  staff_id: string;
  create_date: Date;
  last_modified_date?: Date | null;
}
const staff_services = {
  tableName: 'staff_services',
  columns: ['id', 'service_definition_id', 'is_active', 'notes_translations', 'staff_id', 'create_date', 'last_modified_date'],
  requiredForInsert: ['id', 'service_definition_id', 'is_active', 'notes_translations', 'staff_id', 'create_date'],
  primaryKey: 'id',
  foreignKeys: {
    service_definition_id: { table: 'service_definitions', column: 'id', $type: null as unknown as ServiceDefinitions },
    staff_id: { table: 'staff', column: 'id', $type: null as unknown as Staff },
  },
  $type: null as unknown as StaffServices,
  $input: null as unknown as StaffServicesInput
} as const;

// Table staff_specializations
export interface StaffSpecializations {
  staff_id: string;
  specialty: string;
  create_date: Date;
}
export interface StaffSpecializationsInput {
  staff_id: string;
  specialty: string;
  create_date?: Date;
}
const staff_specializations = {
  tableName: 'staff_specializations',
  columns: ['staff_id', 'specialty', 'create_date'],
  requiredForInsert: ['staff_id', 'specialty'],
  primaryKey: 'staff_id',
  foreignKeys: { staff_id: { table: 'staff', column: 'id', $type: null as unknown as Staff }, },
  $type: null as unknown as StaffSpecializations,
  $input: null as unknown as StaffSpecializationsInput
} as const;


export interface TableTypes {
  __EFMigrationsHistory: {
    select: EFMigrationsHistory;
    input: EFMigrationsHistoryInput;
  };
  addon_details: {
    select: AddonDetails;
    input: AddonDetailsInput;
  };
  addons: {
    select: Addons;
    input: AddonsInput;
  };
  attribute_types: {
    select: AttributeTypes;
    input: AttributeTypesInput;
  };
  categories: {
    select: Categories;
    input: CategoriesInput;
  };
  category_groups: {
    select: CategoryGroups;
    input: CategoryGroupsInput;
  };
  currencies: {
    select: Currencies;
    input: CurrenciesInput;
  };
  Currency: {
    select: Currency;
    input: CurrencyInput;
  };
  inbox_message_consumers: {
    select: InboxMessageConsumers;
    input: InboxMessageConsumersInput;
  };
  inbox_messages: {
    select: InboxMessages;
    input: InboxMessagesInput;
  };
  internal_command_message_consumers: {
    select: InternalCommandMessageConsumers;
    input: InternalCommandMessageConsumersInput;
  };
  internal_command_messages: {
    select: InternalCommandMessages;
    input: InternalCommandMessagesInput;
  };
  locations: {
    select: Locations;
    input: LocationsInput;
  };
  LocationType: {
    select: LocationType;
    input: LocationTypeInput;
  };
  outbox_message_consumers: {
    select: OutboxMessageConsumers;
    input: OutboxMessageConsumersInput;
  };
  outbox_messages: {
    select: OutboxMessages;
    input: OutboxMessagesInput;
  };
  provider_attribute_definition_domain_options: {
    select: ProviderAttributeDefinitionDomainOptions;
    input: ProviderAttributeDefinitionDomainOptionsInput;
  };
  provider_attribute_definitions: {
    select: ProviderAttributeDefinitions;
    input: ProviderAttributeDefinitionsInput;
  };
  provider_attributes: {
    select: ProviderAttributes;
    input: ProviderAttributesInput;
  };
  provider_certifications: {
    select: ProviderCertifications;
    input: ProviderCertificationsInput;
  };
  provider_gallery_items: {
    select: ProviderGalleryItems;
    input: ProviderGalleryItemsInput;
  };
  provider_languages: {
    select: ProviderLanguages;
    input: ProviderLanguagesInput;
  };
  provider_policies: {
    select: ProviderPolicies;
    input: ProviderPoliciesInput;
  };
  provider_recommendations: {
    select: ProviderRecommendations;
    input: ProviderRecommendationsInput;
  };
  provider_service_addons: {
    select: ProviderServiceAddons;
    input: ProviderServiceAddonsInput;
  };
  provider_service_gallery_items: {
    select: ProviderServiceGalleryItems;
    input: ProviderServiceGalleryItemsInput;
  };
  provider_services: {
    select: ProviderServices;
    input: ProviderServicesInput;
  };
  provider_staffs: {
    select: ProviderStaffs;
    input: ProviderStaffsInput;
  };
  provider_types: {
    select: ProviderTypes;
    input: ProviderTypesInput;
  };
  review_images: {
    select: ReviewImages;
    input: ReviewImagesInput;
  };
  service_attribute_definition_options: {
    select: ServiceAttributeDefinitionOptions;
    input: ServiceAttributeDefinitionOptionsInput;
  };
  service_attribute_definitions: {
    select: ServiceAttributeDefinitions;
    input: ServiceAttributeDefinitionsInput;
  };
  service_attribute_values: {
    select: ServiceAttributeValues;
    input: ServiceAttributeValuesInput;
  };
  service_definition_domain_requirements: {
    select: ServiceDefinitionDomainRequirements;
    input: ServiceDefinitionDomainRequirementsInput;
  };
  service_definitions: {
    select: ServiceDefinitions;
    input: ServiceDefinitionsInput;
  };
  service_faqs: {
    select: ServiceFaqs;
    input: ServiceFaqsInput;
  };
  service_included: {
    select: ServiceIncluded;
    input: ServiceIncludedInput;
  };
  service_process: {
    select: ServiceProcess;
    input: ServiceProcessInput;
  };
  service_provider_comments: {
    select: ServiceProviderComments;
    input: ServiceProviderCommentsInput;
  };
  service_provider_grades: {
    select: ServiceProviderGrades;
    input: ServiceProviderGradesInput;
  };
  service_provider_request_statuses: {
    select: ServiceProviderRequestStatuses;
    input: ServiceProviderRequestStatusesInput;
  };
  service_provider_requests: {
    select: ServiceProviderRequests;
    input: ServiceProviderRequestsInput;
  };
  service_providers: {
    select: ServiceProviders;
    input: ServiceProvidersInput;
  };
  service_upload_file_requirements: {
    select: ServiceUploadFileRequirements;
    input: ServiceUploadFileRequirementsInput;
  };
  staff: {
    select: Staff;
    input: StaffInput;
  };
  staff_achievements: {
    select: StaffAchievements;
    input: StaffAchievementsInput;
  };
  staff_availabilities: {
    select: StaffAvailabilities;
    input: StaffAvailabilitiesInput;
  };
  staff_availability_statuses: {
    select: StaffAvailabilityStatuses;
    input: StaffAvailabilityStatusesInput;
  };
  staff_before_after: {
    select: StaffBeforeAfter;
    input: StaffBeforeAfterInput;
  };
  staff_certifications: {
    select: StaffCertifications;
    input: StaffCertificationsInput;
  };
  staff_credentials: {
    select: StaffCredentials;
    input: StaffCredentialsInput;
  };
  staff_education: {
    select: StaffEducation;
    input: StaffEducationInput;
  };
  staff_gallery_items: {
    select: StaffGalleryItems;
    input: StaffGalleryItemsInput;
  };
  staff_languages: {
    select: StaffLanguages;
    input: StaffLanguagesInput;
  };
  staff_services: {
    select: StaffServices;
    input: StaffServicesInput;
  };
  staff_specializations: {
    select: StaffSpecializations;
    input: StaffSpecializationsInput;
  };
}

export const tables = {
  __EFMigrationsHistory,
  addon_details,
  addons,
  attribute_types,
  categories,
  category_groups,
  currencies,
  Currency,
  inbox_message_consumers,
  inbox_messages,
  internal_command_message_consumers,
  internal_command_messages,
  locations,
  LocationType,
  outbox_message_consumers,
  outbox_messages,
  provider_attribute_definition_domain_options,
  provider_attribute_definitions,
  provider_attributes,
  provider_certifications,
  provider_gallery_items,
  provider_languages,
  provider_policies,
  provider_recommendations,
  provider_service_addons,
  provider_service_gallery_items,
  provider_services,
  provider_staffs,
  provider_types,
  review_images,
  service_attribute_definition_options,
  service_attribute_definitions,
  service_attribute_values,
  service_definition_domain_requirements,
  service_definitions,
  service_faqs,
  service_included,
  service_process,
  service_provider_comments,
  service_provider_grades,
  service_provider_request_statuses,
  service_provider_requests,
  service_providers,
  service_upload_file_requirements,
  staff,
  staff_achievements,
  staff_availabilities,
  staff_availability_statuses,
  staff_before_after,
  staff_certifications,
  staff_credentials,
  staff_education,
  staff_gallery_items,
  staff_languages,
  staff_services,
  staff_specializations,
}
