export type BugReportLocale = "en" | "fa" | "ar";

export function normalizeBugReportLocale(locale?: string | null): BugReportLocale {
  const normalized = (locale || "en").toLowerCase();
  if (normalized.startsWith("fa")) return "fa";
  if (normalized.startsWith("ar")) return "ar";
  return "en";
}

export const BUG_REPORT_COPY = {
  en: {
    pageTitle: "Report a bug",
    pageSubtitle: "Send us screenshots, steps, and device details so the team can reproduce and fix the issue faster.",
    title: "Bug title",
    area: "Where did it happen?",
    severity: "Severity",
    sourceUrl: "Page URL",
    description: "What happened?",
    expected: "What did you expect?",
    actual: "What actually happened?",
    steps: "Steps to reproduce",
    contact: "Contact info",
    name: "Name",
    email: "Email",
    phoneCode: "Code",
    phone: "Phone",
    screenshots: "Screenshots and files",
    pasteHint: "Paste a screenshot here, drag files, or choose files.",
    submit: "Submit bug report",
    submitting: "Submitting...",
    success: "Bug report submitted",
    myReports: "My recent bug reports",
    noReports: "You have not submitted bug reports yet.",
    adminTitle: "Bug reports",
    adminSubtitle: "Jira/Trello-style board for reported customer and admin issues.",
  },
  fa: {
    pageTitle: "گزارش باگ",
    pageSubtitle: "اسکرین‌شات، مراحل و مشخصات دستگاه را ارسال کنید تا تیم سریع‌تر مشکل را بازتولید و رفع کند.",
    title: "عنوان باگ",
    area: "مشکل کجا رخ داد؟",
    severity: "شدت مشکل",
    sourceUrl: "آدرس صفحه",
    description: "چه اتفاقی افتاد؟",
    expected: "انتظار داشتید چه اتفاقی بیفتد؟",
    actual: "در عمل چه اتفاقی افتاد؟",
    steps: "مراحل بازتولید",
    contact: "اطلاعات تماس",
    name: "نام",
    email: "ایمیل",
    phoneCode: "کد",
    phone: "شماره تماس",
    screenshots: "اسکرین‌شات و فایل‌ها",
    pasteHint: "اسکرین‌شات را اینجا Paste کنید، فایل بکشید یا انتخاب کنید.",
    submit: "ارسال گزارش باگ",
    submitting: "در حال ارسال...",
    success: "گزارش باگ ثبت شد",
    myReports: "گزارش‌های اخیر من",
    noReports: "هنوز گزارشی ثبت نکرده‌اید.",
    adminTitle: "گزارش‌های باگ",
    adminSubtitle: "برد مدیریتی مشابه Jira/Trello برای مشکلات گزارش‌شده مشتریان و ادمین‌ها.",
  },
  ar: {
    pageTitle: "الإبلاغ عن خطأ",
    pageSubtitle: "أرسل لقطات شاشة وخطوات وتفاصيل الجهاز حتى يتمكن الفريق من إعادة إنتاج المشكلة وإصلاحها بسرعة.",
    title: "عنوان الخطأ",
    area: "أين حدثت المشكلة؟",
    severity: "الخطورة",
    sourceUrl: "رابط الصفحة",
    description: "ماذا حدث؟",
    expected: "ماذا كنت تتوقع؟",
    actual: "ماذا حدث فعلياً؟",
    steps: "خطوات إعادة الإنتاج",
    contact: "معلومات التواصل",
    name: "الاسم",
    email: "البريد الإلكتروني",
    phoneCode: "الرمز",
    phone: "الهاتف",
    screenshots: "لقطات الشاشة والملفات",
    pasteHint: "الصق لقطة شاشة هنا أو اسحب الملفات أو اخترها.",
    submit: "إرسال تقرير الخطأ",
    submitting: "جارٍ الإرسال...",
    success: "تم إرسال تقرير الخطأ",
    myReports: "تقاريري الأخيرة",
    noReports: "لم ترسل أي تقارير بعد.",
    adminTitle: "تقارير الأخطاء",
    adminSubtitle: "لوحة إدارية شبيهة بـ Jira/Trello لمشاكل العملاء والإدارة.",
  },
} as const;
