// Generated by https://quicktype.io

namespace QuickType
{
    using System;
    using System.Collections.Generic;

    using System.Text.Json;
    using System.Text.Json.Serialization;
    public partial class GetHomePageResponse
    {
        public HomePageCategory[] Categories { get; set; } = Array.Empty<HomePageCategory>();
        public string[] QuickSearches { get; set; } = Array.Empty<string>();
    }

    // IMPORTANT:
    // In your DB schema category.categories.id is uuid, so this must be Guid (or string), not long.
    public partial class HomePageCategory
    {
        public Guid Id { get; set; }
        public string Label { get; set; } = string.Empty;
        public string Path { get; set; } = string.Empty;
        public string Image { get; set; } = string.Empty;
        public string Gradient { get; set; } = string.Empty;
    }

    internal sealed class HomePageCategoryRow
    {
        public Guid Id { get; set; }
        public string Label { get; set; } = string.Empty;
        public string Path { get; set; } = string.Empty;
        public string Image { get; set; } = string.Empty;
        public string Gradient { get; set; } = string.Empty;
    }

    public partial class GetHomePageResponse
    {
        public static string SampleJson= "{\"categories\":[{\"id\":1,\"label\":\"Medical\",\"path\":\"/n/app/mobile/medical/clinics\",\"image\":\"/unsplash_images/photo-1631217868264-e5b90bb7e133__w=400&h=300&fit=crop.jpg\",\"gradient\":\"from-red-500/90 to-red-600/90\"},{\"id\":2,\"label\":\"Beauty & Spa\",\"path\":\"/n/app/mobile/beauty\",\"image\":\"/unsplash_images/photo-1560066984-138dadb4c035__w=400&h=300&fit=crop.jpg\",\"gradient\":\"from-pink-500/90 to-rose-600/90\"},{\"id\":3,\"label\":\"Fitness\",\"path\":\"/n/n/app/mobile/mobile/fitness\",\"image\":\"/unsplash_images/photo-1534438327276-14e5300c3a48__w=400&h=300&fit=crop.jpg\",\"gradient\":\"from-purple-500/90 to-purple-600/90\"},{\"id\":4,\"label\":\"Hotels\",\"path\":\"/n/app/mobile/hotels\",\"image\":\"/unsplash_images/photo-1566073771259-6a8506099945__w=400&h=300&fit=crop.jpg\",\"gradient\":\"from-blue-500/90 to-blue-600/90\"},{\"id\":5,\"label\":\"Pharmacy\",\"path\":\"/n/app/mobile/pharmacy\",\"image\":\"/unsplash_images/photo-1576602976047-174e57a47881__w=400&h=300&fit=crop.jpg\",\"gradient\":\"from-teal-500/90 to-teal-600/90\"},{\"id\":6,\"label\":\"Education\",\"path\":\"/n/app/mobile/education\",\"image\":\"/unsplash_images/photo-1523240795612-9a054b0db644__w=400&h=300&fit=crop.jpg\",\"gradient\":\"from-amber-500/90 to-orange-600/90\"}],\"quickSearches\":[\"Hair Transplant\",\"Dental Veneers\",\"Spa Day\",\"IVF Treatment\",\"Gym Membership\"]}\r\n";
        public static GetHomePageResponse FromJson(string json) => JsonSerializer.Deserialize<GetHomePageResponse>(json, QuickType.Converter.Settings);
    }

}
