import { z } from "zod";
import { translatedTextSchema } from "./catalog";
export const adminProductUpsertSchema = z.object({
  id: z.string().uuid().optional(),
  productType: z.enum(["simple", "variant", "bundle", "digital"]),
  status: z.enum(["draft", "active", "archived"]),
  brandId: z.string().uuid().nullable().optional(),
  primaryCategoryId: z.string().uuid().nullable().optional(),
  nameTranslations: translatedTextSchema,
  shortDescriptionTranslations: translatedTextSchema,
  descriptionTranslations: translatedTextSchema,
  slug: z.string().trim().min(2).max(180),
  baseCurrency: z.string().trim().min(3).max(15),
  basePrice: z.coerce.number().min(0),
  compareAtPrice: z.coerce.number().min(0).nullable().optional(),
  costPrice: z.coerce.number().min(0).nullable().optional(),
  taxClass: z.string().trim().min(1).max(40),
  allowBackorder: z.coerce.boolean().default(false),
  requiresShipping: z.coerce.boolean().default(true),
  isFeatured: z.coerce.boolean().default(false),
  isBestSeller: z.coerce.boolean().default(false),
  isNewArrival: z.coerce.boolean().default(false),
  fulfillmentType: z.enum(["delivery", "pickup", "download"]),
  categoryIds: z.array(z.string().uuid()).default([]),
});
export const adminCouponUpsertSchema = z.object({
  id: z.string().uuid().optional(),
  code: z.string().trim().min(2).max(50),
  titleTranslations: translatedTextSchema,
  descriptionTranslations: translatedTextSchema,
  couponType: z.enum(["fixed", "percentage", "free_shipping"]),
  value: z.coerce.number().min(0),
  currency: z.string().trim().max(15).nullable().optional(),
  isActive: z.coerce.boolean().default(true),
  startsAt: z.string().datetime().nullable().optional(),
  expiresAt: z.string().datetime().nullable().optional(),
  minSubtotal: z.coerce.number().min(0).default(0),
  maxDiscountAmount: z.coerce.number().min(0).nullable().optional(),
  usageLimit: z.coerce.number().int().min(1).nullable().optional(),
  usagePerCustomer: z.coerce.number().int().min(1).nullable().optional(),
  stackable: z.coerce.boolean().default(false),
  scope: z.enum(["cart", "product", "category", "brand", "shipping"]),
  appliesTo: z.record(z.string(), z.any()).default({}),
});
