<?xml version="1.0" encoding="utf-8"?>
<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Configurations>Debug;Release;Production</Configurations>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Deterministic>true</Deterministic>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
  </PropertyGroup>
  <PropertyGroup>
    <NeutralLanguage>en</NeutralLanguage>
  </PropertyGroup>
  <PropertyGroup>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <OpenApiDocumentsDirectory>$(MSBuildProjectDirectory)</OpenApiDocumentsDirectory>
  </PropertyGroup>
  <PropertyGroup>
    <AnalysisLevel>latest</AnalysisLevel>
    <AnalysisMode>Recommended</AnalysisMode>
    <AnalysisModeGlobalization>None</AnalysisModeGlobalization>
    <AnalysisModeSecurity>All</AnalysisModeSecurity>
    <EnableNETAnalyzers>false</EnableNETAnalyzers>
    <CodeAnalysisTreatWarningsAsErrors>false</CodeAnalysisTreatWarningsAsErrors>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <RunAnalyzersDuringLiveAnalysis>false</RunAnalyzersDuringLiveAnalysis>
    <RunAnalyzersDuringBuild>false</RunAnalyzersDuringBuild>
    <EnforceCodeStyleInBuild>false</EnforceCodeStyleInBuild>
  </PropertyGroup>
  <PropertyGroup>
    <IsTransformWebConfigDisabled>true</IsTransformWebConfigDisabled>
    <ErrorOnDuplicatePublishOutputFiles>false</ErrorOnDuplicatePublishOutputFiles>
    <Features>IOperation</Features>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
    <DebugType>full</DebugType>
    <DefineConstants>DEBUG;TRACE;$(DefineConstants)</DefineConstants>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
    <Optimize>true</Optimize>
    <DebugType>pdbonly</DebugType>
    <DefineConstants>TRACE;$(DefineConstants)</DefineConstants>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference
      Include="Meziantou.Analyzer"
      Condition="$(MSBuildProjectExtension) == '.csproj'"
      PrivateAssets="all"
    >
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference
      Include="StyleCop.Analyzers"
      PrivateAssets="all"
      Condition="$(MSBuildProjectExtension) == '.csproj'"
    />
    <PackageReference
      Include="SerilogAnalyzer"
      PrivateAssets="all"
      Condition="$(MSBuildProjectExtension) == '.csproj'"
    />
    <PackageReference
      Include="NetFabric.Hyperlinq.Analyzer"
      PrivateAssets="all"
      Condition="$(MSBuildProjectExtension) == '.csproj'"
    />
    <PackageReference
      Include="Roslynator.Analyzers"
      PrivateAssets="all"
      Condition="$(MSBuildProjectExtension) == '.csproj'"
    />
    <PackageReference
      Include="Roslynator.CodeAnalysis.Analyzers"
      PrivateAssets="all"
      Condition="$(MSBuildProjectExtension) == '.csproj'"
    />
    <PackageReference
      Include="Roslynator.Formatting.Analyzers"
      PrivateAssets="all"
      Condition="$(MSBuildProjectExtension) == '.csproj'"
    />
    <PackageReference Include="AsyncFixer" PrivateAssets="all" Condition="$(MSBuildProjectExtension) == '.csproj'" />
    <PackageReference
      Include="AsyncAwaitBestPractices"
      PrivateAssets="all"
      Condition="$(MSBuildProjectExtension) == '.csproj'"
    />
    <PackageReference
      Include="Microsoft.VisualStudio.Threading.Analyzers"
      PrivateAssets="all"
      Condition="$(MSBuildProjectExtension) == '.csproj'"
    >
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference
      Include="ErrorProne.NET.CoreAnalyzers"
      PrivateAssets="all"
      Condition="$(MSBuildProjectExtension) == '.csproj'"
    >
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
  <PropertyGroup Label="ConfigFiles">
    <StyleCopFile Condition=" '$(StyleCopFile)' == '' "
      >$([MSBuild]::GetPathOfFileAbove('stylecop.json',
      $(MSBuildProjectDirectory)))</StyleCopFile
    >
    <EditorConfigFile Condition=" '$(EditorConfigFile)' == '' "
      >$([MSBuild]::GetPathOfFileAbove('.editorconfig',
      $(MSBuildProjectDirectory)))</EditorConfigFile
    >
  </PropertyGroup>
  <ItemGroup Label="ConfigFiles">
    <AdditionalFiles Condition="Exists('$(StyleCopFile)')" Include="$(StyleCopFile)" Visible="false" />
    <None Condition="Exists('$(EditorConfigFile)')" Include="$(EditorConfigFile)" Visible="false" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Nerdbank.GitVersioning" PrivateAssets="all" Condition="!Exists('packages.config')" />
  </ItemGroup>
</Project>
