import { normalizePortalLocale, type PortalLocale } from "@core/i18n/config";

const en = {
  moduleName: "Ownership & Access", myProviders: "My workspaces", myProvidersDescription: "Provider workspaces connected to your LSevin account.", newApplication: "New application",
  noProviders: "No active provider workspace", noProvidersDescription: "You are signed in, but you do not currently have active provider access.", manage: "Manage", profile: "Profile", services: "Services", staff: "Staff", bookings: "Bookings", rating: "Rating", noDescription: "No description yet.",
  settings: "Access settings", settingsDescription: "Invite LSevin users, manage roles, suspend access, and preserve membership history.", members: "Members", invitations: "Invitations", inviteUser: "Invite user", email: "LSevin email", role: "Role", expiresIn: "Expires in", sevenDays: "7 days", fourteenDays: "14 days", thirtyDays: "30 days", createInvitation: "Create invitation", invitationCreated: "Invitation created", copyLinkHelp: "Share this one-time acceptance link with the intended user through an approved channel.",
  active: "Active", suspended: "Suspended", revoked: "Revoked", pending: "Pending", accepted: "Accepted", declined: "Declined", cancelled: "Cancelled", expired: "Expired", defaultWorkspace: "Default workspace", setDefault: "Set as default", updateRole: "Update role", suspend: "Suspend", revoke: "Revoke", reactivate: "Reactivate", cancelInvitation: "Cancel invitation", reason: "Reason", reasonHelp: "Required for access changes and recorded in the audit trail.", save: "Save", processing: "Processing…", confirmSuspend: "Suspend this member's access?", confirmRevoke: "Revoke this member's access? Historical membership will be retained.", confirmReactivate: "Reactivate this member's access?", confirmCancelInvite: "Cancel this pending invitation?",
  ownerProtected: "Owner access is protected and cannot be changed from this screen.", invitationTitle: "Provider workspace invitation", invitationDescription: "Review the provider and role before accepting access.", acceptInvitation: "Accept invitation", declineInvitation: "Decline", invalidInvitation: "This invitation is invalid, expired, or is intended for another LSevin account.", invitedAs: "Invited role", expires: "Expires", returnToWorkspaces: "My workspaces",
  owner: "Owner", admin: "Administrator", manager: "Manager", editor: "Editor", viewer: "Viewer", staffRole: "Staff",
  userNotFound: "LSevin user was not found.", alreadyMember: "This user already has a provider membership. Manage the existing membership instead of inviting again.", invalidRole: "That role cannot be granted by this account.", reasonRequired: "A reason is required.", memberNotFound: "Membership was not found.", cannotModifyOwner: "Owner membership cannot be changed here.", cannotModifySelf: "You cannot change your own provider role or access from member administration.", insufficientRole: "You cannot manage a member with an equal or higher role.", invitationAccepted: "Invitation accepted.", invitationDeclined: "Invitation declined.",
} as const;
type Copy = { [K in keyof typeof en]: string };

const fa: Copy = { ...en,
  moduleName:"مالکیت و دسترسی", myProviders:"محیط‌های کاری من", myProvidersDescription:"محیط‌های ارائه‌دهنده متصل به حساب السوین شما.", newApplication:"درخواست جدید", noProviders:"محیط کاری فعالی ندارید", noProvidersDescription:"وارد شده‌اید اما در حال حاضر دسترسی فعال به ارائه‌دهنده‌ای ندارید.", manage:"مدیریت", profile:"پروفایل", services:"خدمات", staff:"پرسنل", bookings:"رزروها", rating:"امتیاز", noDescription:"هنوز توضیحی ثبت نشده است.", settings:"تنظیمات دسترسی", settingsDescription:"کاربران السوین را دعوت کنید، نقش‌ها را مدیریت کنید و بدون حذف سابقه دسترسی را تعلیق یا لغو کنید.", members:"اعضا", invitations:"دعوت‌نامه‌ها", inviteUser:"دعوت کاربر", email:"ایمیل السوین", role:"نقش", expiresIn:"انقضا", sevenDays:"۷ روز", fourteenDays:"۱۴ روز", thirtyDays:"۳۰ روز", createInvitation:"ایجاد دعوت‌نامه", invitationCreated:"دعوت‌نامه ایجاد شد", copyLinkHelp:"این لینک یک‌بارمصرف را از یک مسیر تأییدشده برای کاربر مقصد ارسال کنید.", active:"فعال", suspended:"تعلیق‌شده", revoked:"لغوشده", pending:"در انتظار", accepted:"پذیرفته‌شده", declined:"ردشده", cancelled:"لغوشده", expired:"منقضی", defaultWorkspace:"محیط پیش‌فرض", setDefault:"انتخاب به‌عنوان پیش‌فرض", updateRole:"تغییر نقش", suspend:"تعلیق", revoke:"لغو دسترسی", reactivate:"فعال‌سازی مجدد", cancelInvitation:"لغو دعوت‌نامه", reason:"دلیل", reasonHelp:"برای تغییر دسترسی الزامی است و در سابقه ممیزی ذخیره می‌شود.", save:"ذخیره", processing:"در حال انجام…", confirmSuspend:"دسترسی این عضو تعلیق شود؟", confirmRevoke:"دسترسی این عضو لغو شود؟ سابقه عضویت حفظ خواهد شد.", confirmReactivate:"دسترسی این عضو دوباره فعال شود؟", confirmCancelInvite:"این دعوت‌نامه لغو شود؟", ownerProtected:"دسترسی مالک محافظت شده و از این صفحه قابل تغییر نیست.", invitationTitle:"دعوت به محیط ارائه‌دهنده", invitationDescription:"پیش از پذیرش، ارائه‌دهنده و نقش را بررسی کنید.", acceptInvitation:"پذیرش دعوت", declineInvitation:"رد دعوت", invalidInvitation:"دعوت‌نامه نامعتبر یا منقضی است، یا برای حساب دیگری صادر شده است.", invitedAs:"نقش دعوت‌شده", expires:"انقضا", returnToWorkspaces:"محیط‌های کاری من", owner:"مالک", admin:"مدیر", manager:"مدیر اجرایی", editor:"ویرایشگر", viewer:"مشاهده‌گر", staffRole:"پرسنل", userNotFound:"کاربر السوین یافت نشد.", alreadyMember:"این کاربر قبلاً عضویت این ارائه‌دهنده را دارد؛ عضویت موجود را مدیریت کنید.", invalidRole:"این حساب اجازه اعطای این نقش را ندارد.", reasonRequired:"وارد کردن دلیل الزامی است.", memberNotFound:"عضویت یافت نشد.", cannotModifyOwner:"عضویت مالک از این بخش قابل تغییر نیست.", cannotModifySelf:"نمی‌توانید نقش یا دسترسی خودتان را از مدیریت اعضا تغییر دهید.", insufficientRole:"امکان مدیریت عضوی با نقش هم‌سطح یا بالاتر وجود ندارد.", invitationAccepted:"دعوت پذیرفته شد.", invitationDeclined:"دعوت رد شد." };
const ar: Copy = { ...en, moduleName:"الملكية والوصول", myProviders:"مساحات عملي", myProvidersDescription:"مساحات مقدمي الخدمة المرتبطة بحساب LSevin.", newApplication:"طلب جديد", noProviders:"لا توجد مساحة عمل نشطة", noProvidersDescription:"أنت مسجل الدخول لكن ليس لديك وصول نشط إلى مقدم خدمة.", manage:"إدارة", profile:"الملف", services:"الخدمات", staff:"الموظفون", bookings:"الحجوزات", rating:"التقييم", settings:"إعدادات الوصول", settingsDescription:"ادعُ مستخدمي LSevin وأدر الأدوار وعلّق أو ألغِ الوصول مع حفظ السجل.", members:"الأعضاء", invitations:"الدعوات", inviteUser:"دعوة مستخدم", email:"بريد LSevin", role:"الدور", createInvitation:"إنشاء دعوة", active:"نشط", suspended:"معلّق", revoked:"ملغى", pending:"قيد الانتظار", accepted:"مقبول", declined:"مرفوض", cancelled:"ملغى", expired:"منتهي", setDefault:"تعيين كافتراضي", updateRole:"تحديث الدور", suspend:"تعليق", revoke:"إلغاء الوصول", reactivate:"إعادة التفعيل", reason:"السبب", save:"حفظ", invitationTitle:"دعوة مساحة مقدم الخدمة", acceptInvitation:"قبول الدعوة", declineInvitation:"رفض", owner:"المالك", admin:"مسؤول", manager:"مدير", editor:"محرر", viewer:"مشاهد", staffRole:"موظف" };
const tr: Copy = { ...en, moduleName:"Sahiplik ve Erişim", myProviders:"Çalışma alanlarım", settings:"Erişim ayarları", members:"Üyeler", invitations:"Davetler", inviteUser:"Kullanıcı davet et", email:"LSevin e-postası", role:"Rol", createInvitation:"Davet oluştur", active:"Etkin", suspended:"Askıya alındı", revoked:"İptal edildi", pending:"Bekliyor", accepted:"Kabul edildi", declined:"Reddedildi", cancelled:"İptal edildi", expired:"Süresi doldu", updateRole:"Rolü güncelle", suspend:"Askıya al", revoke:"Erişimi iptal et", reactivate:"Yeniden etkinleştir", reason:"Gerekçe", invitationTitle:"Sağlayıcı çalışma alanı daveti", acceptInvitation:"Daveti kabul et", declineInvitation:"Reddet", owner:"Sahip", admin:"Yönetici", manager:"Müdür", editor:"Editör", viewer:"Görüntüleyici", staffRole:"Personel" };
const es: Copy = { ...en, moduleName:"Propiedad y acceso", myProviders:"Mis espacios", settings:"Configuración de acceso", members:"Miembros", invitations:"Invitaciones", inviteUser:"Invitar usuario", email:"Correo de LSevin", role:"Rol", createInvitation:"Crear invitación", active:"Activo", suspended:"Suspendido", revoked:"Revocado", pending:"Pendiente", accepted:"Aceptado", declined:"Rechazado", cancelled:"Cancelado", expired:"Caducado", updateRole:"Actualizar rol", suspend:"Suspender", revoke:"Revocar acceso", reactivate:"Reactivar", reason:"Motivo", invitationTitle:"Invitación al espacio del proveedor", acceptInvitation:"Aceptar invitación", declineInvitation:"Rechazar", owner:"Propietario", admin:"Administrador", manager:"Gerente", editor:"Editor", viewer:"Lector", staffRole:"Personal" };
const ku: Copy = { ...en, moduleName:"خاوەندارێتی و دەستگەیشتن", myProviders:"شوێنەکانی کارم", settings:"ڕێکخستنی دەستگەیشتن", members:"ئەندامان", invitations:"بانگهێشتەکان", inviteUser:"بانگهێشتی بەکارهێنەر", email:"ئیمەیڵی LSevin", role:"ڕۆڵ", createInvitation:"دروستکردنی بانگهێشت", active:"چالاک", suspended:"ڕاگیراو", revoked:"هەڵوەشاوە", pending:"چاوەڕوان", accepted:"پەسەندکراو", declined:"ڕەتکراو", cancelled:"هەڵوەشاوە", expired:"بەسەرچوو", updateRole:"نوێکردنەوەی ڕۆڵ", suspend:"ڕاگرتن", revoke:"هەڵوەشاندنەوەی دەستگەیشتن", reactivate:"چالاککردنەوە", reason:"هۆکار", invitationTitle:"بانگهێشتی شوێنی کاری دابینکەر", acceptInvitation:"پەسەندکردنی بانگهێشت", declineInvitation:"ڕەتکردنەوە", owner:"خاوەن", admin:"بەڕێوەبەر", manager:"بەڕێوەبەری کار", editor:"دەستکاریکەر", viewer:"بینەر", staffRole:"ستاف" };
const de: Copy = { ...en, moduleName:"Eigentum & Zugriff", myProviders:"Meine Arbeitsbereiche", settings:"Zugriffseinstellungen", members:"Mitglieder", invitations:"Einladungen", inviteUser:"Benutzer einladen", email:"LSevin-E-Mail", role:"Rolle", createInvitation:"Einladung erstellen", active:"Aktiv", suspended:"Gesperrt", revoked:"Entzogen", pending:"Ausstehend", accepted:"Angenommen", declined:"Abgelehnt", cancelled:"Storniert", expired:"Abgelaufen", updateRole:"Rolle aktualisieren", suspend:"Sperren", revoke:"Zugriff entziehen", reactivate:"Reaktivieren", reason:"Grund", invitationTitle:"Einladung zum Anbieter-Arbeitsbereich", acceptInvitation:"Einladung annehmen", declineInvitation:"Ablehnen", owner:"Inhaber", admin:"Administrator", manager:"Manager", editor:"Redakteur", viewer:"Betrachter", staffRole:"Mitarbeiter" };
const fr: Copy = { ...en, moduleName:"Propriété et accès", myProviders:"Mes espaces", settings:"Paramètres d’accès", members:"Membres", invitations:"Invitations", inviteUser:"Inviter un utilisateur", email:"E-mail LSevin", role:"Rôle", createInvitation:"Créer l’invitation", active:"Actif", suspended:"Suspendu", revoked:"Révoqué", pending:"En attente", accepted:"Accepté", declined:"Refusé", cancelled:"Annulé", expired:"Expiré", updateRole:"Mettre à jour le rôle", suspend:"Suspendre", revoke:"Révoquer l’accès", reactivate:"Réactiver", reason:"Motif", invitationTitle:"Invitation à l’espace prestataire", acceptInvitation:"Accepter l’invitation", declineInvitation:"Refuser", owner:"Propriétaire", admin:"Administrateur", manager:"Manager", editor:"Éditeur", viewer:"Lecteur", staffRole:"Personnel" };

const dictionaries: Record<PortalLocale, Copy> = { en, fa, ar, tr, es, ku, de, fr };
export function providerAccessCopy(locale?: string | null) { return dictionaries[normalizePortalLocale(locale).locale]; }
export const providerAccessMetadata = Object.fromEntries(Object.entries(dictionaries).map(([locale, copy]) => [locale, { name: copy.moduleName, providers: copy.myProviders, settings: copy.settings, invitation: copy.invitationTitle }])) as Record<PortalLocale, { name: string; providers: string; settings: string; invitation: string }>;
export type ProviderAccessCopy = Copy;
